/* Session 3 drills (Networking & connectivity). stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit.
   Q7 and Q46 are his baseline-exam misses (mine: true). K-drills are new. */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _o = (t, ok, why) => ({ t, ok: !!ok, why });
  const BASTION = 'Banks still expect a bastion in a public subnet. For new designs AWS recommends Session Manager or EC2 Instance Connect Endpoint, which need no public bastion.';
  const RNAT = 'Since Nov 2025 a **regional NAT gateway** can replace the per-AZ pattern: one NAT gateway, no public subnet, expands to every AZ with workloads. Banks still expect one zonal NAT gateway per AZ.';
  S.drills = [
    /* ---------------- his exam misses ---------------- */
    { id: 'Q7', src: 'Exam Q7', line: 'peer', mine: true, tag: 'F',
      q: 'A company has three VPCs in the same AWS Region: VPC-A (10.0.0.0/16), VPC-B (10.1.0.0/16) and VPC-C (10.2.0.0/16). VPC-A is peered with VPC-B, and VPC-A is peered with VPC-C. Route tables and security groups are configured for both peering connections. Applications in VPC-B now also need to query a database in VPC-C. Which solution meets this requirement in the MOST cost-effective way with the LEAST configuration?',
      opts: [_o('Add a route for 10.2.0.0/16 in VPC-B and a route for 10.1.0.0/16 in VPC-C, both targeting their VPC-A peering connections, and allow 10.1.0.0/16 in the database security group.', 0, 'Peering is not transitive: VPC-A never forwards traffic between its two peers, whatever the routes say.'),
        _o('Create a VPC peering connection between VPC-B and VPC-C, add a route for each other’s CIDR block in both VPCs’ route tables, and allow 10.1.0.0/16 in the database security group.', 1, 'One direct connection for the one pair that needs it: no hourly charge, two routes and one rule.'),
        _o('Create a transit gateway, attach VPC-B and VPC-C, add a route for each other’s CIDR block that targets the transit gateway, and allow 10.1.0.0/16 in the database security group.', 0, 'Works, but adds attachment-hours and per-GB charges for one pair. Loses on cost. Prestige distractor.'),
        _o('Create a VPC peering connection between VPC-B and VPC-C, add a route for 10.2.0.0/16 to it in VPC-B’s route table only, and allow 10.1.0.0/16 in the database security group.', 0, 'Replies from VPC-C have no route back to 10.1.0.0/16. Peering needs a route on both sides.')],
      stub: { who: 'VPC↔VPC', scale: 'one pair', path: 'private AWS network', sup: 'cheapest' }, words: ['VPC-A is peered with VPC-B', 'MOST cost-effective', 'LEAST configuration'],
      expl: 'WHO = VPC↔VPC, SCALE = one new pair (B–C). Peering is not transitive, so B–C needs its own peering connection, with routes on both sides. A transit gateway would work but costs more: cheapest + least configuration = peer B with C.' },
    { id: 'Q46', src: 'Exam Q46', line: 'access', mine: true, tag: 'R',
      q: 'A company runs application servers on Amazon EC2 instances in private subnets of a VPC. Administrators must connect to the instances over SSH from the corporate network, whose public IP range is 203.0.113.0/24. The security team requires a single hardened bastion host and wants to minimise the exposure of the application servers. Which configuration meets these requirements?',
      opts: [_o('Launch the bastion host in a private subnet and assign it an Elastic IP address. Allow SSH from 203.0.113.0/24 in its security group, and allow SSH on the application servers only from the bastion’s security group.', 0, 'A private subnet has no route to the internet gateway, so the bastion is unreachable even with an Elastic IP. This was your pick.'),
        _o('Create a NAT gateway in a public subnet and forward inbound SSH from 203.0.113.0/24 through it to a bastion host in a private subnet. Allow SSH on the application servers only from the bastion’s security group.', 0, 'A NAT gateway only carries connections that start inside the VPC. It cannot forward inbound SSH.'),
        _o('Launch the bastion host in a public subnet. Allow SSH from 203.0.113.0/24 in the bastion’s security group, and allow SSH on the application servers only from the bastion’s security group.', 1, 'Reachable from the corporate range only; the application servers accept SSH only from the bastion.'),
        _o('Launch the bastion host in a public subnet. Allow SSH from 203.0.113.0/24 in the bastion’s security group, and allow SSH on the application servers from the VPC’s entire CIDR block.', 0, 'Every resource in the VPC can now open SSH to the application servers, not only the bastion. Not minimal exposure.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'most secure' }, words: ['private subnets', 'single hardened bastion host', 'minimise the exposure'],
      expl: 'A bastion is only useful if admins can reach it: it must sit in a **public** subnet (route 0.0.0.0/0 → IGW). Minimal exposure = its SG allows 22 from the corporate range, and the app SG allows 22 only from the bastion SG, not from a CIDR block.', update: BASTION },

    /* ---------------- VPC basics ---------------- */
    { id: 'K1', src: 'New', line: 'vpc',
      q: 'A company is designing a VPC with the CIDR block 10.20.0.0/16. Each application subnet must hold at least 100 EC2 instances plus 20 additional IP addresses for interface endpoints and Lambda network interfaces. The network team wants to use the smallest subnet size that meets this requirement so the rest of the range stays free. Which subnet size should the team use?',
      opts: [_o('Create each application subnet with a /24 prefix, for example 10.20.1.0/24.', 0, '256 − 5 reserved = 251 usable: enough, but twice the size that is needed.'),
        _o('Create each application subnet with a /26 prefix, for example 10.20.1.0/26.', 0, '64 − 5 reserved = 59 usable: too small.'),
        _o('Create each application subnet with a /27 prefix, for example 10.20.1.0/27.', 0, '32 − 5 = 27 usable: far too small.'),
        _o('Create each application subnet with a /25 prefix, for example 10.20.1.0/25.', 1, '128 − 5 reserved = 123 usable ≥ 120 needed. The smallest that fits.')],
      stub: { who: 'inside one VPC', scale: 'n/a', path: 'n/a', sup: 'none stated' }, words: ['at least 100 EC2 instances plus 20 additional IP addresses', 'smallest subnet size'],
      expl: 'Need 120 addresses. AWS reserves 5 in every subnet (network, router, DNS, one spare, broadcast). /26 gives 59, /25 gives 123. Do the “minus 5” every time.' },
    { id: 'K2', src: 'New', line: 'vpc',
      q: 'A developer launches an EC2 instance running a web server into a newly created subnet. The VPC has an internet gateway attached. Users on the internet cannot reach the instance, and the instance cannot download updates. The instance’s security group allows HTTP from 0.0.0.0/0, and the subnet uses the default network ACL. Which actions must a solutions architect take so that users can reach the web server? (Select TWO.)',
      opts: [_o('Add a route for 0.0.0.0/0 that targets the internet gateway to the route table associated with the subnet.', 1, 'That route is what makes a subnet public.'),
        _o('Create a NAT gateway in the subnet, and add a route for 0.0.0.0/0 that targets the NAT gateway.', 0, 'NAT is outbound only; users still could not reach the server.'),
        _o('Assign a public IPv4 address or an Elastic IP address to the instance’s primary network interface.', 1, 'The internet gateway translates to a public address; without one, nothing on the internet can address the instance.'),
        _o('Add a security group outbound rule that allows TCP 1024–65535 to 0.0.0.0/0 for the HTTP replies.', 0, 'Security groups are stateful and allow all outbound by default; replies are already allowed.'),
        _o('Create an egress-only internet gateway, and add a route for ::/0 that targets it in the subnet.', 0, 'Egress-only gateways are for IPv6 outbound traffic only; nothing can come in through them.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'none stated' }, words: ['newly created subnet', 'internet gateway attached', 'cannot reach the instance'],
      expl: 'Attaching an IGW to the VPC is not enough. A subnet is public only when its route table sends 0.0.0.0/0 to the IGW, and the instance needs a public IPv4 or Elastic IP.' },

    /* ---------------- NAT ---------------- */
    { id: 'K3', src: 'New', line: 'nat',
      q: 'EC2 instances in private subnets in two Availability Zones must download software patches from the internet. The internet must not be able to initiate connections to the instances. Internet access must keep working if one Availability Zone fails. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('Create a NAT gateway in a public subnet in each Availability Zone, and route each private subnet to the gateway in its own AZ.', 1, 'Managed and redundant inside each AZ; an AZ failure only affects that AZ’s own subnets.'),
        _o('Create one NAT gateway in a public subnet in the first Availability Zone, and route the private subnets in both Availability Zones to it.', 0, 'A zonal NAT gateway lives in one AZ. If that AZ fails, the other AZ loses internet access too.'),
        _o('Launch a NAT instance in a public subnet in each Availability Zone, disable source/destination checks, and route each private subnet to it.', 0, 'Survives an AZ failure, but you patch, size and replace the instances yourself. Loses on operational overhead.'),
        _o('Create an egress-only internet gateway for the VPC, and route 0.0.0.0/0 from the private subnets in both Availability Zones to it.', 0, 'Egress-only gateways carry IPv6 only; 0.0.0.0/0 is IPv4.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'least ops' }, words: ['must not be able to initiate connections', 'if one Availability Zone fails', 'LEAST operational overhead'],
      expl: 'Out only → NAT. Least ops → NAT gateway, not an instance. Survive an AZ failure → a zonal NAT gateway per AZ with per-AZ routes, not one shared gateway.', update: RNAT },
    { id: 'K4', src: 'New', line: 'nat',
      q: 'To save cost, a company routes a small private subnet through a NAT instance. The team replaces the NAT instance with a new one built from a custom Amazon Linux 2023 AMI, on which IP forwarding and NAT masquerading are configured exactly as on the old instance. Instances in the private subnet can no longer reach the internet. The private route table sends 0.0.0.0/0 to the new instance, which is in a public subnet with an Elastic IP address, and its security group allows all traffic from the private subnet. What is the MOST likely cause?',
      opts: [_o('NAT instances can be launched only from the AWS-provided NAT AMI, not from a custom Amazon Linux AMI.', 0, 'False: AWS documents building your own NAT AMI from current Amazon Linux.'),
        _o('The public subnet needs an egress-only internet gateway before the new instance can forward IPv4 traffic.', 0, 'Egress-only gateways are for IPv6; unrelated to IPv4 NAT.'),
        _o('The new instance has no IAM instance profile with a policy that allows it to forward other instances’ traffic.', 0, 'Packet forwarding has nothing to do with IAM.'),
        _o('Source/destination checking is still enabled on the network interface of the new NAT instance.', 1, 'Every instance drops traffic that is not addressed to it unless the check is disabled; a NAT must forward other hosts’ traffic.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'none stated' }, words: ['NAT instance', 'custom Amazon Linux 2023 AMI', 'can no longer reach the internet'],
      expl: 'A NAT instance forwards packets whose source or destination is not itself, so its source/destination check must be disabled. New instance = check back on by default.',
      update: 'The AWS NAT AMI is built on Amazon Linux AMI 2018.03, which is past end of maintenance; AWS recommends NAT gateways, or building your own NAT AMI.' },
    { id: 'K15', src: 'New', line: 'nat',
      q: 'A company runs IPv6-only EC2 instances in a subnet of a dual-stack VPC. The instances must call IPv6 APIs on the internet. Nothing on the internet may initiate a connection to the instances. Which solution meets these requirements?',
      opts: [_o('Create an egress-only internet gateway, and add a route for ::/0 that targets it in the subnet’s route table.', 1, 'Stateful, IPv6, outbound only: exactly the job.'),
        _o('Create a NAT gateway in a public subnet, and add a route for ::/0 that targets it in the subnet’s route table.', 0, 'IPv6 addresses need no translation; a NAT gateway’s IPv6 feature is NAT64, for reaching IPv4 destinations.'),
        _o('Route ::/0 to the internet gateway, and deny all inbound IPv6 traffic in the subnet’s network ACL.', 0, 'NACLs are stateless: denying all inbound also drops the API replies, so the calls fail.'),
        _o('Create an AWS Global Accelerator with the instances as endpoints, and send the API calls through it.', 0, 'Global Accelerator brings users in to your endpoints; it is not an outbound path. Prestige distractor.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'none stated' }, words: ['IPv6', 'Nothing on the internet may initiate'],
      expl: 'IPv6 addresses are globally unique and public by default. “Outbound only” for IPv6 = egress-only internet gateway, which is stateful, so replies come back in.' },

    /* ---------------- filtering ---------------- */
    { id: 'K5', src: 'New', line: 'filter',
      q: 'A web server in a public subnet listens on HTTPS (TCP 443). Its security group allows inbound TCP 443 from 0.0.0.0/0. The subnet uses a custom network ACL with inbound rule 100 allowing TCP 443 from 0.0.0.0/0 and outbound 100 allow TCP 443 to 0.0.0.0/0, followed by the default deny (*) rules. Clients reach the server, but their requests time out. What should a solutions architect change?',
      opts: [_o('Add an outbound rule to the security group that allows TCP 1024–65535 to 0.0.0.0/0.', 0, 'Security groups are stateful; replies to allowed inbound traffic already leave.'),
        _o('Add an inbound rule to the network ACL that allows TCP 1024–65535 from 0.0.0.0/0.', 0, 'That serves replies to connections the server starts. Here the replies go out.'),
        _o('Add an outbound rule to the network ACL that allows TCP 1024–65535 to 0.0.0.0/0.', 1, 'The server’s replies go to the client’s ephemeral port; the stateless NACL must allow them out.'),
        _o('Route the subnet through AWS Network Firewall with a stateful rule that allows TCP 443.', 0, 'The NACL still drops the replies at the subnet edge. A managed firewall does not fix a NACL. Prestige distractor.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'none stated' }, words: ['custom network ACL', 'outbound 100 allow TCP 443', 'requests time out'],
      expl: 'NACLs are stateless. The reply to a client on port 443 goes back to the client’s ephemeral port (1024–65535), so the NACL needs an outbound allow for that range.' },
    { id: 'K6', src: 'New', line: 'filter',
      q: 'A company runs a public web application on EC2 instances in a public subnet, without a load balancer. The security team has found malicious requests coming from 198.51.100.0/24 and must block it immediately for every instance in the subnet. The network ACL currently has inbound rule 100 that allows TCP 443 from 0.0.0.0/0. Which solution meets these requirements with the LEAST cost and effort?',
      opts: [_o('Add a network ACL inbound rule numbered 50 that denies all traffic from 198.51.100.0/24.', 1, 'Evaluated before rule 100, subnet-wide, free.'),
        _o('Add an inbound rule to the instances’ security group that denies all traffic from 198.51.100.0/24.', 0, 'Security groups have allow rules only.'),
        _o('Add a network ACL inbound rule numbered 200 that denies all traffic from 198.51.100.0/24.', 0, 'Rule 100 matches first and allows the traffic; 200 is never reached.'),
        _o('Associate an AWS WAF web ACL that blocks the 198.51.100.0/24 IP set with the EC2 instances.', 0, 'AWS WAF attaches to ALB, CloudFront, API Gateway and similar, not to EC2 instances. There is no load balancer here.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'cheapest' }, words: ['must block it immediately', '198.51.100.0/24', 'least cost and effort'],
      expl: 'Deny = NACL (SGs cannot deny). NACL rules run lowest number first, so the deny must be numbered before the allow. WAF would need a load balancer or CloudFront in front.' },
    { id: 'K7', src: 'New', line: 'filter',
      q: 'A three-tier application runs its web tier in an EC2 Auto Scaling group and its application tier on port 8080 in another Auto Scaling group, all in one VPC. The application tier must accept traffic only from the web tier instances, whose IP addresses change as the group scales. Which solution is the MOST secure and needs the least maintenance?',
      opts: [_o('Allow TCP 8080 in the application tier’s security group from the CIDR block of the whole VPC.', 0, 'Lets every resource in the VPC in, not only the web tier.'),
        _o('Use a Lambda function on scaling events to write the web instances’ IPs into the app tier’s security group.', 0, 'Custom code to maintain what a group reference does natively.'),
        _o('Allow TCP 8080 in the application tier’s security group with the web tier’s security group as the source.', 1, 'The rule follows group membership, whatever the IPs are.'),
        _o('Allow TCP 8080 in the application subnets’ network ACL from the CIDR blocks of the web tier’s subnets.', 0, 'Coarser (anything in those subnets), stateless, and needs return rules.')],
      stub: { who: 'inside one VPC', scale: 'n/a', path: 'n/a', sup: 'most secure' }, words: ['IP addresses change', 'only from the web tier'],
      expl: 'A security group rule can name another security group as its source. Membership, not addresses, decides: the tightest rule with zero upkeep.' },

    /* ---------------- endpoints / PrivateLink ---------------- */
    { id: 'K8', src: 'New', line: 'pl',
      q: 'EC2 instances in private subnets process several terabytes of objects each day from an Amazon S3 bucket in the same Region. Today the traffic goes through a NAT gateway, and the NAT gateway data processing charges are high. The company wants the traffic to stay off the internet and to reduce cost as much as possible. What should a solutions architect do?',
      opts: [_o('Create an interface VPC endpoint for Amazon S3 in each private subnet, and use the endpoint-specific DNS names.', 0, 'Private, but billed per hour per AZ and per GB. Not the cheapest.'),
        _o('Create a gateway VPC endpoint for Amazon S3 and associate it with the public subnet route table that holds the NAT route.', 0, 'The private instances use the private route tables; their S3 traffic still goes to the NAT gateway.'),
        _o('Replace the NAT gateway with a NAT instance on a Graviton instance type to avoid the per-GB processing charge.', 0, 'Still an internet path, and adds operations.'),
        _o('Create a gateway VPC endpoint for Amazon S3 and associate it with the route tables of the private subnets.', 1, 'Route-table target to S3, no charge, no internet.')],
      stub: { who: 'VPC→service', scale: 'n/a', path: 'private AWS network', sup: 'cheapest' }, words: ['same Region', 'NAT gateway', 'reduce cost as much as possible'],
      expl: 'S3 (or DynamoDB) from inside the VPC + cheapest = gateway endpoint: free, route-table based, and it removes the NAT processing charge. It only works for the route tables you associate it with.' },
    { id: 'K9', src: 'New', line: 'pl',
      q: 'An on-premises analytics cluster connects to a VPC over AWS Direct Connect with a private virtual interface. The cluster must read and write objects in Amazon S3 using private IP addresses only. The security policy forbids any traffic to public AWS endpoints. Which solution meets these requirements?',
      opts: [_o('Create a gateway VPC endpoint for Amazon S3, and route the cluster’s S3 traffic to it through the VPC over the private VIF.', 0, 'Gateway endpoints do not allow access from on-premises networks.'),
        _o('Create an interface VPC endpoint for Amazon S3, and have the cluster call its endpoint-specific DNS names.', 1, 'Private IPs in the VPC, reachable over the DX private VIF.'),
        _o('Create a public virtual interface on the Direct Connect connection, and reach the Regional S3 endpoints over that VIF.', 0, 'That is exactly the public endpoint the policy forbids.'),
        _o('Enable S3 Transfer Acceleration, and send the cluster’s requests to the accelerate endpoint over Direct Connect.', 0, 'Public edge endpoints: the opposite of private.')],
      stub: { who: 'on-prem↔AWS', scale: 'n/a', path: 'dedicated line', sup: 'none stated' }, words: ['private IP addresses only', 'forbids any traffic to public AWS endpoints', 'Direct Connect'],
      expl: 'From on-prem, only an **interface** endpoint works: it is an ENI with a private IP that DX (or VPN) traffic can reach. Gateway endpoints serve only the VPC they are in.' },
    { id: 'K10', src: 'New', line: 'pl',
      q: 'Lambda functions and EC2 instances run in private subnets that, by policy, have no internet access and no NAT gateway. The workloads must send messages to Amazon SQS and decrypt data with AWS KMS by using the default SDK endpoints, without code changes. Which solution meets these requirements?',
      opts: [_o('Create gateway VPC endpoints for Amazon SQS and AWS KMS, and add them to the private subnets’ route tables.', 0, 'Gateway endpoints exist only for S3 and DynamoDB.'),
        _o('Create interface VPC endpoints for Amazon SQS and AWS KMS in the private subnets with private DNS enabled.', 1, 'ENIs in your subnets; the default service names resolve to them.'),
        _o('Create interface VPC endpoints for Amazon SQS and AWS KMS in the private subnets with private DNS disabled.', 0, 'The default names still resolve to public IPs, which the subnets cannot reach. Code would have to use endpoint-specific names.'),
        _o('Create a NAT gateway in a public subnet whose security group allows only the SQS and KMS endpoints.', 0, 'Breaks the no-NAT policy, and a NAT gateway has no security group.')],
      stub: { who: 'VPC→service', scale: 'n/a', path: 'private AWS network', sup: 'none stated' }, words: ['no internet access', 'Amazon SQS', 'AWS KMS', 'without code changes'],
      expl: 'Any AWS API other than S3/DynamoDB from a private subnet without internet = interface endpoint (PrivateLink). Private DNS makes the SDK’s default endpoint names resolve to the endpoint’s private IPs.' },
    { id: 'K11', src: 'New', line: 'pl',
      q: 'A SaaS company runs an API on EC2 instances in its own VPC. Hundreds of customers must reach one TCP port of this API privately from their own VPCs in their own AWS accounts. Many customer VPCs use the same CIDR block, 10.0.0.0/16, as the provider VPC. Customers must not get access to any other resource in the provider VPC. Which solution meets these requirements?',
      opts: [_o('Create a VPC peering connection to each customer VPC, and allow only the API port in the provider security group.', 0, 'Peering fails with overlapping CIDRs, and it joins whole networks.'),
        _o('Share a transit gateway with the customer accounts through AWS RAM, and use a separate route table per customer.', 0, 'Overlapping CIDRs cannot be routed, and it connects networks, not one service.'),
        _o('Put the API behind a Network Load Balancer as a VPC endpoint service, and let customers create interface endpoints.', 1, 'PrivateLink: one service, one direction, overlapping CIDRs are fine.'),
        _o('Put the API behind AWS Global Accelerator, and allow only the customers’ NAT gateway IP addresses to reach it.', 0, 'Public internet entry; not private. Prestige distractor.')],
      stub: { who: 'VPC→service', scale: 'many / hub', path: 'private AWS network', sup: 'none stated' }, words: ['same CIDR block', 'must not get access to any other resource', 'Hundreds of customers'],
      expl: 'Expose one service to many consumers, overlapping CIDRs, nothing else visible → PrivateLink endpoint service behind an NLB.' },

    /* ---------------- peering ---------------- */
    { id: 'K14', src: 'New', line: 'peer',
      q: 'A reporting application in VPC-1 queries a database in VPC-2 a few times a day. Both VPCs are in the same AWS account and Region, and their CIDR blocks do not overlap. No other VPCs will be added. Which solution is the MOST cost-effective?',
      opts: [_o('Create a transit gateway, attach both VPCs, and add routes that target the transit gateway in both route tables.', 0, 'Two attachment-hours around the clock plus per-GB processing, for one pair. Prestige distractor.'),
        _o('Create a Site-to-Site VPN connection between virtual private gateways attached to each of the two VPCs.', 0, 'A VPN connection needs a customer gateway at one end; two VGWs cannot form one.'),
        _o('Create a VPC peering connection, add routes in both VPCs, and allow VPC-1’s CIDR in the database security group.', 1, 'No hourly charge, one pair, done.'),
        _o('Publish the database as a VPC endpoint service behind a Network Load Balancer, and add an interface endpoint in VPC-1.', 0, 'Works one-way, but pays for an NLB and endpoint hours.')],
      stub: { who: 'VPC↔VPC', scale: 'one pair', path: 'private AWS network', sup: 'cheapest' }, words: ['No other VPCs will be added', 'MOST cost-effective'],
      expl: 'Two VPCs, no overlap, cheapest → peering. There is no charge to create a peering connection; data within one AZ is free.' },
    { id: 'K16', src: 'New', line: 'peer',
      q: 'VPC-A has a NAT gateway that gives its private subnets internet access. VPC-B, which has no internet gateway, is peered with VPC-A. An administrator adds a 0.0.0.0/0 route in VPC-B that points to the peering connection, but instances in VPC-B still cannot reach the internet. What is the MOST cost-effective way to give VPC-B outbound IPv4 internet access?',
      opts: [_o('Add a route in VPC-A’s NAT gateway subnet that sends VPC-B’s CIDR block back through the peering connection.', 0, 'Edge-to-edge routing through a peering connection is not supported; the NAT gateway will not serve VPC-B.'),
        _o('Create an egress-only internet gateway in VPC-B, and route 0.0.0.0/0 from VPC-B’s private subnets to it.', 0, 'Egress-only gateways carry IPv6 only; 0.0.0.0/0 is IPv4.'),
        _o('Attach an internet gateway to VPC-B, and add a NAT gateway in a new public subnet for its private subnets.', 1, 'VPC-B gets its own way out; nothing depends on the peer.'),
        _o('Replace the peering with a transit gateway, and route VPC-B’s 0.0.0.0/0 to VPC-A’s NAT gateway through it.', 0, 'Centralised egress works for many VPCs; for two it adds attachment-hours and per-GB charges on top of the NAT.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'cheapest' }, words: ['0.0.0.0/0', 'peering connection', 'still cannot reach the internet'],
      expl: 'No edge-to-edge: a peer cannot use the other VPC’s IGW, NAT, VPN, DX or gateway endpoint. For one VPC, give it its own NAT gateway.' },

    /* ---------------- Transit Gateway ---------------- */
    { id: 'K12', src: 'New', line: 'tgw',
      q: 'A company has 40 VPCs across 12 accounts in one AWS Region and two data centers connected by Site-to-Site VPN. Every VPC must reach every other VPC and both data centers. The current full mesh of VPC peering connections and per-VPC VPN connections has become unmanageable. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('Create a transit gateway, share it with every account through AWS RAM, attach all VPCs, and move both VPNs to it.', 1, 'One hub; every network attaches once; routing is central.'),
        _o('Create a transit gateway in each account, peer them with each other, and attach each account’s VPCs to its own gateway.', 0, 'Twelve hubs and a peering mesh with static routes: the mesh problem moved up one level.'),
        _o('Build a transit VPC with third-party VPN router appliances on EC2, and connect every VPC and both data centers to it.', 0, 'The pre-TGW pattern: you run, patch and scale the routers.'),
        _o('Create a Direct Connect gateway, associate the virtual private gateways of all 40 VPCs, and attach both VPNs to it.', 0, 'A Direct Connect gateway does not route between associated VPCs, and VPN connections do not attach to it.')],
      stub: { who: 'VPC↔VPC', scale: 'many / hub', path: 'private AWS network', sup: 'least ops' }, words: ['40 VPCs', '12 accounts', 'unmanageable', 'LEAST operational overhead'],
      expl: 'Many VPCs + on-prem, all-to-all, least ops = one Transit Gateway shared with RAM. This is the TGW’s real job — the opposite of the two-VPC prestige trap.' },
    { id: 'K13', src: 'New', line: 'tgw',
      q: 'A company attaches development, production and shared-services VPCs to one transit gateway. Development and production VPCs must both reach the shared-services VPC, but development must never reach production, and production must never reach development. Which configuration meets these requirements?',
      opts: [_o('Keep every attachment associated with the default route table, and disable route propagation from the development and production attachments.', 0, 'One shared table: shared services also loses its routes to development and production, so replies have no path.'),
        _o('Keep the default route table, and attach security groups to the development and production attachments that deny each other’s CIDR blocks.', 0, 'Transit gateway attachments have no security groups, and security groups cannot deny.'),
        _o('Associate shared services with a route table that has only the development and production routes, and the others with one that propagates every attachment.', 0, 'The development and production table then contains each other’s routes.'),
        _o('Associate development and production with a route table that has only the shared-services route, and shared services with one that has routes to both.', 1, 'Segmentation by routing: no route, no path.')],
      stub: { who: 'VPC↔VPC', scale: 'many / hub', path: 'private AWS network', sup: 'none stated' }, words: ['development must never reach production', 'one transit gateway'],
      expl: 'Each attachment is associated with exactly one TGW route table. Give dev and prod a table without each other’s routes, and give shared services a table with both.' },

    /* ---------------- VPN ---------------- */
    { id: 'K17', src: 'New', line: 'vpn',
      q: 'A company must connect its data center to a VPC within one week so that a migration can start. All traffic between the sites must be encrypted. The data center has a 500 Mbps internet connection. Which solution meets these requirements MOST cost-effectively?',
      opts: [_o('Order a 1 Gbps dedicated Direct Connect connection, and run an IPsec VPN over it to encrypt the traffic.', 0, 'Encrypted, but a new dedicated connection takes weeks to months. Misses the one-week deadline.'),
        _o('Create a Site-to-Site VPN from a customer gateway to a virtual private gateway, and configure both tunnels.', 1, 'Encrypted IPsec over the existing internet link, up in hours.'),
        _o('Create an AWS Client VPN endpoint, and install the OpenVPN client on every data center server that needs access.', 0, 'Client VPN is for individual users’ devices, not site-to-site routing.'),
        _o('Create an accelerated Site-to-Site VPN connection to a virtual private gateway, and configure both tunnels.', 0, 'Accelerated VPN is available only on a transit gateway, not on a virtual private gateway.')],
      stub: { who: 'on-prem↔AWS', scale: 'one pair', path: 'encrypted tunnel', sup: 'cheapest' }, words: ['within one week', 'encrypted', '500 Mbps internet connection'],
      expl: 'Deadline in days + encrypted + an internet link that is big enough = Site-to-Site VPN. Two tunnels in two AZs for redundancy. DX loses on lead time; acceleration needs a TGW.' },
    { id: 'K18', src: 'New', line: 'vpn',
      q: 'A company has 800 remote employees who work from laptops at home and while travelling. They need access to internal applications in a VPC and in the data center, which is already connected to the VPC. Users must authenticate with the company’s Active Directory. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('Create an AWS Client VPN endpoint that uses Active Directory authentication, with routes to the VPC and the data center.', 1, 'Managed, OpenVPN-based, scales with users, AD-integrated.'),
        _o('Create a Site-to-Site VPN connection for each laptop, with each laptop registered as a customer gateway.', 0, 'Site-to-Site VPN connects networks through a customer gateway device, not individual laptops.'),
        _o('Run OpenVPN Access Server on EC2 in an Auto Scaling group, and connect it to Active Directory over LDAP.', 0, 'Works, but you run, patch and scale the VPN servers. Loses on operational overhead.'),
        _o('Create an AWS Client VPN endpoint that uses mutual certificate authentication, with routes to the VPC and the data center.', 0, 'Certificates alone do not authenticate users against Active Directory.')],
      stub: { who: 'on-prem↔AWS', scale: 'many / hub', path: 'encrypted tunnel', sup: 'least ops' }, words: ['remote employees', 'laptops', 'Active Directory'],
      expl: 'People (not sites) outside AWS → Client VPN, with the authentication the stem names. Remote users count as the “outside” end: WHO = on-prem↔AWS.' },
    { id: 'K19', src: 'New', line: 'vpn',
      q: 'A retailer has six branch offices. Each branch already has a Site-to-Site VPN connection to the same virtual private gateway, and each uses a unique BGP ASN with non-overlapping IP ranges. The branches now need to exchange traffic with each other without new circuits. Which solution meets these requirements MOST cost-effectively?',
      opts: [_o('Order Direct Connect connections with SiteLink at each branch, so branch traffic flows between DX locations.', 0, 'New circuits at every branch: the opposite of the brief.'),
        _o('Use AWS VPN CloudHub, so the virtual private gateway re-advertises each branch’s BGP routes to the others.', 1, 'Hub-and-spoke over the existing VPNs; no new resources to pay for.'),
        _o('Create a transit gateway, move the six VPN connections to it, and propagate them into one shared route table.', 0, 'Works, but adds attachment-hours and per-GB charges. Loses on cost.'),
        _o('Put AWS Global Accelerator in front of the virtual private gateway so the branches reach each other over AWS.', 0, 'Global Accelerator fronts internet-facing endpoints; it does not route between VPN sites. Prestige distractor.')],
      stub: { who: 'on-prem↔AWS', scale: 'many / hub', path: 'encrypted tunnel', sup: 'cheapest' }, words: ['same virtual private gateway', 'with each other', 'without new circuits'],
      expl: 'Branches ↔ branches through existing VPNs on one VGW, unique ASNs = VPN CloudHub. A transit gateway would also route them, at a price.' },

    /* ---------------- Direct Connect ---------------- */
    { id: 'K20', src: 'New', line: 'dx',
      q: 'A company transfers about 5 TB between its data center and AWS every day over a Site-to-Site VPN. Latency and throughput vary during business hours. The company needs consistent performance of 10 Gbps over a private connection that does not use the public internet. The project will go live in three months. Which solution meets these requirements?',
      opts: [_o('Add more Site-to-Site VPN connections to the virtual private gateway, and spread traffic across the tunnels with ECMP.', 0, 'A VGW does not support ECMP across tunnels, and it is still the internet.'),
        _o('Move the VPN to a transit gateway with two 5 Gbps Large Bandwidth Tunnels, and use ECMP across both tunnels.', 0, 'Reaches 10 Gbps, but every tunnel still rides the public internet.'),
        _o('Order a 10 Gbps dedicated Direct Connect connection, and create a public virtual interface to reach the VPC.', 0, 'A public VIF reaches public AWS endpoints, not the private IPs in a VPC.'),
        _o('Order a 10 Gbps dedicated Direct Connect connection, and create a private virtual interface to the VPC’s gateway.', 1, 'Private, consistent, and three months is enough lead time.')],
      stub: { who: 'on-prem↔AWS', scale: 'one pair', path: 'dedicated line', sup: 'consistent bandwidth' }, words: ['consistent performance of 10 Gbps', 'three months'],
      expl: 'Consistent + private + large every day, and months of lead time = Direct Connect with a private VIF.' },
    { id: 'K21', src: 'New', line: 'dx',
      q: 'A bank connects its data center to AWS with a 10 Gbps dedicated AWS Direct Connect connection and a private virtual interface. A new regulation requires that all traffic between the data center and AWS is encrypted in transit. Which solutions meet this requirement? (Select TWO.)',
      opts: [_o('Enable MACsec on the 10 Gbps dedicated connection, at a Direct Connect location and port that support it.', 1, 'Layer-2, point-to-point encryption on 10/100/400 Gbps dedicated ports.'),
        _o('Keep the current setup, because a dedicated Direct Connect connection encrypts its traffic by default.', 0, 'False: Direct Connect does not encrypt traffic in transit by default.'),
        _o('Run a Site-to-Site VPN over the connection, through a public VIF or as a private IP VPN on a transit VIF.', 1, 'IPsec end to end on top of the private line.'),
        _o('Deploy AWS Network Firewall in the VPC with TLS inspection enabled for traffic from the data center.', 0, 'Network Firewall inspects traffic; it does not encrypt the link. Prestige distractor.'),
        _o('Turn on encryption for the private virtual interface in the Direct Connect console, with an AWS KMS key.', 0, 'There is no such setting.')],
      stub: { who: 'on-prem↔AWS', scale: 'one pair', path: 'dedicated line', sup: 'none stated' }, words: ['encrypted in transit', '10 Gbps dedicated'],
      expl: 'DX alone is private but not encrypted. Two ways to encrypt it: MACsec (supported dedicated speeds and locations) or IPsec VPN over DX.' },
    { id: 'K22', src: 'New', line: 'dx',
      q: 'A trading platform depends on AWS Direct Connect. The connectivity must survive a device failure, a fibre cut, and the loss of an entire Direct Connect location, and the company wants the highest level of resiliency that AWS recommends for critical workloads. Which design meets these requirements?',
      opts: [_o('Two dedicated connections terminating on separate devices at one Direct Connect location.', 0, 'The Development and Test model: survives a device failure, not a location failure.'),
        _o('Two dedicated connections on separate devices at each of two Direct Connect locations.', 1, 'The Maximum Resiliency model: device, fibre and location failures, with redundancy left after one.'),
        _o('One dedicated connection at each of two Direct Connect locations, with BGP failover.', 0, 'The High Resiliency model: survives a location loss, but it is not the highest level.'),
        _o('One dedicated connection, with a Site-to-Site VPN over the internet as the backup path.', 0, 'A cheap backup, not the highest resiliency; the VPN rides the internet.')],
      stub: { who: 'on-prem↔AWS', scale: 'one pair', path: 'dedicated line', sup: 'resilient' }, words: ['loss of an entire Direct Connect location', 'highest level of resiliency'],
      expl: 'The Direct Connect Resiliency Toolkit models: Maximum (separate connections on separate devices in more than one location), High (one connection at each of two locations), Development and Test (two connections, one location). “Highest” = Maximum.' },
    { id: 'K23', src: 'New', line: 'dx',
      q: 'A company has a single 1 Gbps AWS Direct Connect connection to a virtual private gateway for non-critical workloads. Traffic averages 300 Mbps. The company wants a low-cost backup path that takes over automatically if the Direct Connect connection fails. Which solution is the MOST cost-effective?',
      opts: [_o('Order a second 1 Gbps dedicated Direct Connect connection at another Direct Connect location.', 0, 'The most resilient, but not low-cost, and weeks away.'),
        _o('Order a 500 Mbps hosted connection from a Direct Connect Partner to the same virtual private gateway.', 0, 'Cheaper than dedicated, still a monthly circuit and lead time.'),
        _o('Add a Site-to-Site VPN to the same virtual private gateway, and let BGP prefer the Direct Connect path.', 1, 'Cheap, up in hours, 300 Mbps fits one tunnel.'),
        _o('Create a Transit Gateway Connect attachment over the internet, and use its GRE tunnels as the backup path.', 0, 'Connect runs GRE over an existing VPC or DX transport attachment, not over the internet.')],
      stub: { who: 'on-prem↔AWS', scale: 'one pair', path: 'encrypted tunnel', sup: 'cheapest' }, words: ['low-cost backup', '1 Gbps', 'averages 300 Mbps'],
      expl: 'Low-cost DX backup = Site-to-Site VPN. AWS advises it for DX up to about 1 Gbps; standard tunnels carry up to 1.25 Gbps each.' },
    { id: 'K24', src: 'New', line: 'dx',
      q: 'A company has one AWS Direct Connect connection at a location near Frankfurt. Applications on premises must reach VPCs in three AWS Regions: eu-central-1, eu-west-1 and us-east-1, all in the same account, over private IP addresses. What should a solutions architect do?',
      opts: [_o('Create a Direct Connect gateway, attach a private VIF to it, and associate the three VPCs’ virtual private gateways.', 1, 'A DX gateway is global: one private VIF reaches VGWs in any Region.'),
        _o('Create one private VIF per Region on the connection, each attached directly to that Region’s virtual private gateway.', 0, 'Without a DX gateway a private VIF reaches a VGW in the local Region only.'),
        _o('Attach a private VIF to the eu-central-1 VPC, and peer that VPC with the eu-west-1 and us-east-1 VPCs.', 0, 'Edge-to-edge through peering is not supported.'),
        _o('Create a transit gateway in eu-central-1, connect it with a transit VIF, and attach the VPCs from all three Regions.', 0, 'A transit gateway attaches VPCs in its own Region only; the other Regions need their own transit gateways.')],
      stub: { who: 'on-prem↔AWS', scale: 'many / hub', path: 'dedicated line', sup: 'none stated' }, words: ['one AWS Direct Connect connection', 'three AWS Regions'],
      expl: 'One DX to VPCs in several Regions (or accounts) = Direct Connect gateway. With many VPCs per Region, a transit VIF to a DX gateway associated with a transit gateway in each Region.' },

    /* ---------------- access ---------------- */
    { id: 'K25', src: 'New', line: 'access',
      q: 'Administrators need shell access to 200 EC2 instances in private subnets. The security team forbids inbound SSH rules on any security group and forbids long-lived SSH keys. Every session must be logged to Amazon S3. Which solution meets these requirements?',
      opts: [_o('Deploy a bastion host in a public subnet, and rotate the administrators’ SSH keys monthly with Secrets Manager.', 0, 'Needs inbound SSH and keys: both forbidden.'),
        _o('Use Session Manager with the SSM Agent and an instance profile, and enable session logging to an S3 bucket.', 1, 'No inbound ports, no SSH keys, IAM-controlled, sessions logged to S3.'),
        _o('Create an EC2 Instance Connect Endpoint, and allow SSH from its security group on the instances.', 0, 'Short-lived keys, but it needs an inbound port 22 rule from the endpoint.'),
        _o('Use Session Manager with the SSM Agent and an instance profile, and stream session logs to CloudWatch Logs.', 0, 'Logged, but to CloudWatch Logs; the requirement names Amazon S3.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'any', sup: 'none stated' }, words: ['forbids inbound SSH', 'long-lived SSH keys', 'logged to Amazon S3'],
      expl: 'No inbound ports + no keys + audit = Session Manager, with logging sent where the requirement says. (The instances reach Systems Manager through interface endpoints or NAT.)' },

    /* ---------------- inspection & tools ---------------- */
    { id: 'K26', src: 'New', line: 'inspect',
      q: 'A company has 30 VPCs attached to a transit gateway. The security team requires that outbound web traffic from every VPC goes only to an approved list of domains, and that traffic is checked with intrusion prevention rules. The team wants one managed service to maintain centrally. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('Send egress through an inspection VPC with AWS Network Firewall via the transit gateway, using domain list and IPS rules.', 1, 'Managed, central, domain filtering plus Suricata-compatible IPS.'),
        _o('Associate a Route 53 Resolver DNS Firewall rule group that allows only the approved domains with all 30 VPCs through AWS RAM.', 0, 'Filters DNS lookups by domain, but has no intrusion prevention.'),
        _o('Add network ACL rules in all 30 VPCs that allow outbound HTTPS only to the published IP ranges of the approved domains.', 0, 'NACLs match IP ranges and ports; no domains, no IPS, and the ranges change.'),
        _o('Deploy AWS WAF web ACLs with managed threat rule groups in every VPC, and filter the outbound web requests by domain name.', 0, 'WAF protects inbound HTTP to ALB, CloudFront and similar; it does not filter VPC egress.')],
      stub: { who: 'internet↔VPC', scale: 'many / hub', path: 'public internet', sup: 'least ops' }, words: ['approved list of domains', 'intrusion prevention', '30 VPCs'],
      expl: 'Here Network Firewall **is** the answer: domain allow-list + IPS + centralised through a TGW inspection VPC. The word that earns it is “intrusion prevention”.' },
    { id: 'K27', src: 'New', line: 'inspect',
      q: 'A company already licenses a third-party next-generation firewall and wants to run a fleet of its virtual appliances in AWS. The appliances must be inserted transparently in the traffic path of several VPCs and must scale automatically with traffic. Which solution meets these requirements?',
      opts: [_o('Deploy the appliances behind an Application Load Balancer, and route each VPC’s traffic to the load balancer.', 0, 'An ALB terminates HTTP; it is not a transparent network hop.'),
        _o('Deploy AWS Network Firewall in each VPC, and import the vendor’s rule sets as Suricata-compatible rules.', 0, 'Drops the licensed product the company wants to keep.'),
        _o('Deploy the appliances behind a Network Load Balancer, and point each VPC’s route tables at the load balancer.', 0, 'An NLB is not a route-table target for transparent inspection.'),
        _o('Deploy the appliances behind a Gateway Load Balancer, and route each VPC’s traffic through GWLB endpoints.', 1, 'Transparent bump-in-the-wire (GENEVE), scales the appliance fleet.')],
      stub: { who: 'any', scale: 'many / hub', path: 'private AWS network', sup: 'none stated' }, words: ['third-party next-generation firewall', 'transparently'],
      expl: 'Your own appliances, transparent, scaled = Gateway Load Balancer + GWLB endpoints.' },
    { id: 'K28', src: 'New', line: 'observe',
      q: 'After a change window, an EC2 instance can no longer connect to an Amazon RDS database in another subnet of the same VPC. The team wants to find which component (security group, network ACL or route table) blocks the path, without sending test traffic. Which tool should the team use?',
      opts: [_o('Enable VPC Flow Logs on the instance’s network interface, and look for REJECT records on the database port.', 0, 'Records flows that actually happened; it needs traffic and does not name the blocking rule.'),
        _o('Run VPC Reachability Analyzer from the instance’s network interface to the database’s network interface.', 1, 'Models the configuration and reports the component that blocks the path. Sends no packets.'),
        _o('Search AWS CloudTrail for security group and network ACL changes made during the change window.', 0, 'Shows who changed what, not whether or where the path is blocked.'),
        _o('Use Network Access Analyzer with a scope from the instance to the database, and review its findings.', 0, 'Finds access paths that exist and should not; it does not explain why a path is blocked.')],
      stub: { who: 'inside one VPC', scale: 'n/a', path: 'n/a', sup: 'none stated' }, words: ['without sending test traffic', 'which component'],
      expl: 'Configuration question, no traffic = Reachability Analyzer. “What traffic was rejected last week” = Flow Logs.' }
  ];
})();
