/* Session 3 drills (Networking & connectivity). stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit.
   Q7 and Q46 are his baseline-exam misses (mine: true). K-drills are new. */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _o = (t, ok, why) => ({ t, ok: !!ok, why });
  const BASTION = 'Banks still expect a bastion in a public subnet. For new designs AWS recommends Session Manager or EC2 Instance Connect Endpoint, which need no public bastion.';
  const RNAT = 'Since Nov 2025 a **regional NAT gateway** can replace the per-AZ pattern: one NAT gateway, no public subnet, expands to every AZ with workloads. Banks still expect one zonal NAT gateway per AZ.';
  S.drills = [
    /* ---------------- his exam misses ---------------- */
    { id: 'Q7', src: 'Exam Q7', line: 'peer', mine: true, tag: 'F',
      q: 'A company has three VPCs in the same AWS Region: VPC-A (10.0.0.0/16), VPC-B (10.1.0.0/16) and VPC-C (10.2.0.0/16). VPC-A is peered with VPC-B, and VPC-A is peered with VPC-C. Route tables and security groups are configured for both peering connections. Applications in VPC-B now also need to query a database in VPC-C. The company wants the most cost-effective solution that requires the least configuration. What should a solutions architect do?',
      opts: [_o('Add a route in VPC-B’s route table that sends 10.2.0.0/16 to the VPC-A peering connection.', 0, 'Peering is not transitive: VPC-A never forwards traffic between its peers.'),
        _o('Create a VPC peering connection between VPC-B and VPC-C, and add routes for each other’s CIDR in both route tables.', 1, 'One direct wire for the one pair that needs it: no hourly charge, two route entries.'),
        _o('Create a transit gateway, attach all three VPCs, and replace the peering routes with routes to the transit gateway.', 0, 'Works, but adds attachment-hours and per-GB charges and re-does all routing for three VPCs. Prestige distractor.'),
        _o('Enable DNS resolution support on both existing peering connections.', 0, 'DNS settings resolve names; they do not create a path from B to C.')],
      stub: { who: 'VPC↔VPC', scale: 'one pair', path: 'private AWS network', sup: 'cheapest' }, words: ['VPC-A is peered with VPC-B', 'most cost-effective', 'least configuration'],
      expl: 'WHO = VPC↔VPC, SCALE = one new pair (B–C). Peering is not transitive, so B–C needs its own peering connection. A transit gateway would work but costs more and changes everything: cheapest + least configuration = peer B with C.' },
    { id: 'Q46', src: 'Exam Q46', line: 'access', mine: true, tag: 'R',
      q: 'A company runs application servers on Amazon EC2 instances in private subnets of a VPC. Administrators must connect to the instances over SSH from the corporate network, whose public IP range is 203.0.113.0/24. The security team requires a single hardened bastion host and wants to minimise the exposure of the application servers. Which configuration meets these requirements?',
      opts: [_o('Launch the bastion host in a private subnet, assign it an Elastic IP address, and allow SSH from 203.0.113.0/24 in its security group.', 0, 'A private subnet has no route to the internet gateway, so the bastion is unreachable even with an Elastic IP. This was your pick.'),
        _o('Create a NAT gateway in a public subnet and forward inbound SSH from 203.0.113.0/24 through it to the application servers.', 0, 'A NAT gateway only carries connections that start inside the VPC. It cannot forward inbound SSH.'),
        _o('Launch the bastion host in a public subnet. Allow SSH from 203.0.113.0/24 in the bastion’s security group, and allow SSH on the application servers only from the bastion’s security group.', 1, 'Reachable from the corporate range only; the application servers accept SSH only from the bastion.'),
        _o('Launch the bastion host in a public subnet, and allow SSH from 0.0.0.0/0 in the application servers’ security group so the bastion can reach them.', 0, 'Opens the application servers to every address that can route to them. The opposite of minimal exposure.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'most secure' }, words: ['private subnets', 'single hardened bastion host', 'minimise the exposure'],
      expl: 'A bastion is only useful if admins can reach it: it must sit in a **public** subnet (route 0.0.0.0/0 → IGW). Minimal exposure = its SG allows 22 from the corporate range, and the app SG allows 22 only from the bastion SG.', update: BASTION },

    /* ---------------- VPC basics ---------------- */
    { id: 'K1', src: 'New', line: 'vpc',
      q: 'A company is designing a VPC with the CIDR block 10.20.0.0/16. Each application subnet must hold at least 100 EC2 instances plus 20 additional IP addresses for interface endpoints and Lambda network interfaces. The network team wants to use the smallest subnet size that meets this requirement so the rest of the range stays free. Which subnet size should the team use?',
      opts: [_o('/24', 0, '251 usable addresses: enough, but twice the size that is needed.'),
        _o('/26', 0, '64 − 5 reserved = 59 usable: too small.'),
        _o('/27', 0, '32 − 5 = 27 usable: far too small.'),
        _o('/25', 1, '128 − 5 reserved = 123 usable ≥ 120 needed. The smallest that fits.')],
      stub: { who: 'inside one VPC', scale: 'n/a', path: 'n/a', sup: 'none stated' }, words: ['at least 100 EC2 instances plus 20 additional IP addresses', 'smallest subnet size'],
      expl: 'Need 120 addresses. AWS reserves 5 in every subnet (network, router, DNS, one spare, broadcast). /26 gives 59, /25 gives 123. Do the “minus 5” every time.' },
    { id: 'K2', src: 'New', line: 'vpc',
      q: 'A developer launches an EC2 instance running a web server into a newly created subnet. The VPC has an internet gateway attached. Users on the internet cannot reach the instance, and the instance cannot download updates. The instance’s security group allows HTTP from 0.0.0.0/0, and the subnet uses the default network ACL. Which actions must a solutions architect take so that users can reach the web server? (Select TWO.)',
      opts: [_o('Add a route for 0.0.0.0/0 with the internet gateway as the target to the subnet’s route table.', 1, 'That route is what makes a subnet public.'),
        _o('Create a NAT gateway in the subnet and route 0.0.0.0/0 to it.', 0, 'NAT is outbound only; users still could not reach the server.'),
        _o('Assign a public IPv4 address or an Elastic IP address to the instance.', 1, 'The internet gateway translates to a public address; without one, nothing on the internet can address the instance.'),
        _o('Add an outbound rule for ephemeral ports 1024–65535 to the security group.', 0, 'Security groups are stateful and allow all outbound by default; replies are already allowed.'),
        _o('Create an egress-only internet gateway and associate it with the subnet.', 0, 'Egress-only gateways are for IPv6 outbound traffic only.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'none stated' }, words: ['newly created subnet', 'internet gateway attached', 'cannot reach the instance'],
      expl: 'Attaching an IGW to the VPC is not enough. A subnet is public only when its route table sends 0.0.0.0/0 to the IGW, and the instance needs a public IPv4 or Elastic IP.' },

    /* ---------------- NAT ---------------- */
    { id: 'K3', src: 'New', line: 'nat',
      q: 'EC2 instances in private subnets in two Availability Zones must download software patches from the internet. The internet must not be able to initiate connections to the instances. Internet access must keep working if one Availability Zone fails, and the solution must require the least operational overhead. Which solution meets these requirements?',
      opts: [_o('Create a NAT gateway in a public subnet in each Availability Zone, and route each private subnet to the NAT gateway in its own Availability Zone.', 1, 'Managed and redundant inside each AZ; an AZ failure only affects that AZ’s own subnets.'),
        _o('Launch one NAT instance in a public subnet and route both private subnets to it.', 0, 'One instance in one AZ is a single point of failure, and you patch and scale it yourself.'),
        _o('Attach an egress-only internet gateway and route 0.0.0.0/0 from the private subnets to it.', 0, 'Egress-only gateways carry IPv6 only; 0.0.0.0/0 is IPv4.'),
        _o('Route the private subnets to the internet gateway and remove all inbound rules from the security groups.', 0, 'Instances without public IPs cannot use the IGW, and this would make the subnets public.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'least ops' }, words: ['must not be able to initiate connections', 'if one Availability Zone fails', 'least operational overhead'],
      expl: 'Out only → NAT. Least ops → NAT gateway, not an instance. Survive an AZ failure → a zonal NAT gateway per AZ with per-AZ routes.', update: RNAT },
    { id: 'K4', src: 'New', line: 'nat',
      q: 'To save cost, a company routes a small private subnet through a NAT instance. After the team replaces the NAT instance with a new one built from a custom Amazon Linux 2023 AMI, instances in the private subnet can no longer reach the internet. The private route table sends 0.0.0.0/0 to the new instance, which is in a public subnet with an Elastic IP address, and its security group allows all traffic from the private subnet. What is the MOST likely cause?',
      opts: [_o('NAT instances only work with the AWS-provided NAT AMI.', 0, 'False: AWS documents building your own NAT AMI from current Amazon Linux.'),
        _o('An egress-only internet gateway must be attached for a NAT instance to forward traffic.', 0, 'Egress-only gateways are for IPv6; unrelated to IPv4 NAT.'),
        _o('The NAT instance needs an IAM role that allows it to route traffic.', 0, 'Packet forwarding has nothing to do with IAM.'),
        _o('Source/destination checking is still enabled on the new NAT instance.', 1, 'Every instance drops traffic that is not addressed to it unless the check is disabled; a NAT must forward other hosts’ traffic.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'none stated' }, words: ['NAT instance', 'custom Amazon Linux 2023 AMI', 'can no longer reach the internet'],
      expl: 'A NAT instance forwards packets whose source or destination is not itself, so its source/destination check must be disabled. New instance = check back on by default.',
      update: 'The AWS NAT AMI is built on Amazon Linux AMI 2018.03, which is past end of maintenance; AWS recommends NAT gateways, or building your own NAT AMI.' },
    { id: 'K15', src: 'New', line: 'nat',
      q: 'A company runs IPv6-only EC2 instances in a subnet of a dual-stack VPC. The instances must call IPv6 APIs on the internet. Nothing on the internet may initiate a connection to the instances. Which solution meets these requirements?',
      opts: [_o('Create an egress-only internet gateway and route ::/0 from the subnet to it.', 1, 'Stateful, IPv6, outbound only: exactly the job.'),
        _o('Create a NAT gateway and route ::/0 to it.', 0, 'IPv6 addresses need no translation; a NAT gateway’s IPv6 feature is NAT64 for reaching IPv4 destinations.'),
        _o('Assign public IPv4 addresses to the instances.', 0, 'The instances are IPv6-only and the targets are IPv6.'),
        _o('Put the instances behind AWS Global Accelerator.', 0, 'Global Accelerator brings users in to your endpoints; it is not an outbound path.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'none stated' }, words: ['IPv6', 'Nothing on the internet may initiate'],
      expl: 'IPv6 addresses are globally unique and public by default. “Outbound only” for IPv6 = egress-only internet gateway.' },

    /* ---------------- filtering ---------------- */
    { id: 'K5', src: 'New', line: 'filter',
      q: 'A web server in a public subnet listens on HTTPS (TCP 443). Its security group allows inbound TCP 443 from 0.0.0.0/0. The subnet uses a custom network ACL with inbound rule 100 allowing TCP 443 from 0.0.0.0/0 and outbound 100 allow TCP 443 to 0.0.0.0/0, followed by the default deny (*) rules. Clients reach the server, but their requests time out. What should a solutions architect change?',
      opts: [_o('Add an outbound rule to the security group that allows TCP 1024–65535 to 0.0.0.0/0.', 0, 'Security groups are stateful; replies to allowed inbound traffic already leave.'),
        _o('Add an inbound rule to the network ACL that allows TCP 1024–65535 from 0.0.0.0/0.', 0, 'That serves replies to connections the server starts. Here the replies go out.'),
        _o('Add an outbound rule to the network ACL that allows TCP 1024–65535 to 0.0.0.0/0.', 1, 'The server’s replies go to the client’s ephemeral port; the stateless NACL must allow them out.'),
        _o('Replace the network ACL with AWS Network Firewall.', 0, 'A managed firewall for a one-line NACL fix. Prestige distractor.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'none stated' }, words: ['custom network ACL', 'outbound 100 allow TCP 443', 'requests time out'],
      expl: 'NACLs are stateless. The reply to a client on port 443 goes back to the client’s ephemeral port (1024–65535), so the NACL needs an outbound allow for that range.' },
    { id: 'K6', src: 'New', line: 'filter',
      q: 'A company runs a public web application on EC2 instances in a public subnet, without a load balancer. The security team has found malicious requests coming from 198.51.100.0/24 and must block it immediately for every instance in the subnet. The network ACL currently has inbound rule 100 that allows TCP 443 from 0.0.0.0/0. The team wants the least cost and effort. What should a solutions architect do?',
      opts: [_o('Add a network ACL inbound rule numbered 50 that denies all traffic from 198.51.100.0/24.', 1, 'Evaluated before rule 100, subnet-wide, free.'),
        _o('Add a deny rule for 198.51.100.0/24 to the instances’ security group.', 0, 'Security groups have allow rules only.'),
        _o('Add a network ACL inbound rule numbered 200 that denies all traffic from 198.51.100.0/24.', 0, 'Rule 100 matches first and allows the traffic; 200 is never reached.'),
        _o('Deploy AWS Network Firewall in a new firewall subnet and route the traffic through it.', 0, 'Works, but costs money and effort for a one-line block. Prestige distractor.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'cheapest' }, words: ['must block it immediately', '198.51.100.0/24', 'least cost and effort'],
      expl: 'Deny = NACL (SGs cannot deny). NACL rules run lowest number first, so the deny must be numbered before the allow.' },
    { id: 'K7', src: 'New', line: 'filter',
      q: 'A three-tier application runs its web tier in an EC2 Auto Scaling group and its application tier on port 8080 in another Auto Scaling group, all in one VPC. The application tier must accept traffic only from the web tier instances, whose IP addresses change as the group scales. Which solution is the MOST secure and needs the least maintenance?',
      opts: [_o('Allow TCP 8080 from the VPC CIDR block in the application tier’s security group.', 0, 'Lets every resource in the VPC in, not only the web tier.'),
        _o('Write a Lambda function that updates the application tier’s security group with the web instances’ IP addresses on every scaling event.', 0, 'Custom code to do what a group reference does natively.'),
        _o('Allow TCP 8080 in the application tier’s security group with the web tier’s security group as the source.', 1, 'The rule follows group membership, whatever the IPs are.'),
        _o('Add network ACL rules on the application subnets that allow TCP 8080 from the web subnets’ CIDR blocks.', 0, 'Coarser (anything in those subnets), stateless, and needs return rules.')],
      stub: { who: 'inside one VPC', scale: 'n/a', path: 'n/a', sup: 'most secure' }, words: ['IP addresses change', 'only from the web tier'],
      expl: 'A security group rule can name another security group as its source. Membership, not addresses, decides: the tightest rule with zero upkeep.' },

    /* ---------------- endpoints / PrivateLink ---------------- */
    { id: 'K8', src: 'New', line: 'pl',
      q: 'EC2 instances in private subnets process several terabytes of objects each day from an Amazon S3 bucket in the same Region. Today the traffic goes through a NAT gateway, and the NAT gateway data processing charges are high. The company wants the traffic to stay off the internet and to reduce cost as much as possible. What should a solutions architect do?',
      opts: [_o('Create an interface VPC endpoint for Amazon S3 in each private subnet.', 0, 'Private, but billed per hour per AZ and per GB. Not the cheapest.'),
        _o('Put AWS Global Accelerator in front of the S3 bucket.', 0, 'Global Accelerator accelerates internet users to endpoints; it is not a private path from a VPC. Prestige distractor.'),
        _o('Replace the NAT gateway with a NAT instance.', 0, 'Still an internet path, and adds operations.'),
        _o('Create a gateway VPC endpoint for Amazon S3 and associate it with the private subnets’ route tables.', 1, 'Route-table target to S3, no charge, no internet.')],
      stub: { who: 'VPC→service', scale: 'n/a', path: 'private AWS network', sup: 'cheapest' }, words: ['same Region', 'NAT gateway', 'reduce cost as much as possible'],
      expl: 'S3 (or DynamoDB) from inside the VPC + cheapest = gateway endpoint: free, route-table based, and it removes the NAT processing charge.' },
    { id: 'K9', src: 'New', line: 'pl',
      q: 'An on-premises analytics cluster connects to a VPC over AWS Direct Connect with a private virtual interface. The cluster must read and write objects in Amazon S3 using private IP addresses only. The security policy forbids any traffic to public AWS endpoints. Which solution meets these requirements?',
      opts: [_o('Create a gateway VPC endpoint for Amazon S3 and route on-premises traffic through the VPC to it.', 0, 'Gateway endpoints do not allow access from on-premises networks.'),
        _o('Create an interface VPC endpoint for Amazon S3 and have the cluster use the endpoint-specific DNS names.', 1, 'Private IPs in the VPC, reachable over the DX private VIF.'),
        _o('Create a public virtual interface and use the regional S3 endpoints.', 0, 'That is exactly the public endpoint the policy forbids.'),
        _o('Enable S3 Transfer Acceleration on the bucket.', 0, 'Public edge endpoints over the internet: the opposite of private.')],
      stub: { who: 'on-prem↔AWS', scale: 'n/a', path: 'dedicated line', sup: 'most secure' }, words: ['private IP addresses only', 'forbids any traffic to public AWS endpoints', 'Direct Connect'],
      expl: 'From on-prem, only an **interface** endpoint works: it is an ENI with a private IP that DX (or VPN) traffic can reach. Gateway endpoints serve only the VPC they are in.' },
    { id: 'K10', src: 'New', line: 'pl',
      q: 'Lambda functions and EC2 instances run in private subnets that, by policy, have no internet access and no NAT gateway. The workloads must send messages to Amazon SQS and decrypt data with AWS KMS. Which solution meets these requirements?',
      opts: [_o('Create gateway VPC endpoints for Amazon SQS and AWS KMS.', 0, 'Gateway endpoints exist only for S3 and DynamoDB.'),
        _o('Add a NAT gateway only for the SQS and KMS API calls.', 0, 'Violates the no-internet policy.'),
        _o('Peer the VPC with the AWS service VPCs for SQS and KMS.', 0, 'You cannot peer with an AWS service; that is what endpoints are for.'),
        _o('Create interface VPC endpoints for Amazon SQS and AWS KMS with private DNS enabled.', 1, 'ENIs in your subnets; the default service names resolve to them.')],
      stub: { who: 'VPC→service', scale: 'n/a', path: 'private AWS network', sup: 'none stated' }, words: ['no internet access', 'Amazon SQS', 'AWS KMS'],
      expl: 'Any AWS API other than S3/DynamoDB from a private subnet without internet = interface endpoint (PrivateLink). Private DNS keeps the SDK’s default endpoints working.' },
    { id: 'K11', src: 'New', line: 'pl',
      q: 'A SaaS company runs an API on EC2 instances in its own VPC. Hundreds of customers must reach one TCP port of this API privately from their own VPCs in their own AWS accounts. Many customer VPCs use the same CIDR block, 10.0.0.0/16, as the provider VPC. Customers must not get access to any other resource in the provider VPC. Which solution meets these requirements?',
      opts: [_o('Create a VPC peering connection with each customer VPC and restrict access with security groups.', 0, 'Peering fails with overlapping CIDRs, and it opens whole networks.'),
        _o('Share a transit gateway with the customers through AWS RAM and attach their VPCs.', 0, 'Overlapping CIDRs cannot be routed, and it connects networks, not one service.'),
        _o('Put the API behind a Network Load Balancer, create a VPC endpoint service, and let customers create interface endpoints to it.', 1, 'PrivateLink: one service, one direction, overlapping CIDRs are fine.'),
        _o('Put the API behind AWS Global Accelerator and allow-list the customers’ IP addresses.', 0, 'Public internet entry; not private.')],
      stub: { who: 'VPC→service', scale: 'many / hub', path: 'private AWS network', sup: 'most secure' }, words: ['same CIDR block', 'must not get access to any other resource', 'Hundreds of customers'],
      expl: 'Expose one service to many consumers, overlapping CIDRs, nothing else visible → PrivateLink endpoint service behind an NLB.' },

    /* ---------------- peering ---------------- */
    { id: 'K14', src: 'New', line: 'peer',
      q: 'A reporting application in VPC-1 queries a database in VPC-2 a few times a day. Both VPCs are in the same AWS account and Region, and their CIDR blocks do not overlap. No other VPCs will be added. Which solution is the most cost-effective?',
      opts: [_o('Create a transit gateway and attach both VPCs.', 0, 'Two attachment-hours around the clock plus per-GB processing, for one pair. Prestige distractor.'),
        _o('Create a Site-to-Site VPN between virtual private gateways in the two VPCs.', 0, 'VPN connections terminate on customer gateways, and it would be slower and cost more.'),
        _o('Create a VPC peering connection and update both route tables and the database security group.', 1, 'No hourly charge, one pair, done.'),
        _o('Expose the database through a VPC endpoint service behind a Network Load Balancer.', 0, 'Works one-way, but pays for an NLB and endpoint hours.')],
      stub: { who: 'VPC↔VPC', scale: 'one pair', path: 'private AWS network', sup: 'cheapest' }, words: ['No other VPCs will be added', 'most cost-effective'],
      expl: 'Two VPCs, no overlap, cheapest → peering. There is no charge to create a peering connection; data within one AZ is free.' },
    { id: 'K16', src: 'New', line: 'peer',
      q: 'VPC-A has a NAT gateway that gives its private subnets internet access. VPC-B, which has no internet gateway, is peered with VPC-A. An administrator adds a 0.0.0.0/0 route in VPC-B that points to the peering connection, but instances in VPC-B still cannot reach the internet. What is the most cost-effective way to give VPC-B outbound internet access?',
      opts: [_o('Add a route in VPC-A’s NAT gateway subnet that sends VPC-B’s CIDR back through the peering connection.', 0, 'Edge-to-edge routing through a peering connection is not supported; the NAT gateway will not serve VPC-B.'),
        _o('Enable DNS resolution support on the peering connection.', 0, 'DNS does not create a route to the internet.'),
        _o('Create an internet gateway, a public subnet and a NAT gateway in VPC-B.', 1, 'VPC-B gets its own way out; nothing depends on the peer.'),
        _o('Replace the peering with a transit gateway and a new centralised egress VPC.', 0, 'A valid pattern for many VPCs; for two it adds attachment and processing charges.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'public internet', sup: 'cheapest' }, words: ['0.0.0.0/0', 'peering connection', 'still cannot reach the internet'],
      expl: 'No edge-to-edge: a peer cannot use the other VPC’s IGW, NAT, VPN, DX or gateway endpoint. For one VPC, give it its own NAT gateway.' },

    /* ---------------- Transit Gateway ---------------- */
    { id: 'K12', src: 'New', line: 'tgw',
      q: 'A company has 40 VPCs across 12 accounts in one AWS Region and two data centers connected by Site-to-Site VPN. Every VPC must reach every other VPC and both data centers. The current full mesh of VPC peering connections and per-VPC VPN connections has become unmanageable. Which solution meets these requirements with the least operational overhead?',
      opts: [_o('Create a transit gateway, share it with the other accounts through AWS RAM, attach all VPCs, and move the VPN connections to the transit gateway.', 1, 'One hub; every network attaches once; routing is central.'),
        _o('Keep the peering mesh and add VPN connections from each data center to every VPC.', 0, 'That is the unmanageable design, made bigger.'),
        _o('Build a transit VPC with third-party VPN appliances on EC2 instances.', 0, 'The pre-TGW pattern: you run, patch and scale the routers.'),
        _o('Create a Direct Connect gateway and associate all 40 VPCs so they route to each other.', 0, 'A Direct Connect gateway does not route traffic between the VPCs associated with it.')],
      stub: { who: 'VPC↔VPC', scale: 'many / hub', path: 'private AWS network', sup: 'least ops' }, words: ['40 VPCs', '12 accounts', 'unmanageable', 'least operational overhead'],
      expl: 'Many VPCs + on-prem, all-to-all, least ops = Transit Gateway. This is the TGW’s real job — the opposite of the two-VPC prestige trap.' },
    { id: 'K13', src: 'New', line: 'tgw',
      q: 'A company attaches development, production and shared-services VPCs to one transit gateway. Development and production VPCs must both reach the shared-services VPC, but development must never reach production, and production must never reach development. Which configuration meets these requirements?',
      opts: [_o('Keep the default transit gateway route table and add network ACL deny rules in every development and production subnet.', 0, 'Leaves the routes in place and relies on many stateless rules to hold back traffic.'),
        _o('Attach a security group to the transit gateway that blocks traffic between development and production.', 0, 'Transit gateways have no security groups.'),
        _o('Create one transit gateway per environment and peer them.', 0, 'More gateways and peering to maintain, for what route tables already do.'),
        _o('Create separate transit gateway route tables: development and production attachments use a table that has only the shared-services routes, and the shared-services attachment uses a table with routes to both.', 1, 'Segmentation by routing: no route, no path.')],
      stub: { who: 'VPC↔VPC', scale: 'many / hub', path: 'private AWS network', sup: 'most secure' }, words: ['development must never reach production', 'one transit gateway'],
      expl: 'Each attachment is associated with exactly one TGW route table. Give dev and prod a table without each other’s routes, and give shared services a table with both.' },

    /* ---------------- VPN ---------------- */
    { id: 'K17', src: 'New', line: 'vpn',
      q: 'A company must connect its data center to a VPC within one week so that a migration can start. All traffic between the sites must be encrypted. The data center has a 500 Mbps internet connection. Which solution meets these requirements MOST cost-effectively?',
      opts: [_o('Order a 1 Gbps dedicated AWS Direct Connect connection.', 0, 'Weeks to months to provision, and not encrypted by default.'),
        _o('Create an AWS Site-to-Site VPN connection from the customer gateway to a virtual private gateway, and configure both tunnels.', 1, 'Encrypted IPsec over the existing internet link, up in hours.'),
        _o('Deploy AWS Client VPN and install the client on the data center servers.', 0, 'Client VPN is for individual users’ devices, not site-to-site routing.'),
        _o('Use AWS Global Accelerator to route traffic from the data center to the VPC.', 0, 'Not a private network link. Prestige distractor.')],
      stub: { who: 'on-prem↔AWS', scale: 'one pair', path: 'encrypted tunnel', sup: 'fastest to set up' }, words: ['within one week', 'encrypted', '500 Mbps internet connection'],
      expl: 'Deadline in days + encrypted + an internet link that is big enough = Site-to-Site VPN. Two tunnels in two AZs for redundancy.' },
    { id: 'K18', src: 'New', line: 'vpn',
      q: 'A company has 800 remote employees who work from laptops at home and while travelling. They need access to internal applications in a VPC and in the data center, which is already connected to the VPC. Users must authenticate with the company’s Active Directory, and the service must scale without the company managing VPN servers. Which solution meets these requirements?',
      opts: [_o('Create an AWS Client VPN endpoint that uses Active Directory authentication, with routes to the VPC and the data center.', 1, 'Managed, OpenVPN-based, scales with users, AD-integrated.'),
        _o('Create a Site-to-Site VPN connection for each laptop.', 0, 'Site-to-Site VPN connects networks through a customer gateway device, not individual laptops.'),
        _o('Deploy a bastion host in a public subnet for the employees.', 0, 'A shell jump host, not network access for 800 users.'),
        _o('Order a hosted Direct Connect connection for the remote employees.', 0, 'DX connects a building; homes and hotels have no DX.')],
      stub: { who: 'on-prem↔AWS', scale: 'many / hub', path: 'encrypted tunnel', sup: 'least ops' }, words: ['remote employees', 'laptops', 'Active Directory'],
      expl: 'People (not sites) outside AWS → Client VPN. Remote users count as the “outside” end: WHO = on-prem↔AWS.' },
    { id: 'K19', src: 'New', line: 'vpn',
      q: 'A retailer has six branch offices. Each branch already has a Site-to-Site VPN connection to the same virtual private gateway, and each uses a unique BGP ASN with non-overlapping IP ranges. The branches now need to exchange traffic with each other. The company wants a low-cost solution without new circuits. What should a solutions architect recommend?',
      opts: [_o('Order Direct Connect with SiteLink for every branch.', 0, 'New circuits at every branch: the opposite of the brief.'),
        _o('Use AWS VPN CloudHub so the virtual private gateway re-advertises each branch’s routes to the others.', 1, 'Hub-and-spoke over the existing VPNs; low cost.'),
        _o('Create VPC peering connections between the branches.', 0, 'Branches are not VPCs; peering joins VPCs only.'),
        _o('Replace the virtual private gateway with AWS Network Firewall.', 0, 'A firewall is not a VPN hub. Prestige distractor.')],
      stub: { who: 'on-prem↔AWS', scale: 'many / hub', path: 'encrypted tunnel', sup: 'cheapest' }, words: ['same virtual private gateway', 'with each other', 'without new circuits'],
      expl: 'Branches ↔ branches through existing VPNs on one VGW, unique ASNs = VPN CloudHub.' },

    /* ---------------- Direct Connect ---------------- */
    { id: 'K20', src: 'New', line: 'dx',
      q: 'A company transfers about 5 TB between its data center and AWS every day over a Site-to-Site VPN. Latency and throughput vary during business hours. The company needs consistent performance of 10 Gbps over a private connection. The project will go live in three months. Which solution meets these requirements?',
      opts: [_o('Add more tunnels to the virtual private gateway and use ECMP.', 0, 'A VGW does not support ECMP across tunnels, and it is still the internet.'),
        _o('Enable acceleration on the existing VPN connection.', 0, 'Acceleration needs a TGW and a new connection, and it is still an internet-borne VPN.'),
        _o('Put AWS Global Accelerator in front of the VPC.', 0, 'For internet users reaching endpoints. Prestige distractor.'),
        _o('Order a 10 Gbps dedicated AWS Direct Connect connection.', 1, 'Private, consistent, and three months is enough lead time.')],
      stub: { who: 'on-prem↔AWS', scale: 'one pair', path: 'dedicated line', sup: 'consistent bandwidth' }, words: ['consistent performance of 10 Gbps', 'three months'],
      expl: 'Consistent + private + large every day, and months of lead time = Direct Connect.' },
    { id: 'K21', src: 'New', line: 'dx',
      q: 'A bank connects its data center to AWS with a 10 Gbps dedicated AWS Direct Connect connection and a private virtual interface. A new regulation requires that all traffic between the data center and AWS is encrypted in transit. Which solutions meet this requirement? (Select TWO.)',
      opts: [_o('Enable MACsec on the 10 Gbps dedicated connection at a Direct Connect location that supports it.', 1, 'Layer-2, point-to-point encryption on 10/100/400 Gbps dedicated ports.'),
        _o('No change is needed, because Direct Connect encrypts traffic by default.', 0, 'False: Direct Connect does not encrypt traffic in transit by default.'),
        _o('Run an AWS Site-to-Site VPN over the Direct Connect connection (over a public VIF, or a private IP VPN over a transit VIF to a transit gateway).', 1, 'IPsec end to end on top of the private line.'),
        _o('Deploy AWS Network Firewall in the VPC to encrypt traffic from the data center.', 0, 'Network Firewall inspects traffic; it does not encrypt the link. Prestige distractor.'),
        _o('Turn on encryption for the private virtual interface in the Direct Connect console.', 0, 'There is no such setting.')],
      stub: { who: 'on-prem↔AWS', scale: 'one pair', path: 'dedicated line', sup: 'most secure' }, words: ['encrypted in transit', '10 Gbps dedicated'],
      expl: 'DX alone is private but not encrypted. Two ways to encrypt it: MACsec (supported dedicated speeds and locations) or IPsec VPN over DX.' },
    { id: 'K22', src: 'New', line: 'dx',
      q: 'A trading platform depends on AWS Direct Connect. The connectivity must survive a device failure, a fibre cut, and the loss of an entire Direct Connect location, and the company wants the highest level of resiliency that AWS recommends for critical workloads. Which design meets these requirements?',
      opts: [_o('Two dedicated connections terminating on separate devices at one Direct Connect location.', 0, 'The Development and Test model: survives a device failure, not a location failure.'),
        _o('Separate dedicated connections on separate devices at each of two Direct Connect locations.', 1, 'The Maximum Resiliency model: device, fibre and location failures.'),
        _o('One dedicated connection with a Site-to-Site VPN as backup.', 0, 'A cheap backup, not the highest resiliency; the VPN rides the internet.'),
        _o('One dedicated connection plus AWS Global Accelerator for failover.', 0, 'Global Accelerator does not back up a private link. Prestige distractor.')],
      stub: { who: 'on-prem↔AWS', scale: 'one pair', path: 'dedicated line', sup: 'resilient' }, words: ['loss of an entire Direct Connect location', 'highest level of resiliency'],
      expl: 'The Direct Connect Resiliency Toolkit models: Maximum (separate connections on separate devices in more than one location), High (one connection at each of two locations), Development and Test (two connections, one location).' },
    { id: 'K23', src: 'New', line: 'dx',
      q: 'A company has a single 1 Gbps AWS Direct Connect connection to a virtual private gateway for non-critical workloads. Traffic averages 300 Mbps. The company wants a low-cost backup path that takes over automatically if the Direct Connect connection fails. What should a solutions architect recommend?',
      opts: [_o('Order a second dedicated Direct Connect connection at another location.', 0, 'The most resilient, but not low-cost, and weeks away.'),
        _o('Order a 500 Mbps hosted connection from a Direct Connect Partner.', 0, 'Cheaper than dedicated, still a monthly circuit and lead time.'),
        _o('Create a Site-to-Site VPN connection to the same virtual private gateway, and let BGP prefer the Direct Connect path.', 1, 'Cheap, up in hours, 300 Mbps fits one tunnel.'),
        _o('Create a Transit Gateway Connect attachment as the backup.', 0, 'Connect is GRE for SD-WAN appliances over an existing transport; not a backup path.')],
      stub: { who: 'on-prem↔AWS', scale: 'one pair', path: 'encrypted tunnel', sup: 'cheapest' }, words: ['low-cost backup', '1 Gbps', 'averages 300 Mbps'],
      expl: 'Low-cost DX backup = Site-to-Site VPN. AWS advises it for DX up to about 1 Gbps; standard tunnels carry up to 1.25 Gbps each.' },
    { id: 'K24', src: 'New', line: 'dx',
      q: 'A company has one AWS Direct Connect connection at a location near Frankfurt. Applications on premises must reach VPCs in three AWS Regions: eu-central-1, eu-west-1 and us-east-1, all in the same account, over private IP addresses. What should a solutions architect do?',
      opts: [_o('Create a Direct Connect gateway, attach a private virtual interface to it, and associate the virtual private gateways of the three VPCs.', 1, 'A DX gateway is global: one private VIF reaches VGWs in any Region.'),
        _o('Create a private virtual interface directly to each VPC’s virtual private gateway, one per Region.', 0, 'Without a DX gateway a private VIF reaches one VPC in the local Region only.'),
        _o('Peer the eu-central-1 VPC with the other two VPCs and route on-premises traffic through it.', 0, 'Edge-to-edge through peering is not supported.'),
        _o('Use AWS Global Accelerator to route on-premises traffic to the three Regions.', 0, 'Not a private hybrid link. Prestige distractor.')],
      stub: { who: 'on-prem↔AWS', scale: 'many / hub', path: 'dedicated line', sup: 'none stated' }, words: ['one AWS Direct Connect connection', 'three AWS Regions'],
      expl: 'One DX to VPCs in several Regions (or accounts) = Direct Connect gateway. With many VPCs per Region, a transit VIF to a DX gateway associated with transit gateways.' },

    /* ---------------- access ---------------- */
    { id: 'K25', src: 'New', line: 'access',
      q: 'Administrators need shell access to 200 EC2 instances in private subnets. The security team forbids inbound SSH rules on any security group and forbids long-lived SSH keys. Every session must be logged to Amazon S3. Which solution meets these requirements?',
      opts: [_o('Deploy a bastion host in a public subnet with SSH keys rotated monthly.', 0, 'Needs inbound SSH and keys: both forbidden.'),
        _o('Create an EC2 Instance Connect Endpoint and allow SSH from it in the instances’ security groups.', 0, 'Needs an inbound port 22 rule from the endpoint.'),
        _o('Connect through AWS Client VPN and use SSH to each instance.', 0, 'Still SSH with keys and inbound port 22.'),
        _o('Use AWS Systems Manager Session Manager with the SSM Agent and an instance profile, and enable session logging to Amazon S3.', 1, 'No inbound ports, no SSH keys, IAM-controlled, sessions logged.')],
      stub: { who: 'internet↔VPC', scale: 'n/a', path: 'any', sup: 'most secure' }, words: ['forbids inbound SSH', 'long-lived SSH keys', 'logged to Amazon S3'],
      expl: 'No inbound ports + no keys + audit = Session Manager. (The instances reach Systems Manager through interface endpoints or NAT.)' },

    /* ---------------- inspection & tools ---------------- */
    { id: 'K26', src: 'New', line: 'inspect',
      q: 'A company has 30 VPCs attached to a transit gateway. The security team requires that outbound web traffic from every VPC goes only to an approved list of domains, and that traffic is checked with intrusion prevention rules. The team wants one managed service to maintain centrally. Which solution meets these requirements?',
      opts: [_o('Add the approved domain names to outbound security group rules in every VPC.', 0, 'Security groups use IP ranges, prefix lists and groups, not domain names.'),
        _o('Create network ACL rules that allow only the approved domains.', 0, 'NACLs match IP ranges and ports; no domains, no IPS.'),
        _o('Create an inspection VPC with AWS Network Firewall, route egress from all VPCs through it via the transit gateway, and use stateful domain list and IPS rules.', 1, 'Managed, central, domain filtering plus Suricata-compatible IPS.'),
        _o('Enable VPC Flow Logs and alert on unapproved domains.', 0, 'Flow logs record IP flows after the fact; they block nothing.')],
      stub: { who: 'internet↔VPC', scale: 'many / hub', path: 'public internet', sup: 'least ops' }, words: ['approved list of domains', 'intrusion prevention', '30 VPCs'],
      expl: 'Here Network Firewall **is** the answer: domain allow-list + IPS + centralised through a TGW inspection VPC. The word that earns it is “intrusion prevention”.' },
    { id: 'K27', src: 'New', line: 'inspect',
      q: 'A company already licenses a third-party next-generation firewall and wants to run a fleet of its virtual appliances in AWS. The appliances must be inserted transparently in the traffic path of several VPCs and must scale automatically with traffic. Which solution meets these requirements?',
      opts: [_o('Deploy the appliances behind an Application Load Balancer.', 0, 'An ALB terminates HTTP; it is not a transparent network hop.'),
        _o('Replace the appliances with AWS Network Firewall.', 0, 'Drops the licensed product the company wants to keep.'),
        _o('Deploy the appliances behind a Network Load Balancer and point route tables at it.', 0, 'An NLB is not a route-table target for transparent inspection.'),
        _o('Deploy the appliances behind a Gateway Load Balancer and route each VPC’s traffic through Gateway Load Balancer endpoints.', 1, 'Transparent bump-in-the-wire (GENEVE), scales the appliance fleet.')],
      stub: { who: 'any', scale: 'many / hub', path: 'private AWS network', sup: 'none stated' }, words: ['third-party next-generation firewall', 'transparently'],
      expl: 'Your own appliances, transparent, scaled = Gateway Load Balancer + GWLB endpoints.' },
    { id: 'K28', src: 'New', line: 'observe',
      q: 'After a change window, an EC2 instance can no longer connect to an Amazon RDS database in another subnet of the same VPC. The team wants to find which component (security group, network ACL or route table) blocks the path, without sending test traffic. Which tool should the team use?',
      opts: [_o('VPC Flow Logs', 0, 'Records IP flows that actually happened (accept/reject); it needs traffic and does not name the blocking rule.'),
        _o('VPC Reachability Analyzer', 1, 'Models the configuration and reports the component that blocks the path. Sends no packets.'),
        _o('AWS CloudTrail', 0, 'Records API calls: who changed what, not whether the path works.'),
        _o('AWS Network Firewall logs', 0, 'Only for traffic that passes a firewall, which this path has none of.')],
      stub: { who: 'inside one VPC', scale: 'n/a', path: 'n/a', sup: 'none stated' }, words: ['without sending test traffic', 'which component'],
      expl: 'Configuration question, no traffic = Reachability Analyzer. “What traffic was rejected last week” = Flow Logs.' }
  ];
})();
