/* Session 7 drills (HA & disaster recovery). stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit.
   H1 (Exam Q61, tag F) and H2 (Exam Q29, tag C) come from his baseline misses; H3–H5 from his prestige-distractor
   pattern (src 'Exam pattern', tag C): multi-site + Global Accelerator tempting and wrong (H3), Global Accelerator
   genuinely right (H4), a second Region / Global Accelerator for an AZ failure wrong (H5).
   Other drills with a prestige option that is wrong: H6 H9 H10 H13 H22 H26 H28 H30.
   Select TWO: H11, H24. Correct letters: A 7 · B 7 · C 7 · D 7 · BD 1 · AC 1. */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _o = (t, ok, why) => ({ t, ok: !!ok, why });
  const GA_AZ = 'Global Accelerator fronts endpoints in one or more Regions with static IPs. The load balancer already spans the AZs, so it adds nothing against an AZ failure — prestige distractor.';
  const MS_COST = 'Multi-site active/active runs full production in two Regions all the time: the most expensive strategy, for RTO and RPO near zero.';
  S.drills = [
    /* ---------------- his record ---------------- */
    { id: 'H1', src: 'Exam Q61', line: 'rds', mine: true, tag: 'F',
      q: 'An application connects to an Amazon RDS for PostgreSQL Multi-AZ DB instance using the DB instance endpoint. The primary instance’s Availability Zone suffers an outage. What happens, and what must the application team do so that the application reconnects?',
      opts: [_o('RDS moves the primary’s IP address to the standby; the team must restart the application servers.', 0, 'No IP address moves; the endpoint name stays and its DNS record changes.'),
        _o('The team must promote the read replica and update the connection string to the replica’s endpoint.', 0, 'A Multi-AZ standby is not a read replica, and Multi-AZ failover is automatic.'),
        _o('RDS fails over automatically by pointing the endpoint’s DNS CNAME at the standby, which becomes the primary; the application reconnects to the same endpoint.', 1, 'That is the mechanism: same endpoint name, new target. Typically 60–120 seconds; apps should retry and not cache DNS for long.'),
        _o('Put AWS Global Accelerator in front of the database so that clients keep one static IP address during failover.', 0, 'Global Accelerator does not front RDS databases, and the endpoint already survives failover — prestige distractor.')],
      stub: { fail: 'AZ', rto: 'minutes', rpo: 'zero', sup: 'least ops' }, words: ['Multi-AZ DB instance', 'DB instance endpoint', 'reconnects'],
      expl: 'Your baseline **Q61**. Multi-AZ = a **synchronous** standby in another AZ (so RPO zero). On failure RDS updates the endpoint’s **DNS CNAME** to the standby; the application just reconnects to the same name.' },
    { id: 'H2', src: 'Exam Q29', line: 'backup', mine: true, tag: 'C',
      q: 'A company runs workloads on Amazon EC2 with EBS volumes, Amazon RDS, Amazon DynamoDB and Amazon EFS. It needs daily backups of all of them managed from one place, with copies kept in a second AWS Region and in a separate backup account, with the least operational overhead.',
      opts: [_o('Use Amazon Data Lifecycle Manager policies to snapshot the resources and copy the snapshots to the other Region and account.', 0, 'DLM automates EBS snapshots and EBS-backed AMIs only — it cannot back up RDS, DynamoDB or EFS.'),
        _o('Create an AWS Backup plan that selects the resources by tag, with copy rules to a vault in the second Region and to a vault in the backup account.', 1, 'One plan, many services, cross-Region and cross-account copies built in.'),
        _o('Write a Lambda function per service that creates snapshots and copies them, triggered by EventBridge Scheduler.', 0, 'Works, but it is custom code for what AWS Backup does — fails least ops.'),
        _o('Enable S3 Cross-Region Replication on the buckets where each service stores its snapshots.', 0, 'You cannot replicate service-managed snapshots with S3 CRR; they are not in your buckets.')],
      stub: { fail: 'Region', rto: 'hours', rpo: 'hours', sup: 'least ops' }, words: ['EBS volumes, Amazon RDS, Amazon DynamoDB and Amazon EFS', 'managed from one place', 'separate backup account', 'least operational overhead'],
      expl: 'Your baseline **Q29** was DLM vs AWS Backup. **DLM = EBS only**, the simplest tool when only EBS is named. Several services + another account + one place = **AWS Backup**.' },
    { id: 'H3', src: 'Exam pattern', line: 'tiers', mine: true, tag: 'C',
      q: 'A company runs an internal reporting application in one AWS Region on EC2 instances and Amazon RDS. The business accepts an RTO of 24 hours and an RPO of 24 hours for a Regional disaster. The DR solution must be the most cost-effective.',
      opts: [_o('Deploy the full stack in a second Region, replicate the database with Aurora Global Database, and route users with AWS Global Accelerator (multi-site active/active).', 0, MS_COST + ' Global Accelerator adds nothing a 24-hour RTO needs — prestige distractor.'),
        _o('Run a scaled-down copy of the application in a second Region with a cross-Region read replica (warm standby).', 0, 'Pays all year for minutes of RTO that nobody asked for.'),
        _o('Keep a cross-Region read replica running and AMIs ready, with the compute switched off (pilot light).', 0, 'Cheaper than warm standby, but still pays for a replica to get an RPO of minutes; 24 hours allows backups.'),
        _o('Take daily backups with AWS Backup, copy them to a second Region, and keep the infrastructure as code to rebuild and restore there after a disaster (backup and restore).', 1, 'Nothing runs in the DR Region; RPO and RTO of hours are exactly backup and restore.')],
      stub: { fail: 'Region', rto: 'hours', rpo: 'hours', sup: 'cheapest' }, words: ['RTO of 24 hours', 'RPO of 24 hours', 'most cost-effective'],
      expl: 'RTO and RPO in **hours** + **most cost-effective** = **backup and restore**. The most complete option is the prestige distractor: multi-site plus Global Accelerator is the right design for near-zero RTO, not for 24 hours.' },
    { id: 'H4', src: 'Exam pattern', line: 'ga', mine: true, tag: 'C',
      q: 'A company serves a TCP and UDP game API from Network Load Balancers in us-east-1 and eu-west-1. Partners allow-list the API’s IP addresses in their firewalls, so the addresses must never change. If one Region fails, traffic must move to the other within about a minute without depending on DNS caches expiring.',
      opts: [_o('Create an AWS Global Accelerator with an endpoint group in each Region, the NLBs as endpoints, and give partners the two static anycast IP addresses.', 1, 'Static IPs that never change, UDP support, and health-based failover at the edge with no DNS TTL.'),
        _o('Create Route 53 failover records with health checks pointing to the two NLBs, with a TTL of 60 seconds.', 0, 'The answer changes to the other NLB’s addresses — partners’ allow lists break, and resolvers may cache longer.'),
        _o('Put an Amazon CloudFront distribution in front of both NLBs with an origin group for failover.', 0, 'CloudFront proxies HTTP(S) and WebSocket traffic, not a TCP and UDP game API, and origin failover only retries GET, HEAD and OPTIONS requests.'),
        _o('Assign Elastic IP addresses to the NLBs and move them to the other Region during a failure.', 0, 'Elastic IPs are regional; they cannot move to another Region.')],
      stub: { fail: 'Region', rto: 'minutes', rpo: 'any', sup: 'none stated' }, words: ['allow-list the API’s IP addresses', 'must never change', 'TCP and UDP', 'without depending on DNS caches'],
      expl: 'Here **Global Accelerator is genuinely the answer**: static IPs + UDP + failover without DNS. The prestige test is not “never pick GA”; it is “pick it only when the scenario gives its built-for reason”.' },
    { id: 'H5', src: 'Exam pattern', line: 'asg', mine: true, tag: 'C',
      q: 'A web application runs on EC2 instances in a single Availability Zone behind an Application Load Balancer, with an Amazon RDS for MySQL Single-AZ database. The company wants the application to survive the failure of an Availability Zone with minimal cost and no manual steps.',
      opts: [_o('Deploy a copy of the stack in a second Region and put AWS Global Accelerator in front of both Regions.', 0, GA_AZ + ' A second Region also doubles the cost.'),
        _o('Change the Auto Scaling group to span at least two Availability Zones behind the ALB, and convert the database to a Multi-AZ deployment.', 1, 'Both tiers now survive an AZ: the ALB routes to healthy instances in other AZs, the database fails over automatically.'),
        _o('Migrate the database to Aurora Global Database with a secondary Region.', 0, 'A cross-Region answer to an AZ problem; the EC2 tier would still sit in one AZ.'),
        _o('Take hourly EBS snapshots and RDS snapshots so the stack can be restored in another AZ.', 0, 'Restoring takes hours and needs manual steps; the requirement is to keep running.')],
      stub: { fail: 'AZ', rto: 'minutes', rpo: 'zero', sup: 'cheapest' }, words: ['single Availability Zone', 'survive the failure of an Availability Zone', 'minimal cost', 'no manual steps'],
      expl: 'FAILURE = AZ → **high availability inside the Region**: Auto Scaling across AZs + ALB + RDS Multi-AZ. Anything with a second Region or Global Accelerator answers a bigger failure at a bigger price — your prestige pattern.' },

    /* ---------------- DR strategies ---------------- */
    { id: 'H6', src: 'New', line: 'tiers',
      q: 'An order-processing system must be recoverable in a second AWS Region with an RPO of a few minutes and an RTO of about 30 minutes. Management wants the lowest cost that meets these targets. The database is Amazon Aurora MySQL and the application runs on EC2 in an Auto Scaling group.',
      opts: [_o('Replicate the database continuously to the second Region, keep AMIs and infrastructure templates there, and leave the application tier switched off until a disaster (pilot light).', 1, 'Data is live (RPO minutes); compute is started and scaled on failover (tens of minutes).'),
        _o('Copy nightly AWS Backup recovery points to the second Region (backup and restore).', 0, 'A nightly backup means up to 24 hours of data loss — fails the RPO.'),
        _o('Run the full application at production size in both Regions behind Route 53 latency records (multi-site).', 0, MS_COST),
        _o('Add AWS Global Accelerator in front of the primary Region’s load balancer.', 0, 'Global Accelerator only routes to endpoints that exist; with nothing running in the second Region it recovers nothing — prestige distractor.')],
      stub: { fail: 'Region', rto: 'tens of min', rpo: 'minutes', sup: 'cheapest' }, words: ['RPO of a few minutes', 'RTO of about 30 minutes', 'lowest cost'],
      expl: 'RPO minutes rules out backups; RTO tens of minutes leaves time to start compute; cheapest → **pilot light**. (Aurora Global Database or a cross-Region replica is the always-on core.)' },
    { id: 'H7', src: 'New', line: 'tiers',
      q: 'A company’s customer portal must keep serving at least some traffic within minutes of losing its primary Region, even before the DR site is scaled up. Data loss must be limited to seconds. The company does not want to pay for full production capacity in two Regions.',
      opts: [_o('Pilot light: replicate the database and keep the application servers switched off.', 0, 'Pilot light cannot process requests until compute is started — fails “keep serving … before the DR site is scaled up”.'),
        _o('Backup and restore with hourly snapshots copied to the DR Region.', 0, 'Hours of RTO and up to an hour of data loss.'),
        _o('Warm standby: run a scaled-down but fully functional copy in the DR Region with continuous data replication, and scale it up during failover.', 1, 'It can take traffic immediately at reduced capacity; seconds of RPO with continuous replication.'),
        _o('Multi-site active/active with full capacity in both Regions.', 0, 'Meets the targets but violates “not … full production capacity in two Regions”.')],
      stub: { fail: 'Region', rto: 'minutes', rpo: 'seconds', sup: 'cheapest' }, words: ['keep serving at least some traffic', 'before the DR site is scaled up', 'limited to seconds', 'not want to pay for full production capacity'],
      expl: 'Serving immediately at reduced capacity = **warm standby** (Well-Architected: RPO seconds, RTO minutes). Pilot light must start compute first; multi-site pays for full capacity twice.' },
    { id: 'H8', src: 'New', line: 'tiers',
      q: 'A global payments API has customers in North America and Europe. It must tolerate the loss of an entire AWS Region with effectively zero downtime; users should always be served from the nearest healthy Region. Cost is secondary to availability.',
      opts: [_o('Warm standby in eu-west-1 with Route 53 failover records.', 0, 'A failover still has to detect, scale and shift — minutes of downtime.'),
        _o('Pilot light in eu-west-1 with an Aurora cross-Region replica.', 0, 'Tens of minutes of RTO.'),
        _o('Backup and restore with AWS Backup copies to eu-west-1.', 0, 'Hours of RTO.'),
        _o('Run the full stack in both Regions, store data in DynamoDB global tables, and route users with Route 53 latency-based records and health checks (multi-site active/active).', 1, 'Both Regions serve users all the time; when one fails, health checks remove it and the other already has the data.')],
      stub: { fail: 'Region', rto: 'near zero', rpo: 'seconds', sup: 'none stated' }, words: ['effectively zero downtime', 'served from the nearest healthy Region', 'Cost is secondary'],
      expl: 'Near-zero RTO and users in several Regions = **multi-site active/active**. Here the most expensive strategy is right because the question pays for it explicitly (“cost is secondary”).' },

    /* ---------------- HA inside a Region ---------------- */
    { id: 'H9', src: 'New', line: 'asg',
      q: 'A stateless web tier needs 12 EC2 instances to handle peak load. It must keep full capacity during an Availability Zone failure without relying on launching new instances during the event. The company wants the most cost-effective layout.',
      opts: [_o('12 instances in each of two Availability Zones (24 in total).', 0, 'Survives, but +100% spare capacity; three AZs need only +50%.'),
        _o('6 instances in each of three Availability Zones (18 in total).', 1, 'Lose any one AZ and 12 remain — full capacity with no launches, at +50%.'),
        _o('4 instances in each of three Availability Zones with Auto Scaling to replace lost capacity.', 0, 'Relies on launching 4 instances during the event — the requirement rules that out.'),
        _o('12 instances in one Availability Zone and 12 in a second Region behind Global Accelerator.', 0, 'A second Region for an AZ failure — prestige distractor, and the most expensive.')],
      stub: { fail: 'AZ', rto: 'near zero', rpo: 'any', sup: 'cheapest' }, words: ['keep full capacity during an Availability Zone failure', 'without relying on launching new instances', 'most cost-effective'],
      expl: '**Static stability**: pre-provision so the survivors carry the load. With k AZs you need N/(k−1) per AZ: 3 AZs × 6 = 18 beats 2 AZs × 12 = 24.' },
    { id: 'H10', src: 'New', line: 'asg',
      q: 'A licensed legacy application runs on a single EC2 instance with EBS volumes and cannot be clustered. Its license is tied to the instance’s private IP address. If the underlying host fails, the instance must come back automatically with the same instance ID, IP addresses and volumes.',
      opts: [_o('Rely on EC2 automatic recovery (simplified automatic recovery, or a CloudWatch alarm with the recover action on the system status check).', 1, 'Recovery moves the instance to new hardware keeping its ID, private and Elastic IPs, metadata and EBS volumes.'),
        _o('Put the instance in an Auto Scaling group with a minimum and maximum of 1.', 0, 'The group launches a **new** instance with a new ID and a new private IP.'),
        _o('Put AWS Global Accelerator in front of the instance.', 0, 'Nothing to fail over to; it does not repair the host — prestige distractor.'),
        _o('Enable EBS Multi-Attach so a second instance can take over the volumes.', 0, 'Needs a cluster-aware application and a second instance with another IP.')],
      stub: { fail: 'instance', rto: 'minutes', rpo: 'zero', sup: 'least ops' }, words: ['cannot be clustered', 'same instance ID, IP addresses and volumes', 'underlying host fails'],
      expl: 'One instance that must stay **the same instance** = **EC2 automatic recovery** (on by default for supported types). Instance-store data would be lost; this instance uses EBS.' },

    /* ---------------- RDS ---------------- */
    { id: 'H11', src: 'New', line: 'rds',
      q: 'An Amazon RDS for MySQL database is slowed down by heavy reporting queries, and it must also fail over automatically if its Availability Zone fails. Which TWO actions meet both requirements? (Select TWO.)',
      opts: [_o('Increase the backup retention period to 35 days.', 0, 'Backups help restore, not read load or automatic failover.'),
        _o('Create a read replica and point the reporting tool at it.', 1, 'Asynchronous, readable copy that takes the reporting load.'),
        _o('Send the reporting queries to the Multi-AZ standby instance.', 0, 'A Multi-AZ DB instance standby serves no traffic.'),
        _o('Convert the DB instance to a Multi-AZ deployment.', 1, 'Synchronous standby with automatic failover.')],
      stub: { fail: 'AZ', rto: 'minutes', rpo: 'zero', sup: 'none stated' }, words: ['heavy reporting queries', 'fail over automatically'],
      expl: 'Two needs, two features: **read replica** for reads, **Multi-AZ** for automatic failover. (A Multi-AZ DB cluster’s readable standbys could cover both in one deployment.)' },
    { id: 'H12', src: 'New', line: 'rds',
      q: 'A PostgreSQL database on Amazon RDS must fail over in well under a minute when an AZ fails, and the company wants the standby capacity to serve read traffic instead of sitting idle. It must stay on RDS for PostgreSQL.',
      opts: [_o('A Multi-AZ DB instance deployment.', 0, 'Failover typically 60–120 seconds, and its standby serves no reads.'),
        _o('A single-AZ instance with two read replicas in other AZs.', 0, 'Replicas are promoted manually — no automatic failover.'),
        _o('A Multi-AZ DB cluster deployment with one writer and two readable standby instances in three AZs.', 1, 'Failover typically under 35 seconds, and both standbys serve reads through the reader endpoint.'),
        _o('An Aurora Global Database.', 0, 'The requirement is to stay on RDS for PostgreSQL and survive an AZ, not a Region.')],
      stub: { fail: 'AZ', rto: 'minutes', rpo: 'zero', sup: 'fastest' }, words: ['well under a minute', 'serve read traffic instead of sitting idle', 'stay on RDS for PostgreSQL'],
      expl: 'Readable standbys + faster failover = **Multi-AZ DB cluster** (MySQL and PostgreSQL). Newer than most banks, which only know the Multi-AZ DB instance.',
      update: 'Multi-AZ DB clusters: one writer and two readable standbys in three AZs, failover typically under 35 seconds (Multi-AZ DB instance: 60–120 s).' },
    { id: 'H13', src: 'New', line: 'rds',
      q: 'A company runs Amazon RDS for PostgreSQL in us-east-1 and needs a disaster recovery copy in us-west-2 with an RPO of minutes. It wants to stay on RDS for PostgreSQL and keep costs low; a manual promotion during a disaster is acceptable.',
      opts: [_o('Create a cross-Region read replica in us-west-2 and promote it to a standalone instance during a disaster.', 1, 'Asynchronous, minutes or less of lag, one extra instance, manual promotion — exactly what was accepted.'),
        _o('Migrate to Aurora PostgreSQL with Aurora Global Database.', 0, 'Violates “stay on RDS” and costs more; its second-level RPO was not asked for — prestige distractor.'),
        _o('Enable Multi-AZ on the instance.', 0, 'Both AZs are in us-east-1; a Region loss takes both.'),
        _o('Copy a manual snapshot to us-west-2 every night.', 0, 'Up to 24 hours of data loss — fails the RPO of minutes.')],
      stub: { fail: 'Region', rto: 'tens of min', rpo: 'minutes', sup: 'cheapest' }, words: ['RPO of minutes', 'stay on RDS for PostgreSQL', 'manual promotion during a disaster is acceptable'],
      expl: 'A **cross-Region read replica** is RDS’s pilot-light database: replication keeps RPO low; promotion is manual. Nightly snapshots are backup and restore (hours).' },

    /* ---------------- Aurora ---------------- */
    { id: 'H14', src: 'New', line: 'aurora',
      q: 'A financial application uses Amazon Aurora PostgreSQL. Regulators require that it can recover from a Regional outage with an RPO of about 1 second and an RTO of about 1 minute, and analysts in a second Region want low-latency read access to the data.',
      opts: [_o('Aurora Replicas in three Availability Zones.', 0, 'All in one Region — no protection against a Regional outage.'),
        _o('Daily Aurora snapshots copied to the second Region.', 0, 'Hours of RPO and RTO.'),
        _o('An AWS DMS task replicating to an RDS for PostgreSQL instance in the second Region.', 0, 'Custom replication with more lag and manual cutover; not built for second-level RPO.'),
        _o('Aurora Global Database with a secondary cluster in the second Region.', 1, 'Storage-level replication typically under a second; secondary serves local reads; managed failover in about a minute.')],
      stub: { fail: 'Region', rto: 'minutes', rpo: 'seconds', sup: 'none stated' }, words: ['RPO of about 1 second', 'RTO of about 1 minute', 'low-latency read access'],
      expl: 'Cross-Region, relational, RPO ≈ 1 s, RTO ≈ 1 min, local reads: **Aurora Global Database** — here the prestige service is right because the numbers demand it.',
      update: 'Global Database now supports up to 10 secondary Regions (May 2025; banks and the DR whitepaper say 5).' },
    { id: 'H15', src: 'New', line: 'aurora',
      q: 'A company runs an Aurora Global Database with its primary cluster in us-east-1 and a secondary in eu-west-1. For a planned compliance exercise it must make eu-west-1 the primary Region for a month, with no data loss, and then move back.',
      opts: [_o('Detach the eu-west-1 cluster from the global database and promote it to a standalone cluster.', 0, 'Breaks the global database; you would have to rebuild replication to move back.'),
        _o('Perform a global database switchover to the eu-west-1 cluster, and a second switchover to move back.', 1, 'Switchover (formerly managed planned failover) keeps the topology and loses no data; it needs a healthy primary — which exists here.'),
        _o('Perform a global database failover to eu-west-1.', 0, 'Failover is for unplanned outages and may lose data not yet replicated.'),
        _o('Change the Route 53 records to point writers at eu-west-1.', 0, 'The secondary is read-only until it becomes primary; DNS alone changes nothing.')],
      stub: { fail: 'any', rto: 'minutes', rpo: 'zero', sup: 'least ops' }, words: ['planned compliance exercise', 'no data loss', 'move back'],
      expl: 'Planned + no data loss = **switchover**. Unplanned Region outage = **failover** (accepting the replication lag as RPO).',
      update: '“Managed planned failover” is now called switchover; the managed unplanned failover dates from Aug 2023 (before, detach and promote).' },
    { id: 'H16', src: 'New', line: 'aurora',
      q: 'A developer ran a DELETE without a WHERE clause on an Amazon Aurora MySQL cluster 10 minutes ago. Backtrack was enabled when the cluster was created. The team wants the fastest way to return the same cluster to its state just before the statement.',
      opts: [_o('Fail over to an Aurora Replica.', 0, 'The replica shares the same storage volume; the rows are gone there too.'),
        _o('Restore the cluster to a point in time from automated backups.', 0, 'Works, but creates a **new** cluster and takes longer; the endpoints change.'),
        _o('Backtrack the cluster to a time just before the DELETE.', 1, 'Rewinds the same cluster in place in minutes, no new cluster, same endpoints.'),
        _o('Promote the secondary cluster of an Aurora Global Database.', 0, 'The secondary replicated the DELETE within a second.')],
      stub: { fail: 'bad data', rto: 'minutes', rpo: 'minutes', sup: 'fastest' }, words: ['DELETE without a WHERE clause', 'Backtrack was enabled', 'same cluster'],
      expl: 'Bad data → a copy from **before**. Aurora MySQL **Backtrack** rewinds in place (window up to 72 h); PITR creates a new cluster. Replicas and Global Database copied the mistake.' },

    /* ---------------- DynamoDB ---------------- */
    { id: 'H17', src: 'New', line: 'ddb',
      q: 'A mobile game stores player profiles in Amazon DynamoDB. Players in the US, Europe and Asia must read and write their profiles with low latency in their own Region, and the game must keep working if one Region becomes unavailable.',
      opts: [_o('Convert the table to a DynamoDB global table with replicas in the three Regions.', 1, 'Every replica accepts reads and writes locally; if one Region fails, players are routed to another that already has the data.'),
        _o('Enable DynamoDB Accelerator (DAX) in each Region.', 0, 'DAX is an in-Region cache in front of one table; it does not replicate across Regions.'),
        _o('Export the table to S3 every hour and replicate the bucket with CRR.', 0, 'Up to an hour of data loss and no writable table in the other Regions.'),
        _o('Create Aurora Global Database clusters in the three Regions.', 0, 'One writer Region only, and a relational engine for key-value data.')],
      stub: { fail: 'Region', rto: 'near zero', rpo: 'seconds', sup: 'none stated' }, words: ['read and write their profiles with low latency in their own Region', 'keep working if one Region becomes unavailable'],
      expl: 'Writes in every Region + survive a Region = **DynamoDB global tables** (multi-active, replication typically within a second).' },
    { id: 'H18', src: 'New', line: 'ddb',
      q: 'A faulty batch job overwrote thousands of items in a DynamoDB global table two hours ago. The table has replicas in two other Regions and point-in-time recovery is enabled. How should the team recover the correct data?',
      opts: [_o('Switch the application to one of the replica tables in another Region.', 0, 'The replicas received the overwrites within about a second.'),
        _o('Restore the latest on-demand backup taken last week.', 0, 'Loses a week of good data; PITR can go back to the second before the job.'),
        _o('Turn on DynamoDB Streams and replay the stream backwards.', 0, 'Streams keep 24 hours of changes going forward; they are not a restore mechanism.'),
        _o('Use point-in-time recovery to restore the table to a new table as of a moment before the job ran, then copy the good items back.', 1, 'PITR restores to any second in its window, into a new table.')],
      stub: { fail: 'bad data', rto: 'hours', rpo: 'seconds', sup: 'none stated' }, words: ['faulty batch job overwrote', 'two hours ago', 'point-in-time recovery is enabled'],
      expl: 'Replication is not a backup: the global table copied the bad writes everywhere. **PITR** restores to a **new table** at any second of its 1–35-day window.' },
    { id: 'H19', src: 'New', line: 'ddb',
      q: 'A bank’s account-balance service uses Amazon DynamoDB. It must run in multiple Regions and survive a Regional outage with an RPO of zero: a read in any Region must always return the latest committed write.',
      opts: [_o('A DynamoDB global table in the default multi-Region eventual consistency mode.', 0, 'Asynchronous, last writer wins: a Region failure can lose the most recent writes.'),
        _o('A DynamoDB global table configured for multi-Region strong consistency across three Regions (or two replicas and a witness).', 1, 'MRSC gives strongly consistent reads everywhere and RPO zero.'),
        _o('A single-Region table with PITR copied to another Region by AWS Backup.', 0, 'Hours of RPO and RTO.'),
        _o('Two separate tables with the application writing to both.', 0, 'No transactional guarantee between them; custom and fragile.')],
      stub: { fail: 'Region', rto: 'near zero', rpo: 'zero', sup: 'none stated' }, words: ['RPO of zero', 'always return the latest committed write'],
      expl: 'RPO zero across Regions needs **synchronous** agreement: DynamoDB **MRSC** (GA June 2025), deployed in exactly three Regions — three replicas, or two plus a witness.',
      update: 'Multi-Region strong consistency for global tables became generally available in June 2025; older material only knows eventually consistent global tables.' },

    /* ---------------- S3 / file ---------------- */
    { id: 'H20', src: 'New', line: 's3rep',
      q: 'A compliance rule says every new object written to a production S3 bucket must be copied to a bucket in another Region within 15 minutes, and the company wants that replication time backed by an SLA and monitored with metrics.',
      opts: [_o('Enable S3 Cross-Region Replication with default settings.', 0, 'Most objects replicate in seconds, but there is no time commitment or SLA.'),
        _o('Schedule an AWS DataSync task every 15 minutes.', 0, 'A scheduled copy job, not an SLA-backed replication time.'),
        _o('Enable S3 Cross-Region Replication with S3 Replication Time Control (RTC).', 1, 'RTC replicates 99.99% of objects within 15 minutes, backed by an SLA (99.9%), with replication metrics and events.'),
        _o('Use S3 Same-Region Replication to a bucket in another account.', 0, 'Same Region — fails “another Region”.')],
      stub: { fail: 'Region', rto: 'any', rpo: 'minutes', sup: 'none stated' }, words: ['within 15 minutes', 'backed by an SLA'],
      expl: '“Within 15 minutes” + SLA = **CRR with RTC**. Versioning must be on in both buckets.',
      update: 'The RTC SLA covers 99.9% of objects within 15 minutes per billing month; 99.99% is the design target (banks often mix the two).' },
    { id: 'H21', src: 'New', line: 's3rep',
      q: 'A team enabled versioning and a Cross-Region Replication rule on a bucket that already holds 40 million objects. New uploads now appear in the destination bucket, but none of the existing objects do. What is the least-effort way to replicate them?',
      opts: [_o('Delete and re-upload the existing objects.', 0, 'Risky, slow and costly.'),
        _o('Disable and re-enable versioning to trigger replication.', 0, 'Versioning cannot be disabled, only suspended; it would not replicate old objects.'),
        _o('Run AWS DataSync from the source to the destination bucket every day.', 0, 'Copies objects outside replication (no replication status, metadata handling differs); not the built-for tool.'),
        _o('Run an S3 Batch Replication job for the existing objects.', 1, 'Batch Replication replicates existing objects, and objects that previously failed or were already replicated elsewhere.')],
      stub: { fail: 'Region', rto: 'any', rpo: 'any', sup: 'least ops' }, words: ['already holds 40 million objects', 'none of the existing objects'],
      expl: 'Replication rules only see **new** objects. Existing ones → **S3 Batch Replication**.' },
    { id: 'H22', src: 'New', line: 'nbr',
      q: 'A Linux application stores shared files on Amazon EFS. The DR plan needs a copy of the file system in another Region that is kept current automatically, with an RPO of minutes, and that can be made writable during a disaster with the least effort.',
      opts: [_o('Enable EFS replication to a destination file system in the other Region; during a disaster fail over to the replica (it becomes writable).', 1, 'Built-in, continuous, RPO of 15 minutes for most file systems; failback reverses the direction.'),
        _o('Copy the files hourly with a cron job and rsync to an EC2 instance in the other Region.', 0, 'Custom work and up to an hour of loss.'),
        _o('Take daily AWS Backup recovery points and copy them to the other Region.', 0, 'Hours of RPO; a restore is needed.'),
        _o('Put the EFS mount targets behind AWS Global Accelerator.', 0, 'Global Accelerator does not replicate data — prestige distractor.')],
      stub: { fail: 'Region', rto: 'minutes', rpo: 'minutes', sup: 'least ops' }, words: ['kept current automatically', 'RPO of minutes', 'made writable during a disaster'],
      expl: '**EFS replication**: AWS states an RPO of 15 minutes for most file systems; failover makes the destination writable.' },

    /* ---------------- AWS Backup ---------------- */
    { id: 'H23', src: 'New', line: 'backup',
      q: 'After a ransomware incident at a competitor, a company requires that its AWS Backup recovery points cannot be deleted or have their retention shortened by anyone — including administrators and the root user — until the retention period ends.',
      opts: [_o('Apply a backup vault access policy that denies DeleteRecoveryPoint to all IAM users.', 0, 'An administrator can edit the access policy, and the root user can remove it.'),
        _o('Enable AWS Backup Vault Lock in governance mode.', 0, 'Governance mode can be removed by users with the right IAM permissions.'),
        _o('Enable AWS Backup Vault Lock in compliance mode and let the grace time expire.', 1, 'After the grace time (at least 72 hours) the lock is immutable: nobody can delete recovery points early or change the lock.'),
        _o('Replicate the recovery points with S3 Cross-Region Replication.', 0, 'Recovery points are not objects in your buckets; and a replica is not immutable.')],
      stub: { fail: 'bad data', rto: 'hours', rpo: 'hours', sup: 'none stated' }, words: ['cannot be deleted', 'including administrators and the root user'],
      expl: '“Nobody, not even root” = **Vault Lock compliance mode** (WORM). Governance mode is for testing or when trusted admins may still change it.' },
    { id: 'H24', src: 'New', line: 'backup',
      q: 'A company wants backups that remain recoverable even if an attacker gains administrator access to the production AWS account. Which TWO measures should a solutions architect combine? (Select TWO.)',
      opts: [_o('Copy the recovery points to a backup vault in a separate account that production administrators cannot access (or use a logically air-gapped vault shared to a recovery account).', 1, 'The attacker’s credentials do not reach the other account.'),
        _o('Increase the retention of automated RDS backups to 35 days.', 0, 'The attacker can delete the database and its automated backups in the same account.'),
        _o('Enable AWS Backup Vault Lock in compliance mode on the vault holding the copies.', 1, 'Even a compromised administrator (or root) cannot delete locked recovery points early.'),
        _o('Enable S3 Cross-Region Replication on application buckets.', 0, 'Replication copies encrypted or deleted data; it is not a protected copy.')],
      stub: { fail: 'bad data', rto: 'hours', rpo: 'hours', sup: 'none stated' }, words: ['attacker gains administrator access', 'production AWS account'],
      expl: 'Ransomware resilience = copies **out of reach** (another account, or an air-gapped vault) **and** **immutable** (compliance-mode lock). Replication and in-account backups fall with the account.',
      update: 'Logically air-gapped vaults (locked by default, shareable through AWS RAM) can now be the primary backup target (Nov 2025).' },
    { id: 'H25', src: 'New', line: 'backup',
      q: 'Auditors ask the company to prove regularly that its RDS and EBS backups can actually be restored and to record how long each restore takes, with minimal manual work.',
      opts: [_o('Write a runbook and restore one backup by hand every quarter.', 0, 'Manual, infrequent, and no recorded metrics.'),
        _o('Create an AWS Backup restore testing plan that restores selected recovery points on a schedule, validates them and reports restore duration.', 1, 'Built for exactly this; results feed audits (restore testing, GA Nov 2023).'),
        _o('Enable AWS Backup Vault Lock.', 0, 'Protects backups from deletion; proves nothing about restorability.'),
        _o('Enable AWS Config rules for backup plans.', 0, 'Checks that backups are configured, not that they restore.')],
      stub: { fail: 'any', rto: 'hours', rpo: 'any', sup: 'least ops' }, words: ['prove regularly', 'can actually be restored', 'how long each restore takes'],
      expl: 'Proving restores with least ops = **AWS Backup restore testing**. (Backup Audit Manager reports compliance of the backup setup — do not confuse it with AWS Audit Manager.)' },

    /* ---------------- DRS ---------------- */
    { id: 'H26', src: 'New', line: 'drs',
      q: 'A company has 200 on-premises VMware and physical servers running line-of-business applications. It needs disaster recovery in AWS with an RPO of seconds and an RTO measured in minutes, while paying as little as possible for AWS compute until a disaster happens.',
      opts: [_o('AWS Application Migration Service (MGN) with a scheduled cutover.', 0, 'Same replication engine, but one-way migration ending in a cutover — not DR.'),
        _o('AWS Backup for VMware with copies to an AWS Region.', 0, 'Covers VMware only (not the physical servers), and restores take hours.'),
        _o('A warm standby of every server on right-sized EC2 instances with DataSync copying files hourly.', 0, 'Pays for 200 running instances and an hour of RPO.'),
        _o('AWS Elastic Disaster Recovery, replicating all servers into a low-cost staging area and launching recovery instances only during drills or a disaster.', 1, 'Continuous block-level replication: RPO seconds, RTO typically 5–20 minutes, cheap staging.')],
      stub: { fail: 'on-prem site', rto: 'minutes', rpo: 'seconds', sup: 'cheapest' }, words: ['on-premises VMware and physical servers', 'RPO of seconds', 'RTO measured in minutes', 'paying as little as possible'],
      expl: 'Servers + RPO seconds + RTO minutes + cheap until needed = **DRS**, pilot light for whole servers. MGN is the migration twin.' },
    { id: 'H27', src: 'New', line: 'drs',
      q: 'During a data-center outage the company failed over 50 servers to AWS with AWS Elastic Disaster Recovery. The data center is repaired. How should the team return the workloads with the least effort and without losing the changes made while running in AWS?',
      opts: [_o('Use Elastic Disaster Recovery failback: install the failback client on the repaired source machines, replicate the recovery instances back, then fail back.', 1, 'Failback replicates the changed data in reverse and cuts back over.'),
        _o('Restore the original servers from last month’s on-premises backups.', 0, 'Loses everything written while running in AWS.'),
        _o('Use AWS Application Migration Service to migrate the servers back on premises.', 0, 'MGN migrates **into** AWS.'),
        _o('Export the EC2 instances as AMIs and copy them to the data center with AWS DataSync.', 0, 'Manual, slow, and not how DRS recovers.')],
      stub: { fail: 'on-prem site', rto: 'hours', rpo: 'zero', sup: 'least ops' }, words: ['data center is repaired', 'without losing the changes made while running in AWS'],
      expl: 'DRS is the **round trip**: fail over, run, then **fail back** with reverse replication.' },

    /* ---------------- failover routing ---------------- */
    { id: 'H28', src: 'New', line: 'r53',
      q: 'A company’s website runs on an Application Load Balancer in one Region. If the site becomes unhealthy, visitors must automatically see a static “we’ll be back” page hosted in an S3 bucket configured for static website hosting. The solution must be simple and low cost.',
      opts: [_o('Put AWS Global Accelerator in front of the ALB and the bucket.', 0, 'S3 website endpoints are not Global Accelerator endpoints, and fixed IPs were not asked for — prestige distractor.'),
        _o('Use a Lambda function that edits the DNS record when a CloudWatch alarm fires.', 0, 'Custom code doing what failover routing does natively.'),
        _o('Create Route 53 failover records: primary alias to the ALB with evaluate target health (or a health check), secondary alias to the S3 website endpoint.', 1, 'Route 53 answers with the S3 site while the primary is unhealthy.'),
        _o('Create a second ALB in another Region.', 0, 'A second copy of the site, not a maintenance page; more cost.')],
      stub: { fail: 'any', rto: 'minutes', rpo: 'any', sup: 'cheapest' }, words: ['automatically see a static', 'S3 bucket configured for static website hosting', 'simple and low cost'],
      expl: 'Active-passive to a static page = **Route 53 failover routing** with alias records. For an alias to an AWS resource, **evaluate target health** replaces a separate health check.' },
    { id: 'H29', src: 'New', line: 'r53',
      q: 'A company uses Route 53 failover routing between two Regions. The primary endpoint is an internal application reachable only inside a VPC, so Route 53 health checkers cannot connect to it. How can failover still be driven by the application’s health?',
      opts: [_o('Create an endpoint health check against the instance’s private IP address.', 0, 'Route 53 health checkers are outside the VPC; they cannot reach a private IP.'),
        _o('Create a calculated health check with no child checks.', 0, 'A calculated check combines other checks; with no children it measures nothing.'),
        _o('Put a Global Accelerator in front of the application.', 0, 'Does not give Route 53 a health signal, and the endpoint is internal.'),
        _o('Publish a CloudWatch metric for the application’s health, create an alarm on it, and create a Route 53 health check based on the CloudWatch alarm.', 1, 'Alarm-based health checks work for resources the checkers cannot reach.')],
      stub: { fail: 'Region', rto: 'minutes', rpo: 'any', sup: 'none stated' }, words: ['reachable only inside a VPC', 'cannot connect to it'],
      expl: 'Private resource → **CloudWatch-alarm health check** (standard-resolution metric, alarm in the same account). Endpoint checks come from the internet.' },
    { id: 'H30', src: 'New', line: 'r53',
      q: 'An application behind an Application Load Balancer spans three Availability Zones. Operators see elevated errors from targets in one AZ caused by a partial infrastructure problem, although health checks still pass. They want to move the load balancer’s traffic out of that AZ immediately and move it back later, with no redeployment.',
      opts: [_o('Deregister every target in the impaired AZ from the target group.', 0, 'Works slowly and manually and must be undone target by target.'),
        _o('Start an Amazon ARC zonal shift for the load balancer away from the impaired AZ.', 1, 'Zonal shift moves traffic out of one AZ for a set time and back when you end it; zonal autoshift can do it automatically.'),
        _o('Fail over to a second Region with Route 53.', 0, 'A Region failover for a one-AZ problem — prestige answer, and disruptive.'),
        _o('Change the Auto Scaling group to launch only in the other two AZs.', 0, 'A configuration change and redeploy; traffic keeps flowing to existing targets meanwhile.')],
      stub: { fail: 'AZ', rto: 'minutes', rpo: 'any', sup: 'fastest' }, words: ['move the load balancer’s traffic out of that AZ', 'health checks still pass', 'no redeployment'],
      expl: 'Gray failure in one AZ = **ARC zonal shift** (temporary, reversible). Static stability makes it safe: the other AZs must already have the capacity.' }
  ];
})();
