/* Session 7 drills (HA & disaster recovery). stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit.
   H1 (Exam Q61, tag F) and H2 (Exam Q29, tag C) come from his baseline misses; H3–H5 from his prestige-distractor
   pattern (src 'Exam pattern', tag C): multi-site + Global Accelerator tempting and wrong (H3), Global Accelerator
   genuinely right (H4), a second Region / Global Accelerator for an AZ failure wrong (H5).
   Other drills with a prestige option that is wrong: H1 H6 H9 H10 H13 H28 H29 H30.
   Options are written to the same size; each distractor breaks on one stated detail. Stub slots record what the
   stem literally states ('any' when it states nothing for that slot).
   Select TWO: H11, H24. Correct letters: A 7 · B 7 · C 7 · D 7 · BD 1 · AC 1. */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _o = (t, ok, why) => ({ t, ok: !!ok, why });
  const GA_AZ = 'Global Accelerator fronts endpoints in one or more Regions with static IPs. The load balancer already spans the AZs, so it adds nothing against an AZ failure — prestige distractor.';
  const MS_COST = 'Multi-site active/active runs full production in two Regions all the time: the most expensive strategy, for RTO and RPO near zero.';
  S.drills = [
    /* ---------------- his record ---------------- */
    { id: 'H1', src: 'Exam Q61', line: 'rds', mine: true, tag: 'F',
      q: 'An application connects to an Amazon RDS for PostgreSQL Multi-AZ DB instance using the DB instance endpoint. The primary instance’s Availability Zone suffers an outage. What happens, and what must the application team do so that the application reconnects?',
      opts: [_o('RDS moves the primary’s private IP address to the standby automatically; the team must restart the application servers to reconnect.', 0, 'No IP address moves. The endpoint name stays and RDS changes the DNS record behind it.'),
        _o('RDS promotes the standby automatically; the team must change the connection string to the standby instance’s own endpoint.', 0, 'The standby has no endpoint of its own to use. The DB instance endpoint stays the same and now resolves to the new primary.'),
        _o('RDS promotes the standby automatically and points the endpoint’s DNS record at it; the application reconnects to the same endpoint.', 1, 'That is the mechanism: same endpoint name, new target. Typically 60–120 seconds; apps should retry and not cache DNS for long.'),
        _o('RDS promotes the standby automatically; the team must add AWS Global Accelerator so clients keep one static IP through the change.', 0, 'Global Accelerator does not front RDS databases, and the endpoint already survives failover — prestige distractor.')],
      stub: { fail: 'AZ', rto: 'any', rpo: 'any', sup: 'none stated' }, words: ['Multi-AZ DB instance', 'DB instance endpoint', 'reconnects'],
      expl: 'Your baseline **Q61**. Multi-AZ = a **synchronous** standby in another AZ. On failure RDS promotes it and updates the endpoint’s **DNS CNAME** to point at it; the application just reconnects to the same name. Every option here starts “promotes automatically” — the detail is what the team must do: nothing but reconnect.' },
    { id: 'H2', src: 'Exam Q29', line: 'backup', mine: true, tag: 'C',
      q: 'A company runs workloads on Amazon EC2 with EBS volumes, Amazon RDS, Amazon DynamoDB and Amazon EFS. It needs daily backups of all of them managed from one place, with copies kept in a second AWS Region and in a separate backup account, with the least operational overhead.',
      opts: [_o('Create Amazon Data Lifecycle Manager policies for the resources, with cross-Region copy rules and cross-account copies to the backup account.', 0, 'DLM automates EBS snapshots and EBS-backed AMIs only — it cannot back up RDS, DynamoDB or EFS.'),
        _o('Create an AWS Backup plan that selects the resources by tag, with copy rules to a vault in the second Region and in the backup account.', 1, 'One plan, many services, cross-Region and cross-account copies built in.'),
        _o('Use EventBridge Scheduler to invoke one Lambda function per service that snapshots the resources and copies them to both targets.', 0, 'Works, but it is custom code for what AWS Backup does — fails least operational overhead.'),
        _o('Create an AWS Backup plan with a daily rule, and replicate the vault’s storage to the second Region and backup account with S3 CRR.', 0, 'A backup vault is not a bucket you can replicate; copies to other Regions and accounts are copy rules in the plan.')],
      stub: { fail: 'any', rto: 'any', rpo: 'hours', sup: 'least ops' }, words: ['EBS volumes, Amazon RDS, Amazon DynamoDB and Amazon EFS', 'managed from one place', 'separate backup account', 'least operational overhead'],
      expl: 'Your baseline **Q29** was DLM vs AWS Backup. **DLM = EBS only**, the simplest tool when only EBS is named. Several services + another account + one place = **AWS Backup**, and its **copy rules** do the cross-Region and cross-account part.' },
    { id: 'H3', src: 'Exam pattern', line: 'tiers', mine: true, tag: 'C',
      q: 'A company runs an internal reporting application in one AWS Region on EC2 instances and Amazon RDS. The business accepts an RTO of 24 hours and an RPO of 24 hours for a Regional disaster. The DR solution must be the most cost-effective.',
      opts: [_o('Run the full stack in a second Region on an Aurora Global Database, and route users with AWS Global Accelerator (multi-site active/active).', 0, MS_COST + ' Global Accelerator adds nothing a 24-hour RTO needs — prestige distractor.'),
        _o('Run a scaled-down copy of the stack in a second Region with a cross-Region read replica, and scale it up after a disaster (warm standby).', 0, 'Pays all year for running compute and a replica to get minutes of RTO that nobody asked for.'),
        _o('Keep a cross-Region read replica and AMIs in a second Region, with the application tier switched off until a disaster (pilot light).', 0, 'Cheaper than warm standby, but still pays for a running replica to get an RPO of minutes; 24 hours allows backups.'),
        _o('Copy daily AWS Backup recovery points to a second Region, and keep the stack as code to rebuild and restore there (backup and restore).', 1, 'Nothing runs in the DR Region; RPO and RTO of hours are exactly backup and restore.')],
      stub: { fail: 'Region', rto: 'hours', rpo: 'hours', sup: 'cheapest' }, words: ['RTO of 24 hours', 'RPO of 24 hours', 'most cost-effective'],
      expl: 'RTO and RPO in **hours** + **most cost-effective** = **backup and restore**. Every option meets the targets; only the cost differs. Multi-site plus Global Accelerator is the right design for near-zero RTO, not for 24 hours.' },
    { id: 'H4', src: 'Exam pattern', line: 'ga', mine: true, tag: 'C',
      q: 'A company serves a TCP and UDP game API from Network Load Balancers in us-east-1 and eu-west-1. Partners allow-list the API’s IP addresses in their firewalls, so the addresses must never change. If one Region fails, traffic must move to the other within about a minute without depending on DNS caches expiring.',
      opts: [_o('Create an AWS Global Accelerator with an endpoint group per Region, add the NLBs as endpoints, and give partners its static IPs.', 1, 'Static anycast IPs that never change, UDP support, and health-based failover at the edge with no DNS TTL.'),
        _o('Give partners the Elastic IP addresses of both NLBs, and create Route 53 failover records with health checks and a 60-second TTL.', 0, 'The allow lists hold, but failover is a DNS answer change — clients wait for resolvers to drop the cached record.'),
        _o('Put a CloudFront distribution with an origin group in front of both NLBs, and give partners the distribution’s anycast static IPs.', 0, 'CloudFront proxies HTTP(S) and WebSocket traffic, not a raw TCP and UDP game protocol.'),
        _o('Attach Elastic IP addresses to the NLB in each Region and, if a Region fails, reassociate them with the NLB in the surviving Region.', 0, 'Elastic IP addresses are regional; they cannot move to another Region.')],
      stub: { fail: 'Region', rto: 'minutes', rpo: 'any', sup: 'none stated' }, words: ['allow-list the API’s IP addresses', 'must never change', 'TCP and UDP', 'without depending on DNS caches'],
      expl: 'Here **Global Accelerator is genuinely the answer**: static IPs + UDP + failover without DNS. The prestige test is not “never pick GA”; it is “pick it only when the scenario gives its built-for reason”.' },
    { id: 'H5', src: 'Exam pattern', line: 'asg', mine: true, tag: 'C',
      q: 'A web application runs on EC2 instances in a single Availability Zone behind an Application Load Balancer, with an Amazon RDS for MySQL Single-AZ database. The company wants the application to survive the failure of an Availability Zone with minimal cost and no manual steps.',
      opts: [_o('Deploy a copy of the stack in a second Region with an RDS cross-Region read replica, and put AWS Global Accelerator in front of both.', 0, GA_AZ + ' A second Region also doubles the cost, and the replica needs a manual promotion.'),
        _o('Extend the Auto Scaling group to a second Availability Zone behind the same ALB, and convert the database to a Multi-AZ deployment.', 1, 'Both tiers now survive an AZ: the ALB routes to healthy instances in other AZs, the database fails over automatically.'),
        _o('Extend the Auto Scaling group to a second Availability Zone behind the same ALB, and add an RDS read replica in that zone.', 0, 'A read replica is promoted by hand — fails “no manual steps”. Multi-AZ fails over by itself.'),
        _o('Keep the single zone, and take hourly EBS and RDS snapshots with AWS Backup so the stack can be restored in another zone.', 0, 'Restoring takes hours and is a manual step; the requirement is to keep running.')],
      stub: { fail: 'AZ', rto: 'any', rpo: 'any', sup: 'cheapest' }, words: ['single Availability Zone', 'survive the failure of an Availability Zone', 'minimal cost', 'no manual steps'],
      expl: 'FAILURE = AZ → **high availability inside the Region**: Auto Scaling across AZs + ALB + RDS **Multi-AZ** (automatic failover; a read replica needs a manual promotion). Anything with a second Region or Global Accelerator answers a bigger failure at a bigger price — your prestige pattern.' },

    /* ---------------- DR strategies ---------------- */
    { id: 'H6', src: 'New', line: 'tiers',
      q: 'An order-processing system must be recoverable in a second AWS Region with an RPO of a few minutes and an RTO of about 30 minutes. Management wants the lowest cost that meets these targets. The database is Amazon Aurora MySQL and the application runs on EC2 in an Auto Scaling group.',
      opts: [_o('Replicate Aurora to the second Region, keep AMIs and templates there, and leave the app tier switched off until a disaster.', 1, 'Pilot light: data is live (RPO minutes); compute is started and scaled on failover (tens of minutes).'),
        _o('Copy hourly AWS Backup recovery points of the cluster and instances to the second Region, and restore them there after a disaster.', 0, 'Backup and restore: up to an hour of data loss — fails the RPO of a few minutes.'),
        _o('Replicate Aurora to the second Region, and run a scaled-down Auto Scaling group there that scales up during a disaster.', 0, 'Warm standby meets the targets but pays for running compute all year — fails lowest cost.'),
        _o('Replicate Aurora to the second Region, and put AWS Global Accelerator in front of the primary Region’s load balancer for failover.', 0, 'Global Accelerator only routes to endpoints that exist; with no application in the second Region it recovers nothing — prestige distractor.')],
      stub: { fail: 'Region', rto: 'tens of min', rpo: 'minutes', sup: 'cheapest' }, words: ['RPO of a few minutes', 'RTO of about 30 minutes', 'lowest cost'],
      expl: 'RPO minutes rules out backups; RTO tens of minutes leaves time to start compute; cheapest → **pilot light**. (Aurora Global Database or a cross-Region replica is the always-on core.)' },
    { id: 'H7', src: 'New', line: 'tiers',
      q: 'A company’s customer portal must keep serving at least some traffic within minutes of losing its primary Region, even before the DR site is scaled up. Data loss must be limited to seconds. The company does not want to pay for full production capacity in two Regions.',
      opts: [_o('Pilot light: replicate the data continuously to the DR Region and keep the application servers switched off until failover.', 0, 'Pilot light cannot process requests until compute is started — fails “keep serving … before the DR site is scaled up”.'),
        _o('Backup and restore: copy hourly snapshots of the data and servers to the DR Region and restore them during failover.', 0, 'Hours of RTO and up to an hour of data loss.'),
        _o('Warm standby: run a scaled-down copy in the DR Region with continuous data replication, and scale it up during failover.', 1, 'It can take traffic immediately at reduced capacity; seconds of RPO with continuous replication.'),
        _o('Multi-site: run the application at full size in both Regions with continuous data replication and latency-based routing.', 0, 'Meets the targets but violates “not … full production capacity in two Regions”.')],
      stub: { fail: 'Region', rto: 'minutes', rpo: 'seconds', sup: 'none stated' }, words: ['keep serving at least some traffic', 'before the DR site is scaled up', 'limited to seconds', 'not want to pay for full production capacity'],
      expl: 'Serving immediately at reduced capacity = **warm standby** (Well-Architected: RPO seconds, RTO minutes). Pilot light must start compute first; multi-site pays for full capacity twice. The stated constraints decide it — no superlative needed.' },
    { id: 'H8', src: 'New', line: 'tiers',
      q: 'A global payments API has customers in North America and Europe. It must tolerate the loss of an entire AWS Region with effectively zero downtime; users should always be served from the nearest healthy Region. Cost is secondary to availability.',
      opts: [_o('Run a warm standby in eu-west-1 on DynamoDB global tables, and use Route 53 failover records to move users when the primary fails.', 0, 'One Region serves everyone, and failover still has to detect, scale and shift — minutes of downtime.'),
        _o('Run a pilot light in eu-west-1 with an Aurora cross-Region replica, and use Route 53 failover records to move users on failure.', 0, 'Compute must start and the replica must be promoted — tens of minutes of RTO.'),
        _o('Run the full stack in both Regions on an Aurora Global Database, and route users with Route 53 latency records and health checks.', 0, 'Aurora Global Database has one writer Region: losing it stops writes until a failover completes — not zero downtime for a payments API.'),
        _o('Run the full stack in both Regions on DynamoDB global tables, and route users with Route 53 latency records and health checks.', 1, 'Both Regions serve and write all the time; when one fails, health checks remove it and the other already has the data.')],
      stub: { fail: 'Region', rto: 'near zero', rpo: 'any', sup: 'none stated' }, words: ['effectively zero downtime', 'served from the nearest healthy Region', 'Cost is secondary'],
      expl: 'Near-zero RTO and users in several Regions = **multi-site active/active** with a **multi-writer** data store. Here the most expensive strategy is right because the question pays for it explicitly (“cost is secondary”). The devil: Aurora Global Database still has a single writer Region.' },

    /* ---------------- HA inside a Region ---------------- */
    { id: 'H9', src: 'New', line: 'asg',
      q: 'A stateless web tier needs 12 EC2 instances to handle peak load. It must keep full capacity during an Availability Zone failure without relying on launching new instances during the event. The company wants the most cost-effective layout.',
      opts: [_o('Run 12 instances in each of two Availability Zones, 24 in total, in one Auto Scaling group behind the load balancer.', 0, 'Survives, but +100% spare capacity; three AZs need only +50%.'),
        _o('Run 6 instances in each of three Availability Zones, 18 in total, in one Auto Scaling group behind the load balancer.', 1, 'Lose any one AZ and 12 remain — full capacity with no launches, at +50%.'),
        _o('Run 4 instances in each of three Availability Zones, 12 in total, and let Auto Scaling replace the capacity that is lost.', 0, 'Relies on launching 4 instances during the event — the requirement rules that out.'),
        _o('Run 12 instances in one Availability Zone and 12 in a second Region, 24 in total, behind AWS Global Accelerator.', 0, 'A second Region for an AZ failure — prestige distractor, and +100% spare capacity.')],
      stub: { fail: 'AZ', rto: 'near zero', rpo: 'any', sup: 'cheapest' }, words: ['keep full capacity during an Availability Zone failure', 'without relying on launching new instances', 'most cost-effective'],
      expl: '**Static stability**: pre-provision so the survivors carry the load. With k AZs you need N/(k−1) per AZ: 3 AZs × 6 = 18 beats 2 AZs × 12 = 24.' },
    { id: 'H10', src: 'New', line: 'asg',
      q: 'A licensed legacy application runs on a single EC2 instance with EBS volumes and cannot be clustered. Its license is tied to the instance’s private IP address. If the underlying host fails, the instance must come back automatically with the same instance ID, IP addresses and volumes.',
      opts: [_o('Rely on EC2 automatic recovery: simplified automatic recovery, or a CloudWatch alarm on the system status check with the recover action.', 1, 'Recovery moves the instance to new hardware keeping its ID, private and Elastic IPs, metadata and EBS volumes.'),
        _o('Put the instance in an Auto Scaling group with a minimum and maximum of 1, using a launch template built from the instance’s AMI.', 0, 'The group launches a **new** instance with a new ID and a new private IP — the license breaks.'),
        _o('Create a CloudWatch alarm on the instance status check with the reboot action, so the instance restarts in place automatically.', 0, 'Wrong check and wrong action: a reboot stays on the failed host. Host failures show in the **system** status check, fixed by **recover**.'),
        _o('Register the instance as an AWS Global Accelerator endpoint, so clients keep one static IP address while the host is replaced.', 0, 'Keeps a front-door IP, but nothing replaces the host or keeps the instance’s ID and private IP — prestige distractor.')],
      stub: { fail: 'instance', rto: 'any', rpo: 'any', sup: 'none stated' }, words: ['cannot be clustered', 'same instance ID, IP addresses and volumes', 'underlying host fails'],
      expl: 'One instance that must stay **the same instance** = **EC2 automatic recovery** (on by default for supported types), driven by the **system** status check. Instance-store data would be lost; this instance uses EBS.' },

    /* ---------------- RDS ---------------- */
    { id: 'H11', src: 'New', line: 'rds',
      q: 'An Amazon RDS for MySQL database is slowed down by heavy reporting queries, and it must also fail over automatically if its Availability Zone fails. Which TWO actions meet both requirements? (Select TWO.)',
      opts: [_o('Put Amazon RDS Proxy in front of the DB instance and route the reporting tool’s connections through it.', 0, 'RDS Proxy pools connections; the queries still run on the same instance, and it adds no standby.'),
        _o('Create a read replica of the DB instance and point the reporting tool at the replica’s endpoint.', 1, 'Asynchronous, readable copy that takes the reporting load.'),
        _o('Convert to Multi-AZ and point the reporting tool at the standby instance through its own endpoint.', 0, 'A Multi-AZ DB instance standby serves no traffic and has no endpoint to query.'),
        _o('Convert the DB instance to a Multi-AZ deployment with a standby in another Availability Zone.', 1, 'Synchronous standby with automatic failover.')],
      stub: { fail: 'AZ', rto: 'any', rpo: 'any', sup: 'none stated' }, words: ['heavy reporting queries', 'fail over automatically'],
      expl: 'Two needs, two features: **read replica** for reads, **Multi-AZ** for automatic failover. (A Multi-AZ DB cluster’s readable standbys could cover both in one deployment.)' },
    { id: 'H12', src: 'New', line: 'rds',
      q: 'A PostgreSQL database on Amazon RDS must fail over in well under a minute when an AZ fails, and the company wants the standby capacity to serve read traffic instead of sitting idle. It must stay on RDS for PostgreSQL.',
      opts: [_o('Convert the DB instance to a Multi-AZ DB instance deployment, and send read traffic to the standby instance in the other AZ.', 0, 'Failover typically 60–120 seconds, and its standby serves no reads.'),
        _o('Keep a Single-AZ primary with two read replicas in other AZs, and send the read traffic to the replicas’ endpoints.', 0, 'Replicas serve reads but are promoted manually — no automatic failover.'),
        _o('Deploy a Multi-AZ DB cluster with one writer and two readable standbys in three AZs, using its reader endpoint.', 1, 'Failover typically under 35 seconds, and both standbys serve reads through the reader endpoint.'),
        _o('Migrate to Aurora PostgreSQL with two Aurora Replicas in other AZs, and send the read traffic to the reader endpoint.', 0, 'Fast failover and readable replicas — but the database must stay on RDS for PostgreSQL.')],
      stub: { fail: 'AZ', rto: 'minutes', rpo: 'any', sup: 'none stated' }, words: ['well under a minute', 'serve read traffic instead of sitting idle', 'stay on RDS for PostgreSQL'],
      expl: 'Readable standbys + faster failover = **Multi-AZ DB cluster** (MySQL and PostgreSQL). Newer than most banks, which only know the Multi-AZ DB instance. Aurora would also work technically; “stay on RDS for PostgreSQL” rules it out.',
      update: 'Multi-AZ DB clusters: one writer and two readable standbys in three AZs, failover typically under 35 seconds (Multi-AZ DB instance: 60–120 s).' },
    { id: 'H13', src: 'New', line: 'rds',
      q: 'A company runs Amazon RDS for PostgreSQL in us-east-1 and needs a disaster recovery copy in us-west-2 with an RPO of minutes. It wants to stay on RDS for PostgreSQL, and a manual promotion during a disaster is acceptable. Which solution is the MOST cost-effective?',
      opts: [_o('Create a cross-Region read replica in us-west-2, and promote it to a standalone instance if us-east-1 fails.', 1, 'Asynchronous, minutes or less of lag, one extra instance, manual promotion — exactly what was accepted.'),
        _o('Migrate to Aurora PostgreSQL with a Global Database secondary in us-west-2, and fail over if us-east-1 fails.', 0, 'Violates “stay on RDS” and costs more; its second-level RPO was not asked for — prestige distractor.'),
        _o('Convert the instance to a Multi-AZ DB cluster with readable standbys, and promote one if us-east-1 fails.', 0, 'All three AZs are in us-east-1; a Region loss takes every standby.'),
        _o('Copy an automated snapshot to us-west-2 every night, and restore a new instance from it if us-east-1 fails.', 0, 'Up to 24 hours of data loss — fails the RPO of minutes.')],
      stub: { fail: 'Region', rto: 'any', rpo: 'minutes', sup: 'cheapest' }, words: ['RPO of minutes', 'stay on RDS for PostgreSQL', 'manual promotion during a disaster is acceptable', 'MOST cost-effective'],
      expl: 'A **cross-Region read replica** is RDS’s pilot-light database: replication keeps RPO low; promotion is manual. Nightly snapshots are backup and restore (hours).' },

    /* ---------------- Aurora ---------------- */
    { id: 'H14', src: 'New', line: 'aurora',
      q: 'A financial application uses Amazon Aurora PostgreSQL. Regulators require that it can recover from a Regional outage with an RPO of about 1 second and an RTO of about 1 minute, and analysts in a second Region want low-latency read access to the data.',
      opts: [_o('Add Aurora Replicas in three Availability Zones of the primary Region, and send the analysts’ queries to the reader endpoint.', 0, 'All in one Region — no protection against a Regional outage, and no local reads for the analysts.'),
        _o('Copy Aurora snapshots to the second Region every hour with AWS Backup, and restore a cluster there for the analysts.', 0, 'An hour of RPO and a restore measured in hours.'),
        _o('Replicate with AWS DMS ongoing replication to an Aurora PostgreSQL cluster in the second Region for analysts and failover.', 0, 'Logical replication with more lag and a manual cutover; not built for a 1-second RPO and 1-minute RTO.'),
        _o('Add an Aurora Global Database secondary cluster in the second Region, and send the analysts’ queries to its reader endpoint.', 1, 'Storage-level replication typically under a second; the secondary serves local reads; managed failover in about a minute.')],
      stub: { fail: 'Region', rto: 'minutes', rpo: 'seconds', sup: 'none stated' }, words: ['RPO of about 1 second', 'RTO of about 1 minute', 'low-latency read access'],
      expl: 'Cross-Region, relational, RPO ≈ 1 s, RTO ≈ 1 min, local reads: **Aurora Global Database** — here the prestige service is right because the numbers demand it.',
      update: 'Global Database now supports up to 10 secondary Regions (May 2025; banks and the DR whitepaper say 5).' },
    { id: 'H15', src: 'New', line: 'aurora',
      q: 'A company runs an Aurora Global Database with its primary cluster in us-east-1 and a secondary in eu-west-1. For a planned compliance exercise it must make eu-west-1 the primary Region for a month, with no data loss, and then move back.',
      opts: [_o('Detach the eu-west-1 cluster from the global database, promote it to a standalone cluster, and rebuild the global database later.', 0, 'Breaks the global database; you would have to rebuild replication to move back.'),
        _o('Run a global database switchover to the eu-west-1 cluster, and a second switchover back to us-east-1 after the month.', 1, 'Switchover (formerly managed planned failover) keeps the topology and loses no data; it needs a healthy primary — which exists here.'),
        _o('Run a global database failover to the eu-west-1 cluster, and a second failover back to us-east-1 after the month.', 0, 'Failover is for unplanned outages and accepts losing data not yet replicated — fails “no data loss”.'),
        _o('Repoint the Route 53 writer record to the eu-west-1 cluster’s endpoint, and repoint it to us-east-1 after the month.', 0, 'The secondary is read-only until it becomes primary; DNS alone changes nothing.')],
      stub: { fail: 'any', rto: 'any', rpo: 'zero', sup: 'none stated' }, words: ['planned compliance exercise', 'no data loss', 'move back'],
      expl: 'Planned + no data loss = **switchover**. Unplanned Region outage = **failover** (accepting the replication lag as RPO).',
      update: '“Managed planned failover” is now called switchover; the managed unplanned failover dates from Aug 2023 (before, detach and promote).' },
    { id: 'H16', src: 'New', line: 'aurora',
      q: 'A developer ran a DELETE without a WHERE clause on an Amazon Aurora MySQL cluster 10 minutes ago. Backtrack was enabled when the cluster was created. The team wants the fastest way to return the same cluster to its state just before the statement.',
      opts: [_o('Fail over the cluster to an Aurora Replica in another Availability Zone, which still holds the rows from before the DELETE.', 0, 'The replica shares the same cluster storage volume; the rows are gone there too.'),
        _o('Restore the cluster from automated backups to a point in time just before the DELETE, and repoint the application to it.', 0, 'Works, but creates a **new** cluster and takes longer; the endpoints change.'),
        _o('Backtrack the cluster to a point in time just before the DELETE, keeping the application on the same cluster endpoints.', 1, 'Rewinds the same cluster in place in minutes, no new cluster, same endpoints.'),
        _o('Restore last night’s automated snapshot to a new cluster, and copy the deleted rows back into the original cluster.', 0, 'Slower than a rewind, and the copied rows miss every change made to them since last night.')],
      stub: { fail: 'bad data', rto: 'any', rpo: 'any', sup: 'fastest' }, words: ['DELETE without a WHERE clause', 'Backtrack was enabled', 'same cluster'],
      expl: 'Bad data → a copy from **before**. Aurora MySQL **Backtrack** rewinds in place (window up to 72 h); PITR creates a new cluster. Replicas share the volume that lost the rows.' },

    /* ---------------- DynamoDB ---------------- */
    { id: 'H17', src: 'New', line: 'ddb',
      q: 'A mobile game stores player profiles in Amazon DynamoDB. Players in the US, Europe and Asia must read and write their profiles with low latency in their own Region, and the game must keep working if one Region becomes unavailable.',
      opts: [_o('Convert the table to a DynamoDB global table with replicas in the three Regions, and route players to the nearest one.', 1, 'Every replica accepts reads and writes locally; if one Region fails, players are routed to another that already has the data.'),
        _o('Keep the table in one Region, and add a DynamoDB Accelerator (DAX) cluster in each Region for low-latency profile reads.', 0, 'DAX is an in-Region cache in front of one table; writes still cross the world and the table still lives in one Region.'),
        _o('Keep the table in one Region, and copy its on-demand backups to the other two Regions with AWS Backup every hour.', 0, 'No local writes, up to an hour of data loss, and a restore before anything works.'),
        _o('Create a table in each Region, and use DynamoDB Streams with Lambda to copy writes from the US table to the other two.', 0, 'One-way copy: writes made in Europe or Asia never reach the other Regions — and it is custom code.')],
      stub: { fail: 'Region', rto: 'any', rpo: 'any', sup: 'none stated' }, words: ['read and write their profiles with low latency in their own Region', 'keep working if one Region becomes unavailable'],
      expl: 'Writes in every Region + survive a Region = **DynamoDB global tables** (multi-active, replication typically within a second).' },
    { id: 'H18', src: 'New', line: 'ddb',
      q: 'A faulty batch job overwrote thousands of items in a DynamoDB global table two hours ago. The table has replicas in two other Regions and point-in-time recovery is enabled. How should the team recover the correct data?',
      opts: [_o('Point the application at a replica table in another Region, which still holds the items as they were before the job.', 0, 'The replicas received the overwrites within about a second.'),
        _o('Restore last week’s on-demand backup to a new table, and copy the overwritten items back into the global table.', 0, 'Loses every legitimate change to those items made during the week; PITR can go back to the second before the job.'),
        _o('Enable DynamoDB Streams on the table, and replay the last two hours of stream records to undo the job’s writes.', 0, 'A stream only records changes from the moment it is enabled, and it is not a restore mechanism.'),
        _o('Use PITR to restore the table to a new table as of a moment before the job ran, and copy the good items back.', 1, 'PITR restores to any second in its window, into a new table.')],
      stub: { fail: 'bad data', rto: 'any', rpo: 'any', sup: 'none stated' }, words: ['faulty batch job overwrote', 'two hours ago', 'point-in-time recovery is enabled'],
      expl: 'Replication is not a backup: the global table copied the bad writes everywhere. **PITR** restores to a **new table** at any second of its 1–35-day window.' },
    { id: 'H19', src: 'New', line: 'ddb',
      q: 'A bank’s account-balance service uses Amazon DynamoDB. It must run in multiple Regions and survive a Regional outage with an RPO of zero: a read in any Region must always return the latest committed write.',
      opts: [_o('Create a DynamoDB global table in three Regions in the default multi-Region eventual consistency (MREC) mode.', 0, 'Asynchronous, last writer wins: a Region failure can lose the most recent writes.'),
        _o('Create a DynamoDB global table in three Regions in multi-Region strong consistency (MRSC) mode.', 1, 'MRSC gives strongly consistent reads everywhere and RPO zero.'),
        _o('Create a single-Region table with PITR, and copy its backups to two other Regions with AWS Backup every hour.', 0, 'Up to an hour of RPO and a restore before anything works.'),
        _o('Create a DynamoDB global table in two Regions in MREC mode, and use strongly consistent reads in each Region.', 0, 'Strongly consistent reads in MREC are consistent only within one Region; the other Region can be behind.')],
      stub: { fail: 'Region', rto: 'any', rpo: 'zero', sup: 'none stated' }, words: ['RPO of zero', 'always return the latest committed write'],
      expl: 'RPO zero across Regions needs **synchronous** agreement: DynamoDB **MRSC** (GA June 2025), deployed in exactly three Regions — three replicas, or two plus a witness.',
      update: 'Multi-Region strong consistency for global tables became generally available in June 2025; older material only knows eventually consistent global tables.' },

    /* ---------------- S3 / file ---------------- */
    { id: 'H20', src: 'New', line: 's3rep',
      q: 'A compliance rule says every new object written to a production S3 bucket must be copied to a bucket in another Region within 15 minutes, and the company wants that replication time backed by an SLA and monitored with metrics.',
      opts: [_o('Enable S3 Cross-Region Replication with default settings, and alarm on its replication metrics in CloudWatch.', 0, 'Most objects replicate in seconds, but there is no time commitment or SLA without RTC.'),
        _o('Schedule an AWS DataSync task from the bucket to a bucket in another Region, and monitor the task in CloudWatch.', 0, 'A scheduled copy job, not an SLA-backed replication time.'),
        _o('Enable S3 Cross-Region Replication with S3 Replication Time Control, and use its replication metrics.', 1, 'RTC replicates 99.99% of objects within 15 minutes, backed by an SLA (99.9%), with replication metrics and events.'),
        _o('Enable S3 Same-Region Replication with S3 Replication Time Control to a bucket in a separate account.', 0, 'Same Region — fails “another Region”.')],
      stub: { fail: 'Region', rto: 'any', rpo: 'minutes', sup: 'none stated' }, words: ['within 15 minutes', 'backed by an SLA'],
      expl: '“Within 15 minutes” + SLA = **CRR with RTC**. Versioning must be on in both buckets.',
      update: 'The RTC SLA covers 99.9% of objects within 15 minutes per billing month; 99.99% is the design target (banks often mix the two).' },
    { id: 'H21', src: 'New', line: 's3rep',
      q: 'A team enabled versioning and a Cross-Region Replication rule on a bucket that already holds 40 million objects. New uploads now appear in the destination bucket, but none of the existing objects do. What is the least-effort way to replicate them?',
      opts: [_o('Suspend versioning on the source bucket and enable it again, so the replication rule re-evaluates every object.', 0, 'Suspending and re-enabling versioning does not touch existing objects; replication still sees only new writes.'),
        _o('Edit the replication rule to add a filter that matches every existing prefix, so S3 replicates the objects under them.', 0, 'A filter only scopes which new writes replicate; it never reaches back to existing objects.'),
        _o('Run aws s3 sync from the source to the destination bucket once, from an EC2 instance in the source Region.', 0, '40 million objects through one instance, latest versions only, no replication status — not least effort.'),
        _o('Create an S3 Batch Replication job for the existing objects, using the bucket’s existing replication rule.', 1, 'Batch Replication replicates existing objects, and objects that previously failed or were already replicated elsewhere.')],
      stub: { fail: 'any', rto: 'any', rpo: 'any', sup: 'least ops' }, words: ['already holds 40 million objects', 'none of the existing objects'],
      expl: 'Replication rules only see **new** objects. Existing ones → **S3 Batch Replication**.' },
    { id: 'H22', src: 'New', line: 'nbr',
      q: 'A Linux application stores shared files on Amazon EFS. The DR plan needs a copy of the file system in another Region that is kept current automatically, with an RPO of minutes, and that can be made writable during a disaster with the least effort.',
      opts: [_o('Enable EFS replication to a file system in the other Region, and fail over to the replica to make it writable.', 1, 'Built-in, continuous, RPO of 15 minutes for most file systems; failback reverses the direction.'),
        _o('Schedule an AWS DataSync task every hour from the file system to an EFS file system in the other Region.', 0, 'Up to an hour of data loss — fails the RPO of minutes — and you run the schedule yourself.'),
        _o('Back up the file system daily with AWS Backup, and copy each recovery point to a vault in the other Region.', 0, 'A day of RPO, and a restore is needed before anything is writable.'),
        _o('Mount the file system from the other Region over inter-Region VPC peering, so DR instances use it directly.', 0, 'No second copy exists: the Region failure takes the only file system with it.')],
      stub: { fail: 'Region', rto: 'any', rpo: 'minutes', sup: 'least ops' }, words: ['kept current automatically', 'RPO of minutes', 'made writable during a disaster'],
      expl: '**EFS replication**: AWS states an RPO of 15 minutes for most file systems; failover makes the destination writable.' },

    /* ---------------- AWS Backup ---------------- */
    { id: 'H23', src: 'New', line: 'backup',
      q: 'After a ransomware incident at a competitor, a company requires that its AWS Backup recovery points cannot be deleted or have their retention shortened by anyone — including administrators and the root user — until the retention period ends.',
      opts: [_o('Attach a backup vault access policy that denies backup:DeleteRecoveryPoint to every principal in the account.', 0, 'An administrator can edit the access policy, and the root user can remove it.'),
        _o('Enable AWS Backup Vault Lock in governance mode on the vault, with a minimum and maximum retention period.', 0, 'Governance mode can be removed by users with the right IAM permissions.'),
        _o('Enable AWS Backup Vault Lock in compliance mode on the vault, and let the grace time pass.', 1, 'After the grace time (at least 72 hours) the lock is immutable: nobody can delete recovery points early or change the lock.'),
        _o('Copy the recovery points into an S3 bucket with S3 Object Lock in compliance mode and a default retention.', 0, 'RDS and EBS recovery points are not objects you can put in your own bucket; AWS Backup keeps them in vaults.')],
      stub: { fail: 'bad data', rto: 'any', rpo: 'any', sup: 'none stated' }, words: ['cannot be deleted', 'including administrators and the root user'],
      expl: '“Nobody, not even root” = **Vault Lock compliance mode** (WORM). Governance mode is for testing or when trusted admins may still change it.' },
    { id: 'H24', src: 'New', line: 'backup',
      q: 'A company wants backups that remain recoverable even if an attacker gains administrator access to the production AWS account. Which TWO measures should a solutions architect combine? (Select TWO.)',
      opts: [_o('Copy the recovery points to a backup vault in a separate account that production admins cannot access.', 1, 'The attacker’s credentials do not reach the other account (a logically air-gapped vault shared to a recovery account works the same way).'),
        _o('Copy the recovery points to a backup vault in a second Region, inside the same production account.', 0, 'Another Region, same account: the compromised administrator can delete the copies there too.'),
        _o('Enable AWS Backup Vault Lock in compliance mode on the backup vault that holds the copied recovery points.', 1, 'Even a compromised administrator (or root) cannot delete locked recovery points early.'),
        _o('Turn on AWS Backup continuous backups with 35-day point-in-time recovery in the production account.', 0, 'Continuous backups live in the same account; the attacker can delete them with the database.')],
      stub: { fail: 'bad data', rto: 'any', rpo: 'any', sup: 'none stated' }, words: ['attacker gains administrator access', 'production AWS account'],
      expl: 'Ransomware resilience = copies **out of reach** (another account, or an air-gapped vault) **and** **immutable** (compliance-mode lock). Copies in the same account fall with the account, whatever the Region.',
      update: 'Logically air-gapped vaults (locked by default, shareable through AWS RAM) can now be the primary backup target (Nov 2025).' },
    { id: 'H25', src: 'New', line: 'backup',
      q: 'Auditors ask the company to prove regularly that its RDS and EBS backups can actually be restored and to record how long each restore takes. The solution must have the LEAST operational overhead.',
      opts: [_o('Write a runbook, and have the operations team restore a sample recovery point by hand every quarter and log the time.', 0, 'Manual and infrequent — the opposite of least operational overhead.'),
        _o('Create an AWS Backup restore testing plan that restores recovery points on a schedule and reports each restore time.', 1, 'Built for exactly this; results feed audits (restore testing, GA Nov 2023).'),
        _o('Turn on AWS Backup Audit Manager with a framework that reports whether each resource has recovery points in its plan.', 0, 'Reports that backups exist and follow policy — proves nothing about whether they restore.'),
        _o('Schedule an EventBridge rule that runs a Lambda function to restore the newest recovery points and log each duration.', 0, 'Works, but it is custom code for what restore testing does natively — fails least operational overhead.')],
      stub: { fail: 'any', rto: 'any', rpo: 'any', sup: 'least ops' }, words: ['prove regularly', 'can actually be restored', 'how long each restore takes', 'LEAST operational overhead'],
      expl: 'Proving restores with least ops = **AWS Backup restore testing**. (Backup Audit Manager reports compliance of the backup setup — do not confuse it with AWS Audit Manager.)' },

    /* ---------------- DRS ---------------- */
    { id: 'H26', src: 'New', line: 'drs',
      q: 'A company has 200 on-premises VMware and physical servers running line-of-business applications. It needs disaster recovery in AWS with an RPO of seconds and an RTO measured in minutes, while paying as little as possible for AWS compute until a disaster happens.',
      opts: [_o('Use AWS Application Migration Service to replicate all servers continuously, and launch them in AWS only during a disaster.', 0, 'Same replication engine, but built for a one-way migration ending in a cutover — no drills or failback, not DR.'),
        _o('Use AWS Backup for VMware through a Backup gateway, and copy the recovery points to an AWS Region for restore.', 0, 'Covers VMware only (not the physical servers), and restores take hours.'),
        _o('Run a warm standby of every server on right-sized EC2 instances, kept current by AWS DataSync tasks every hour.', 0, 'Pays for 200 running instances, and an hourly copy is an hour of RPO.'),
        _o('Use Elastic Disaster Recovery to replicate the servers to a staging area, and launch recovery instances only when needed.', 1, 'Continuous block-level replication: RPO seconds, RTO typically 5–20 minutes, cheap staging.')],
      stub: { fail: 'on-prem site', rto: 'minutes', rpo: 'seconds', sup: 'cheapest' }, words: ['on-premises VMware and physical servers', 'RPO of seconds', 'RTO measured in minutes', 'paying as little as possible'],
      expl: 'Servers + RPO seconds + RTO minutes + cheap until needed = **DRS**, pilot light for whole servers. MGN is the migration twin: same agent, but it ends in a cutover, not a round trip.' },
    { id: 'H27', src: 'New', line: 'drs',
      q: 'During a data-center outage the company failed over 50 servers to AWS with AWS Elastic Disaster Recovery. The data center is repaired. How should the team return the workloads with the least effort and without losing the changes made while running in AWS?',
      opts: [_o('Use Elastic Disaster Recovery failback: install the failback client on the source machines and replicate the instances back.', 1, 'Failback replicates the changed data in reverse and cuts back over.'),
        _o('Restore the repaired servers from the on-premises backups taken before the outage, then resume replication to AWS.', 0, 'Loses everything written while running in AWS.'),
        _o('Use AWS Application Migration Service to replicate the recovery instances back to the repaired on-premises servers.', 0, 'MGN migrates **into** AWS; it has no path back on premises.'),
        _o('Export the recovery instances as VM images with VM Import/Export, and copy them to the data center with DataSync.', 0, 'Hours of manual work per server, and writes made during the copy are lost — not least effort.')],
      stub: { fail: 'on-prem site', rto: 'any', rpo: 'zero', sup: 'least ops' }, words: ['data center is repaired', 'without losing the changes made while running in AWS'],
      expl: 'DRS is the **round trip**: fail over, run, then **fail back** with reverse replication.' },

    /* ---------------- failover routing ---------------- */
    { id: 'H28', src: 'New', line: 'r53',
      q: 'A company’s website runs on an Application Load Balancer in one Region. If the site becomes unhealthy, visitors must automatically see a static “we’ll be back” page hosted in an S3 bucket configured for static website hosting. The solution must have the LEAST operational overhead.',
      opts: [_o('Create an AWS Global Accelerator with the ALB as the primary endpoint and the S3 website endpoint in a standby endpoint group.', 0, 'S3 website endpoints are not Global Accelerator endpoints (ALB, NLB, EC2, Elastic IP only) — prestige distractor.'),
        _o('Create a CloudWatch alarm on the ALB’s 5xx errors that invokes a Lambda function to repoint the DNS record at the bucket.', 0, 'Works, but custom code doing what failover routing does natively — fails least operational overhead.'),
        _o('Create Route 53 failover records: a primary alias to the ALB with evaluate target health, a secondary alias to the bucket.', 1, 'Route 53 answers with the S3 site while the primary is unhealthy.'),
        _o('Deploy a second copy of the site behind an ALB in another Region, and use Route 53 failover records between the two ALBs.', 0, 'A second copy of the site, not the S3 maintenance page — and far more to run.')],
      stub: { fail: 'any', rto: 'any', rpo: 'any', sup: 'least ops' }, words: ['automatically see a static', 'S3 bucket configured for static website hosting', 'LEAST operational overhead'],
      expl: 'Active-passive to a static page = **Route 53 failover routing** with alias records. For an alias to an AWS resource, **evaluate target health** replaces a separate health check.' },
    { id: 'H29', src: 'New', line: 'r53',
      q: 'A company uses Route 53 failover routing between two Regions. The primary endpoint is an internal application reachable only inside a VPC, so Route 53 health checkers cannot connect to it. How can failover still be driven by the application’s health?',
      opts: [_o('Create a Route 53 endpoint health check against the application’s private IP address on its HTTPS health path.', 0, 'Route 53 health checkers are outside the VPC; they cannot reach a private IP.'),
        _o('Create a Route 53 calculated health check that combines endpoint checks on each of the application’s instances.', 0, 'A calculated check only combines other checks — and those child endpoint checks still cannot reach the private instances.'),
        _o('Create a Route 53 VPC Resolver inbound endpoint so that the health checkers can resolve and reach the application.', 0, 'Resolver endpoints carry DNS queries between networks; they give health checkers no path to the application.'),
        _o('Publish a CloudWatch metric for the application’s health, alarm on it, and base the Route 53 health check on the alarm.', 1, 'Alarm-based health checks work for resources the checkers cannot reach.')],
      stub: { fail: 'Region', rto: 'any', rpo: 'any', sup: 'none stated' }, words: ['reachable only inside a VPC', 'cannot connect to it'],
      expl: 'Private resource → **CloudWatch-alarm health check** (standard-resolution metric, alarm in the same account). Endpoint checks come from the internet.' },
    { id: 'H30', src: 'New', line: 'r53',
      q: 'An application behind an Application Load Balancer spans three Availability Zones. Operators see elevated errors from targets in one AZ caused by a partial infrastructure problem, although health checks still pass. They want to move the load balancer’s traffic out of that AZ immediately and move it back later, with no redeployment and the LEAST operational overhead.',
      opts: [_o('Deregister every target in the impaired AZ from the target group, and register each one again when the problem is fixed.', 0, 'Moves traffic, but target by target in both directions — the most manual way to do it.'),
        _o('Start an Amazon ARC zonal shift for the load balancer away from the impaired AZ, and end it when the problem is fixed.', 1, 'Zonal shift moves traffic out of one AZ for a set time and back when you end it; zonal autoshift can do it automatically.'),
        _o('Use Route 53 failover records to send all traffic to a standby stack in a second Region until the problem is fixed.', 0, 'A Region failover for a one-AZ problem — prestige answer, needs a second stack, and disruptive.'),
        _o('Update the Auto Scaling group to use only the two healthy AZs, and add the third AZ back when the problem is fixed.', 0, 'The load balancer keeps sending traffic to existing targets until instances are replaced — not immediate, and a redeploy.')],
      stub: { fail: 'AZ', rto: 'any', rpo: 'any', sup: 'least ops' }, words: ['move the load balancer’s traffic out of that AZ', 'health checks still pass', 'no redeployment', 'LEAST operational overhead'],
      expl: 'Gray failure in one AZ = **ARC zonal shift** (temporary, reversible). Static stability makes it safe: the other AZs must already have the capacity.' }
  ];
})();
