/* Session 1 drills. stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit. */
window.SESSION = window.SESSION || {};
const _o = (t, ok, why) => ({ t, ok: !!ok, why });
window.SESSION.drills = [
  { id: 'D01', src: 'Quiz Q1', line: 'gateway',
    q: 'A company runs a Windows CAD application on-premises. Designers open large files from a local SMB share all day; the share holds 40 TB and is growing. The company wants the authoritative copy in AWS, LAN-speed access for designers, and its existing Active Directory permissions. Which solution has the LEAST operational overhead?',
    opts: [_o('Migrate the share to Amazon EFS with DataSync and mount EFS from on-premises over a VPN.', 0, 'EFS is NFS for Linux, not SMB with AD ACLs; VPN latency kills “LAN speed”.'),
      _o('Deploy Amazon FSx File Gateway on-premises, backed by Amazon FSx for Windows File Server.', 1, 'SMB + AD + local cache, authoritative copy in FSx for Windows.'),
      _o('Deploy S3 File Gateway and have designers access the files over NFS.', 0, 'Windows designers on SMB with AD permissions; NFS is the wrong protocol here.'),
      _o('Use AWS Transfer Family SFTP so designers upload and download files.', 0, 'A partner door, not a mounted share.')],
    stub: { size: 'any', time: 'ongoing', proto: 'NFS/SMB', sup: 'least ops' }, words: ['Windows', 'SMB', 'Active Directory', 'LAN-speed'],
    expl: 'Windows + SMB + AD + “keep opening files at LAN speed” = a Windows file cache on-prem in front of a Windows file system in AWS.',
    update: 'FSx File Gateway is no longer available to new customers; AWS now suggests FSx for Windows File Server directly. Practice exams still use this answer — recognise it, don’t buy it.' },
  { id: 'D02', src: 'Quiz Q2', mine: true, line: 'truck', tag: 'K',
    q: 'A research lab must upload 600 TB of sequencing output from portable drives at a remote field station whose only link is a 50 Mbps satellite connection. The data is needed in Amazon S3 within three weeks, one time. What is the FASTEST and most cost-effective option?',
    opts: [_o('Install an AWS DataSync agent at the station and disable bandwidth throttling.', 0, '50 Mbps ≈ 0.5 TB/day → about 1,200 days.'),
      _o('Provision a 1 Gbps AWS Direct Connect connection to the field station.', 0, 'Weeks to provision, monthly cost, for a one-off job.'),
      _o('Bring the drives to an AWS Data Transfer Terminal and upload them directly to S3.', 1, 'Removes the thin pipe from the critical path.'),
      _o('Enable S3 Transfer Acceleration and upload with multipart.', 0, 'Uses bandwidth better; creates none.')],
    stub: { size: 'weeks+ online', time: 'one-off', proto: 'any', sup: 'fastest' }, words: ['600 TB', '50 Mbps', 'three weeks'],
    expl: 'Run the pipe rule before reading options: 600 TB at ~0.5 TB/day is years. Only the truck line meets three weeks.' },
  { id: 'D03', src: 'Quiz Q3', mine: true, line: 'dms', tag: 'C',
    q: 'An on-premises PostgreSQL database must move to Amazon Aurora PostgreSQL with under one hour of downtime. After cutover, nightly exports of the same data as Parquet files in Amazon S3 are required for analytics. Which combination meets the requirements?',
    opts: [_o('An AWS DataSync full-load and CDC task from PostgreSQL to Aurora.', 0, 'DataSync moves files; it cannot read a database. Right capability, wrong service.'),
      _o('An AWS DMS full-load plus CDC task from PostgreSQL to Aurora.', 1, 'Source stays online; changes stream until cutover.'),
      _o('AWS Application Migration Service to replicate the database server, then cut over.', 0, 'MGN lands on EC2, not in Aurora.'),
      _o('An AWS DMS task with Amazon S3 as the target and Parquet as the output format.', 1, 'DMS writes CSV by default, Parquet on request.'),
      _o('AWS Global Accelerator in front of Aurora to reduce replication latency.', 0, 'Prestige distractor; unrelated to replication.')],
    stub: { size: 'any', time: 'ongoing', proto: 'database', sup: 'none stated' }, words: ['PostgreSQL database', 'under one hour of downtime', 'Parquet'],
    expl: 'The source is a database engine → DMS line. “Under one hour of downtime” forces CDC; Parquet in S3 is a second DMS target.' },
  { id: 'D04', src: 'Quiz Q4', mine: true, line: 'classes', tag: 'F',
    q: 'Application logs land in S3 at 2 TB per day. They are queried heavily for 7 days, occasionally during the following 60 days, must be retrievable within 12 hours for audits for 5 years, and can then be deleted. Which lifecycle is lowest cost?',
    opts: [_o('Standard → Standard-IA at day 7 → Glacier Deep Archive at day 67 → expire at 5 years.', 0, 'Objects must sit in Standard ≥30 days before a Standard-IA transition.'),
      _o('Standard → Standard-IA at day 30 → Glacier Deep Archive at day 90 → expire at 5 years.', 1, 'IA for the occasional reads, Deep Archive for the ≤12 h audit window.'),
      _o('Standard → Glacier Flexible Retrieval at day 7 → expire at 5 years.', 0, 'Occasional reads until ~day 67 pay retrieval fees and waits; 12 h fits Deep Archive, which is cheaper.'),
      _o('S3 Intelligent-Tiering for the full 5 years, then expire.', 0, 'Pays a monitoring fee for a pattern that is fully known.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'objects/HTTP', sup: 'cheapest' }, words: ['occasionally during the following 60 days', 'within 12 hours', 'lowest cost'],
    expl: '12 hours = Deep Archive’s standard retrieval. Occasional reads for 60 days = an IA class, not Glacier. And IA needs 30 days in Standard first.' },
  { id: 'D05', src: 'Quiz Q5', mine: true, line: 'backup', tag: 'F',
    q: 'A 3 TB EBS volume in us-east-1a holds a licensing database. A regulator requires an encrypted copy of every daily backup in a separate AWS account in a different Region, retained for 7 years, impossible to delete early even by the account’s administrators. Which solution meets this?',
    opts: [_o('Use Amazon Data Lifecycle Manager to snapshot daily and share the snapshots with the other account.', 0, 'A share is not a locked copy; no retention lock.'),
      _o('Use AWS Backup with a plan that copies to a vault in the other account and Region, and apply Backup Vault Lock in compliance mode.', 1, 'Cross-account + cross-Region copies, WORM vault.'),
      _o('Enable EBS Multi-Attach and attach the volume to an instance in the other account over VPC peering.', 0, 'Same AZ, same account; and not a backup.'),
      _o('Use S3 Cross-Region Replication with Object Lock on the bucket that holds the snapshots.', 0, 'EBS snapshots are not in a bucket you can see.')],
    stub: { size: 'any', time: 'ongoing', proto: 'AWS-internal', sup: 'most durable/compliant' }, words: ['separate AWS account', 'different Region', 'impossible to delete early'],
    expl: 'Separate account + different Region + undeletable = AWS Backup cross-account copy + Vault Lock (compliance mode).' },
  { id: 'D06', src: 'Quiz Q6', line: 'where',
    q: 'A media company’s 400 Linux render nodes read a 200 TB dataset stored in S3. Render jobs are I/O bound. The pipeline is moving to EC2 and needs sub-millisecond file access without rewriting it to use the S3 API. Which storage?',
    opts: [_o('Amazon EFS in Max I/O mode, synced from S3 with DataSync.', 0, 'An extra copy and sync job; not the HPC file system.'),
      _o('Amazon FSx for Lustre linked to the S3 bucket.', 1, 'Parallel FS that lazy-loads S3 objects as files.'),
      _o('Amazon FSx for Windows File Server with a DFS namespace.', 0, 'Windows/SMB for Linux render nodes.'),
      _o('Amazon S3 Express One Zone accessed through a Volume Gateway.', 0, 'Volume Gateway is an on-prem iSCSI bridge — a nonsense combination.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'NFS/SMB', sup: 'fastest' }, words: ['sub-millisecond', 'I/O bound', 'without rewriting'],
    expl: 'Linux + HPC-style parallel reads + data already in S3 = FSx for Lustre linked to the bucket.' },
  { id: 'D07', src: 'Retest R1', mine: true, line: 'datasync', tag: 'R',
    q: 'A law firm keeps 120 TB of scanned case files on an on-premises NAS exported over NFS. Its 1 Gbps internet link is 70% busy during business hours. Files older than two years are never edited but must stay retrievable, and the firm wants them out of the NAS within a month with no change to how lawyers access recent files. Which is MOST cost-effective?',
    opts: [_o('Reserve an AWS Data Transfer Terminal slot and take the NAS to the facility.', 0, '120 TB ≈ 12 days at 1 Gbps — it fits the pipe.'),
      _o('Deploy an AWS DataSync agent and run a scheduled task, filtered to files older than two years, that writes directly to S3 Glacier Deep Archive with bandwidth throttling during business hours.', 1, 'Mover, straight to the cheapest class, polite to the link.'),
      _o('Deploy an S3 File Gateway, migrate the old files through it, and add a lifecycle rule to Deep Archive after 180 days.', 0, 'A bridge, not a mover; parks 120 TB in Standard for 180 days.'),
      _o('Provision AWS Direct Connect and use DataSync over it to move the old files to S3 Standard-IA.', 0, 'DX for a one-off; IA costs more than Deep Archive.')],
    stub: { size: 'fits the pipe', time: 'one-off', proto: 'NFS/SMB', sup: 'cheapest' }, words: ['within a month', 'never edited', '1 Gbps'],
    expl: '“Within a month” + “never edited” = a fixed set leaving once → TIME is one-off. One-off files over a pipe that fits = DataSync, straight to Deep Archive.' },
  { id: 'D08', src: 'Retest R2', line: 'transfer',
    q: 'A retailer receives daily inventory feeds from 300 suppliers, who deliver files to the retailer’s on-premises FTP server. Several suppliers cannot change their tooling. The files must land in Amazon S3, the on-premises server must be decommissioned, and supplier credentials must stay in the existing Microsoft Active Directory. Which solution has the LEAST operational overhead?',
    opts: [_o('Run an FTP server on an Auto Scaling group of EC2 instances that write to S3, with a Lambda authorizer for AD.', 0, 'Self-managed servers.'),
      _o('Use AWS Transfer Family with an FTP/FTPS endpoint in the VPC, S3 as storage, and AWS Directory Service for authentication.', 1, 'Managed endpoint, suppliers keep their clients.'),
      _o('Install a DataSync agent on the FTP server and copy hourly to S3; keep the FTP server running.', 0, 'Keeps the server they want decommissioned.'),
      _o('Deploy an S3 File Gateway and give suppliers NFS access over a client VPN.', 0, 'NFS is not FTP, and suppliers cannot change tooling.')],
    stub: { size: 'any', time: 'ongoing', proto: 'SFTP/FTP/AS2', sup: 'least ops' }, words: ['cannot change their tooling', 'FTP server', 'decommissioned'],
    expl: 'Other parties + their own protocol + no agents on their side = Transfer Family. Name the violated constraint when you cross out: C keeps the server, D breaks “cannot change tooling”.' },
  { id: 'D09', src: 'Retest R3', line: 'backup',
    q: 'A company runs Oracle on EC2 with a 2 TB io2 volume in eu-west-1. It needs a nightly, application-consistent backup restorable in eu-central-1 within 4 hours, and it wants backup retention for this volume, its RDS instances and its EFS file systems managed in one place. Which solution?',
    opts: [_o('Use Amazon Data Lifecycle Manager to snapshot the volume nightly and copy the snapshot to eu-central-1.', 0, 'DLM is EBS/AMI only — fails “RDS and EFS in one place”.'),
      _o('Use AWS Backup with a backup plan covering the EC2 instance, RDS and EFS, with cross-Region copy to eu-central-1.', 1, 'One place, many services, cross-Region copies.'),
      _o('Use S3 Cross-Region Replication on the bucket that stores the volume’s snapshots.', 0, 'No visible snapshot bucket exists.'),
      _o('Use AWS DataSync to copy the volume’s files nightly to an EFS file system in eu-central-1.', 0, 'Not a consistent DB backup, and not “one place”.')],
    stub: { size: 'any', time: 'ongoing', proto: 'AWS-internal', sup: 'none stated' }, words: ['managed in one place', 'RDS instances', 'EFS file systems'],
    expl: 'When two options both “work”, the constraint only one satisfies decides it: “one place” for EC2 + RDS + EFS = AWS Backup.' },
  { id: 'D10', src: 'Exam Q8', mine: true, line: 'datasync', tag: 'C',
    q: 'An on-premises storage system holds historical records and frequently accessed data. Active data is growing fast and capacity is nearly exhausted, so the historical records will move to AWS. Which option is best for cost and operational management?',
    opts: [_o('Use DataSync to move the historical records to S3 Standard, with a lifecycle rule to Glacier Deep Archive after 30 days.', 0, 'Pays for Standard for 30 days for no reason.'),
      _o('Use Storage Gateway to move the records to S3 Glacier, with a lifecycle rule from Standard to Deep Archive after 30 days.', 0, 'A bridge, not a mover.'),
      _o('Use DataSync to move the historical records directly to S3 Glacier Deep Archive.', 1, 'DataSync writes to any S3 class.'),
      _o('Use Storage Gateway to move the historical records to S3 Glacier Deep Archive.', 0, 'A bridge, not a mover.')],
    stub: { size: 'fits the pipe', time: 'one-off', proto: 'NFS/SMB', sup: 'cheapest' }, words: ['historical records', 'move'],
    expl: 'The records leave on-prem for good — mover, not bridge. DataSync can land them straight in Deep Archive.' },
  { id: 'D11', src: 'Exam Q12', mine: true, line: 'truck', tag: 'C',
    q: 'A company must move an 80 TB data warehouse to the cloud. At its current bandwidth the transfer would take 2 months. Which option is the most cost-effective for a quick upload?',
    opts: [_o('AWS Data Transfer Terminal', 1, 'Bypasses the bandwidth bottleneck.'), _o('AWS DataSync', 0, 'Still limited by the same bandwidth.'), _o('AWS Storage Gateway Volume Gateway', 0, 'Hybrid block access, not a bulk move.'), _o('AWS Direct Connect', 0, 'Provisioning time + ongoing cost for a one-off.')],
    stub: { size: 'weeks+ online', time: 'one-off', proto: 'any', sup: 'fastest' }, words: ['2 months'],
    expl: 'The scenario already did the pipe math for you: 2 months. One-off + weeks → the truck line.' },
  { id: 'D12', src: 'Exam Q29', mine: true, line: 'backup', tag: 'C',
    q: 'A company must set up automated backups of all EBS volumes attached to its EC2 instances as soon as possible. The solution must be cost-effective and simple to maintain. What is the fastest and most cost-effective solution?',
    opts: [_o('Use an EBS snapshot retention rule in AWS Backup.', 0, 'Works, but the multi-service tool is more than an EBS-only need (per the source provider).'),
      _o('Create a scheduled job that calls create-snapshot with the AWS CLI.', 0, 'Custom scripting to maintain.'),
      _o('Use Amazon Data Lifecycle Manager to automate EBS snapshots.', 1, 'EBS-only, policy-based, no extra cost.'),
      _o('Use Storage Gateway with the EBS volumes as a source and store backups on-premises.', 0, 'Not what Storage Gateway does.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'AWS-internal', sup: 'least ops' }, words: ['EBS volumes', 'as soon as possible', 'simple to maintain'],
    expl: 'Only EBS, and “fastest / simplest” → DLM. Had it said RDS or another account too, AWS Backup.' },
  { id: 'D13', src: 'Exam Q41', mine: true, line: 'gateway', tag: 'K',
    q: 'An organization uses a tape backup solution on-premises. It plans to keep the backup data in a cloud storage service for up to 10 years, accessed about once or twice a year. Which option is the most cost-effective?',
    opts: [_o('Use AWS Storage Gateway to back up the data and transition it to S3 Glacier Deep Archive.', 1, 'Tape Gateway → Deep Archive.'),
      _o('Use AWS Storage Gateway to back up the data directly to S3 Glacier Flexible Retrieval.', 0, 'Works, but dearer than Deep Archive.'),
      _o('Store the backup data in S3 and add a lifecycle rule to transition it to S3 Glacier.', 0, 'The backup software cannot write to a bucket; not the cheapest class.'),
      _o('Use AWS Data Transfer Terminal to move the backup data into S3 Glacier Flexible Retrieval.', 0, 'A one-off physical move, not a replacement for ongoing tape backups.')],
    stub: { size: 'any', time: 'ongoing', proto: 'tape', sup: 'cheapest' }, words: ['tape backup', '10 years', 'once or twice a year'],
    expl: 'One keyword decides it: tape. Then 10 years at 1–2 reads/year = Deep Archive.' },
  { id: 'D14', src: 'Exam Q54', mine: true, line: 'truck', tag: 'C',
    q: 'A media company has about 250 TB of archived video and audio on portable storage and a 100 Mbps dedicated internet line. It must import the archive into Amazon S3. What is the FASTEST and MOST COST-EFFECTIVE way?',
    opts: [_o('Import the dataset through AWS Data Transfer Terminal.', 1, 'No pipe in the critical path.'), _o('Upload it directly to S3.', 0, '100 Mbps ≈ 1 TB/day → ~250 days.'), _o('Set up AWS Direct Connect and transfer over it.', 0, 'Setup time and cost for a one-off.'), _o('Use S3 Transfer Acceleration.', 0, 'Still limited by 100 Mbps.')],
    stub: { size: 'weeks+ online', time: 'one-off', proto: 'any', sup: 'fastest' }, words: ['250 TB', '100 Mbps'],
    expl: '250 TB at ~1 TB/day is most of a year. Truck.' },
  { id: 'D15', src: 'Exam Q56', mine: true, line: 'dms', tag: 'C',
    q: 'An on-premises MySQL database must be replicated to Amazon S3 as CSV files. After the full copy, ongoing changes must be streamed continually into the bucket. The solution must need little management and be highly secure. Which approach?',
    opts: [_o('Use AWS SCT to convert MySQL data to CSV and AWS MGN to capture ongoing changes.', 0, 'SCT converts schemas; MGN rehosts servers.'),
      _o('Use DataSync to migrate the data to S3 and Data Transfer Terminal for ongoing changes, with a custom KMS key.', 0, 'DataSync cannot read a database; DTT is physical.'),
      _o('Create a DMS full load and change data capture (CDC) task; add a CA certificate and use an SSL endpoint.', 1, 'Full load + CDC to S3 (CSV by default), encrypted in transit.'),
      _o('Create a DMS full-load-only task and an SSL endpoint using AWS Network Firewall.', 0, 'No CDC; Network Firewall does not create DMS endpoints.')],
    stub: { size: 'any', time: 'ongoing', proto: 'database', sup: 'least ops' }, words: ['MySQL database', 'ongoing changes', 'CSV'],
    expl: 'Database + ongoing changes = DMS full load + CDC, even when the target is plain CSV files in S3.' },
  { id: 'D16', src: 'Exam Q11', mine: true, line: 'backup', tag: 'C',
    q: 'An API on EKS uses an Amazon DynamoDB table in us-east-1. Database calls must not traverse the public internet, and an automated cross-account backup of the table is required for long-term retention. Which solution?',
    opts: [_o('Create a DynamoDB interface endpoint and enable point-in-time recovery to restore into another account.', 0, 'PITR restores within the same account and Region.'),
      _o('Create a DynamoDB gateway endpoint, add a NACL rule, and use native on-demand backups for cross-account copies.', 0, 'Native on-demand backups cannot be copied cross-account.'),
      _o('Create an interface endpoint, filter with AWS Network Firewall, and use Amazon Timestream for recovery.', 0, 'Nonsense combination.'),
      _o('Create a DynamoDB gateway endpoint on the route table and use AWS Backup to copy backups to another account.', 1, 'Private path + cross-account copies.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'AWS-internal', sup: 'most durable/compliant' }, words: ['cross-account backup', 'long-term retention', 'public internet'],
    expl: '“Another account” is where native backups stop and AWS Backup starts. (DynamoDB now also offers interface endpoints; the gateway endpoint is the classic, free answer.)' },
  { id: 'D17', src: 'Exam Q4', mine: true, line: 'edge', tag: 'C',
    q: 'AWS Outposts servers in remote locations worldwide frequently download software updates made of many files from an S3 bucket in us-west-2, and distribution is slow. What reduces the latency MOST effectively with minimal operational overhead?',
    opts: [_o('A CloudFront distribution with a secondary origin in another Region and a CachingDisabled policy, with signed URLs.', 0, 'Disabling caching removes the benefit.'),
      _o('AWS Global Accelerator to the nearest edge, then private VIFs to the bucket.', 0, 'Prestige distractor; not an S3 download cache.'),
      _o('A CloudFront distribution with the bucket as origin, and signed URLs for downloads.', 1, 'Cached at the edge, private access.'),
      _o('S3 Transfer Acceleration, with the servers downloading from its endpoint.', 0, 'TA is for uploads and caches nothing.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'objects/HTTP', sup: 'least ops' }, words: ['download', 'frequently', 'worldwide'],
    expl: 'Same files, downloaded repeatedly, from everywhere = cache at the edge = CloudFront.' },
  { id: 'D18', src: 'New', line: 'gateway',
    q: 'An on-premises iSCSI SAN is 95% full. The company wants primary data stored in AWS while recently accessed blocks stay on-premises with low latency. Which solution?',
    opts: [_o('Volume Gateway with cached volumes.', 1, 'Cloud primary, hot subset local.'), _o('Volume Gateway with stored volumes.', 0, 'Keeps the full dataset on-prem — frees nothing.'), _o('S3 File Gateway.', 0, 'NFS/SMB files, not iSCSI blocks.'), _o('DataSync to Amazon EBS.', 0, 'DataSync does not target EBS; not ongoing block access.')],
    stub: { size: 'any', time: 'ongoing', proto: 'iSCSI/block', sup: 'none stated' }, words: ['iSCSI', '95% full', 'primary data stored in AWS'],
    expl: 'iSCSI → Volume Gateway. Running out of space → cached, not stored.' },
  { id: 'D19', src: 'New', line: 'gateway',
    q: 'A trading desk needs low-latency access to its entire 20 TB iSCSI dataset on-premises, plus point-in-time backups in AWS that could be restored as EBS volumes during a disaster. Which solution?',
    opts: [_o('Volume Gateway with stored volumes.', 1, 'Full copy local, async snapshots to AWS.'), _o('Volume Gateway with cached volumes.', 0, 'Only a hot subset stays local.'), _o('Tape Gateway.', 0, 'For backup software writing tapes, not live block access.'), _o('FSx File Gateway.', 0, 'SMB files, not iSCSI; and closed to new customers.')],
    stub: { size: 'any', time: 'ongoing', proto: 'iSCSI/block', sup: 'fastest' }, words: ['entire 20 TB', 'low-latency', 'restored as EBS volumes'],
    expl: '“Entire dataset” local → stored volumes. Their snapshots restore as EBS in AWS.' },
  { id: 'D20', src: 'New', line: 'datasync',
    q: 'A company must copy 300 TB from Azure Blob Storage to Amazon S3 and keep new files synchronised weekly for three months during a migration. Which option has the LEAST operational overhead?',
    opts: [_o('AWS DataSync with a scheduled task.', 1, 'Supports Azure Blob as a source; schedules and verifies.'), _o('AWS Transfer Family SFTP endpoint.', 0, 'Azure is not an SFTP client.'), _o('S3 File Gateway deployed in Azure.', 0, 'A bridge for on-prem apps.'), _o('AWS Data Transfer Terminal.', 0, 'Trucks don’t do weekly sync.')],
    stub: { size: 'fits the pipe', time: 'ongoing', proto: 'objects/HTTP', sup: 'least ops' }, words: ['Azure Blob Storage', 'synchronised weekly'],
    expl: 'Other clouds are DataSync sources. Ongoing weekly sync rules out any physical option.' },
  { id: 'D21', src: 'New', line: 'where',
    q: 'A .NET application runs on Windows EC2 instances in two Availability Zones and needs a shared file system with SMB and Active Directory ACLs that survives an AZ failure. Which storage?',
    opts: [_o('Amazon FSx for Windows File Server, Multi-AZ.', 1, 'SMB, AD, two AZs.'), _o('Amazon EFS (Regional).', 0, 'NFS for Linux.'), _o('EBS io2 with Multi-Attach.', 0, 'Single AZ, needs a cluster FS.'), _o('An S3 File Gateway running on EC2.', 0, 'An on-prem bridge; needless hop.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'NFS/SMB', sup: 'most durable/compliant' }, words: ['Windows', 'SMB', 'Active Directory', 'two Availability Zones'],
    expl: 'Windows + SMB + AD → FSx for Windows. AZ failure → Multi-AZ deployment.' },
  { id: 'D22', src: 'New', line: 'where',
    q: 'Thousands of Linux containers across three Availability Zones need shared POSIX storage. The data size is unpredictable. Which option has the LEAST operational overhead?',
    opts: [_o('Amazon EFS (Regional) with Elastic throughput.', 1, 'Scales automatically, multi-AZ, NFS.'), _o('EBS io2 with Multi-Attach.', 0, 'One AZ, max 16 instances.'), _o('Amazon FSx for Windows File Server.', 0, 'SMB for Windows.'), _o('EC2 instance store.', 0, 'Ephemeral and not shared.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'NFS/SMB', sup: 'least ops' }, words: ['Thousands of Linux', 'three Availability Zones', 'unpredictable'],
    expl: 'Linux + thousands of clients + multi-AZ + no capacity planning = EFS.' },
  { id: 'D23', src: 'New', line: 'where',
    q: 'A company runs NetApp ONTAP on-premises, replicates with SnapMirror, and serves NFS and SMB from the same volumes. It wants the same capabilities as a managed service in AWS with minimal changes. Which service?',
    opts: [_o('Amazon FSx for NetApp ONTAP.', 1, 'Managed ONTAP, SnapMirror-compatible, multi-protocol.'), _o('Amazon FSx for Windows File Server.', 0, 'SMB only, no SnapMirror.'), _o('Amazon EFS.', 0, 'NFS only.'), _o('Amazon FSx for OpenZFS.', 0, 'No SnapMirror, no SMB/iSCSI multi-protocol.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'NFS/SMB', sup: 'least ops' }, words: ['NetApp ONTAP', 'SnapMirror', 'NFS and SMB'],
    expl: 'The word NetApp is the whole question.' },
  { id: 'D24', src: 'New', line: 'where',
    q: 'A genomics pipeline must process 50 TB of input stored in S3 with massively parallel, high-throughput file access for a 3-day job, then write the results back to S3. Which option is lowest cost?',
    opts: [_o('An FSx for Lustre scratch file system linked to the bucket.', 1, 'Temporary, cheapest Lustre, S3-linked.'), _o('An FSx for Lustre persistent file system.', 0, 'Pays for durability a 3-day job does not need.'), _o('Amazon EFS in Max I/O mode.', 0, 'Not built for this, and needs a copy.'), _o('Amazon FSx for NetApp ONTAP.', 0, 'Enterprise NAS features unused.')],
    stub: { size: 'not about transfer', time: 'one-off', proto: 'NFS/SMB', sup: 'cheapest' }, words: ['high-throughput', '3-day job', 'lowest cost'],
    expl: 'HPC on S3 data → Lustre. Temporary + cheapest → scratch.' },
  { id: 'D25', src: 'New', line: 'classes',
    q: 'A data lake holds objects whose access patterns are unknown and change over time. The team wants automatic cost savings, no retrieval fees and no lifecycle tuning. Which storage class?',
    opts: [_o('S3 Intelligent-Tiering.', 1, 'Moves objects between tiers for you; no retrieval fees.'), _o('S3 Standard-IA.', 0, 'Retrieval fees; wrong if data turns hot.'), _o('A lifecycle rule to Glacier Instant Retrieval after 30 days.', 0, 'Needs tuning; retrieval fees.'), _o('S3 One Zone-IA.', 0, 'Single AZ, retrieval fees.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'objects/HTTP', sup: 'least ops' }, words: ['unknown', 'change over time', 'no retrieval fees'],
    expl: 'Unknown or changing access = Intelligent-Tiering.' },
  { id: 'D26', src: 'New', line: 'classes',
    q: 'An application stores thumbnails it can regenerate from the originals at any time. Thumbnails are rarely read but must load instantly. Which storage class is cheapest?',
    opts: [_o('S3 One Zone-IA.', 1, 'Re-creatable + instant + cheap.'), _o('S3 Standard-IA.', 0, 'Pays for multi-AZ resilience on re-creatable data.'), _o('S3 Glacier Instant Retrieval.', 0, '90-day minimum and higher retrieval price for this use.'), _o('S3 Glacier Flexible Retrieval.', 0, 'Not instant.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'objects/HTTP', sup: 'cheapest' }, words: ['regenerate', 'instantly', 'cheapest'],
    expl: 'The word “regenerate” (re-creatable) is what unlocks One Zone-IA.' },
  { id: 'D27', src: 'New', line: 'classes',
    q: 'Medical images are kept for 5 years, typically read about once a quarter, and must be viewable within milliseconds when requested. Which storage class is lowest cost?',
    opts: [_o('S3 Glacier Instant Retrieval.', 1, 'Built for ~quarterly access with millisecond reads.'), _o('S3 Glacier Flexible Retrieval.', 0, 'Minutes to hours.'), _o('S3 Standard-IA.', 0, 'Works, but higher storage cost for quarterly access.'), _o('S3 Glacier Deep Archive.', 0, 'Up to 12 hours.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'objects/HTTP', sup: 'cheapest' }, words: ['once a quarter', 'milliseconds'],
    expl: 'Quarterly + milliseconds is the definition of Glacier Instant Retrieval.' },
  { id: 'D28', src: 'New', line: 'classes',
    q: 'Legal archives are kept for 10 years and rarely needed, but when a court request arrives the files must be available within 15 minutes. Which option is lowest cost?',
    opts: [_o('S3 Glacier Flexible Retrieval, using expedited retrievals when needed.', 1, 'Expedited = 1–5 minutes.'), _o('S3 Glacier Deep Archive.', 0, 'Standard retrieval takes up to 12 hours.'), _o('S3 Standard-IA.', 0, 'Far more storage cost than needed.'), _o('Intelligent-Tiering with the Deep Archive Access tier.', 0, 'That tier takes hours to restore.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'objects/HTTP', sup: 'cheapest' }, words: ['within 15 minutes', '10 years', 'rarely'],
    expl: '“Minutes” rules out Deep Archive; Flexible with expedited retrieval is the cheapest class that meets it.' },
  { id: 'D29', src: 'New', line: 'classes',
    q: 'Audit logs must be retained for 7 years in WORM form. Nobody, including the root user, may delete or overwrite them during that period. Which solution?',
    opts: [_o('S3 Object Lock in compliance mode with a 7-year retention period (versioning enabled).', 1, 'Even root cannot shorten or remove it.'), _o('S3 Object Lock in governance mode.', 0, 'Users with bypass permission can delete.'), _o('Enable MFA Delete on the bucket.', 0, 'The root user with MFA can still delete.'), _o('A bucket policy that denies DeleteObject.', 0, 'Admins can change the policy.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'objects/HTTP', sup: 'most durable/compliant' }, words: ['WORM', 'including the root user'],
    expl: '“Even root” → compliance mode. Governance mode is for “only privileged users may override”.' },
  { id: 'D30', src: 'New', line: 'edge',
    q: 'Users on five continents upload multi-GB video files to a single S3 bucket in us-east-1. Uploads from Asia are slow. How can upload speed improve with minimal changes?',
    opts: [_o('Enable S3 Transfer Acceleration and use its endpoint.', 1, 'Uploads enter AWS at the nearest edge.'), _o('Put a CloudFront distribution in front of the bucket.', 0, 'Built for downloads and caching.'), _o('Install DataSync agents at the users’ sites.', 0, 'Users are not servers you manage.'), _o('Put AWS Global Accelerator in front of the bucket.', 0, 'Prestige distractor; not the S3 upload feature.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'objects/HTTP', sup: 'least ops' }, words: ['upload', 'five continents', 'single S3 bucket'],
    expl: 'Many far-away clients uploading into one bucket = Transfer Acceleration.' },
  { id: 'D31', src: 'New', line: 'backup',
    q: 'A team enabled S3 Cross-Region Replication on a bucket that already holds 2 million objects. New objects replicate; the existing objects do not. How can they replicate the existing objects with the least effort?',
    opts: [_o('Run S3 Batch Replication.', 1, 'Built for existing objects.'), _o('Disable and re-enable versioning.', 0, 'Does not trigger replication.'), _o('Copy them with DataSync between the buckets.', 0, 'Possible, but not the purpose-built answer.'), _o('Add a lifecycle rule to copy the objects.', 0, 'Lifecycle transitions or expires; it does not copy.')],
    stub: { size: 'not about transfer', time: 'one-off', proto: 'objects/HTTP', sup: 'least ops' }, words: ['already holds 2 million objects', 'existing objects'],
    expl: 'CRR is not retroactive. Existing objects → Batch Replication.' },
  { id: 'D32', src: 'New', line: 'where',
    q: 'A mission-critical database on EC2 needs the highest IOPS, sub-millisecond latency and the highest durability EBS offers. Which volume type?',
    opts: [_o('EBS io2 Block Express.', 1, 'Up to 256,000 IOPS, 99.999% durability.'), _o('EBS gp3.', 0, 'Now up to 80,000 IOPS, but lower durability and ceiling.'), _o('EBS st1.', 0, 'HDD for throughput, not IOPS.'), _o('EC2 instance store.', 0, 'Fast but lost on stop — not a system of record.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'iSCSI/block', sup: 'fastest' }, words: ['highest IOPS', 'mission-critical', 'highest durability'],
    expl: '“Highest” anything on EBS = io2 Block Express.' },
  { id: 'D33', src: 'New', line: 'where',
    q: 'A nightly batch job needs very fast temporary scratch space. The data is recreated on every run and losing it is acceptable. Which option gives the performance at the lowest cost?',
    opts: [_o('EC2 instance store.', 1, 'Local NVMe, included in the instance price.'), _o('EBS io2.', 0, 'Paying for durability you do not need.'), _o('Amazon EFS.', 0, 'A network file system; slower and dearer for scratch.'), _o('S3 Express One Zone.', 0, 'An object API, not a local disk.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'iSCSI/block', sup: 'cheapest' }, words: ['temporary scratch', 'losing it is acceptable'],
    expl: 'Temporary + loss OK + fastest = instance store.' },
  { id: 'D34', src: 'New', line: 'where',
    q: 'A security review finds an unencrypted EBS volume attached to a production instance. The volume must be encrypted. What should the team do?',
    opts: [_o('Snapshot the volume, copy the snapshot with encryption enabled, create a volume from it, and swap it in.', 1, 'The only path for an existing volume.'), _o('Modify the volume and enable encryption.', 0, 'An existing volume cannot be encrypted in place.'), _o('Enable EBS encryption by default in the Region.', 0, 'Only affects new volumes.'), _o('Use DataSync to copy the volume to an encrypted volume.', 0, 'DataSync does not target EBS.')],
    stub: { size: 'not about transfer', time: 'one-off', proto: 'iSCSI/block', sup: 'none stated' }, words: ['unencrypted EBS volume'],
    expl: 'Encryption is set at creation. Snapshot → encrypted copy → new volume.' },
  { id: 'D35', src: 'New', line: 'backup',
    q: 'An EBS snapshot encrypted with the AWS managed key (aws/ebs) must be shared with a partner account, and the share fails. What fixes it?',
    opts: [_o('Copy the snapshot, re-encrypting it with a customer managed KMS key, then share both the key and the snapshot.', 1, 'Customer managed keys can be shared.'), _o('Make the snapshot public.', 0, 'Encrypted snapshots cannot be public — and it would expose data.'), _o('Add the partner account to the AWS managed key policy.', 0, 'AWS managed key policies cannot be edited.'), _o('Replicate the snapshot to the partner with S3 CRR.', 0, 'There is no visible snapshot bucket.')],
    stub: { size: 'not about transfer', time: 'one-off', proto: 'AWS-internal', sup: 'none stated' }, words: ['AWS managed key', 'partner account'],
    expl: 'AWS managed keys stay in their account. Re-encrypt with a customer managed key.' },
  { id: 'D36', src: 'New', line: 'where',
    q: 'An EBS volume in us-east-1a must be used by an instance in us-east-1c. How?',
    opts: [_o('Snapshot the volume and create a new volume from the snapshot in us-east-1c.', 1, 'Snapshots are Regional; volumes are AZ-scoped.'), _o('Detach it and attach it to the instance in us-east-1c.', 0, 'EBS attaches only within its AZ.'), _o('Enable Multi-Attach.', 0, 'Same AZ only.'), _o('Copy it with DataSync.', 0, 'Not an EBS tool.')],
    stub: { size: 'not about transfer', time: 'one-off', proto: 'iSCSI/block', sup: 'none stated' }, words: ['us-east-1a', 'us-east-1c'],
    expl: 'EBS lives in one AZ. Crossing AZs always goes through a snapshot.' },
  { id: 'D37', src: 'New', line: 'transfer',
    q: 'A retailer exchanges EDI purchase orders with trading partners over AS2 and wants the messages stored in S3 without running any servers. Which service?',
    opts: [_o('AWS Transfer Family with an AS2 server and S3 storage.', 1, 'Managed AS2.'), _o('AWS DataSync.', 0, 'Partners do not run your agent.'), _o('API Gateway and Lambda parsing AS2 messages.', 0, 'A custom build.'), _o('S3 File Gateway.', 0, 'An on-prem bridge.')],
    stub: { size: 'any', time: 'ongoing', proto: 'SFTP/FTP/AS2', sup: 'least ops' }, words: ['AS2', 'trading partners'],
    expl: 'AS2 is one of Transfer Family’s four protocols.' },
  { id: 'D38', src: 'New', line: 'datasync',
    q: 'A company will migrate a 50 TB NAS to Amazon S3 over its 1 Gbps connection within two weeks, then retire the NAS. Afterwards, on-premises applications must still read a small subset of those files with low latency. Which combination?',
    opts: [_o('AWS DataSync to migrate the data to S3.', 1, 'Mover for the migration.'), _o('S3 File Gateway for ongoing on-premises access.', 1, 'Bridge for what stays in use.'), _o('AWS Data Transfer Terminal.', 0, '50 TB ≈ 5 days at 1 Gbps — fits the pipe.'), _o('AWS Transfer Family.', 0, 'A partner door.'), _o('Volume Gateway stored volumes.', 0, 'Block, full local copy.')],
    stub: { size: 'fits the pipe', time: 'ongoing', proto: 'NFS/SMB', sup: 'none stated' }, words: ['migrate', 'retire the NAS', 'still read'],
    expl: 'AWS’s own pattern: DataSync to migrate, then File Gateway for ongoing access.' },
  { id: 'D39', src: 'New', line: 'backup',
    q: 'A company must back up its on-premises VMware VMs and its Amazon RDS databases under one backup policy, with centralised reports for auditors. Which solution?',
    opts: [_o('AWS Backup with backup plans and AWS Backup Audit Manager.', 1, 'One policy across VMware and AWS services, with audit reports.'), _o('Amazon Data Lifecycle Manager.', 0, 'EBS/AMI only.'), _o('RDS automated backups plus Storage Gateway.', 0, 'Two tools, no single policy.'), _o('Tape Gateway.', 0, 'A VTL for backup software.')],
    stub: { size: 'any', time: 'ongoing', proto: 'AWS-internal', sup: 'most durable/compliant' }, words: ['one backup policy', 'VMware VMs', 'auditors'],
    expl: 'Many sources + one policy + audit = AWS Backup.' },
  { id: 'D40', src: 'New', line: 'classes',
    q: 'The S3 bill keeps growing although the object count is flat. Investigation shows many failed multipart uploads. What is the cheapest fix with the least ongoing effort?',
    opts: [_o('A lifecycle rule that aborts incomplete multipart uploads after N days.', 1, 'Built for exactly this.'), _o('Switch to Intelligent-Tiering.', 0, 'Upload parts are not objects.'), _o('A weekly Lambda that lists and aborts uploads.', 0, 'Custom ops.'), _o('Disable versioning.', 0, 'Unrelated.')],
    stub: { size: 'not about transfer', time: 'ongoing', proto: 'objects/HTTP', sup: 'cheapest' }, words: ['failed multipart uploads'],
    expl: 'Lifecycle can abort incomplete multipart uploads.' },
  { id: 'D41', src: 'New', line: 'datasync',
    q: 'A company has a new 10 Gbps Direct Connect link. It must copy 400 TB of NFS data to Amazon S3 within a month and verify that every file arrived intact. Which option?',
    opts: [_o('AWS DataSync over the Direct Connect link, with data verification.', 1, '10 Gbps ≈ 100 TB/day; DataSync verifies.'), _o('AWS Data Transfer Terminal.', 0, 'The link already fits.'), _o('S3 File Gateway.', 0, 'A bridge, not a mover.'), _o('rsync from an EC2 instance.', 0, 'Self-managed, no built-in verification.')],
    stub: { size: 'fits the pipe', time: 'one-off', proto: 'NFS/SMB', sup: 'none stated' }, words: ['10 Gbps Direct Connect', 'verify'],
    expl: 'The exception to the truck rule: a fat link already exists. Run the math — 400 TB ≈ 4 days.' },
  { id: 'D42', src: 'New · current', line: 'gateway',
    q: 'A company’s Windows users map an SMB share on-premises. The company wants the files stored as objects in Amazon S3, a local cache for recently used files, and existing Active Directory users and permissions. The team has not used Storage Gateway before. Which solution is available to them?',
    opts: [_o('S3 File Gateway with an SMB file share joined to the Active Directory domain.', 1, 'SMB + AD, objects in S3, local cache — and open to new customers.'), _o('FSx File Gateway.', 0, 'No longer available to new customers.'), _o('Volume Gateway cached volumes.', 0, 'iSCSI block, not an SMB share.'), _o('AWS DataSync on a schedule.', 0, 'A mover; users would not get a live share.')],
    stub: { size: 'any', time: 'ongoing', proto: 'NFS/SMB', sup: 'none stated' }, words: ['objects in Amazon S3', 'local cache', 'not used Storage Gateway before'],
    expl: 'S3 File Gateway speaks SMB too and can join AD. FSx File Gateway exists only for existing customers now.',
    update: 'Written for the current state (Sept 2026). An older bank might still prefer FSx File Gateway when the target is FSx for Windows.' }
];
