/* Session 2 drills (Migration & Hybrid). stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit. */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _o = (t, ok, why) => ({ t, ok: !!ok, why });
  S.drills = [
    { id: 'M1', src: 'Quiz M1', line: 'mgn',
      q: 'A company’s data-center lease ends in 10 weeks. The data center runs 180 VMware virtual machines and 20 physical Linux servers. The applications are poorly documented and nobody has time to re-architect them. Everything must be running in AWS before the lease ends, with the fewest changes to the applications. Which solution meets these requirements MOST quickly?',
      opts: [_o('Refactor the applications into containers on Amazon ECS and move their databases with AWS DMS.', 0, 'Too much change for undocumented apps; will not finish in 10 weeks.'),
        _o('Use AWS Application Migration Service (MGN) to replicate all servers to Amazon EC2, run test launches, and cut over in waves.', 1, 'Block-level replication of VMware and physical servers to EC2, no app changes, minutes of cutover.'),
        _o('Use AWS DataSync to copy the servers’ file systems to Amazon EFS, then rebuild the servers from AMIs.', 0, 'DataSync moves files, not servers; rebuilding is not “fewest changes”.'),
        _o('Use AWS Elastic Disaster Recovery to replicate the servers, then fail over permanently.', 0, 'DRS is a DR tool that expects failback; migration is MGN’s job.')],
      stub: { what: 'servers', change: 'none (rehost)', down: 'minimal', sup: 'fastest' }, words: ['fewest changes', '10 weeks', 'physical'],
      expl: 'WHAT = whole servers (VMware + physical), CHANGE = none → Rehost, and a hard deadline → MGN replicating to EC2 in waves.' },
    { id: 'M2', src: 'Quiz M2', line: 'discover',
      q: 'A company plans to migrate 400 servers to AWS in waves. The estate is a mix of VMware virtual machines and bare metal hosts. The migration team does not know which servers communicate with each other, and a pilot move already broke an application because a dependency was left behind. Which solution will give the team the data it needs to plan the migration waves?',
      opts: [_o('Deploy the Application Discovery Service agentless collector in vCenter and use its utilisation data.', 0, 'Utilisation shows how busy each VM is, not which servers talk to each other; and a vCenter collector cannot see the bare metal hosts.'),
        _o('Install the AWS Application Discovery Agent on each server and review the network connections between servers.', 1, 'The agent records processes and network connections → dependency map → waves; works on bare metal too.'),
        _o('Enable VPC Flow Logs and analyse traffic between the servers.', 0, 'The servers are not in a VPC yet.'),
        _o('Use AWS Config to record relationships between the servers.', 0, 'Config records resource configurations, not the traffic between servers.')],
      stub: { what: 'inventory/plan', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['communicate with each other', 'bare metal'],
      expl: 'WHAT = plan, and the plan needs dependencies. Of these options only the Discovery agent records network connections, and it runs on bare metal as well as VMs.',
      update: 'Application Discovery Service and Migration Hub are closed to new customers since 7 Nov 2025. AWS Transform’s agentless discovery tool now collects server-to-server connections too (over SSH/WinRM) and builds the dependency map and waves. Banks still say Application Discovery Service and expect the agent.' },
    { id: 'M3', src: 'Quiz M3', line: 'dms',
      q: 'A company runs a 4 TB Oracle 19c database on-premises. The application relies on hundreds of PL/SQL stored procedures. The company wants to move the database to Amazon Aurora PostgreSQL, and the business will accept no more than 30 minutes of downtime at cutover. Which combination of steps should a solutions architect take? (Select TWO.)',
      opts: [_o('Use the AWS Schema Conversion Tool (AWS SCT) or DMS Schema Conversion to convert the schema and the stored procedures to PostgreSQL.', 1, 'Heterogeneous move: schema and code need conversion, and that is SCT’s job.'),
        _o('Use AWS DMS to convert the stored procedures automatically during the full load.', 0, 'DMS moves data; it does not convert stored procedures or code.'),
        _o('Use AWS DMS with a full load plus change data capture (CDC) task, and cut over when replication lag is near zero.', 1, 'Source stays online; only the final catch-up counts as downtime.'),
        _o('Use AWS Application Migration Service to replicate the database server, then switch the engine to PostgreSQL.', 0, 'MGN lands the same Oracle server on EC2; it cannot change the engine.'),
        _o('Take an RMAN backup and restore it into Aurora PostgreSQL.', 0, 'RMAN backups restore only into Oracle; the engines differ.')],
      stub: { what: 'database', change: 'replatform', down: 'minimal', sup: 'none stated' }, words: ['PL/SQL stored procedures', 'Aurora PostgreSQL', '30 minutes'],
      expl: 'Different engine → SCT/DMS Schema Conversion for structure and code; minimal downtime → DMS full load + CDC for the rows.' },
    { id: 'M4', src: 'Quiz M4', line: 'dms',
      q: 'A company runs its production database on Amazon RDS for MySQL. It wants to move to Amazon Aurora MySQL for better performance and automatic storage scaling. The application team asks for the least downtime and least operational effort possible during the move. What should a solutions architect recommend?',
      opts: [_o('Create an Aurora MySQL read replica of the RDS for MySQL DB instance, and promote it when replica lag reaches zero.', 1, 'Native path: no extra tooling, downtime is only the switch after lag hits zero.'),
        _o('Take a snapshot of the RDS DB instance and restore it as an Aurora MySQL DB cluster.', 0, 'Downtime for the whole restore, or writes after the snapshot are lost.'),
        _o('Use AWS DMS with a full load plus CDC task from RDS for MySQL to Aurora MySQL.', 0, 'Works, but a replication instance, endpoints and tasks are more to manage.'),
        _o('Export the database with mysqldump and import it into a new Aurora MySQL cluster.', 0, 'Writes must stop for the whole dump and import: long downtime.')],
      stub: { what: 'database', change: 'replatform', down: 'minimal', sup: 'least ops' }, words: ['RDS for MySQL', 'least downtime and least operational effort'],
      expl: 'Same engine family, minimal downtime, least ops → Aurora read replica of the RDS instance, promote at zero lag. DMS only when engines differ or you need flexibility.' },
    { id: 'M5', src: 'Quiz M5', line: 'dns',
      q: 'A company connects its data center to a VPC with AWS Direct Connect. Applications on Amazon EC2 instances must resolve hostnames in the company’s on-premises domain, corp.internal. On-premises servers must resolve records in an Amazon Route 53 private hosted zone that is associated with the VPC. Which actions meet these requirements? (Select TWO.)',
      opts: [_o('Create a Route 53 Resolver outbound endpoint and a forwarding rule that sends queries for corp.internal to the on-premises DNS servers.', 1, 'EC2 asks on-prem → the query leaves the VPC → outbound + rule.'),
        _o('Create a Route 53 Resolver inbound endpoint, and configure the on-premises DNS servers to conditionally forward the private zone’s domain to the endpoint IP addresses.', 1, 'On-prem asks AWS → the query enters the VPC → inbound.'),
        _o('Create a Route 53 Resolver inbound endpoint with a forwarding rule for corp.internal.', 0, 'Wrong direction: forwarding rules belong to outbound endpoints.'),
        _o('Convert the private hosted zone to a public hosted zone so on-premises servers can resolve it.', 0, 'Exposes internal names to the internet.'),
        _o('Use AWS Global Accelerator to route DNS queries between on-premises and the VPC.', 0, 'Prestige distractor; Global Accelerator routes application traffic, not DNS.')],
      stub: { what: 'DNS', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['resolve hostnames in the company’s on-premises domain', 'private hosted zone'],
      expl: 'Name the endpoint after the direction of the query relative to the VPC: out to corp.internal = outbound + rule; in to the private zone = inbound.',
      update: 'Route 53 Resolver is now called Route 53 VPC Resolver (Route 53 Resolver in older banks).' },
    { id: 'M6', src: 'Quiz M6', line: 'identity',
      q: 'A company is moving a line-of-business application to AWS. The database will run on Amazon RDS for SQL Server with Windows authentication, and the file shares will move to Amazon FSx for Windows File Server, which must be domain-joined. Users must keep signing in with their existing on-premises Active Directory credentials. Authentication in AWS must keep working if the link goes down between AWS and the data center. Which solution meets these requirements?',
      opts: [_o('Deploy AD Connector in AWS and point it at the on-premises domain controllers.', 0, 'Not supported by RDS for SQL Server or FSx for Windows, and it fails when the link is down.'),
        _o('Deploy Simple AD and recreate the users in it.', 0, 'No trusts; users duplicated, so no existing credentials.'),
        _o('Deploy AWS Managed Microsoft AD and create a trust relationship with the on-premises Active Directory.', 1, 'Real AD in two AZs: RDS and FSx join it, the trust keeps on-prem credentials, and it keeps working without the link.'),
        _o('Use Amazon Cognito user pools federated with the on-premises Active Directory.', 0, 'Cognito is for application end users, not Windows authentication or domain joins.')],
      stub: { what: 'identity', change: 'n/a', down: 'n/a', sup: 'resilient' }, words: ['Windows authentication', 'domain-joined', 'link goes down'],
      expl: 'AWS services need a real domain and auth must survive a link outage → AWS Managed Microsoft AD with a trust to on-prem.' },
    { id: 'S7', src: 'Quiz S7', line: 'gateway',
      q: 'A video production company’s editing workstations save projects to an on-premises SMB share. The company wants to stop buying on-premises storage but keep recent projects available at LAN speed. All files must be stored in Amazon S3, and files should move to a cheaper storage class after 90 days. Which solution is the MOST cost-effective?',
      opts: [_o('Run an AWS DataSync task every night to copy the share to S3, with a lifecycle rule to S3 Glacier Flexible Retrieval.', 0, 'Copies only; the share stays on-prem and keeps needing storage. Flexible Retrieval is not instantly readable.'),
        _o('Deploy Amazon S3 File Gateway with an SMB share, and add an S3 Lifecycle rule that moves objects to S3 Standard-IA after 90 days.', 1, 'SMB share with a local cache for recent files, everything in S3, cheaper class after 90 days.'),
        _o('Move the files to Amazon FSx for Windows File Server and access it over a Site-to-Site VPN.', 0, 'No local cache, so not LAN speed; and the files are not in S3.'),
        _o('Deploy Volume Gateway stored volumes and present them to the workstations over iSCSI.', 0, 'Block storage with a full local copy: the company keeps buying storage.')],
      stub: { what: 'files', change: 'any', down: 'n/a', sup: 'cheapest' }, words: ['SMB share', 'LAN speed', 'after 90 days'],
      expl: 'Carry-over from Session 1: a live SMB share with LAN-speed access and S3 behind it is S3 File Gateway; a lifecycle rule handles the 90-day move.',
      update: 'S3 File Gateway does not support Glacier Instant Retrieval, so the lifecycle target here is Standard-IA.' },

    { id: 'N1', src: 'New', line: 'discover',
      q: 'A company runs its entire estate on VMware vSphere and is planning a migration to AWS. The security team forbids installing any software agents on the guest operating systems. The migration team needs CPU and memory utilisation data for every VM so it can right-size the Amazon EC2 instances. Which solution meets these requirements?',
      opts: [_o('Install the AWS Application Discovery Agent on each VM.', 0, 'Installing agents is forbidden.'),
        _o('Install the Amazon CloudWatch agent on each VM and send metrics to CloudWatch.', 0, 'Still an agent install, and it is a monitoring tool, not a discovery tool.'),
        _o('Use AWS Trusted Advisor to analyse the VMs for right-sizing.', 0, 'Trusted Advisor checks AWS resources only.'),
        _o('Deploy the Application Discovery Service agentless collector in vCenter to collect VM inventory and utilisation.', 1, 'Reads inventory and utilisation from vCenter; nothing installed on the VMs.')],
      stub: { what: 'inventory/plan', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['VMware vSphere', 'forbids installing any software agents', 'utilisation'],
      expl: 'WHAT = inventory for sizing, VMware only, no agents → the agentless collector. Dependencies are not asked for, so the agent is not needed.',
      update: 'For new customers this is AWS Transform discovery (agentless discovery tool OVA for vCenter). Banks still say Application Discovery Service.' },
    { id: 'N2', src: 'New', line: 'discover',
      q: 'A company is migrating 60 applications to AWS using several tools: AWS Application Migration Service for servers and AWS DMS for databases. Leadership wants a single place to see the migration status of each application. Which AWS service should the company use?',
      opts: [_o('An Amazon CloudWatch dashboard built from service metrics.', 0, 'Metrics, not migration status per application.'),
        _o('AWS Migration Hub.', 1, 'One dashboard that tracks progress per application across migration tools.'),
        _o('AWS Config with a conformance pack.', 0, 'Records resource configuration and compliance, not migration progress.'),
        _o('AWS Service Catalog.', 0, 'Publishes approved products to users; nothing to do with tracking.')],
      stub: { what: 'inventory/plan', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['several tools', 'single place to see the migration status'],
      expl: 'WHAT = plan/track. “One place for migration status across tools” is Migration Hub’s trigger.',
      update: 'Migration Hub is closed to new customers since 7 Nov 2025; AWS Transform now provides migration tracking and orchestration. Banks still say Migration Hub.' },
    { id: 'N3', src: 'New', line: 'placement',
      q: 'A company must exit its data center quickly. It runs 300 virtual machines on VMware vSphere. The operations team must keep using its existing vCenter tooling and processes, and the company does not want to convert any VMs. Which migration approach meets these requirements?',
      opts: [_o('Use AWS Application Migration Service to replicate the VMs to Amazon EC2.', 0, 'MGN converts VMs into EC2 instances; vCenter tooling does not follow.'),
        _o('Refactor the applications into containers on Amazon EKS.', 0, 'The most change and the slowest; the opposite of “quickly”.'),
        _o('Relocate the VMs to VMware Cloud on AWS with VMware HCX and keep managing them from vCenter.', 1, 'Relocate: the hypervisor moves, the VMs are not converted, vCenter stays.'),
        _o('Use AWS Elastic Disaster Recovery to fail the VMs over to AWS.', 0, 'A DR tool, and it also lands VMs on EC2.')],
      stub: { what: 'servers', change: 'none (rehost)', down: 'any', sup: 'fastest' }, words: ['vCenter tooling', 'not want to convert any VMs', 'quickly'],
      expl: '“Keep vSphere/vCenter, no conversion” = Relocate, the hypervisor-level move. MGN would convert every VM to EC2.',
      update: 'VMware Cloud on AWS is now sold by Broadcom, not AWS (since 30 Apr 2024). AWS’s current Relocate answer is Amazon Elastic VMware Service (EVS, GA Aug 2025) with VMware HCX. Banks still expect VMware Cloud on AWS.' },
    { id: 'N4', src: 'New', line: 'dms',
      q: 'A company is migrating an on-premises Microsoft SQL Server database to Amazon Aurora MySQL. The database contains many views, functions and stored procedures written in T-SQL. The company wants to convert as much of the database code as possible automatically. Which solution meets these requirements?',
      opts: [_o('Use AWS DMS alone with a full load plus CDC task.', 0, 'DMS moves rows; it does not convert T-SQL code.'),
        _o('Use AWS Application Migration Service to replicate the SQL Server host.', 0, 'MGN lands SQL Server on EC2; the engine never changes.'),
        _o('Take a native SQL Server backup and restore it into Aurora MySQL.', 0, 'A SQL Server backup restores only into SQL Server.'),
        _o('Use AWS SCT or DMS Schema Conversion to convert the schema and T-SQL code, then use AWS DMS to migrate the data.', 1, 'Structure and code by SCT/DMS SC, rows by DMS.')],
      stub: { what: 'database', change: 'replatform', down: 'any', sup: 'none stated' }, words: ['SQL Server', 'Aurora MySQL', 'T-SQL'],
      expl: 'Heterogeneous engines + code to convert → SCT or DMS Schema Conversion for structure and code, DMS for the data.' },
    { id: 'N5', src: 'New', line: 'dms',
      q: 'A company must migrate a 10 TB on-premises Oracle database to Amazon RDS for Oracle. The data center’s only connection to AWS is a 50 Mbps internet link, and the database receives constant writes. The business requires minimal downtime at cutover. Which solution meets these requirements?',
      opts: [_o('Run an AWS DMS full load over the 50 Mbps link, then switch the application.', 0, '10 TB at ~0.5 TB/day ≈ 20 days of copying, with changes piling up and no CDC.'),
        _o('Load the initial copy offline through an AWS Data Transfer Terminal, then use an AWS DMS CDC task to catch up and cut over.', 1, 'Truck the bulk, stream only the changes over the thin pipe.'),
        _o('Order an AWS Direct Connect connection and run the migration once it is available.', 0, 'Weeks to provision; nothing in the question pays for that wait.'),
        _o('Use AWS Application Migration Service to replicate the database server.', 0, 'MGN lands on EC2, not RDS, and it still pushes 10 TB through 50 Mbps.')],
      stub: { what: 'database', change: 'replatform', down: 'minimal', sup: 'none stated' }, words: ['10 TB', '50 Mbps', 'minimal downtime'],
      expl: 'Pipe rule first: 10 TB over 50 Mbps is weeks. Huge DB + thin pipe + minimal downtime = seed offline, then DMS CDC.' },
    { id: 'N6', src: 'New', line: 'dms',
      q: 'A company is using AWS DMS to replicate an on-premises PostgreSQL database to Amazon Aurora PostgreSQL. The CDC phase will run for a month before cutover. The company requires that replication continue automatically if an Availability Zone fails. What should a solutions architect do?',
      opts: [_o('Create two DMS tasks on two replication instances in different Availability Zones.', 0, 'Two tasks write the same changes twice; not a failover design.'),
        _o('Take regular snapshots of the replication instance.', 0, 'A snapshot is not automatic failover.'),
        _o('Choose a larger replication instance class.', 0, 'More capacity, still one AZ.'),
        _o('Configure the DMS replication instance as Multi-AZ.', 1, 'A standby in another AZ takes over automatically.')],
      stub: { what: 'database', change: 'any', down: 'minimal', sup: 'resilient' }, words: ['continue automatically', 'Availability Zone fails'],
      expl: 'Resilient DMS = Multi-AZ replication instance (or DMS Serverless in Multi-AZ).' },
    { id: 'N7', src: 'New', line: 'drs',
      q: 'A company runs 120 servers on-premises and will keep them there. It needs a disaster recovery site in AWS with a recovery point objective (RPO) of seconds and a recovery time objective (RTO) of minutes. After the data center is repaired, the company must fail back to it. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('AWS Elastic Disaster Recovery with continuous replication to AWS.', 1, 'Same engine as MGN, but it keeps replicating, fails over and fails back.'),
        _o('AWS Application Migration Service with a test launch kept ready.', 0, 'MGN is one-way migration, not ongoing DR with failback.'),
        _o('AWS Backup with daily backups of the servers copied to AWS.', 0, 'Daily backups mean an RPO of hours, not seconds.'),
        _o('A pilot light environment built by hand with scripts and AMIs.', 0, 'Heavy to build and run; the RPO depends on your own tooling.')],
      stub: { what: 'servers', change: 'none (rehost)', down: 'n/a', sup: 'resilient' }, words: ['will keep them there', 'seconds', 'fail back'],
      expl: 'Servers stay, AWS is the recovery site, RPO seconds and failback → Elastic Disaster Recovery.' },
    { id: 'N8', src: 'New', line: 'mgn',
      q: 'A company is migrating 50 on-premises servers to Amazon EC2. It wants to test-launch each server in AWS before cutover, keep cutover windows to a few minutes, and then decommission the on-premises servers. Which service meets these requirements?',
      opts: [_o('AWS Elastic Disaster Recovery.', 0, 'DR with failback; the servers are leaving, not being protected.'),
        _o('AWS DataSync.', 0, 'Moves files, not bootable servers.'),
        _o('AWS Application Migration Service (MGN).', 1, 'Continuous replication, test launches, minutes of cutover, then finalise.'),
        _o('VM Import/Export.', 0, 'Offline image import: no continuous replication, longer downtime.')],
      stub: { what: 'servers', change: 'none (rehost)', down: 'minimal', sup: 'none stated' }, words: ['test-launch', 'few minutes', 'decommission'],
      expl: 'Servers moving one way, test launches and minutes of cutover = MGN.' },
    { id: 'N9', src: 'New', line: 'placement',
      q: 'A manufacturer wants to run applications that use AWS APIs and services on-site in its factory. The applications need single-digit millisecond latency to machines on the factory floor, and production data must stay in the plant for regulatory reasons. Which solution meets these requirements?',
      opts: [_o('Deploy the applications in the nearest AWS Local Zone.', 0, 'A Local Zone is an AWS site in a metro area, not in your building.'),
        _o('Install AWS Outposts racks in the factory.', 1, 'AWS-managed infrastructure and APIs in your own building; data stays on-site.'),
        _o('Deploy the applications in AWS Wavelength Zones.', 0, 'Wavelength sits in a telco 5G network, not the plant.'),
        _o('Use Snowball Edge compute-optimised devices in the factory.', 0, 'No longer offered to new customers, and not a long-term AWS-managed platform.')],
      stub: { what: 'placement', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['on-site', 'stay in the plant'],
      expl: 'Whose building? Ours → Outposts. Local Zones and Wavelength are AWS or telco sites.' },
    { id: 'N10', src: 'New', line: 'placement',
      q: 'A gaming company runs its game servers in us-west-2. Players in Los Angeles report lag, and the company wants single-digit millisecond latency for them. The company does not want to buy or manage any on-site hardware. Which solution provides the LOWEST latency for these players?',
      opts: [_o('Deploy AWS Outposts in a Los Angeles colocation facility.', 0, 'Buying and housing hardware is ruled out.'),
        _o('Serve the game through Amazon CloudFront.', 0, 'Caches content at the edge; it does not run game servers.'),
        _o('Put AWS Global Accelerator in front of the game servers in us-west-2.', 0, 'Better routing, but the compute is still far from the players.'),
        _o('Run the game servers in the AWS Local Zone in Los Angeles.', 1, 'AWS compute in the players’ metro area, run by AWS.')],
      stub: { what: 'placement', change: 'n/a', down: 'n/a', sup: 'fastest' }, words: ['Los Angeles', 'single-digit millisecond', 'on-site hardware'],
      expl: 'Users in one city, no own hardware → Local Zone in that city.' },
    { id: 'N11', src: 'New', line: 'placement',
      q: 'A company is building an augmented reality app for smartphones on 5G networks. Rendering must run on compute as close as possible to the mobile devices to give ultra-low latency. Which AWS offering should the company use?',
      opts: [_o('AWS Wavelength.', 1, 'AWS compute and storage inside the telco’s 5G network.'),
        _o('AWS Local Zones.', 0, 'Close to a city, but traffic still leaves the carrier network.'),
        _o('Amazon CloudFront.', 0, 'Caches content; it does not run rendering compute.'),
        _o('AWS Outposts.', 0, 'For your own building, not mobile devices on a carrier network.')],
      stub: { what: 'placement', change: 'n/a', down: 'n/a', sup: 'fastest' }, words: ['5G', 'mobile devices', 'ultra-low latency'],
      expl: '5G + phones = Wavelength.' },
    { id: 'N12', src: 'New', line: 'identity',
      q: 'A company wants its employees to sign in to the AWS Management Console with their existing on-premises Active Directory credentials. No directory data may be stored in AWS. A VPN connects the data center to AWS. Which solution is the MOST cost-effective?',
      opts: [_o('Deploy AWS Managed Microsoft AD and create a trust with the on-premises domain.', 0, 'Works, but a full directory in AWS costs more and stores directory data.'),
        _o('Deploy Simple AD and recreate the users.', 0, 'Separate users, and directory data stored in AWS.'),
        _o('Deploy AD Connector pointing to the on-premises domain controllers.', 1, 'A proxy: forwards auth to on-prem, stores nothing, cheapest.'),
        _o('Create IAM users with the same names as the AD users.', 0, 'Separate credentials; not their AD credentials.')],
      stub: { what: 'identity', change: 'n/a', down: 'n/a', sup: 'cheapest' }, words: ['existing on-premises Active Directory credentials', 'No directory data may be stored'],
      expl: 'Proxy only, store nothing, cheapest → AD Connector (it depends on the link, which the question accepts).' },
    { id: 'N13', src: 'New', line: 'identity',
      q: 'A small startup runs 40 Linux and Windows Amazon EC2 instances and needs a basic domain for user sign-in and group policies. It has no on-premises Active Directory and no need for trusts. Which solution is the LOWEST cost?',
      opts: [_o('Simple AD.', 1, 'Small, Samba-based, basic domain features, cheapest managed option.'),
        _o('AWS Managed Microsoft AD (Enterprise Edition).', 0, 'Full AD with trusts; far more than a small basic domain needs.'),
        _o('AD Connector.', 0, 'A proxy needs an existing directory; there is none.'),
        _o('Self-managed Active Directory on EC2.', 0, 'Instances to pay for plus full operations.')],
      stub: { what: 'identity', change: 'n/a', down: 'n/a', sup: 'cheapest' }, words: ['basic domain', 'no on-premises Active Directory', 'LOWEST cost'],
      expl: 'Small, basic, no trust, cheapest → Simple AD.',
      update: 'Simple AD closed to new customers on 30 Jul 2026 (existing customers keep it). A new account today would pick AWS Managed Microsoft AD (Standard Edition); banks still expect Simple AD.' },
    { id: 'N14', src: 'New', line: 'dns',
      q: 'A company connects its data center to a VPC over a Site-to-Site VPN. Applications on Amazon EC2 instances must resolve hostnames in the on-premises domain, example.corp. On-premises systems do not need to resolve any AWS names. What should a solutions architect configure?',
      opts: [_o('A Route 53 VPC Resolver inbound endpoint.', 0, 'Inbound serves queries coming into the VPC from on-prem.'),
        _o('A private hosted zone with copies of the on-premises records.', 0, 'Manual copies drift from the real DNS.'),
        _o('A public hosted zone for example.corp.', 0, 'Exposes internal names and is not authoritative on-prem.'),
        _o('A Route 53 VPC Resolver outbound endpoint and a forwarding rule for example.corp.', 1, 'Queries leave the VPC towards on-prem DNS.')],
      stub: { what: 'DNS', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['EC2 instances must resolve hostnames in the on-premises domain'],
      expl: 'Who is asking? EC2. The query leaves the VPC → outbound endpoint + forwarding rule.',
      update: 'Route 53 VPC Resolver was called Route 53 Resolver in older banks.' },
    { id: 'N15', src: 'New', line: 'dns',
      q: 'A company’s on-premises servers must resolve records in an Amazon Route 53 private hosted zone associated with a VPC. AWS Direct Connect links the data center to the VPC. Resources in the VPC do not need to resolve on-premises names. What should a solutions architect do?',
      opts: [_o('Create a Route 53 VPC Resolver outbound endpoint with a forwarding rule.', 0, 'Outbound is for queries leaving the VPC.'),
        _o('Create a Route 53 VPC Resolver inbound endpoint, and conditionally forward the zone from the on-premises DNS servers to the endpoint IP addresses.', 1, 'Queries come into the VPC from on-prem.'),
        _o('Change the private hosted zone to a public hosted zone.', 0, 'Exposes internal names to the internet.'),
        _o('Add the records to the hosts file on every on-premises server.', 0, 'Manual, drifts, does not scale.')],
      stub: { what: 'DNS', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['on-premises servers must resolve records', 'private hosted zone'],
      expl: 'Who is asking? On-prem. The query comes into the VPC → inbound endpoint + conditional forwarder on-prem.' },
    { id: 'N16', src: 'New', line: 'ops',
      q: 'A company runs 300 servers on-premises and 200 Amazon EC2 instances. The operations team wants to patch all of them and run commands on them from a single place, without managing extra infrastructure. Which solution has the LEAST operational overhead?',
      opts: [_o('AWS OpsWorks stacks for both environments.', 0, 'A Chef/Puppet service, now end of life; not the patch-and-command tool.'),
        _o('AWS Systems Manager, registering the on-premises servers with hybrid activations.', 1, 'On-prem servers become managed nodes (mi- IDs) next to EC2: Patch Manager and Run Command for all.'),
        _o('AWS Config rules to detect missing patches.', 0, 'Detects configuration state; does not patch or run commands.'),
        _o('A cron job on each server that pulls and installs updates.', 0, 'No central view, 500 things to maintain.')],
      stub: { what: 'servers', change: 'n/a', down: 'n/a', sup: 'least ops' }, words: ['300 servers on-premises', 'single place', 'LEAST operational overhead'],
      expl: 'Operate on-prem + EC2 together → Systems Manager with hybrid activations.' },
    { id: 'N17', src: 'New', line: 'placement',
      q: 'A company runs containerised workloads on Amazon ECS in AWS. It also wants to run containers on its existing on-premises servers and manage them with the same ECS control plane, without buying new hardware. Which solution meets these requirements?',
      opts: [_o('Order AWS Outposts and run ECS on it.', 0, 'That is buying AWS hardware.'),
        _o('Run Amazon EKS on Amazon EC2.', 0, 'Runs in AWS, not on the existing on-premises servers.'),
        _o('Amazon ECS Anywhere.', 1, 'Registers your own servers as external instances in an ECS cluster.'),
        _o('AWS Fargate.', 0, 'Serverless compute in AWS Regions only.')],
      stub: { what: 'placement', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['existing on-premises servers', 'same ECS control plane'],
      expl: 'Own servers + AWS control plane → ECS Anywhere. Outposts is AWS hardware in your building.' },
    { id: 'N18', src: 'New', line: '7r',
      q: 'During a migration assessment, a company finds an internal reporting application that nobody has used for a year. The application still runs on two on-premises servers. Which migration strategy is the MOST cost-effective for this application?',
      opts: [_o('Retain.', 0, 'Keeps paying for servers nobody uses.'),
        _o('Rehost.', 0, 'Pays to move and run something with no users.'),
        _o('Repurchase.', 0, 'Buys a SaaS replacement for a need that no longer exists.'),
        _o('Retire.', 1, 'No users → turn it off.')],
      stub: { what: 'inventory/plan', change: 'n/a', down: 'n/a', sup: 'cheapest' }, words: ['nobody has used for a year'],
      expl: 'Unused for a year = Retire. The cheapest server is the one you switch off.' },
    { id: 'N19', src: 'New', line: '7r',
      q: 'A company runs a self-hosted CRM application in its data center. As part of its move to AWS, it decides to replace the application with Salesforce, a SaaS product, so it no longer has to operate the software. Which migration strategy is this?',
      opts: [_o('Repurchase.', 1, 'Switch to a different, usually SaaS, product.'),
        _o('Replatform.', 0, 'Keeps your app, swaps a component for a managed one.'),
        _o('Refactor.', 0, 'Rewrites your own app cloud-native.'),
        _o('Rehost.', 0, 'Moves the same app to EC2 unchanged.')],
      stub: { what: 'inventory/plan', change: 'refactor/rebuy', down: 'any', sup: 'least ops' }, words: ['replace the application with Salesforce', 'SaaS'],
      expl: 'Buy a SaaS product instead of running your own = Repurchase.' },
    { id: 'N20', src: 'New', line: '7r',
      q: 'A company wants to keep its application code as it is but move the self-managed MySQL database to Amazon RDS for MySQL to reduce database administration work. Which migration strategy does this describe?',
      opts: [_o('Rehost.', 0, 'Would move the MySQL server as-is to EC2, still self-managed.'),
        _o('Refactor.', 0, 'The code is not being rewritten.'),
        _o('Replatform.', 1, 'Lift-tinker-shift: same app, managed database (DMS → RDS).'),
        _o('Retain.', 0, 'Nothing would move.')],
      stub: { what: 'inventory/plan', change: 'replatform', down: 'any', sup: 'least ops' }, words: ['keep its application code', 'reduce database administration'],
      expl: 'Same app, swap a self-managed part for a managed service = Replatform.' },
    { id: 'N21', src: 'New', line: 'dms',
      q: 'A company wants to build a data lake in Amazon S3 from its on-premises Oracle database. Ongoing changes in the database must be streamed into S3 continuously, and the analytics team needs the files in Parquet format. Which solution meets these requirements?',
      opts: [_o('Use AWS DataSync to copy the database files to S3 every hour.', 0, 'DataSync copies files; it cannot read rows or changes from a database.'),
        _o('Point an AWS Glue crawler at the Oracle database.', 0, 'A crawler catalogues schema; it does not capture ongoing changes.'),
        _o('Send the data to Amazon Data Firehose on its own.', 0, 'Something still has to read the changes out of Oracle.'),
        _o('Use an AWS DMS CDC task with an Amazon S3 target endpoint set to Parquet format.', 1, 'DMS reads changes from Oracle and writes Parquet to S3 (CSV is the default).')],
      stub: { what: 'database', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['Ongoing changes', 'Parquet'],
      expl: 'Rows + ongoing changes = DMS CDC; S3 is a DMS target, Parquet on request.' },
    { id: 'N22', src: 'New', line: 'bytes',
      q: 'A company must migrate 40 servers and 5 TB of file data to AWS within 2 weeks. It has ordered AWS Direct Connect, but the connection will not be ready for several weeks. The data center has a 1 Gbps internet connection. Which approach meets the deadline?',
      opts: [_o('Wait for Direct Connect, then run the migration over it.', 0, 'Weeks to provision; misses the 2-week deadline.'),
        _o('Set up an AWS Site-to-Site VPN over the internet and start MGN and DataSync over it now.', 1, '1 Gbps ≈ 10 TB/day; 5 TB fits easily, and the VPN encrypts it.'),
        _o('Book an AWS Data Transfer Terminal slot and ship the data.', 0, '5 TB fits the pipe in under a day; trucks are for when it doesn’t.'),
        _o('Enable S3 Transfer Acceleration for the uploads.', 0, 'Helps long-distance uploads to one bucket; does not move servers.')],
      stub: { what: 'any', change: 'none (rehost)', down: 'any', sup: 'fastest' }, words: ['within 2 weeks', 'several weeks', '1 Gbps'],
      expl: 'VPN now, Direct Connect later. Pipe rule: 1 Gbps ≈ 10 TB/day, so 5 TB is under a day.' },
    { id: 'N23', src: 'New', line: 'dms',
      q: 'A company wants to migrate its on-premises Teradata data warehouse to Amazon Redshift. The schema must be converted, and many terabytes of warehouse data must be extracted and loaded. Which AWS tool is designed for this migration?',
      opts: [_o('AWS DMS on its own.', 0, 'No schema conversion, and not the path for a large warehouse.'),
        _o('AWS Application Migration Service.', 0, 'Moves servers to EC2, not a warehouse into Redshift.'),
        _o('AWS DataSync.', 0, 'Moves files, not warehouse schemas or tables.'),
        _o('AWS Schema Conversion Tool (AWS SCT) with its data extraction agents.', 1, 'Converts the warehouse schema and extracts and loads the data into Redshift.')],
      stub: { what: 'database', change: 'replatform', down: 'any', sup: 'none stated' }, words: ['Teradata data warehouse', 'Amazon Redshift'],
      expl: 'Data warehouse → Redshift = SCT with data extraction agents.' }
  ];
})();
