/* Session 2 drills (Migration & Hybrid). stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit. */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _o = (t, ok, why) => ({ t, ok: !!ok, why });
  S.drills = [
    { id: 'M1', src: 'Quiz M1', line: 'mgn',
      q: 'A company’s data-center lease ends in 10 weeks. The data center runs 180 VMware virtual machines and 20 physical Linux servers. The applications are poorly documented and nobody has time to re-architect them. Everything must be running in AWS before the lease ends, with the fewest changes to the applications. Which solution meets these requirements MOST quickly?',
      opts: [_o('Export every server as a disk image, import the images as AMIs with VM Import/Export, and launch them on Amazon EC2.', 0, 'The 20 physical servers have no VM image to export, and offline images mean a long outage per server.'),
        _o('Use AWS Application Migration Service to replicate all 200 servers to Amazon EC2, run test launches, and cut over in waves.', 1, 'Block-level replication of VMware and physical servers to EC2, no app changes, minutes of cutover.'),
        _o('Relocate the 180 VMs to VMware Cloud on AWS with VMware HCX, and copy the physical servers to AWS with AWS DataSync.', 0, 'DataSync copies files, not bootable servers; the 20 physical hosts never arrive.'),
        _o('Use AWS Elastic Disaster Recovery to replicate all 200 servers, launch recovery instances, and then stop the sources.', 0, 'DRS is built to protect servers that stay and fail back; a one-way move is MGN’s job.')],
      stub: { what: 'servers', change: 'none (rehost)', down: 'minimal', sup: 'fastest' }, words: ['fewest changes', '10 weeks', 'physical'],
      expl: 'WHAT = whole servers (VMware + physical), CHANGE = none → Rehost, and a hard deadline → MGN replicating to EC2 in waves. Relocate would suit the VMs, but nothing in that option moves a physical server.' },
    { id: 'M2', src: 'Quiz M2', line: 'discover',
      q: 'A company plans to migrate 400 servers to AWS in waves. The estate is a mix of VMware virtual machines and bare metal hosts. The migration team does not know which servers communicate with each other, and a pilot move already broke an application because a dependency was left behind. Which solution will give the team the data it needs to plan the migration waves?',
      opts: [_o('Install the AWS Application Discovery Agent on every server and export the network connections it records between servers.', 1, 'The agent records processes and network connections → dependency map → waves; it runs on bare metal too.'),
        _o('Deploy the Application Discovery Service agentless collector in vCenter and group the servers by their utilisation data.', 0, 'A vCenter collector cannot see the bare metal hosts, and utilisation shows how busy a server is, not who it talks to.'),
        _o('Enable VPC Flow Logs in the target VPC and map the traffic between the servers as each migration wave arrives.', 0, 'The servers are not in a VPC yet; the map would arrive after the waves it was meant to plan.'),
        _o('Install the Amazon CloudWatch agent on every server and chart each server’s network bytes in a CloudWatch dashboard.', 0, 'Bytes in and out per server, with no record of which peer the traffic went to.')],
      stub: { what: 'inventory/plan', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['communicate with each other', 'bare metal'],
      expl: 'WHAT = plan, and the plan needs dependencies. Of these options only the Discovery agent records connections between servers, and it runs on bare metal as well as VMs.',
      update: 'Application Discovery Service and Migration Hub are closed to new customers since 7 Nov 2025. AWS Transform’s agentless discovery tool now collects server-to-server connections too (over SSH/WinRM) and builds the dependency map and waves. Banks still say Application Discovery Service and expect the agent.' },
    { id: 'M3', src: 'Quiz M3', line: 'dms',
      q: 'A company runs a 4 TB Oracle 19c database on-premises. The application relies on hundreds of PL/SQL stored procedures. The company wants to move the database to Amazon Aurora PostgreSQL, and the business will accept no more than 30 minutes of downtime at cutover. Which combination of steps should a solutions architect take? (Select TWO.)',
      opts: [_o('Use AWS DMS with a full load plus CDC task, and let DMS convert the PL/SQL stored procedures as it loads the tables.', 0, 'DMS moves rows; it does not convert stored procedures or other code.'),
        _o('Use AWS SCT or DMS Schema Conversion to convert the Oracle schema and the PL/SQL code to PostgreSQL.', 1, 'Heterogeneous move: schema and code need conversion, and that is SCT’s job.'),
        _o('Use AWS DMS with a full load plus change data capture (CDC) task, and cut over when replication lag is near zero.', 1, 'The source stays online; only the final catch-up counts as downtime.'),
        _o('Use AWS DMS with a full-load-only task during a weekend outage, after converting the schema with AWS SCT.', 0, 'Without CDC the whole 4 TB copy is downtime: far more than 30 minutes.'),
        _o('Use AWS Application Migration Service to replicate the database server to EC2, then convert the engine in place.', 0, 'MGN lands the same Oracle server on EC2; it cannot change the engine.')],
      stub: { what: 'database', change: 'replatform', down: 'minimal', sup: 'none stated' }, words: ['PL/SQL stored procedures', 'Aurora PostgreSQL', '30 minutes'],
      expl: 'Different engine → SCT/DMS Schema Conversion for structure and code; minimal downtime → DMS full load + CDC for the rows. Full load alone makes the whole copy downtime.' },
    { id: 'M4', src: 'Quiz M4', line: 'dms',
      q: 'A company runs its production database on Amazon RDS for MySQL. It wants to move to Amazon Aurora MySQL for better performance and automatic storage scaling. The application team asks for the least downtime and least operational effort possible during the move. What should a solutions architect recommend?',
      opts: [_o('Create an RDS for MySQL read replica, convert the replica to Aurora MySQL, and promote it when replica lag is zero.', 0, 'An RDS read replica cannot be converted to Aurora; the native path is an Aurora read replica.'),
        _o('Take a snapshot of the RDS for MySQL DB instance, restore it as an Aurora MySQL cluster, and repoint the application.', 0, 'Writes after the snapshot are lost unless the app stops for the whole restore: long downtime.'),
        _o('Create an Aurora MySQL read replica of the RDS for MySQL DB instance, and promote it when replica lag is zero.', 1, 'Native path: no extra tooling, and downtime is only the switch after lag hits zero.'),
        _o('Use AWS DMS with a full load plus CDC task from RDS for MySQL to a new Aurora MySQL cluster, then cut over.', 0, 'Works, but a replication instance, endpoints and a task are more to run than a native replica.')],
      stub: { what: 'database', change: 'replatform', down: 'minimal', sup: 'least ops' }, words: ['RDS for MySQL', 'least downtime and least operational effort'],
      expl: 'Same engine family, minimal downtime, least ops → Aurora read replica of the RDS instance, promote at zero lag. DMS only when engines differ or you need flexibility.' },
    { id: 'M5', src: 'Quiz M5', line: 'dns',
      q: 'A company connects its data center to a VPC with AWS Direct Connect. Applications on Amazon EC2 instances must resolve hostnames in the company’s on-premises domain, corp.internal. On-premises servers must resolve records in an Amazon Route 53 private hosted zone that is associated with the VPC. Which actions meet these requirements? (Select TWO.)',
      opts: [_o('Create a Route 53 Resolver inbound endpoint, and configure the on-premises DNS servers to forward the private zone’s domain to its IP addresses.', 1, 'On-prem asks AWS → the query enters the VPC → inbound.'),
        _o('Create a Route 53 Resolver inbound endpoint and a forwarding rule that sends queries for corp.internal to the on-premises DNS servers.', 0, 'Wrong direction: forwarding rules send queries out, through an outbound endpoint.'),
        _o('Create a Route 53 Resolver outbound endpoint, and configure the on-premises DNS servers to forward the private zone’s domain to its IP addresses.', 0, 'Wrong direction: an outbound endpoint only sends queries out of the VPC; it does not answer on-prem.'),
        _o('Create a Route 53 Resolver outbound endpoint and a forwarding rule that sends queries for corp.internal to the on-premises DNS servers.', 1, 'EC2 asks on-prem → the query leaves the VPC → outbound + rule.'),
        _o('Create an AWS Global Accelerator with the on-premises DNS servers as endpoints so that EC2 queries for corp.internal reach them.', 0, 'Prestige distractor: Global Accelerator fronts AWS endpoints for application traffic; it does not forward DNS.')],
      stub: { what: 'DNS', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['resolve hostnames in the company’s on-premises domain', 'private hosted zone'],
      expl: 'Name the endpoint after the direction of the query relative to the VPC: out to corp.internal = outbound + rule; in to the private zone = inbound, with on-prem DNS forwarding to it.',
      update: 'Route 53 Resolver is now called Route 53 VPC Resolver (Route 53 Resolver in older banks).' },
    { id: 'M6', src: 'Quiz M6', line: 'identity',
      q: 'A company is moving a line-of-business application to AWS. The database will run on Amazon RDS for SQL Server with Windows authentication, and the file shares will move to Amazon FSx for Windows File Server, which must be domain-joined. Users must keep signing in with their existing on-premises Active Directory credentials. Authentication in AWS must keep working if the link goes down between AWS and the data center. Which solution meets these requirements?',
      opts: [_o('Deploy AD Connector in two subnets in different Availability Zones, and point it at the on-premises domain controllers.', 0, 'RDS for SQL Server and FSx for Windows cannot use AD Connector, and it fails when the link is down.'),
        _o('Deploy Simple AD in two Availability Zones, create a trust with the on-premises domain, and join RDS and FSx to it.', 0, 'Simple AD has no trusts, so existing on-prem credentials cannot be used.'),
        _o('Deploy AWS Managed Microsoft AD, create a trust with the on-premises domain, and join RDS and FSx to the AWS domain.', 1, 'Real AD in two AZs: RDS and FSx join it, the trust keeps on-prem credentials, and it keeps working without the link.'),
        _o('Deploy AWS Managed Microsoft AD, recreate the users in it with new passwords, and join RDS and FSx to the AWS domain.', 0, 'Right directory, but recreated users lose their existing on-prem credentials.')],
      stub: { what: 'identity', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['Windows authentication', 'domain-joined', 'link goes down'],
      expl: 'AWS services need a real domain, existing credentials need a trust, and auth must survive a link outage → AWS Managed Microsoft AD with a trust to on-prem.' },
    { id: 'S7', src: 'Quiz S7', line: 'gateway',
      q: 'A video production company’s editing workstations save projects to an on-premises SMB share. The company wants to stop buying on-premises storage but keep recent projects available at LAN speed. All files must be stored in Amazon S3, and files should move to a cheaper storage class after 90 days. Projects of any age must still open directly from the share. Which solution is the MOST cost-effective?',
      opts: [_o('Run a nightly AWS DataSync task that copies the SMB share to S3, and add a Lifecycle rule to S3 Standard-IA after 90 days.', 0, 'A copy: the share stays on-prem, so the company keeps buying storage for it.'),
        _o('Deploy Amazon S3 File Gateway with an SMB share, and add an S3 Lifecycle rule to S3 Standard-IA after 90 days.', 1, 'SMB share with a local cache for recent files, everything in S3, cheaper class after 90 days, still readable.'),
        _o('Deploy Amazon S3 File Gateway with an SMB share, and add an S3 Lifecycle rule to S3 Glacier Flexible Retrieval after 90 days.', 0, 'Archived objects need a restore before the gateway can read them; old projects no longer open from the share.'),
        _o('Deploy Volume Gateway cached volumes over iSCSI, and add a Lifecycle rule that moves older data to S3 Standard-IA after 90 days.', 0, 'Block volumes, not an SMB share of files in S3; there are no file objects for a Lifecycle rule to move.')],
      stub: { what: 'files', change: 'any', down: 'n/a', sup: 'cheapest' }, words: ['SMB share', 'LAN speed', 'after 90 days'],
      expl: 'Carry-over from Session 1: a live SMB share with LAN-speed access and S3 behind it is S3 File Gateway; a lifecycle rule handles the 90-day move to a class the gateway can still read.',
      update: 'S3 File Gateway does not support Glacier Instant Retrieval, so the lifecycle target here is Standard-IA.' },

    { id: 'N1', src: 'New', line: 'discover',
      q: 'A company runs its entire estate on VMware vSphere and is planning a migration to AWS. The security team forbids installing any software agents on the guest operating systems. The migration team needs CPU and memory utilisation data for every VM so it can right-size the Amazon EC2 instances. Which solution meets these requirements?',
      opts: [_o('Install the AWS Application Discovery Agent on each VM to record CPU and memory utilisation for right-sizing.', 0, 'Installing agents is forbidden.'),
        _o('Register each VM with AWS Systems Manager hybrid activations and collect its utilisation with Inventory.', 0, 'Hybrid activations need the SSM Agent installed on every VM: still an agent.'),
        _o('Use AWS Compute Optimizer to analyse each VM’s CPU and memory history and recommend EC2 instance types.', 0, 'Compute Optimizer analyses resources already running in AWS, not on-prem VMs.'),
        _o('Deploy the Application Discovery Service agentless collector in vCenter to gather VM utilisation.', 1, 'Reads inventory and utilisation from vCenter; nothing installed on the VMs.')],
      stub: { what: 'inventory/plan', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['VMware vSphere', 'forbids installing any software agents', 'utilisation'],
      expl: 'WHAT = inventory for sizing, VMware only, no agents → the agentless collector. Dependencies are not asked for, so the agent is not needed.',
      update: 'For new customers this is AWS Transform discovery (agentless discovery tool OVA for vCenter). Banks still say Application Discovery Service.' },
    { id: 'N2', src: 'New', line: 'discover',
      q: 'A company is migrating 60 applications to AWS using several tools: AWS Application Migration Service for servers and AWS DMS for databases. Leadership wants a single place to see the migration status of each application. Which AWS service should the company use?',
      opts: [_o('The AWS Application Migration Service console, which shows replication and cutover status for each server.', 0, 'Covers MGN’s servers only; the DMS database moves never appear there.'),
        _o('AWS Migration Hub, which receives status from MGN and DMS and groups the servers into applications.', 1, 'One dashboard that tracks progress per application across migration tools.'),
        _o('An Amazon CloudWatch dashboard with one widget per application, built from the MGN and DMS metrics.', 0, 'Metrics such as lag and throughput, not a migration status per application.'),
        _o('AWS Config aggregators that track the resources each migration tool creates, grouped by application tag.', 0, 'Records resource configuration, not how far each application’s migration has got.')],
      stub: { what: 'inventory/plan', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['several tools', 'single place to see the migration status'],
      expl: 'WHAT = plan/track. “One place for migration status across tools” is Migration Hub’s trigger.',
      update: 'Migration Hub is closed to new customers since 7 Nov 2025; AWS Transform now provides migration tracking and orchestration. Banks still say Migration Hub.' },
    { id: 'N3', src: 'New', line: 'placement',
      q: 'A company must exit its data center quickly. It runs 300 virtual machines on VMware vSphere. The operations team must keep using its existing vCenter tooling and processes, and the company does not want to convert any VMs. Which migration approach meets these requirements?',
      opts: [_o('Use AWS Application Migration Service to replicate the 300 VMs to Amazon EC2, and cut over in waves.', 0, 'MGN turns every VM into an EC2 instance; vCenter tooling does not follow.'),
        _o('Import the VMs’ disk images as AMIs with VM Import/Export, and launch them into the same subnets.', 0, 'Imported images become EC2 instances: a conversion, and vCenter no longer manages them.'),
        _o('Relocate the VMs to VMware Cloud on AWS with VMware HCX, and keep managing them from vCenter.', 1, 'Relocate: the hypervisor moves, the VMs are not converted, vCenter stays.'),
        _o('Repackage the applications as containers with AWS App2Container, and run them on Amazon EKS.', 0, 'A rebuild into containers: the opposite of “no conversion”, and not quick for 300 VMs.')],
      stub: { what: 'servers', change: 'none (rehost)', down: 'any', sup: 'none stated' }, words: ['vCenter tooling', 'not want to convert any VMs', 'quickly'],
      expl: '“Keep vSphere/vCenter, no conversion” = Relocate, the hypervisor-level move. MGN and VM Import/Export both turn VMs into EC2 instances.',
      update: 'VMware Cloud on AWS is now sold by Broadcom, not AWS (since 30 Apr 2024). AWS’s current Relocate answer is Amazon Elastic VMware Service (EVS, GA Aug 2025) with VMware HCX. Banks still expect VMware Cloud on AWS.' },
    { id: 'N4', src: 'New', line: 'dms',
      q: 'A company is migrating an on-premises Microsoft SQL Server database to Amazon Aurora MySQL. The database contains many views, functions and stored procedures written in T-SQL. The company wants to convert as much of the database code as possible automatically. Which solution meets these requirements?',
      opts: [_o('Use AWS DMS with a full load plus CDC task, and set target table preparation to drop and recreate the tables.', 0, 'DMS creates basic tables only; views, functions and T-SQL procedures are not converted.'),
        _o('Use AWS SCT to convert the schema, and use AWS Application Migration Service to move the data to Aurora.', 0, 'MGN replicates whole servers to EC2; it cannot load rows into Aurora.'),
        _o('Take a native SQL Server backup to Amazon S3, and restore it into Aurora MySQL with the S3 import feature.', 0, 'A SQL Server backup restores only into SQL Server; Aurora MySQL imports MySQL backups.'),
        _o('Use DMS Schema Conversion or AWS SCT to convert the schema and T-SQL code, then move the data with AWS DMS.', 1, 'Structure and code by SCT/DMS SC, rows by DMS.')],
      stub: { what: 'database', change: 'replatform', down: 'any', sup: 'none stated' }, words: ['SQL Server', 'Aurora MySQL', 'T-SQL'],
      expl: 'Heterogeneous engines + code to convert → SCT or DMS Schema Conversion for structure and code, DMS for the data.' },
    { id: 'N5', src: 'New', line: 'dms',
      q: 'A company must migrate a 10 TB on-premises Oracle database to Amazon RDS for Oracle within 2 weeks. The data center’s only connection to AWS is a 50 Mbps internet link, and the database receives constant writes. The business requires minimal downtime at cutover. Which solution meets these requirements?',
      opts: [_o('Set up a Site-to-Site VPN over the 50 Mbps link, and run an AWS DMS full load plus CDC task through the tunnel.', 0, 'A VPN adds encryption, not bandwidth: 10 TB at 50 Mbps is about 20 days of copying.'),
        _o('Seed the initial copy offline through an AWS Data Transfer Terminal, then run an AWS DMS CDC task to catch up.', 1, 'Truck the bulk, stream only the changes over the thin pipe.'),
        _o('Order a 1 Gbps AWS Direct Connect connection, and run an AWS DMS full load plus CDC task over it.', 0, 'A new dedicated connection takes weeks to months: it misses the 2-week deadline.'),
        _o('Use AWS Application Migration Service to replicate the Oracle server, and cut over once it catches up.', 0, 'MGN lands on EC2, not RDS, and still pushes 10 TB through 50 Mbps.')],
      stub: { what: 'database', change: 'replatform', down: 'minimal', sup: 'none stated' }, words: ['10 TB', '50 Mbps', 'minimal downtime'],
      expl: 'Pipe rule first: 10 TB over 50 Mbps is about 20 days, past the 2-week deadline. Huge DB + thin pipe + minimal downtime = seed offline, then DMS CDC.' },
    { id: 'N6', src: 'New', line: 'dms',
      q: 'A company is using AWS DMS to replicate an on-premises PostgreSQL database to Amazon Aurora PostgreSQL. The CDC phase will run for a month before cutover. The company requires that replication continue automatically if an Availability Zone fails. What should a solutions architect do?',
      opts: [_o('Run two DMS tasks on two replication instances in different Availability Zones, both writing to the cluster.', 0, 'Two tasks apply the same changes twice; that is duplication, not failover.'),
        _o('Place the Single-AZ replication instance in a subnet group that spans two Availability Zones.', 0, 'The subnet group only lists where it may run; a Single-AZ instance still has no standby.'),
        _o('Move the task to a DMS Serverless replication configuration with its Single-AZ setting.', 0, 'Serverless, but still in one AZ; it needs the Multi-AZ setting.'),
        _o('Modify the replication instance to Multi-AZ, with a standby instance in a second Availability Zone.', 1, 'A standby in another AZ takes over automatically.')],
      stub: { what: 'database', change: 'any', down: 'minimal', sup: 'none stated' }, words: ['continue automatically', 'Availability Zone fails'],
      expl: 'Resilient DMS = Multi-AZ replication instance (or DMS Serverless in Multi-AZ). A subnet group across AZs is a prerequisite, not the failover.' },
    { id: 'N7', src: 'New', line: 'drs',
      q: 'A company runs 120 servers on-premises and will keep them there. It needs a disaster recovery site in AWS with a recovery point objective (RPO) of seconds and a recovery time objective (RTO) of minutes. After the data center is repaired, the company must fail back to it. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('Use AWS Elastic Disaster Recovery to replicate the servers continuously to AWS, and fail back after repair.', 1, 'Same engine as MGN, but it keeps replicating, fails over and fails back.'),
        _o('Use AWS Application Migration Service to replicate the servers, and launch cutover instances in a disaster.', 0, 'MGN is a one-way migration that ends at cutover; there is no failback.'),
        _o('Use AWS Backup with hourly backups of the servers, restored to Amazon EC2 and back on-premises as needed.', 0, 'Hourly backups mean an RPO of up to an hour, not seconds.'),
        _o('Build a pilot light by hand with AMIs and custom replication scripts, and reverse the scripts to fail back.', 0, 'Heavy to build and run; the RPO depends on your own tooling.')],
      stub: { what: 'servers', change: 'none (rehost)', down: 'n/a', sup: 'least ops' }, words: ['will keep them there', 'seconds', 'fail back'],
      expl: 'Servers stay, AWS is the recovery site, RPO seconds and failback, least ops → Elastic Disaster Recovery.' },
    { id: 'N8', src: 'New', line: 'mgn',
      q: 'A company is migrating 50 on-premises servers to Amazon EC2. It wants to test-launch each server in AWS before cutover, keep cutover windows to a few minutes, and then decommission the on-premises servers. Which solution meets these requirements?',
      opts: [_o('Use VM Import/Export to import images of the 50 servers as AMIs, test them, and import again at cutover.', 0, 'Offline images: every cutover waits for a fresh export and import, far more than minutes.'),
        _o('Use AWS DataSync to copy each server’s file systems to Amazon EFS, test the applications, and switch over.', 0, 'DataSync moves files, not bootable servers.'),
        _o('Use AWS Application Migration Service to replicate the servers, launch test instances, then cut over.', 1, 'Continuous replication, test launches, minutes of cutover, then finalise.'),
        _o('Use AWS Elastic Disaster Recovery to replicate the servers, run recovery drills, then fail over for good.', 0, 'DRS protects servers that stay and fail back; the servers here are leaving.')],
      stub: { what: 'servers', change: 'none (rehost)', down: 'minimal', sup: 'none stated' }, words: ['test-launch', 'few minutes', 'decommission'],
      expl: 'Servers moving one way, test launches and minutes of cutover = MGN.' },
    { id: 'N9', src: 'New', line: 'placement',
      q: 'A manufacturer wants to run applications that use AWS APIs and services on-site in its factory. The applications need single-digit millisecond latency to machines on the factory floor, and production data must stay in the plant for regulatory reasons. Which solution meets these requirements?',
      opts: [_o('Run the applications in the nearest AWS Local Zone, connected to the factory over AWS Direct Connect.', 0, 'A Local Zone is an AWS site in a metro area: the data leaves the plant.'),
        _o('Install AWS Outposts racks in the factory, and run the applications on EC2 and EBS in the Outpost.', 1, 'AWS-managed infrastructure and APIs in your own building; data stays on-site.'),
        _o('Run the applications in the AWS Wavelength Zone of the factory’s 5G carrier, reached over 5G.', 0, 'Wavelength sits in the telco’s network, not the plant: the data leaves.'),
        _o('Run the applications as containers on the factory’s own servers, registered with ECS Anywhere.', 0, 'Data stays, but ECS Anywhere brings no AWS services such as EC2 or EBS on-site.')],
      stub: { what: 'placement', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['on-site', 'stay in the plant'],
      expl: 'Whose building? Ours, with AWS services on-site → Outposts. Local Zones and Wavelength are AWS or telco sites; ECS Anywhere only runs containers.' },
    { id: 'N10', src: 'New', line: 'placement',
      q: 'A gaming company runs its game servers in us-west-2. Players in Los Angeles report lag, and the company wants single-digit millisecond latency for them. The company does not want to buy or manage any on-site hardware. Which solution provides the LOWEST latency for these players?',
      opts: [_o('Deploy AWS Outposts in a Los Angeles colocation facility, and run the game servers on it.', 0, 'Outposts is hardware you order and house: ruled out.'),
        _o('Put Amazon CloudFront in front of the game servers, and cache game assets at Los Angeles edge locations.', 0, 'Caches content at the edge; the game servers still run in Oregon.'),
        _o('Put AWS Global Accelerator in front of the game servers, so traffic enters at a Los Angeles edge.', 0, 'Better routing, but the compute is still in us-west-2.'),
        _o('Run the game servers on EC2 in the AWS Local Zone in Los Angeles, as an extension of us-west-2.', 1, 'AWS compute in the players’ metro area, run by AWS.')],
      stub: { what: 'placement', change: 'n/a', down: 'n/a', sup: 'fastest' }, words: ['Los Angeles', 'single-digit millisecond', 'on-site hardware'],
      expl: 'Users in one city, no own hardware → Local Zone in that city.' },
    { id: 'N11', src: 'New', line: 'placement',
      q: 'A company is building an augmented reality app for smartphones on 5G networks. Rendering must run on compute as close as possible to the mobile devices. Which solution provides the LOWEST latency to the devices?',
      opts: [_o('Run the rendering servers in AWS Wavelength Zones inside the mobile carriers’ 5G networks.', 1, 'AWS compute and storage inside the telco’s 5G network.'),
        _o('Run the rendering servers in the AWS Local Zone nearest the 5G users, linked to its Region.', 0, 'Close to a city, but traffic still leaves the carrier network.'),
        _o('Run the rendering in Lambda@Edge functions at the CloudFront locations nearest the phones.', 0, 'Edge functions at CloudFront, outside the carrier network, and not built to render.'),
        _o('Install AWS Outposts racks in the company’s offices, and route the phones’ 5G traffic to them.', 0, 'For your own building, not mobile devices on a carrier network.')],
      stub: { what: 'placement', change: 'n/a', down: 'n/a', sup: 'fastest' }, words: ['5G', 'mobile devices', 'LOWEST latency'],
      expl: '5G + phones = Wavelength: the compute sits inside the carrier network, so traffic never leaves it.' },
    { id: 'N12', src: 'New', line: 'identity',
      q: 'A company wants its employees to sign in to the AWS Management Console with their existing on-premises Active Directory credentials. No directory data may be stored in AWS. A VPN connects the data center to AWS. Which solution is the MOST cost-effective?',
      opts: [_o('Deploy AWS Managed Microsoft AD, and create a trust with the on-premises domain over the VPN.', 0, 'A whole directory in AWS: costs more and stores directory data.'),
        _o('Deploy Simple AD, and synchronise the on-premises users into it on a schedule.', 0, 'A separate copy of the users, stored in AWS.'),
        _o('Deploy AD Connector, and point it at the on-premises domain controllers over the VPN.', 1, 'A proxy: forwards auth to on-prem, stores nothing, cheapest.'),
        _o('Run domain controllers on EC2 as an extra site of the on-premises domain over the VPN.', 0, 'Replicates the directory into AWS, and you pay for and run the instances.')],
      stub: { what: 'identity', change: 'n/a', down: 'n/a', sup: 'cheapest' }, words: ['existing on-premises Active Directory credentials', 'No directory data may be stored'],
      expl: 'Proxy only, store nothing, cheapest → AD Connector (it depends on the link, which the question accepts).' },
    { id: 'N13', src: 'New', line: 'identity',
      q: 'A small startup runs 40 Linux and Windows Amazon EC2 instances and needs a basic domain for user sign-in and group policies. It has no on-premises Active Directory and no need for trusts. Which solution is the LOWEST cost?',
      opts: [_o('Deploy Simple AD (Small) in the VPC, and join the 40 instances to its domain.', 1, 'Small, Samba-based, basic domain features, cheapest managed option.'),
        _o('Deploy AWS Managed Microsoft AD (Enterprise), and join the 40 instances to it.', 0, 'A full AD sized for large directories and trusts: far more than needed.'),
        _o('Deploy AD Connector in the VPC, and join the 40 instances through it.', 0, 'A proxy needs an existing directory to forward to; there is none.'),
        _o('Run two Windows Server domain controllers on EC2 in two Availability Zones.', 0, 'Instances and Windows licences to pay for, plus all the operations.')],
      stub: { what: 'identity', change: 'n/a', down: 'n/a', sup: 'cheapest' }, words: ['basic domain', 'no on-premises Active Directory', 'LOWEST cost'],
      expl: 'Small, basic, no trust, cheapest → Simple AD.',
      update: 'Simple AD closed to new customers on 30 Jul 2026 (existing customers keep it). A new account today would pick AWS Managed Microsoft AD (Standard Edition); banks still expect Simple AD.' },
    { id: 'N14', src: 'New', line: 'dns',
      q: 'A company connects its data center to a VPC over a Site-to-Site VPN. Applications on Amazon EC2 instances must resolve hostnames in the on-premises domain, example.corp. The instances must keep using the VPC’s own resolver for every other name. On-premises systems do not need to resolve any AWS names. What should a solutions architect configure?',
      opts: [_o('A Route 53 VPC Resolver inbound endpoint, with a forwarding rule that sends example.corp queries to the on-premises DNS servers.', 0, 'Wrong direction: inbound serves queries coming into the VPC; rules need an outbound endpoint.'),
        _o('A private hosted zone for example.corp associated with the VPC, holding copies of the on-premises DNS records.', 0, 'Manual copies drift from the real on-prem DNS.'),
        _o('A DHCP options set that points the VPC’s instances at the on-premises DNS servers for all name resolution.', 0, 'Every query, not just example.corp, would leave the VPC’s resolver.'),
        _o('A Route 53 VPC Resolver outbound endpoint, with a forwarding rule that sends example.corp queries to the on-premises DNS servers.', 1, 'Queries for example.corp leave the VPC towards on-prem DNS; all else stays local.')],
      stub: { what: 'DNS', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['EC2 instances must resolve hostnames in the on-premises domain'],
      expl: 'Who is asking? EC2. The query leaves the VPC → outbound endpoint + forwarding rule, only for that domain.',
      update: 'Route 53 VPC Resolver was called Route 53 Resolver in older banks.' },
    { id: 'N15', src: 'New', line: 'dns',
      q: 'A company’s on-premises servers must resolve records in an Amazon Route 53 private hosted zone associated with a VPC. AWS Direct Connect links the data center to the VPC. The record names must not be resolvable from the internet, and resources in the VPC do not need to resolve on-premises names. What should a solutions architect do?',
      opts: [_o('Create a Route 53 VPC Resolver outbound endpoint, and conditionally forward the zone from the on-premises DNS servers to its IP addresses.', 0, 'Outbound endpoints only send queries out of the VPC; they do not answer on-prem.'),
        _o('Create a Route 53 VPC Resolver inbound endpoint, and conditionally forward the zone from the on-premises DNS servers to its IP addresses.', 1, 'Queries come into the VPC from on-prem.'),
        _o('Conditionally forward the zone from the on-premises DNS servers to the VPC’s base resolver address (the VPC CIDR +2).', 0, 'The +2 resolver answers only from inside the VPC; on-prem cannot reach it.'),
        _o('Convert the private hosted zone to a public hosted zone, and point the on-premises DNS servers at the Route 53 name servers.', 0, 'Public zones are resolvable from the internet, which is ruled out.')],
      stub: { what: 'DNS', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['on-premises servers must resolve records', 'private hosted zone'],
      expl: 'Who is asking? On-prem. The query comes into the VPC → inbound endpoint + conditional forwarder on-prem.' },
    { id: 'N16', src: 'New', line: 'ops',
      q: 'A company runs 300 servers on-premises and 200 Amazon EC2 instances. The operations team wants to patch all of them and run commands on them from a single place, without managing extra infrastructure. Which solution has the LEAST operational overhead?',
      opts: [_o('Run a self-managed Ansible control node on EC2 that patches and runs commands over SSH on all 500 servers.', 0, 'Works, but the control node is extra infrastructure to run and patch.'),
        _o('Register the on-premises servers with Systems Manager hybrid activations, then use Patch Manager and Run Command.', 1, 'On-prem servers become managed nodes (mi- IDs) next to EC2: Patch Manager and Run Command for all.'),
        _o('Record all 500 servers in AWS Config, and use a conformance pack to find and report the missing patches.', 0, 'Detects configuration state; it does not patch or run commands.'),
        _o('Use Systems Manager Patch Manager for the EC2 instances, and a WSUS server for the on-premises servers.', 0, 'Two tools in two places, and a WSUS server to run: not a single place.')],
      stub: { what: 'servers', change: 'n/a', down: 'n/a', sup: 'least ops' }, words: ['300 servers on-premises', 'single place', 'LEAST operational overhead'],
      expl: 'Operate on-prem + EC2 together → Systems Manager with hybrid activations.' },
    { id: 'N17', src: 'New', line: 'placement',
      q: 'A company runs containerised workloads on Amazon ECS in AWS. It also wants to run containers on its existing on-premises servers and manage them with the same ECS control plane, without buying new hardware. Which solution meets these requirements?',
      opts: [_o('Order AWS Outposts racks for the data center, and run the ECS tasks on the Outpost’s EC2 capacity.', 0, 'That is buying AWS hardware.'),
        _o('Install EKS Anywhere on the on-premises servers, and deploy the containers into that cluster.', 0, 'Own servers, but a Kubernetes cluster you run on-prem, not the ECS control plane.'),
        _o('Register the on-premises servers as external instances in the ECS cluster with ECS Anywhere.', 1, 'Registers your own servers as external instances in an ECS cluster.'),
        _o('Register the servers with Systems Manager hybrid activations, and start containers with Run Command.', 0, 'Managed nodes running scripts, not tasks scheduled by the ECS control plane.')],
      stub: { what: 'placement', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['existing on-premises servers', 'same ECS control plane'],
      expl: 'Own servers + AWS control plane → ECS Anywhere. Outposts is AWS hardware in your building; EKS Anywhere runs its own control plane.' },
    { id: 'N18', src: 'New', line: '7r',
      q: 'During a migration assessment, a company finds an internal reporting application that nobody has used for a year. The application still runs on two on-premises servers. Which migration strategy is the MOST cost-effective for this application?',
      opts: [_o('Retain: keep it running on its two servers and revisit it later.', 0, 'Keeps paying for servers nobody uses.'),
        _o('Rehost: move both servers to small EC2 instances with MGN, unchanged.', 0, 'Pays to move and run something with no users.'),
        _o('Repurchase: replace the reports with a SaaS reporting product.', 0, 'Buys a replacement for a need that no longer exists.'),
        _o('Retire: archive the application’s data and switch off both servers.', 1, 'No users → turn it off.')],
      stub: { what: 'inventory/plan', change: 'n/a', down: 'n/a', sup: 'cheapest' }, words: ['nobody has used for a year'],
      expl: 'Unused for a year = Retire. The cheapest server is the one you switch off.' },
    { id: 'N19', src: 'New', line: '7r',
      q: 'A company runs a self-hosted CRM application in its data center. As part of its move to AWS, it decides to replace the application with Salesforce, a SaaS product, so it no longer has to operate the software. Which migration strategy is this?',
      opts: [_o('Repurchase: drop the current product and move to a different one.', 1, 'Switch to a different, usually SaaS, product.'),
        _o('Replatform: keep the application, swap parts for managed services.', 0, 'Keeps your app and swaps a component for a managed one; here the app is replaced.'),
        _o('Refactor: rebuild the application as a cloud-native SaaS service.', 0, 'Rewrites your own app; here someone else’s product replaces it.'),
        _o('Rehost: move the application to Amazon EC2 without changes.', 0, 'Moves the same app unchanged; the company would still operate it.')],
      stub: { what: 'inventory/plan', change: 'refactor/rebuy', down: 'any', sup: 'none stated' }, words: ['replace the application with Salesforce', 'SaaS'],
      expl: 'Buy a SaaS product instead of running your own = Repurchase. Refactor rebuilds your own code, even if the result is SaaS-like.' },
    { id: 'N20', src: 'New', line: '7r',
      q: 'A company wants to keep its application code as it is but move the self-managed MySQL database to Amazon RDS for MySQL to reduce database administration work. Which migration strategy does this describe?',
      opts: [_o('Rehost: move the application and MySQL servers to EC2 as they are.', 0, 'MySQL would still be self-managed on EC2; no DBA work saved.'),
        _o('Refactor: re-architect the application around managed AWS services.', 0, 'The code is not being rewritten.'),
        _o('Replatform: keep the code, move the database to a managed service.', 1, 'Lift-tinker-shift: same app, managed database (DMS → RDS).'),
        _o('Relocate: move the servers with their hypervisor, without conversion.', 0, 'A hypervisor move; the database stays self-managed.')],
      stub: { what: 'inventory/plan', change: 'replatform', down: 'any', sup: 'none stated' }, words: ['keep its application code', 'reduce database administration'],
      expl: 'Same app, swap a self-managed part for a managed service = Replatform.' },
    { id: 'N21', src: 'New', line: 'dms',
      q: 'A company wants to build a data lake in Amazon S3 from its on-premises Oracle database. Ongoing changes in the database must be streamed into S3 continuously, and the analytics team needs the files in Parquet format. Which solution meets these requirements?',
      opts: [_o('Use AWS DataSync to copy the Oracle data files to S3 every hour, and convert them to Parquet with AWS Glue.', 0, 'DataSync copies files; it cannot read rows or changes out of a database.'),
        _o('Run an AWS Glue JDBC job every hour with job bookmarks, writing the new rows to S3 in Parquet format.', 0, 'Hourly batches, and bookmarks track new rows only; updates and deletes are missed.'),
        _o('Run an AWS DMS full-load task every night with an S3 target endpoint set to write Parquet files.', 0, 'Nightly full copies, not a continuous stream of changes.'),
        _o('Run an AWS DMS full load plus CDC task with an Amazon S3 target endpoint set to Parquet format.', 1, 'DMS reads changes from Oracle and writes Parquet to S3 (CSV is the default).')],
      stub: { what: 'database', change: 'n/a', down: 'n/a', sup: 'none stated' }, words: ['Ongoing changes', 'Parquet'],
      expl: 'Rows + ongoing changes = DMS CDC; S3 is a DMS target, Parquet on request.' },
    { id: 'N22', src: 'New', line: 'bytes',
      q: 'A company must migrate 40 servers and 5 TB of file data to AWS within 2 weeks. It has ordered AWS Direct Connect, but the connection will not be ready for several weeks. The data center has a 1 Gbps internet connection. Which approach meets the deadline with the LEAST operational overhead?',
      opts: [_o('Wait for the Direct Connect connection, then run MGN for the servers and DataSync for the files over it.', 0, 'Weeks to provision; misses the 2-week deadline.'),
        _o('Set up a Site-to-Site VPN over the internet now, and run MGN for the servers and DataSync for the files.', 1, '1 Gbps ≈ 10 TB/day; 5 TB fits easily, and the VPN encrypts it.'),
        _o('Book an AWS Data Transfer Terminal slot, carry the files and server images there, and import them.', 0, 'Devices, a booking and a trip for 5 TB that the pipe moves in under a day.'),
        _o('Set up a Site-to-Site VPN over the internet now, and run DataSync for the servers and MGN for the files.', 0, 'Tools swapped: DataSync copies files and MGN replicates servers.')],
      stub: { what: 'any', change: 'none (rehost)', down: 'any', sup: 'least ops' }, words: ['within 2 weeks', 'several weeks', '1 Gbps'],
      expl: 'VPN now, Direct Connect later. Pipe rule: 1 Gbps ≈ 10 TB/day, so 5 TB is under a day; a truck only adds work.' },
    { id: 'N23', src: 'New', line: 'dms',
      q: 'A company wants to migrate its on-premises Teradata data warehouse to Amazon Redshift. The schema must be converted, and many terabytes of warehouse data must be extracted and loaded. Which AWS tool is designed for this migration?',
      opts: [_o('AWS DMS with a full load task to Redshift, letting target table preparation create the tables.', 0, 'DMS creates basic tables; it does not convert a warehouse schema.'),
        _o('AWS Application Migration Service, replicating the Teradata servers to EC2 before the load.', 0, 'Moves servers to EC2, not a warehouse into Redshift.'),
        _o('AWS DataSync, copying exported Teradata tables to S3 for a Redshift COPY command.', 0, 'Moves files; nothing converts the schema.'),
        _o('AWS SCT, converting the schema and moving the data with its data extraction agents.', 1, 'Converts the warehouse schema and extracts and loads the data into Redshift.')],
      stub: { what: 'database', change: 'replatform', down: 'any', sup: 'none stated' }, words: ['Teradata data warehouse', 'Amazon Redshift'],
      expl: 'Data warehouse → Redshift = SCT with data extraction agents. DMS and DataSync move data but convert nothing.' }
  ];
})();
