/* Session 8 drills (databases & caching). stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit.
   B1 (Exam Q15, tag A) and B2 (Exam Q57, tag K) come from his baseline misses; B3–B4 from his prestige-distractor
   pattern (src 'Exam pattern', tag C): a cross-Region service offered for a one-Region read problem (B3), Global
   Accelerator / DAX / Global Database offered for a caching problem (B4). Other drills with a prestige option that is
   wrong: B9 B13. Options are written to the same size; each distractor breaks on one stated detail. Stub slots record
   what the stem literally states ('any' / 'none stated' when it states nothing for that slot).
   Select TWO: B24, B28. Correct letters as authored: A 7 · B 7 · C 7 · D 7 · AD 1 · AC 1. */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _o = (t, ok, why) => ({ t, ok: !!ok, why });
  S.drills = [
    /* ---------------- his record ---------------- */
    { id: 'B1', src: 'Exam Q15', line: 'proxy', mine: true, tag: 'A',
      q: 'A serverless order API uses AWS Lambda functions that connect directly to an Amazon RDS for MySQL DB instance. During flash sales, invocations fail with “too many connections” errors while the database CPU stays below 40%. The fix must need the LEAST operational overhead and no change of database engine.',
      opts: [_o('Raise the reserved concurrency of the order functions so that more invocations run in parallel and retry their failed connections.', 0, 'Your baseline pick. Every extra invocation opens another connection — the errors get worse, not better.'),
        _o('Put an Amazon RDS Proxy between the functions and the DB instance, and have the functions connect to the proxy endpoint.', 1, 'The proxy pools connections: thousands of invocations share a few hundred database connections, and the rest queue instead of failing.'),
        _o('Add two read replicas and spread the functions’ connections across the replica endpoints with a Route 53 weighted record.', 0, 'The functions write orders; replicas are read-only, and each replica has its own connection limit anyway.'),
        _o('Move the DB instance to a larger class with more memory, which raises max_connections, and resize it before each sale.', 0, 'A higher ceiling the next burst will reach again, plus a manual resize before every sale — fails least operational overhead.')],
      stub: { model: 'relational', load: 'many connections', lat: 'any', sup: 'least ops' }, words: ['too many connections', 'CPU stays below 40%', 'LEAST operational overhead'],
      expl: 'Your baseline **Q15**. The CPU is idle; the **connections** run out, because each Lambda execution environment opens its own. **RDS Proxy** was built for exactly this: pool and share connections, queue the excess. Raising concurrency is the opposite of the fix.' },
    { id: 'B2', src: 'Exam Q57', line: 'redshift', mine: true, tag: 'K',
      q: 'A retailer collects 3 PB of clickstream and sales data in Amazon S3. Data engineers must run Apache Spark jobs to clean and join it every night, and 200 analysts must then run complex SQL queries from business intelligence (BI) dashboards on the results with consistently fast response times.',
      opts: [_o('Run the Spark jobs on Amazon EMR, load the results into Amazon Redshift, and connect the BI dashboards to the Redshift warehouse.', 1, 'EMR is built for Spark on big data; Redshift is built for fast, concurrent SQL and BI over the results.'),
        _o('Run the Spark jobs on Amazon EMR, load the results into an Amazon Aurora PostgreSQL cluster, and connect the dashboards to its readers.', 0, 'Aurora is an OLTP engine: complex scans and joins over petabytes from 200 analysts are a warehouse job.'),
        _o('Run the clean-up as AWS Lambda functions, write the results to Amazon DynamoDB, and connect the BI dashboards through a connector.', 0, 'Lambda is not a Spark engine for nightly petabyte joins, and DynamoDB has no SQL joins or aggregates for BI.'),
        _o('Run the Spark jobs on Amazon EMR, keep the results in Amazon S3, and let every dashboard refresh query them with Amazon Athena.', 0, 'Athena suits ad hoc queries; 200 analysts running complex dashboards all day need a warehouse for consistently fast answers.')],
      stub: { model: 'analytics', load: 'any', lat: 'any', sup: 'none stated' }, words: ['3 PB', 'Apache Spark', 'business intelligence (BI) dashboards', 'complex SQL queries', 'consistently fast'],
      expl: 'Your baseline **Q57**, tag K: the keywords decide it. **Big data** processing (Spark) = **EMR**; **SQL + BI** over the results = **Redshift**. An OLTP database or a per-query scanner answers a different question.' },
    { id: 'B3', src: 'Exam pattern', line: 'aurora', mine: true, tag: 'C',
      q: 'An application in eu-west-1 runs on an Amazon Aurora MySQL cluster with one writer. Read traffic from a new reporting feature has pushed the writer’s CPU to 90%. All users and reports are in the same Region. The company wants the MOST cost-effective way to absorb the extra reads.',
      opts: [_o('Convert the cluster to an Aurora Global Database with a secondary in eu-central-1, and send the reporting queries to that secondary.', 0, 'A second Region for a one-Region read problem — it works, at the price of a whole cluster elsewhere. Prestige distractor.'),
        _o('Move the reporting data to Amazon DynamoDB global tables, and rewrite the reporting feature to read it through the DynamoDB API.', 0, 'A rewrite onto a key-value store with no SQL for reports, plus replicas in other Regions nobody needs.'),
        _o('Add two Aurora Replicas in other Availability Zones, and point the reporting feature at the cluster’s reader endpoint.', 1, 'Replicas share the cluster volume, add read capacity in the same Region, and the reader endpoint balances them.'),
        _o('Scale the writer up one instance class, and enable Aurora I/O-Optimized so the extra read I/O carries no per-request charge.', 0, 'A bigger writer still serves every read, and I/O-Optimized changes the bill for I/O, not the CPU load.')],
      stub: { model: 'relational', load: 'read-heavy', lat: 'any', sup: 'cheapest' }, words: ['same Region', 'MOST cost-effective', 'reporting feature'],
      expl: 'Your prestige pattern, database edition. **Same Region + reads** = **Aurora Replicas + reader endpoint**. Global Database answers a cross-Region requirement that this scenario never states.' },
    { id: 'B4', src: 'Exam pattern', line: 'cache', mine: true, tag: 'C',
      q: 'An e-commerce site in us-east-1 serves product pages from an Amazon RDS for PostgreSQL database. The same few thousand catalog queries run millions of times a day, and the database part of a page load must drop below 10 ms. All users are in North America. The solution must be the MOST cost-effective.',
      opts: [_o('Put AWS Global Accelerator in front of the Application Load Balancer so that requests reach the database tier over the AWS network.', 0, 'Global Accelerator speeds up the path to the load balancer; it does nothing for repeated database queries. Prestige distractor.'),
        _o('Add a DynamoDB Accelerator (DAX) cluster in front of the RDS database, and send the catalog queries through the DAX client.', 0, 'DAX caches DynamoDB only — it cannot sit in front of RDS for PostgreSQL.'),
        _o('Create an Aurora Global Database secondary in us-west-2, so that West Coast users read the catalog from a nearer Region.', 0, 'An engine migration and a second Region for a repeated-query problem — the most expensive option here.'),
        _o('Cache the catalog query results in Amazon ElastiCache for Valkey with lazy loading and a TTL, and read the cache first.', 1, 'Repeated queries + sub-10 ms = an in-memory cache in front of the database; Valkey is the cheapest ElastiCache engine.')],
      stub: { model: 'relational', load: 'read-heavy', lat: 'milliseconds', sup: 'cheapest' }, words: ['same few thousand catalog queries', 'below 10 ms', 'MOST cost-effective'],
      expl: '**Repeated reads** of the same results = **cache** (ElastiCache) in front of RDS. DAX is the same idea for DynamoDB only; Global Accelerator and Global Database answer network distance and Region loss.' },

    /* ---------------- RDS ---------------- */
    { id: 'B5', src: 'New', line: 'rds',
      q: 'A company is moving a third-party application that requires Microsoft SQL Server to AWS. The vendor supports only SQL Server, the application needs no access to the operating system, and the operations team wants AWS to handle patching, backups and failover with the LEAST operational overhead.',
      opts: [_o('Deploy Amazon RDS for SQL Server in a Multi-AZ deployment, and let RDS handle patching, automated backups and failover.', 1, 'The vendor’s engine, fully managed, with automatic failover to the standby.'),
        _o('Convert the schema with AWS SCT and run the application on an Amazon Aurora MySQL cluster with a replica in another AZ.', 0, 'The vendor supports only SQL Server; Aurora is MySQL- or PostgreSQL-compatible.'),
        _o('Deploy Amazon RDS Custom for SQL Server, and use its operating system access to install the vendor’s own patching tools.', 0, 'OS access is not needed here, and RDS Custom shares more of the administration with you.'),
        _o('Install SQL Server on two Amazon EC2 instances in different AZs, and configure an Always On availability group.', 0, 'Works, but you patch, back up and fail over yourself — fails least operational overhead.')],
      stub: { model: 'relational', load: 'any', lat: 'any', sup: 'least ops' }, words: ['requires Microsoft SQL Server', 'needs no access to the operating system', 'LEAST operational overhead'],
      expl: 'Commercial engine + no OS access + least ops = **RDS** for that engine. Aurora would need an engine change; RDS Custom and EC2 hand work back to you.' },
    { id: 'B6', src: 'New', line: 'rds',
      q: 'A packaged ERP system runs on Microsoft SQL Server. Its vendor requires a monitoring agent and custom drivers to be installed on the database server’s operating system. The company wants AWS to automate backups and as much other database administration as possible.',
      opts: [_o('Deploy Amazon RDS for SQL Server, and install the agent and the drivers through an option group attached to the DB instance.', 0, 'Option groups enable features AWS provides; RDS gives no operating system access for your own software.'),
        _o('Deploy Amazon RDS Custom for SQL Server, install the agent and drivers on the host, and keep RDS automation for backups.', 1, 'RDS Custom is built for exactly this: privileged OS and database access with RDS automation kept.'),
        _o('Install SQL Server on Amazon EC2 with the agent and the drivers, and schedule native backups to Amazon S3 with a script.', 0, 'Meets the vendor’s needs, but every administrative task is yours — fails “as much … as possible”.'),
        _o('Deploy Amazon Aurora PostgreSQL, and run the vendor’s agent and drivers on a separate EC2 instance next to the cluster.', 0, 'Changes the engine the vendor requires, and the agent must run on the database server itself.')],
      stub: { model: 'relational', load: 'any', lat: 'any', sup: 'least ops' }, words: ['installed on the database server’s operating system', 'as much other database administration as possible'],
      expl: 'Needs **OS access** + wants managed backups = **RDS Custom** (SQL Server; RDS Custom for Oracle is in sunset until March 2027). Plain RDS gives no host access; EC2 gives no automation.' },
    { id: 'B7', src: 'New', line: 'rds',
      q: 'A team must upgrade an Amazon RDS for MySQL 8.0 Multi-AZ DB instance to MySQL 8.4. They want to test the upgraded database with production data first, then cut over with about a minute of downtime and no change to the application’s endpoint, with the LEAST operational effort.',
      opts: [_o('Create a read replica, upgrade it to MySQL 8.4, test it, then promote the replica and update the application’s connection string.', 0, 'Testable, but the endpoint changes and the promotion and repointing are manual.'),
        _o('Take a snapshot, restore it to a new 8.4 instance for testing, then repeat the snapshot and restore in a maintenance window.', 0, 'Long downtime while the final restore runs, and a new endpoint at the end.'),
        _o('Modify the DB instance in place to MySQL 8.4 in the next maintenance window, relying on the Multi-AZ standby to stay online.', 0, 'A major version upgrade takes the primary and the standby down together, and nothing is tested first.'),
        _o('Create an RDS Blue/Green Deployment, upgrade and test the green environment, then switch over so it takes the production endpoints.', 1, 'Green stays in sync, is tested with real data, and switchover typically takes under a minute with the same endpoints.')],
      stub: { model: 'relational', load: 'any', lat: 'any', sup: 'least ops' }, words: ['test the upgraded database with production data first', 'about a minute of downtime', 'no change to the application’s endpoint', 'LEAST operational effort'],
      expl: '**Blue/Green Deployments** (RDS for MySQL, MariaDB, PostgreSQL) = staged copy kept in sync, tested, then switched over in typically under a minute; the green environment takes over the names and endpoints.' },

    /* ---------------- RDS Proxy ---------------- */
    { id: 'B8', src: 'New', line: 'proxy',
      q: 'Hundreds of concurrent AWS Lambda functions connect to an Amazon Aurora PostgreSQL cluster. Security requires that no database password is stored in function code or environment variables, that the database credentials rotate automatically, and that connection counts on the cluster stay low.',
      opts: [_o('Store the password in an encrypted Lambda environment variable with a customer managed KMS key, and rotate that key yearly.', 0, 'The password is still stored in the function configuration, and rotating the key does not rotate the password.'),
        _o('Enable IAM database authentication on the cluster, and have every function open its own connection with a fresh token.', 0, 'No stored password, but every function still opens its own connection — fails “connection counts … stay low”.'),
        _o('Create an RDS Proxy that reads rotating credentials from Secrets Manager, and require IAM authentication from the functions.', 1, 'Functions authenticate with IAM, the proxy holds the rotating secret, and the pool keeps connections low.'),
        _o('Store the password as a SecureString in Parameter Store, and have each function read it at start-up and open a connection.', 0, 'Parameter Store has no automatic rotation, and the connections still grow with the functions.')],
      stub: { model: 'relational', load: 'many connections', lat: 'any', sup: 'none stated' }, words: ['no database password is stored', 'rotate automatically', 'connection counts on the cluster stay low'],
      expl: 'Three requirements, one service: **RDS Proxy** pools connections, reads credentials from **Secrets Manager** (rotation), and can require **IAM authentication** from clients. IAM DB auth alone meets two of the three.' },
    { id: 'B9', src: 'New', line: 'proxy',
      q: 'An application connects to an Amazon Aurora MySQL cluster through the cluster endpoint. In failover tests, clients keep failing for well over a minute because their connection pools hold stale DNS answers. The team wants to shorten this disruption with the LEAST change to the application.',
      opts: [_o('Put an Amazon RDS Proxy in front of the cluster and point the application at the proxy endpoint, which follows the new writer.', 1, 'The proxy keeps client connections open and routes to the new writer without waiting for DNS — AWS says up to 66% faster failover.'),
        _o('Add a secondary Region with Aurora Global Database, and fail over to it whenever the writer in the primary Region is unhealthy.', 0, 'A cross-Region failover is slower and bigger than the in-Region one being fixed. Prestige distractor.'),
        _o('Create a Route 53 failover record with health checks on the writer and replica endpoints, and point the application at it.', 0, 'Still a DNS answer that the clients’ pools cache — the same problem with one more layer.'),
        _o('Raise the failover priority of the largest Aurora Replica, so that promotion of the new writer completes sooner.', 0, 'Promotion is already quick; the delay is the clients’ cached DNS, which a tier does not change.')],
      stub: { model: 'relational', load: 'any', lat: 'any', sup: 'least ops' }, words: ['stale DNS answers', 'LEAST change to the application'],
      expl: 'RDS Proxy’s second job: **faster failover**. Clients stay connected to the proxy while it switches to the new writer, so stale DNS in the application stops mattering.' },

    /* ---------------- Aurora ---------------- */
    { id: 'B10', src: 'New', line: 'aurora',
      q: 'A company runs dozens of internal tools on Amazon Aurora PostgreSQL. Each database is busy for a few hours on some weekdays and idle the rest of the time, often for days. The company wants to stop paying for database compute while a database is idle, with the LEAST operational overhead.',
      opts: [_o('Use provisioned Aurora instances, and run an EventBridge schedule that stops each cluster at night and starts it every morning.', 0, 'The busy hours are irregular, the clusters still run on idle days, and the schedules are yours to maintain.'),
        _o('Use Aurora Serverless v2 with a minimum capacity of 0 ACUs, so idle databases pause and resume on the next connection.', 1, 'Scaling to zero (auto-pause) stops compute charges while idle and needs no schedules.'),
        _o('Use Aurora Serverless v2 with a minimum capacity of 0.5 ACUs, so each database shrinks to its smallest size when idle.', 0, 'It shrinks but never stops: you still pay for 0.5 ACU around the clock.'),
        _o('Use Aurora I/O-Optimized clusters, so that idle databases incur no I/O charges and only pay for instances while running.', 0, 'I/O-Optimized removes per-I/O fees; the instances keep running and billing while idle.')],
      stub: { model: 'relational', load: 'spiky', lat: 'any', sup: 'least ops' }, words: ['idle the rest of the time', 'stop paying for database compute', 'LEAST operational overhead'],
      expl: '**Aurora Serverless v2** can now scale to **0 ACUs** (auto-pause, Nov 2024) — no compute charge while paused, resumes on connection. A 0.5 ACU minimum keeps billing.' },
    { id: 'B11', src: 'New', line: 'aurora',
      q: 'Cost Explorer shows that read and write I/O charges make up about 45% of an Amazon Aurora MySQL cluster’s monthly bill. The workload is steady and I/O-intensive. The company wants to lower the cluster’s cost with no change to the application and the LEAST effort.',
      opts: [_o('Move the cluster to Aurora Serverless v2 capacity, so that its I/O charges scale down automatically with the load.', 0, 'Serverless changes how compute is billed; under Aurora Standard storage every I/O is still charged.'),
        _o('Add Aurora Replicas and send half of the reads to the reader endpoint, so that the writer performs fewer I/O operations.', 0, 'The replicas read the same cluster volume; the I/O is billed all the same, plus more instances.'),
        _o('Buy Reserved Instances for the writer and the replicas, which also discount the cluster’s read and write I/O charges.', 0, 'Reserved Instances discount instance hours, not I/O requests.'),
        _o('Switch the cluster’s storage configuration to Aurora I/O-Optimized, which charges no per-request fee for read and write I/O.', 1, 'AWS’s rule: I/O-Optimized is the better choice when I/O is 25% or more of the Aurora spend.')],
      stub: { model: 'relational', load: 'steady', lat: 'any', sup: 'cheapest' }, words: ['about 45%', 'I/O-intensive', 'LEAST effort'],
      expl: 'I/O ≥ **25%** of the Aurora bill → **I/O-Optimized** (no I/O charges; switch to it once every 30 days, back any time). Under 25% → Aurora Standard.' },
    { id: 'B12', src: 'New', line: 'aurora',
      q: 'An Aurora MySQL cluster has four Aurora Replicas: two small instances that serve the web application’s reads, and two large instances added for long-running analytics queries. Analytics must never run on the small replicas, and web reads must stay off the large ones. Which solution has the LEAST operational overhead?',
      opts: [_o('Point both workloads at the reader endpoint, and give the large replicas a higher failover priority so they take the analytics.', 0, 'Priority tiers decide promotion order; the reader endpoint still balances across all replicas.'),
        _o('Create two custom endpoints, one for the small replicas and one for the large replicas, and point each workload at its own.', 1, 'Custom endpoints exist for exactly this: a load-balanced endpoint over a chosen subset of instances.'),
        _o('Hard-code the two large replicas’ instance endpoints in the analytics tool, and keep the web application on the reader endpoint.', 0, 'The reader endpoint still sends web reads to the large replicas, and instance endpoints break when instances change.'),
        _o('Restore a snapshot of the cluster into a separate analytics cluster every night, and run all analytics queries there.', 0, 'Day-old data and a nightly restore job to run — more work than an endpoint.')],
      stub: { model: 'relational', load: 'read-heavy', lat: 'any', sup: 'least ops' }, words: ['must never run on the small replicas', 'LEAST operational overhead'],
      expl: 'Reader endpoint = **all** replicas. **Custom endpoint** = a named subset (for example the big ones for analytics). Instance endpoints are for diagnosis, not routing.' },
    { id: 'B13', src: 'New', line: 'aurora',
      q: 'A payments platform on Amazon Aurora PostgreSQL has reached the write throughput of the largest instance class for its single writer; reads are already on Aurora Replicas. It must scale writes horizontally to millions of transactions per second while the applications keep using one PostgreSQL database.',
      opts: [_o('Add more Aurora Replicas and spread the application’s write traffic across them through the cluster’s reader endpoint.', 0, 'Aurora Replicas are read-only.'),
        _o('Convert the cluster to an Aurora Global Database, and send writes to secondary clusters in other Regions to share the load.', 0, 'Secondaries are read-only (write forwarding passes writes to the one primary). Prestige distractor.'),
        _o('Move to Aurora PostgreSQL Limitless Database, which shards tables across many writers while routers present one database.', 1, 'Limitless is built for horizontal write scaling inside a single database interface.'),
        _o('Enable Aurora I/O-Optimized on the cluster, which removes the I/O ceiling that limits how much one writer can write.', 0, 'A pricing configuration; one writer stays one writer.')],
      stub: { model: 'relational', load: 'write-heavy', lat: 'any', sup: 'none stated' }, words: ['scale writes horizontally', 'one PostgreSQL database'],
      expl: 'Writes beyond one writer, still one PostgreSQL database = **Aurora PostgreSQL Limitless Database** (GA Oct 2024): routers plus shards in a DB shard group. Replicas and Global Database only add readers.' },

    /* ---------------- DynamoDB ---------------- */
    { id: 'B14', src: 'New', line: 'ddb',
      q: 'A mobile game stores each player’s state as a JSON item looked up by player ID. Day-to-day traffic is unpredictable, and launch events scheduled weeks ahead push it from a few hundred to about 30,000 requests per second within minutes. Reads and writes need single-digit-millisecond latency with the LEAST operational overhead.',
      opts: [_o('Store the items in a DynamoDB on-demand table keyed by player ID, and pre-warm its warm throughput before each launch event.', 1, 'Serverless key-value lookups with no capacity to manage; pre-warming lets the table take the launch spike instantly instead of scaling into it.'),
        _o('Store the items in a DynamoDB on-demand table keyed by player ID, and let on-demand scale up as the launch traffic arrives.', 0, 'On-demand instantly takes up to double the previous peak; a jump from hundreds to 30,000 within minutes can throttle until it scales.'),
        _o('Store the items in a DynamoDB table in provisioned mode sized for the average load, with the player ID as the partition key.', 0, 'Right table, wrong mode: a launch spike throttles against capacity sized for the average.'),
        _o('Store the items in an Amazon DocumentDB cluster, with the player ID as the document key and replicas for the reads.', 0, 'Instance-based clusters to size and manage, and a single primary for all the writes.')],
      stub: { model: 'key-value', load: 'spiky', lat: 'milliseconds', sup: 'least ops' }, words: ['looked up by player ID', 'unpredictable', 'scheduled weeks ahead', 'single-digit-millisecond latency', 'LEAST operational overhead'],
      expl: 'Key-value + spiky + least ops = **DynamoDB on-demand** (the default mode). On-demand instantly serves up to **double the previous peak** (a new table starts at 4,000 writes and 12,000 reads per second); a known, much larger spike needs **warm throughput** pre-warmed first. Provisioned for the average throttles at launch.' },
    { id: 'B15', src: 'New', line: 'ddb',
      q: 'A DynamoDB table stores user sessions and grows by millions of items a day. Each session must be removed about a day after it was last used; a delay of a few days before removal is acceptable. The company wants expired sessions deleted with the LEAST cost and operational overhead.',
      opts: [_o('Run an hourly Lambda function that scans the table for sessions older than a day and deletes them in batches of 25 items.', 0, 'Pays read units for full scans and write units for every delete, and the function is yours to run.'),
        _o('Write an expiry timestamp attribute on each item and enable DynamoDB TTL on it, so that DynamoDB deletes expired items.', 1, 'TTL deletes expired items within a few days at no write-throughput cost.'),
        _o('Create a new table every day, write that day’s sessions into it, and delete the table that is more than two days old.', 0, 'Works without delete costs, but the application must track table names — far more moving parts.'),
        _o('Enable DynamoDB Streams, and have a Lambda function delete each session item 24 hours after its insert record arrives.', 0, 'A function cannot wait 24 hours per record, and stream records only live 24 hours.')],
      stub: { model: 'key-value', load: 'any', lat: 'any', sup: 'cheapest' }, words: ['a delay of a few days before removal is acceptable', 'LEAST cost and operational overhead'],
      expl: '**TTL**: an epoch-seconds attribute; DynamoDB deletes expired items typically within a few days, without consuming write capacity, and the deletes appear in Streams as service deletions.' },
    { id: 'B16', src: 'New', line: 'ddb',
      q: 'A DynamoDB table in provisioned mode must support 80 strongly consistent reads per second and 40 writes per second of items that are 4.5 KB each. How many read capacity units and write capacity units must be provisioned at a minimum?',
      opts: [_o('80 RCU and 180 WCU, because each 4.5 KB read uses one read unit and each write uses 4.5 write units.', 0, 'Sizes round up: a 4.5 KB read is 8 KB (2 units); a 4.5 KB write is 5 KB (5 units).'),
        _o('80 RCU and 200 WCU, because a strongly consistent read uses half a unit per 4 KB and a write rounds to 5 KB.', 0, 'Half a unit is the eventually consistent rate; strongly consistent reads cost a full unit per 4 KB.'),
        _o('160 RCU and 200 WCU, because each read rounds up to 8 KB of throughput and each write rounds up to 5 KB.', 1, '80 × 2 = 160 RCU; 40 × 5 = 200 WCU.'),
        _o('160 RCU and 400 WCU, because each read rounds up to 8 KB and each write costs two write units per 1 KB.', 0, 'Two units per 1 KB is the transactional write rate.')],
      stub: { model: 'key-value', load: 'any', lat: 'any', sup: 'none stated' }, words: ['80 strongly consistent reads per second', '40 writes per second', '4.5 KB'],
      expl: 'Read: round up to **4 KB** steps (4.5 → 8 KB = 2 units strongly consistent; 1 unit eventually; 4 transactional). Write: round up to **1 KB** steps (4.5 → 5 units; 10 transactional).' },
    { id: 'B17', src: 'New', line: 'ddb',
      q: 'An IoT platform writes sensor readings to a DynamoDB table whose partition key is the reading date, for example 2026-10-03. Writes are throttled every day although the table’s total provisioned write capacity is far above the traffic. The company wants to remove the throttling in the MOST cost-effective way.',
      opts: [_o('Double the table’s provisioned write capacity and enable auto scaling, so that the daily peak always has spare write units.', 0, 'All of today’s writes still land on one partition, capped at 1,000 WCU — more table capacity does not reach it.'),
        _o('Add a global secondary index keyed on the sensor ID, and send the writes to the index instead of to the table.', 0, 'You cannot write to an index; it is maintained from the table’s writes.'),
        _o('Put a DynamoDB Accelerator (DAX) cluster in front of the table, so that its write-through cache absorbs the writes.', 0, 'DAX writes through to the table; the hot partition receives exactly the same writes.'),
        _o('Change the partition key to the sensor ID, or the date plus a random suffix, so that writes spread across many partitions.', 1, 'A high-cardinality key (or write sharding) spreads the load over many partitions’ limits.')],
      stub: { model: 'key-value', load: 'write-heavy', lat: 'any', sup: 'cheapest' }, words: ['partition key is the reading date', 'far above the traffic', 'MOST cost-effective'],
      expl: 'Throttling with spare table capacity = a **hot partition**. One partition serves at most **3,000 RCU / 1,000 WCU**. Fix the key: high cardinality, or **write sharding** with a suffix.' },
    { id: 'B18', src: 'New', line: 'ddb',
      q: 'An existing DynamoDB orders table uses OrderId as its partition key. A new feature must list all orders for a CustomerId, sorted by order date; eventually consistent results are acceptable. The table must stay online, and the solution must need the LEAST operational overhead.',
      opts: [_o('Add a local secondary index to the existing table with CustomerId as its key and OrderDate as its sort key.', 0, 'LSIs are created with the table only, and must keep the table’s partition key (OrderId).'),
        _o('Add a global secondary index to the existing table with CustomerId as the partition key and OrderDate as the sort key.', 1, 'GSIs take any keys, can be added to a live table, and are eventually consistent — which is acceptable.'),
        _o('Scan the table with a filter expression on CustomerId, and sort the returned items by OrderDate in the application.', 0, 'Reads (and pays for) the whole table on every request.'),
        _o('Create a new table with an LSI on CustomerId and OrderDate, copy all the items into it, and switch the application.', 0, 'An LSI still shares the table’s partition key, and copying a live table is the opposite of least overhead.')],
      stub: { model: 'key-value', load: 'any', lat: 'any', sup: 'least ops' }, words: ['existing DynamoDB orders table', 'eventually consistent results are acceptable', 'LEAST operational overhead'],
      expl: 'New partition key on an existing table = **GSI**. An LSI keeps the table’s partition key and exists only from creation; it is the choice when you need **strongly consistent** reads on another sort key.' },
    { id: 'B19', src: 'New', line: 'ddb',
      q: 'A DynamoDB table in on-demand mode serves a steady 20,000 reads and 5,000 writes per second around the clock with less than 10% variation, and growth is predictable for the next year. The finance team asks for the MOST cost-effective capacity configuration.',
      opts: [_o('Switch to provisioned mode with auto scaling around the steady level, and buy DynamoDB reserved capacity for the base load.', 1, 'Steady traffic near its peak is where provisioned capacity — discounted further by reserved capacity — beats per-request pricing.'),
        _o('Keep on-demand mode, because it is now the default and recommended mode and its price was cut in half in November 2024.', 0, 'True facts, wrong conclusion: at a flat, near-peak load provisioned capacity costs less per request served.'),
        _o('Keep on-demand mode, and pre-warm the table’s warm throughput to the steady level so that requests are billed at a lower rate.', 0, 'Pre-warming raises what the table can take instantly (and is charged); it does not lower the request price.'),
        _o('Switch the table to the Standard-IA table class, which lowers the price of every read and write request on large tables.', 0, 'Standard-IA lowers storage cost and raises throughput cost — the opposite of this table’s profile.')],
      stub: { model: 'key-value', load: 'steady', lat: 'any', sup: 'cheapest' }, words: ['steady 20,000 reads', 'less than 10% variation', 'MOST cost-effective'],
      expl: '**Steady and predictable** → provisioned (+ auto scaling, + reserved capacity). **Spiky or unknown** → on-demand. At list prices the break-even is near 29% average utilisation of the provisioned peak.' },
    { id: 'B20', src: 'New', line: 'ddb',
      q: 'A real-time bidding service reads the same few thousand DynamoDB items tens of thousands of times per second. Read latency must drop from milliseconds to microseconds, eventually consistent reads are acceptable, and the team wants the fewest changes to its existing DynamoDB data-access code.',
      opts: [_o('Add an Amazon ElastiCache for Valkey cluster, and change the code to read the cache first and fill it from DynamoDB on misses.', 0, 'Reaches microseconds, but the cache-aside logic is new code — fails “fewest changes”.'),
        _o('Switch the table to provisioned mode with more read capacity, and use strongly consistent reads for every bid request.', 0, 'More capacity and stronger reads are still DynamoDB’s milliseconds, not microseconds.'),
        _o('Create a DynamoDB Accelerator (DAX) cluster in the VPC, and replace the DynamoDB client with the DAX client in the service.', 1, 'DAX is API-compatible with DynamoDB and serves eventually consistent reads from memory in microseconds.'),
        _o('Add a global secondary index that projects only the bid attributes, and read the smaller index items instead of the table.', 0, 'Smaller items, same millisecond latency.')],
      stub: { model: 'key-value', load: 'read-heavy', lat: 'microseconds', sup: 'least ops' }, words: ['microseconds', 'eventually consistent reads are acceptable', 'fewest changes'],
      expl: 'DynamoDB + **microseconds** + **minimal code change** = **DAX**. ElastiCache also reaches microseconds but needs your own caching code; DAX is a drop-in client.' },

    /* ---------------- caching ---------------- */
    { id: 'B21', src: 'New', line: 'cache',
      q: 'A web application behind an Application Load Balancer keeps user sessions in each EC2 instance’s memory and uses sticky sessions. When Auto Scaling removes an instance, its users are logged out. Sessions must survive the loss of an instance and be readable from any instance with sub-millisecond latency.',
      opts: [_o('Keep sticky sessions and raise the load balancer’s stickiness duration, so users stay on their instance until the session ends.', 0, 'The session still dies with the instance — stickiness only decides where requests go.'),
        _o('Store the sessions on an Amazon EBS volume attached to each instance, and snapshot the volumes every five minutes.', 0, 'Still per-instance, unreadable by other instances, and minutes of sessions lost per failure.'),
        _o('Store the sessions in an Amazon RDS for MySQL table, and read the session row on every request from any instance.', 0, 'Shared and durable, but a disk-based database round trip is not sub-millisecond.'),
        _o('Store the sessions in Amazon ElastiCache for Valkey with a replica, and let every instance read and write them there.', 1, 'A shared in-memory store: any instance reads any session in sub-millisecond time, and the replica survives a node loss.')],
      stub: { model: 'key-value', load: 'any', lat: 'microseconds', sup: 'none stated' }, words: ['sticky sessions', 'survive the loss of an instance', 'sub-millisecond latency'],
      expl: 'Externalise session state: **ElastiCache** (sub-millisecond) or DynamoDB (single-digit ms). The latency requirement picks the in-memory store.' },
    { id: 'B22', src: 'New', line: 'cache',
      q: 'An application caches product details in Amazon ElastiCache using lazy loading. After prices change in the database, customers keep seeing old prices for hours. Prices change a few times a day, and showing a price up to five minutes old is acceptable. What fixes this with the LEAST effort?',
      opts: [_o('Set a five-minute TTL on every cached product entry, so that stale entries expire and the next read reloads them.', 1, 'The smallest change that bounds staleness to the stated five minutes.'),
        _o('Rewrite every price update to write through to the cache as well, and remove lazy loading so that no entry is missing.', 0, 'Fixes staleness but changes every write path — far more effort than a TTL, and misses now go unfilled.'),
        _o('Add read replicas to the cache cluster, so that reads are spread across more nodes and each entry is refreshed sooner.', 0, 'Replicas copy the same stale entries; they add read capacity, not freshness.'),
        _o('Turn on cluster mode with more shards, so that each shard holds fewer keys and evicts its old entries more often.', 0, 'Eviction follows memory pressure, not age; more shards means less pressure and even older entries.')],
      stub: { model: 'any', load: 'any', lat: 'any', sup: 'least ops' }, words: ['lazy loading', 'old prices for hours', 'up to five minutes old is acceptable', 'LEAST effort'],
      expl: 'Lazy loading never touches the cache on a write, so entries go **stale**. A **TTL** caps how stale; write-through removes staleness at the cost of every write path.' },
    { id: 'B23', src: 'New', line: 'cache',
      q: 'A startup’s leaderboard service uses Redis OSS sorted sets and needs microsecond reads. Its data is the only copy of the scores, so no acknowledged write may be lost if a node or an Availability Zone fails. The team wants a fully managed service and no separate database behind it.',
      opts: [_o('Use Amazon ElastiCache for Redis OSS with cluster mode enabled and one replica per shard, and take a snapshot every hour.', 0, 'Replication is asynchronous and snapshots are hourly: acknowledged writes can be lost on failure.'),
        _o('Use Amazon DynamoDB with DAX in front of it, and model each sorted set as items with a sort key on the score.', 0, 'Durable, but the service must be rewritten off Redis sorted sets onto a different data model.'),
        _o('Use Amazon MemoryDB, which stores every write durably in a Multi-AZ transaction log before acknowledging it.', 1, 'A Redis OSS- and Valkey-compatible primary database: microsecond reads, durable writes across AZs.'),
        _o('Use Amazon ElastiCache Serverless for Valkey, which replicates the cached data across Availability Zones on its own.', 0, 'Replicated across AZs, but still a cache: a write can be acknowledged before it is safe.')],
      stub: { model: 'key-value', load: 'any', lat: 'microseconds', sup: 'none stated' }, words: ['only copy of the scores', 'no acknowledged write may be lost', 'no separate database behind it'],
      expl: 'In-memory **and durable** as the primary store = **MemoryDB**. (ElastiCache for Valkey 9.0+ gained an optional durability setting in June 2026 — newer than any bank; MemoryDB stays the classic answer.)' },
    { id: 'B24', src: 'New', line: 'cache',
      q: 'An application on Amazon RDS for PostgreSQL has two read problems: the same product-lookup queries repeat thousands of times a second, and nightly reports with large joins slow down the primary. The team must fix both with managed services. Which TWO actions should the team take? (Select TWO.)',
      opts: [_o('Cache the repeated product lookups in Amazon ElastiCache for Valkey, reading the cache first and loading it on misses.', 1, 'Repeated identical queries are what a cache is for.'),
        _o('Point the nightly reports at the Multi-AZ standby instance, which already holds a synchronous copy of every table.', 0, 'A Multi-AZ DB instance’s standby serves no reads.'),
        _o('Put a DynamoDB Accelerator (DAX) cluster in front of the RDS database to cache the product lookups in microseconds.', 0, 'DAX works with DynamoDB only.'),
        _o('Create an RDS read replica, and run the nightly reports against the replica’s endpoint instead of the primary.', 1, 'Reports read a copy; the primary keeps serving the application.'),
        _o('Enable RDS Optimized Writes on the primary instance, so that both the reports and the lookups finish twice as fast.', 0, 'Optimized Writes speeds up writes (RDS for MySQL); these are read problems on PostgreSQL.')],
      stub: { model: 'relational', load: 'read-heavy', lat: 'any', sup: 'none stated' }, words: ['repeat thousands of times a second', 'nightly reports with large joins', 'Select TWO'],
      expl: 'Two read problems, two tools: **repeated** queries → **cache**; **heavy, varied** queries → **read replica**. Standbys and DAX are look-alikes that do not apply.' },

    /* ---------------- Redshift ---------------- */
    { id: 'B25', src: 'New', line: 'redshift',
      q: 'A company keeps the last 12 months of sales in an Amazon Redshift cluster and 8 years of older sales as Parquet files in Amazon S3. Analysts occasionally run SQL that joins current and historical data. The company does not want to load the history into Redshift and wants the MOST cost-effective solution.',
      opts: [_o('Add RA3 nodes to the cluster, and COPY the eight years of history into Redshift managed storage for the occasional joins.', 0, 'Loads the history the company does not want to load, and pays for nodes for occasional queries.'),
        _o('Load the S3 history into an Amazon Aurora PostgreSQL cluster, and join it there with exports of the Redshift tables.', 0, 'A second database to run and feed, and an OLTP engine for analytic joins.'),
        _o('Unload the current Redshift tables to S3 every night, and run every joined query in Amazon Athena instead of Redshift.', 0, 'Adds a nightly unload job and moves current-data queries off the warehouse that already holds them.'),
        _o('Define the S3 history as external tables and query them with Redshift Spectrum, joining them to the local tables in one query.', 1, 'Spectrum queries S3 in place from Redshift: no loading, pay for the data scanned.')],
      stub: { model: 'analytics', load: 'any', lat: 'any', sup: 'cheapest' }, words: ['does not want to load the history', 'joins current and historical data', 'MOST cost-effective'],
      expl: 'Warehouse + data that stays in S3 = **Redshift Spectrum** (external tables). Athena is the S3-only answer when there is no warehouse in the picture.' },
    { id: 'B26', src: 'New', line: 'redshift',
      q: 'A company wants analytics in Amazon Redshift on orders written to its Amazon Aurora MySQL cluster. Today a nightly AWS Glue job copies the data, so it is up to a day old. The new solution must keep the Redshift data within seconds of Aurora with the LEAST operational overhead.',
      opts: [_o('Run the AWS Glue job every five minutes instead of nightly, and use job bookmarks so each run loads only the new rows.', 0, 'Minutes, not seconds, and a busier pipeline to run.'),
        _o('Create an Aurora zero-ETL integration with Amazon Redshift, so that Aurora replicates the data into Redshift continuously.', 1, 'Built for exactly this: near-real-time replication into Redshift with no pipeline to manage.'),
        _o('Stream the changes with AWS DMS into Amazon Kinesis Data Streams, and load them into Redshift with a consumer application.', 0, 'Can reach seconds, but it is three services and custom code — fails least operational overhead.'),
        _o('Query the Aurora cluster from Redshift with federated queries, and refresh a materialized view of the orders every night.', 0, 'The view is still a day old, and federated queries load the production cluster.')],
      stub: { model: 'analytics', load: 'any', lat: 'seconds', sup: 'least ops' }, words: ['within seconds of Aurora', 'LEAST operational overhead'],
      expl: '**Zero-ETL integrations** replicate Aurora MySQL/PostgreSQL, RDS for MySQL/PostgreSQL/Oracle and DynamoDB into Redshift. When the stem says least ops and near real time, a pipeline you build loses.' },

    /* ---------------- security ---------------- */
    { id: 'B27', src: 'New', line: 'sec',
      q: 'A compliance audit finds that a production Amazon RDS for PostgreSQL DB instance was created without encryption at rest. The company must encrypt it with a customer managed AWS KMS key; some downtime in a maintenance window is acceptable. What should a solutions architect do?',
      opts: [_o('Modify the DB instance, turn on storage encryption with the customer managed key, and apply the change in the maintenance window.', 0, 'Encryption at rest can only be chosen when an instance is created.'),
        _o('Create an encrypted read replica of the instance with the customer managed key, then promote the replica and repoint the app.', 0, 'An unencrypted instance cannot have an encrypted read replica.'),
        _o('Take a snapshot, copy it with encryption under the customer managed key, restore a new instance from the copy, and repoint the app.', 1, 'The documented path: an encrypted copy of an unencrypted snapshot, restored to a new, encrypted instance.'),
        _o('Turn on EBS encryption by default for the account with the customer managed key, then reboot the DB instance to re-encrypt.', 0, 'Default EBS encryption affects new volumes only, and RDS storage is not changed by a reboot.')],
      stub: { model: 'relational', load: 'any', lat: 'any', sup: 'none stated' }, words: ['created without encryption at rest', 'customer managed AWS KMS key', 'some downtime'],
      expl: 'RDS encryption at rest is a **creation-time** choice: **snapshot → copy with encryption → restore → switch**. Replicas follow the source’s encryption; you cannot turn encryption off either.' },
    { id: 'B28', src: 'New', line: 'purpose',
      q: 'A company is moving two self-managed databases to AWS managed services: a MongoDB cluster behind a content app, and an Apache Cassandra cluster behind a messaging app. Both apps must keep their existing drivers and query languages with the LEAST code change. Which TWO actions meet these requirements? (Select TWO.)',
      opts: [_o('Migrate the MongoDB application to Amazon DocumentDB, keeping its existing MongoDB drivers and queries.', 1, 'DocumentDB is MongoDB-compatible.'),
        _o('Migrate the Cassandra application to Amazon DynamoDB, rewriting its CQL queries for the DynamoDB API.', 0, 'A rewrite — fails “keep their existing drivers and query languages”.'),
        _o('Migrate the Cassandra application to Amazon Keyspaces, keeping its CQL queries and Cassandra drivers.', 1, 'Keyspaces is Apache Cassandra-compatible and serverless.'),
        _o('Migrate the MongoDB application to Amazon Neptune, storing every document as a vertex with properties.', 0, 'A graph database with its own query languages; nothing of the MongoDB app survives.'),
        _o('Migrate both applications to Amazon Aurora PostgreSQL, storing documents and rows in JSONB columns.', 0, 'Both apps would need new drivers and SQL.')],
      stub: { model: 'any', load: 'any', lat: 'any', sup: 'least ops' }, words: ['MongoDB cluster', 'Apache Cassandra cluster', 'keep their existing drivers and query languages', 'Select TWO'],
      expl: 'Compatibility is the whole question: **MongoDB → DocumentDB**, **Cassandra (CQL) → Keyspaces**. DynamoDB could store both, but only after a rewrite.' },
    { id: 'B29', src: 'New', line: 'purpose',
      q: 'A bank wants to detect fraud rings by following relationships between accounts, devices, phone numbers and addresses up to six hops away, with queries that return in milliseconds as new transactions arrive. Which database is the BEST fit for this access pattern?',
      opts: [_o('Amazon Neptune, storing accounts, devices and addresses as vertices and their links as edges for multi-hop traversals.', 1, 'A graph database is built to traverse many hops of relationships quickly.'),
        _o('Amazon Aurora PostgreSQL, storing each relationship in a link table and following the hops with recursive self-joins.', 0, 'Possible, but each extra hop multiplies the join work; six hops in milliseconds is a graph job.'),
        _o('Amazon DynamoDB, storing each relationship as an item and following the hops with one query per relationship found.', 0, 'Fast per key, but a six-hop walk becomes thousands of round trips from the application.'),
        _o('Amazon Redshift, storing the relationships in a fact table and computing the hops with scheduled SQL batch queries.', 0, 'Batch analytics, not millisecond answers as transactions arrive.')],
      stub: { model: 'graph', load: 'any', lat: 'milliseconds', sup: 'none stated' }, words: ['following relationships', 'up to six hops', 'BEST fit'],
      expl: '“Relationships”, “hops”, “friends of friends”, “fraud rings”, “knowledge graph” = **Neptune** (Gremlin, openCypher, SPARQL).' },
    { id: 'B30', src: 'New', line: 'purpose',
      q: 'A new AWS customer is building an industrial IoT dashboard that ingests millions of sensor measurements per minute and queries recent values and time-window aggregates in single-digit milliseconds. The team wants a managed time-series database with the LEAST operational overhead.',
      opts: [_o('Amazon Timestream for LiveAnalytics, ingesting the measurements through its write API and querying them with its SQL engine.', 0, 'Closed to new customers since 20 June 2025 — AWS points new customers to Timestream for InfluxDB.'),
        _o('Amazon RDS for PostgreSQL with a measurements table partitioned by day, and B-tree indexes on sensor ID and timestamp.', 0, 'A general relational engine you partition, index and scale yourself — fails least operational overhead.'),
        _o('Amazon Keyspaces with the sensor ID as the partition key and the timestamp as the clustering column for each reading.', 0, 'Stores the readings, but time-window aggregates are not what a wide-column store is built to compute.'),
        _o('Amazon Timestream for InfluxDB, writing the measurements with the InfluxDB API and querying recent windows with InfluxDB.', 1, 'Managed InfluxDB: a purpose-built time-series engine with millisecond queries, open to new customers.')],
      stub: { model: 'time series', load: 'write-heavy', lat: 'milliseconds', sup: 'least ops' }, words: ['new AWS customer', 'time-window aggregates', 'time-series database', 'LEAST operational overhead'],
      expl: 'Time series = **Timestream**. Today that means **Timestream for InfluxDB** for new customers; banks written before mid-2025 still show the original Timestream (LiveAnalytics) as the answer.', update: 'Timestream for LiveAnalytics closed to new customers on 20 June 2025; existing customers keep using it.' }
  ];
})();
