/* Session 6 trigger cards (Multi-account & governance). f = what the exam says, b = the answer. line = transit line id or topic.
   Cards marked mine come from his prestige-distractor pattern (Control Tower, Transit Gateway) — src 'Exam pattern'. */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _c = (id, line, f, b, why, tempt, extra) => Object.assign({ id, line, f, b, why, tempt }, extra || {});
  const MINE = { mine: true, src: 'Exam pattern' };
  S.cards = [
    /* Organizations · SCP · RCP */
    _c('c01', 'org', 'Existing organization: no account may use Regions outside the EU, admins included', 'SCP at the root: Deny when aws:RequestedRegion is not an allowed Region', 'One policy, inherited by every member account; exempt global services with NotAction.', 'Deploy Control Tower for one rule.', MINE),
    _c('c02', 'org', 'What an SCP grants', 'Nothing — it only sets the maximum', 'Effective = SCP ∩ identity/resource policies. FullAWSAccess “leaves room”; IAM must still allow.', 'An SCP that allows S3 lets a role use S3.'),
    _c('c03', 'org', 'Who SCPs never restrict', 'The management account and service-linked roles', 'Everyone else in a member account — admins and the member root user — is bound.', '“The root user of a member account ignores SCPs.”'),
    _c('c04', 'org', 'SCP inheritance rule for an Allow', 'An Allow must exist at every level: root, each OU on the path, and the account', 'That is why FullAWSAccess is attached everywhere by default; a Deny anywhere on the path wins.', 'An Allow at the root is enough.'),
    _c('c05', 'org', 'Deny-list vs allow-list SCP strategy', 'Deny-list: keep FullAWSAccess and add Deny statements · Allow-list: replace FullAWSAccess with Allows for approved services', 'Deny-list is the default and easiest to maintain.', 'Allow-list by adding Allows next to FullAWSAccess (it changes nothing).'),
    _c('c06', 'org', 'Stop member accounts leaving the organization', 'SCP denying organizations:LeaveOrganization', 'Attach at the root; it cannot bind the management account (which cannot leave anyway).', 'Remove the accounts’ root passwords.'),
    _c('c07', 'org', 'Limit what outsiders can do to our S3 buckets and KMS keys, whatever the resource policies say', 'Resource control policy (RCP)', 'Ceiling on resources in member accounts, applies to any caller; not to the management account or service-linked roles.', 'SCP — it only sees your own principals.', { update: 'RCPs launched Nov 2024 and now cover dozens of services (S3, STS, KMS, SQS, Secrets Manager, DynamoDB, ECR …).' }),
    _c('c08', 'org', 'Enforce an EC2 setting (VPC Block Public Access, snapshot block public access) in every account, even as the service adds APIs', 'Declarative policy for EC2', 'Declares the configuration; it is kept even when new features or APIs appear, and accounts cannot change it locally.', 'An SCP listing today’s API calls.', { update: 'Declarative policies launched Dec 2024; unlike SCPs they also apply to the management account.' }),
    _c('c09', 'org', 'Organization with consolidated billing only wants SCPs', 'Enable all features (every invited account must approve)', 'Policies of every type need all features; the switch is one-way.', 'SCPs work in any organization.'),
    _c('c10', 'org', 'Let the security account run GuardDuty, Config or Firewall Manager for the whole organization', 'Register it as delegated administrator for that service', 'Keeps day-to-day work out of the management account.', 'Do everything from the management account.'),
    _c('c11', 'org', 'Move an account to another organization with the least effort', 'Direct account transfer: invite from the new organization, accept in the account', 'No standalone period, no payment method or support plan needed.', 'Leave, add a card, then accept (the old procedure).', { update: 'Direct transfers since Nov 2025; banks still describe leave-then-join.' }),
    _c('c12', 'org', 'Remove root credentials from all member accounts; still unlock a locked bucket policy when needed', 'Centralized root access management (IAM, from the management account or delegated admin)', 'Delete member root passwords and keys; run short-lived privileged root tasks (e.g. S3 unlock) with sts:AssumeRoot.', 'Keep root passwords in a safe for every account.'),
    /* IAM mechanics */
    _c('c13', 'iam', 'Order of policy evaluation', 'Explicit Deny → RCP → SCP → resource policy → identity policy → boundary → session policy', 'Any explicit Deny ends it; each ceiling must leave room; something must grant.', 'The most specific policy wins.'),
    _c('c14', 'iam', 'Same account vs cross-account Allow', 'Same account: identity OR resource policy · cross-account: identity AND resource policy', 'Across accounts both sides are evaluated.', 'A bucket policy alone always works.'),
    _c('c15', 'iam', 'Developers create roles, but never with more than a defined set of permissions', 'Permission boundary, required via the iam:PermissionsBoundary condition', 'Effective = identity ∩ boundary; deny editing the boundary itself.', 'An SCP on the account (restricts everyone).'),
    _c('c16', 'iam', 'Third-party vendor needs access to your account', 'IAM role trusting the vendor’s account, with an external ID', 'Temporary credentials; the external ID blocks the confused deputy.', 'An IAM user with access keys.'),
    _c('c17', 'iam', 'AssumeRole session length', '15 minutes to the role’s maximum (1–12 h, default 1 h); role chaining max 1 h', 'Set MaxSessionDuration on the role.', 'Sessions last until revoked.'),
    _c('c18', 'iam', 'Bucket readable by every account in our organization, including future ones', 'Bucket policy condition aws:PrincipalOrgID', 'aws:PrincipalOrgPaths for one OU.', 'List every account ID.', MINE),
    _c('c19', 'iam', 'An AWS service (e.g. CloudTrail, SNS) writes to your bucket — stop the confused deputy', 'aws:SourceArn / aws:SourceAccount (or aws:SourceOrgID) in the resource policy', 'Ties the service principal to your own resource, account or organization.', 'aws:PrincipalOrgID — service principals are not in your org.'),
    _c('c20', 'iam', 'Which resources are shared with principals outside the account or organization?', 'IAM Access Analyzer — external access analyzer', 'Zone of trust = account or organization; free.', 'Macie or GuardDuty.', { update: 'Access Analyzer now also has internal access and unused access analyzers (paid) and custom policy checks.' }),
    _c('c21', 'iam', 'On-premises servers need temporary AWS credentials without access keys', 'IAM Roles Anywhere (X.509 certificates from a trust anchor)', 'Trust anchor: AWS Private CA or your own CA.', 'IAM user keys on the server.'),
    _c('c22', 'iam', 'Access rules must scale with projects without new policies', 'ABAC: aws:PrincipalTag/project = aws:ResourceTag/project', 'Session tags from the IdP or Identity Center attributes.', 'One role per project.'),
    _c('c23', 'iam', 'Caller must keep its own permissions while using a resource in another account', 'Resource-based policy (bucket, key, queue …), not role assumption', 'Assuming a role replaces the caller’s permissions with the role’s.', 'Cross-account role.'),
    /* Identity Center */
    _c('c24', 'idc', 'Employees sign in once to many AWS accounts with the corporate IdP', 'IAM Identity Center (SAML 2.0 + SCIM, permission sets)', 'Permission sets become roles in each assigned account; no IAM users.', 'IAM users per account, or Cognito.'),
    _c('c25', 'idc', '“AWS Single Sign-On” in an old question', 'IAM Identity Center (renamed July 2022)', 'Same service; APIs still say sso.', '“SSO was discontinued.”'),
    _c('c26', 'idc', 'Employees keep using on-premises AD credentials for AWS accounts', 'Identity Center with AD Connector (or AWS Managed Microsoft AD with a trust)', 'AD Connector proxies to your domain controllers; nothing cached.', 'Cognito or a nightly IAM-user sync.'),
    _c('c27', 'idc', 'Customers of your mobile app sign in', 'Amazon Cognito (Session 5)', 'Identity Center is only for your workforce.', 'IAM Identity Center.'),
    /* Control Tower */
    _c('c28', 'ct', 'Set up a governed multi-account environment fast: log archive, audit, SSO, guardrails, account vending', 'AWS Control Tower landing zone + Account Factory', 'An orchestration layer on Organizations; no extra charge.', 'Organizations + custom scripts.', MINE),
    _c('c29', 'ct', 'Control Tower control behaviours', 'Preventive (SCP/RCP/declarative) · detective (Config rule) · proactive (CloudFormation Hook)', 'Only preventive blocks API calls; proactive only sees CloudFormation.', 'All controls block.'),
    _c('c30', 'ct', 'Provision accounts from Terraform with a GitOps pipeline', 'Account Factory for Terraform (AFT)', 'Account requests as Terraform files trigger provisioning and customisations.', 'A Lambda that calls CreateAccount.'),
    _c('c31', 'ct', '“Guardrails” in an old question', 'Control Tower controls', 'Same concept, renamed; mandatory, strongly recommended, elective.', '“A separate service called Guardrails.”', { update: 'Landing zone 4.0 (Nov 2025) made the Security OU and several integrations optional.' }),
    /* RAM */
    _c('c32', 'ram', 'Many accounts deploy into one VPC owned by a network team', 'VPC sharing: share subnets through AWS RAM', 'Same organization; participants manage only their own resources.', 'Transit Gateway or peering to a VPC per account.', MINE),
    _c('c33', 'ram', 'Dozens of separate VPCs in many accounts need transitive routing and on-premises access', 'Transit Gateway in a network account, shared through RAM', 'The one time TGW is the right “big” answer.', 'Full-mesh peering.', MINE),
    _c('c34', 'ram', 'Share Route 53 VPC Resolver forwarding rules with every account', 'AWS RAM resource share with the organization', 'Also for DNS Firewall rule groups, prefix lists, IPAM pools, License Manager, Aurora clusters …', 'Endpoints and rules in each account.'),
    _c('c35', 'ram', 'Participant needs a route-table or NACL change in a shared VPC', 'Only the owner account can make it', 'Participants cannot modify the VPC, subnets, route tables, NACLs or gateways.', 'Give the participant IAM permissions.'),
    /* Config */
    _c('c36', 'config', 'What did this resource look like last week, and what changed?', 'AWS Config configuration timeline', 'CloudTrail says who called the API; Config records the resulting configuration.', 'CloudTrail alone.'),
    _c('c37', 'config', 'Non-compliant resources fixed automatically', 'Config rule + automatic remediation with an SSM Automation runbook', 'Detect, then fix — there is still a short window.', 'Config blocks the change.'),
    _c('c38', 'config', 'Same Config rules and remediations in every account, members cannot change them', 'Organization conformance pack (management or delegated admin account)', 'Aggregator = view; conformance pack = deploy.', 'An aggregator.'),
    /* billing */
    _c('c39', 'billing', 'Unused Reserved Instances in one account, On-Demand usage in another', 'Consolidated billing shares RI and Savings Plans discounts automatically (on by default)', 'Both accounts must have sharing active; the buyer benefits first.', 'Buy more RIs in the other account.'),
    _c('c40', 'billing', 'Resources must never be created without a CostCenter tag', 'SCP: Deny create when aws:RequestTag/CostCenter is null', 'Tag policies standardise values but ignore untagged resources; activate the cost allocation tag for reports.', 'A tag policy alone.')
  ];
})();
