/* Session 6 drills (Multi-account & governance). stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit.
   G1–G5 come from his prestige-distractor pattern (mine: true, src 'Exam pattern', tag 'C'): Control Tower, Transit Gateway
   and Network Firewall tempting and wrong (G1 G2 G3), Control Tower and Transit Gateway genuinely right (G4 G5).
   Other drills where a prestige service is a wrong option: G6 G15 G19 G20 G22 G28 G30.
   Options are written to the same size; each distractor breaks on one detail. Never refer to options by letter (the engine shuffles).
   Select TWO: G13, G24. Correct letters: A 7 · B 7 · C 7 · D 7 · AC 1 · BD 1. */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _o = (t, ok, why) => ({ t, ok: !!ok, why });
  const CT_ONE = 'Control Tower builds and governs a whole landing zone. Deploying one to get a single restriction in an organization that already exists is far more work than one SCP — prestige distractor.';
  const TGW_ONE = 'Transit Gateway connects many separate VPCs through a hub, billed per attachment-hour and per GB. It does not let other accounts launch resources into one VPC — prestige distractor.';
  const SCP_GRANT = 'SCPs never grant permissions; they only set the maximum.';
  S.drills = [
    /* ---------------- the prestige pattern (his record) ---------------- */
    { id: 'G1', src: 'Exam pattern', line: 'org', mine: true, tag: 'C',
      q: 'A company already uses AWS Organizations with all features enabled and 60 member accounts in several OUs. A new regulation requires that no one in any member account, including account administrators, can create resources in any AWS Region other than eu-west-1 and eu-central-1. Which solution meets this requirement with the least operational overhead?',
      opts: [_o('Set up AWS Control Tower over the existing organization, enroll all 60 accounts, and enable its Region deny control for the two Regions.', 0, CT_ONE + ' It would work in the end, after enrolling every account.'),
        _o('Attach an IAM policy that denies all actions outside eu-west-1 and eu-central-1 to every IAM user and role in the 60 member accounts.', 0, 'Account administrators can detach or edit IAM policies, and roles created later are not covered.'),
        _o('Attach an SCP to the organization root that denies actions when aws:RequestedRegion is not eu-west-1 or eu-central-1, exempting global services.', 1, 'One policy, inherited by every member account and OU, binding administrators and the member root user.'),
        _o('Deploy an organization conformance pack with a Config rule that flags resources created outside the two Regions and deletes them automatically.', 0, 'Config evaluates after the resource exists; the requirement is that no one **can** create it.')],
      stub: { scope: 'whole org', control: 'prevent', who: 'workforce human', sup: 'least ops' }, words: ['already uses AWS Organizations', 'including account administrators', 'least operational overhead'],
      expl: 'SCOPE = whole org, CONTROL = prevent. The organization exists, so the guardrail is **one SCP** at the root with an `aws:RequestedRegion` condition (global services such as IAM, Organizations and CloudFront are excluded with `NotAction`). Control Tower is the prestige pick: it contains a Region deny control, but it is a landing zone, not a single policy. The conformance pack only cleans up after the fact.' },
    { id: 'G2', src: 'Exam pattern', line: 'ram', mine: true, tag: 'C',
      q: 'A central network team manages the company’s networking. Application teams in 15 accounts of the same organization must launch EC2 instances and RDS databases into subnets that the network team controls. The company wants to minimize the number of VPCs, keep routing under the network team’s control, and avoid extra networking charges. Which solution is the MOST cost-effective?',
      opts: [_o('Create one VPC in a network account and share its subnets with the 15 accounts through AWS RAM; the network team keeps the route tables.', 1, 'Participants launch resources into the shared subnets; only the owner manages the VPC, route tables and NACLs. No peering or hub to pay for.'),
        _o('Create a VPC in each application account and attach all 15 VPCs to a transit gateway in the network account that holds the route tables.', 0, TGW_ONE + ' It also adds 15 VPCs and 15 attachments to pay for.'),
        _o('Create one VPC in the network account and peer it with a small VPC in each of the 15 accounts, with the routes managed by the network team.', 0, 'Still 16 VPCs, and each account controls the route tables of its own VPC.'),
        _o('Use AWS Control Tower Account Factory to give each of the 15 accounts a standard VPC whose CIDR ranges and subnets the network team defines.', 0, 'Account Factory creates a VPC per account — the opposite of minimising VPCs, and routing stays in 15 accounts.')],
      stub: { scope: 'whole org', control: 'share', who: 'workload', sup: 'cheapest' }, words: ['launch EC2 instances and RDS databases into subnets that the network team controls', 'minimize the number of VPCs', 'avoid extra networking charges'],
      expl: 'CONTROL = share. Many accounts deploying **into one VPC** is **VPC sharing through RAM**. Transit Gateway is your recorded prestige pick: it connects separate VPCs and is right only when separate VPCs must route to each other or to on-premises.' },
    { id: 'G3', src: 'Exam pattern', line: 'iam', mine: true, tag: 'C',
      q: 'A company stores audit reports in an S3 bucket. Only IAM principals from accounts in the company’s AWS Organizations organization may read them, and accounts added to the organization later must get access without changes to the bucket policy. What should a solutions architect do?',
      opts: [_o('Send S3 traffic through AWS Network Firewall in a central inspection VPC and allow only requests from the organization’s IP ranges.', 0, 'S3 authorization is not a packet filter: principals call S3 from anywhere with credentials, and an IP says nothing about the account. Prestige distractor.'),
        _o('Add a bucket policy statement that allows s3:GetObject and lists the account ID of every current member account as a principal.', 0, 'Works today, but every new account needs a bucket-policy change.'),
        _o('Share the bucket with the organization through AWS Resource Access Manager and let each member account accept the resource share.', 0, 'S3 buckets are not a RAM-shareable resource type.'),
        _o('Add a bucket policy statement that allows s3:GetObject to any principal when aws:PrincipalOrgID equals the organization ID.', 1, 'The condition matches any principal in any account of the organization, now or later.')],
      stub: { scope: 'whole org', control: 'grant', who: 'workforce human', sup: 'none stated' }, words: ['Only IAM principals from accounts in the company’s AWS Organizations organization', 'accounts added to the organization later', 'without changes to the bucket policy'],
      expl: '“Anyone in our organization” in a resource policy = **`aws:PrincipalOrgID`**. For one OU use `aws:PrincipalOrgPaths`. Network Firewall appears because “only our network” sounds like a firewall job; the requirement is about **who** calls, which is IAM.' },
    { id: 'G4', src: 'Exam pattern', line: 'ct', mine: true, tag: 'C',
      q: 'A startup will grow from 1 to about 30 AWS accounts over the next year. It needs a centralized log archive, a separate security audit account, single sign-on for employees, and baseline guardrails applied automatically to every new account. The company has a small cloud team and wants the solution with the least operational overhead.',
      opts: [_o('Create an organization and build CloudFormation StackSets, SCPs and Lambda functions that set up logging, audit and SSO in each new account.', 0, 'Works, but the team builds and maintains everything a landing zone gives out of the box.'),
        _o('Set up an AWS Control Tower landing zone and create every new account through Account Factory so that baseline controls are enabled on it.', 1, 'Log Archive and Audit accounts, organization trail, Identity Center, controls on OUs, and governed account vending out of the box.'),
        _o('Create an organization with a security account, an AWS Config aggregator and a CloudTrail organization trail, and invite each new account.', 0, 'Logs and a compliance view, but no single sign-on and no guardrails: an aggregator only views results.'),
        _o('Create IAM users in a shared identity account with cross-account roles, and enable AWS Config and CloudTrail by hand in each new account.', 0, 'Manual setup per account; nothing is applied automatically and there are no preventive guardrails.')],
      stub: { scope: 'whole org', control: 'provision', who: 'workforce human', sup: 'least ops' }, words: ['grow from 1 to about 30 AWS accounts', 'centralized log archive', 'applied automatically to every new account', 'least operational overhead'],
      expl: 'Here Control Tower is **genuinely the answer**: CONTROL = provision a whole governed environment, SUP = least ops. The prestige test is not “never pick Control Tower”; it is “pick it when the job is a landing zone, not one policy”.',
      update: 'Control Tower landing zone 4.0 (Nov 2025) makes the Security OU, Config, CloudTrail and Backup integrations optional. Banks still describe the classic landing zone (Security OU with Log Archive and Audit), which remains the default design.' },
    { id: 'G5', src: 'Exam pattern', line: 'ram', mine: true, tag: 'C',
      q: 'A company has 60 VPCs spread across 20 accounts in one AWS Region, all in the same organization. The VPCs must stay separate, but every VPC must be able to reach every other VPC and the on-premises data center over an existing AWS Direct Connect connection. The network team wants to manage routing centrally with the least operational overhead.',
      opts: [_o('Share the subnets of one VPC in a network account with all 20 accounts through AWS RAM, and reach on premises through its Direct Connect gateway.', 0, 'VPC sharing collapses workloads into one VPC; here the VPCs must stay separate.'),
        _o('Peer all 60 VPCs with each other in a full mesh and associate each VPC’s virtual private gateway with a Direct Connect gateway.', 0, 'About 1,770 peerings, with route tables in 60 VPCs — peering is not transitive and nothing is central.'),
        _o('Create a transit gateway in a network account, share it through AWS RAM, attach all 60 VPCs, and associate it with a Direct Connect gateway.', 1, 'A hub with central route tables, transitive routing between VPCs and to on-premises.'),
        _o('Set up AWS Control Tower, enroll the 20 accounts, and use the Account Factory network settings to connect each VPC to the data center.', 0, 'Account Factory network settings only shape the VPC it creates (CIDR, subnets); Control Tower routes nothing — prestige distractor.')],
      stub: { scope: 'whole org', control: 'share', who: 'workload', sup: 'least ops' }, words: ['60 VPCs spread across 20 accounts', 'The VPCs must stay separate', 'reach every other VPC and the on-premises data center'],
      expl: 'This time **Transit Gateway is right**: many **separate** VPCs, transitive routing, on-premises. RAM still appears — it is how the network account **shares the transit gateway** with the other accounts. Control Tower is the prestige distractor this time.' },

    /* ---------------- Organizations and SCPs ---------------- */
    { id: 'G6', src: 'New', line: 'org',
      q: 'A developer with the AdministratorAccess managed policy in a member account receives an AccessDenied error when launching EC2 instances in us-east-1. The same action works in eu-west-1. No permission boundary is set on the developer’s role. What is the most likely cause?',
      opts: [_o('An SCP on the account or a parent OU denies EC2 actions when aws:RequestedRegion is not eu-west-1.', 1, 'SCPs bind every principal in a member account, administrators included; AdministratorAccess cannot override a Deny.'),
        _o('The AdministratorAccess policy only covers the Region in which the member account was first created.', 0, 'AdministratorAccess allows all actions on all resources in every Region; IAM is global.'),
        _o('us-east-1 is an opt-in Region that the account’s root user has not yet enabled in account settings.', 0, 'us-east-1 is enabled by default; only Regions launched after March 2019 are opt-in.'),
        _o('The Control Tower landing zone denies every Region except its home Region by default, without an SCP.', 0, 'Control Tower’s Region deny control is optional, and it is itself implemented as an SCP — the cause would still be an SCP.')],
      stub: { scope: 'OU', control: 'prevent', who: 'workforce human', sup: 'none stated' }, words: ['AdministratorAccess', 'member account', 'works in eu-west-1', 'No permission boundary'],
      expl: 'Admin + AccessDenied in one Region + no boundary → an **SCP** with a Region condition. Effective permissions are the **intersection** of SCPs and IAM policies; an explicit Deny in an SCP beats any Allow in the account.' },
    { id: 'G7', src: 'New', line: 'org',
      q: 'A company attached an SCP to the organization root that denies disabling AWS CloudTrail. An audit finds that a user in the management account was still able to stop the organization trail logging. Several production workloads also run in the management account. What should a solutions architect recommend?',
      opts: [_o('Attach the same SCP directly to the management account as well, so it no longer depends on inheritance from the root.', 0, 'SCPs never affect the management account, wherever they are attached.'),
        _o('Attach a permission boundary that denies cloudtrail:StopLogging to the organization root so it covers every account.', 0, 'Permission boundaries attach to IAM users and roles, not to the root, OUs or accounts.'),
        _o('Convert the SCP into an RCP on the organization root so it protects the trail resource in every account.', 0, 'RCPs do not apply to the management account either, and they restrict access to resources, not the principals in it.'),
        _o('Move the workloads into member accounts and limit the management account to a few MFA-protected admins.', 1, 'SCPs cannot protect the management account, so keep it minimal and tightly controlled; workloads belong in member accounts where SCPs apply.')],
      stub: { scope: 'one account', control: 'prevent', who: 'workforce human', sup: 'none stated' }, words: ['user in the management account', 'still able to stop', 'production workloads also run in the management account'],
      expl: 'SCPs (and RCPs) **never apply to the management account**. AWS’s guidance: use the management account only for tasks that need it (organization, billing), protect it strongly, and run nothing else in it.' },
    { id: 'G8', src: 'New', line: 'org',
      q: 'A new member account sits in an OU that has only the default FullAWSAccess SCP attached. A developer creates an IAM role for an application, attaches no policies to it, and the application gets AccessDenied when reading an S3 bucket in the same account. What should the developer do to fix this following least privilege?',
      opts: [_o('Attach an SCP to the account that allows s3:GetObject on the bucket, next to the FullAWSAccess SCP.', 0, SCP_GRANT + ' FullAWSAccess already leaves room for it.'),
        _o('Attach an identity-based policy to the role that allows s3:GetObject on that bucket’s objects.', 1, 'Something must grant the action: an identity policy (or a bucket policy naming the role). Scoped to the one bucket.'),
        _o('Attach the AWS managed AmazonS3ReadOnlyAccess policy to the role so it can read the bucket.', 0, 'It works, but it reads every bucket in the account — broader than least privilege.'),
        _o('Detach the FullAWSAccess SCP from the OU so the account inherits permissions from the root.', 0, 'With no SCP on the OU there is no Allow on the path, so everything is denied; SCPs never grant anyway.')],
      stub: { scope: 'one account', control: 'grant', who: 'workload', sup: 'least privilege' }, words: ['only the default FullAWSAccess SCP', 'attaches no policies to it', 'least privilege'],
      expl: 'FullAWSAccess means “SCPs do not restrict anything here”, not “everything is allowed”. Without a policy that **grants** the action, the default is an **implicit deny**. A managed read-only policy works but is not least privilege.' },
    { id: 'G10', src: 'New', line: 'org',
      q: 'A company gives each developer a sandbox account in a Sandbox OU with full administrator access. To control cost, no one in these accounts may launch any EC2 instance type larger than t3.large, and the developers must not be able to remove the restriction. Which solution meets these requirements?',
      opts: [_o('Attach an SCP to the Sandbox OU that denies ec2:RunInstances unless ec2:InstanceType is an approved type.', 1, 'Inherited by every sandbox account; account administrators cannot detach it.'),
        _o('Attach a permission boundary to each developer’s role that allows ec2:RunInstances only for approved types.', 0, 'The developers are administrators in their own accounts and can remove or edit the boundary.'),
        _o('Create an AWS Budgets action per account that applies a deny policy to developer roles above $100 a month.', 0, 'A Budgets action reacts after spend crosses the threshold; it does not stop the first large instance.'),
        _o('Deploy the desired-instance-type Config rule to each account with remediation that stops larger instances.', 0, 'The instance launches before the rule flags it, and administrators can delete the rule in their own account.')],
      stub: { scope: 'OU', control: 'prevent', who: 'workforce human', sup: 'none stated' }, words: ['full administrator access', 'Sandbox OU', 'must not be able to remove the restriction'],
      expl: 'Restriction on **all principals of several accounts**, administrators included, that they cannot remove → **SCP** on the OU. A boundary is the right tool only when an admin above the developers sets it inside one account. Budgets and Config react after the fact.' },
    { id: 'G30', src: 'New', line: 'org',
      q: 'Company A acquired company B. Company B has an AWS account that is a member of company B’s organization. The account must become a member of company A’s organization with the least operational overhead and without losing consolidated billing benefits during the move.',
      opts: [_o('Create a new account in company A’s organization, migrate the workloads into it, then close company B’s original account.', 0, 'Rebuilding everything is the most work of all.'),
        _o('Remove the account from company B’s organization, add a payment method and support plan, then accept company A’s invitation.', 0, 'The classic procedure. It still works, but the account runs standalone, without consolidated billing, in between.'),
        _o('Invite the account from company A’s management account and accept in the account, so it transfers directly between organizations.', 1, 'Direct account transfer (Nov 2025): no standalone period, no payment method or support plan to set up.'),
        _o('Enroll the account in company A’s AWS Control Tower landing zone with Account Factory, which moves it out of company B’s organization.', 0, 'Enrollment works only for accounts already in the organization; it does not move accounts between organizations.')],
      stub: { scope: 'cross-account', control: 'provision', who: 'any', sup: 'least ops' }, words: ['must become a member of company A’s organization', 'least operational overhead', 'without losing consolidated billing benefits'],
      expl: 'Since **November 2025** an account can **transfer directly** from one organization to another: the destination sends an invitation and the account accepts it. Requirements include the account being at least 4 days old if it was created in its organization, and the destination organization being at least 7 days old.',
      update: 'Practice exams still answer “remove the account from the old organization, then accept the invitation from the new one” (the account had to stand alone in between, with its own payment method). Today AWS supports a **direct transfer** without leaving first.' },

    /* ---------------- IAM mechanics ---------------- */
    { id: 'G9', src: 'New', line: 'iam',
      q: 'A platform team wants developers to create IAM roles for their own Lambda functions without waiting for the security team. The security team must ensure that no role a developer creates can ever have more permissions than a defined set, and that developers cannot escalate their own privileges. What should a solutions architect do?',
      opts: [_o('Attach an SCP to the account that denies iam:CreateRole and iam:PutRolePolicy unless the caller is the security team’s role.', 0, 'Developers could no longer create roles at all — they would wait for the security team again.'),
        _o('Give developers the IAMFullAccess policy and use IAM Access Analyzer unused-access findings to trim role permissions weekly.', 0, 'Detective and late; a developer can create an administrator role and use it before the weekly review.'),
        _o('Require a permission boundary on new roles with the iam:PermissionsBoundary condition, and let developers edit the boundary policy.', 0, 'A developer who can edit the boundary can widen it — the escalation the security team must prevent.'),
        _o('Require a permission boundary on every role developers create (iam:PermissionsBoundary condition) and deny editing or removing it.', 1, 'The delegation pattern: every role they create is capped by the boundary, and they cannot lift it.')],
      stub: { scope: 'one account', control: 'grant', who: 'workforce human', sup: 'none stated' }, words: ['create IAM roles for their own Lambda functions', 'can ever have more permissions than a defined set', 'cannot escalate their own privileges'],
      expl: 'This is the textbook use of a **permission boundary**: delegated administration inside one account. Effective permissions = identity policy ∩ boundary; the boundary grants nothing on its own. The boundary only holds if developers cannot change it — deny `iam:CreatePolicyVersion`/`iam:DeleteRolePermissionsBoundary` on it.' },
    { id: 'G11', src: 'New', line: 'iam',
      q: 'An application role in account A must read objects from an S3 bucket in account B. The bucket policy in account B allows s3:GetObject for the role’s ARN. The application still receives AccessDenied. The objects are encrypted with SSE-S3 and no SCP or RCP restricts S3. What is missing?',
      opts: [_o('A VPC endpoint policy on account A’s S3 gateway endpoint that allows s3:GetObject on the bucket in account B.', 0, 'Endpoint policies only limit what passes through the endpoint; they never grant the role anything.'),
        _o('A resource share in AWS RAM that shares the bucket from account B with account A or with its organization.', 0, 'S3 buckets are not shared through RAM.'),
        _o('An identity-based policy on the role in account A that allows s3:GetObject on the bucket in account B.', 1, 'Cross-account requests need an Allow on both sides: the resource policy in B and the caller’s identity policy in A.'),
        _o('A permission boundary on the role in account A that includes s3:GetObject on the bucket in account B.', 0, 'A boundary never grants; without one, nothing is capped anyway.')],
      stub: { scope: 'cross-account', control: 'grant', who: 'workload', sup: 'none stated' }, words: ['account A must read objects from an S3 bucket in account B', 'bucket policy in account B allows', 'still receives AccessDenied'],
      expl: 'In the **same** account either an identity policy or a resource policy that names the principal is enough. **Across** accounts, AWS evaluates both accounts: the trusting side (bucket policy) **and** the trusted side (the role’s identity policy) must allow.' },
    { id: 'G12', src: 'New', line: 'iam',
      q: 'A company uses a third-party SaaS monitoring vendor that must read CloudWatch metrics and describe EC2 instances in the company’s account. The vendor serves many customers from its own AWS account. The company wants the most secure access that also protects against the confused deputy problem.',
      opts: [_o('Create a read-only IAM user for the vendor and rotate its access keys every 90 days with AWS Secrets Manager.', 0, 'Long-term keys held outside the company, and nothing ties a request to this customer — no confused-deputy protection.'),
        _o('Create a read-only IAM role that trusts the vendor’s account and requires an external ID unique to the company.', 1, 'Temporary credentials via AssumeRole; the external ID ensures the vendor acts for this customer only.'),
        _o('Create a read-only IAM role that trusts the vendor’s account and limits AssumeRole by aws:SourceIp to the vendor.', 0, 'The vendor calls from the same IPs for every customer, so another customer could still steer it to your role.'),
        _o('Create a read-only IAM role that trusts the vendor’s account and requires aws:PrincipalOrgID of the vendor’s org.', 0, 'Every request already comes from the vendor’s organization, whichever customer it serves — no confused-deputy protection.')],
      stub: { scope: 'cross-account', control: 'grant', who: 'third party', sup: 'least privilege' }, words: ['third-party SaaS monitoring vendor', 'serves many customers from its own AWS account', 'confused deputy problem'],
      expl: 'Third party + many customers + “confused deputy” → **role with an external ID** condition (`sts:ExternalId`) in the trust policy. IP and organization conditions identify the vendor, not which customer it is acting for; without the external ID, another customer of the vendor could trick the vendor into using your role.' },
    { id: 'G13', src: 'New', line: 'iam',
      q: 'A Lambda function in account A must write objects to an S3 bucket in account B. Both accounts are in the same organization, and no SCP or RCP restricts S3. Which TWO actions are required? (Select TWO.)',
      opts: [_o('Attach an identity-based policy to the Lambda execution role in account A that allows s3:PutObject on the bucket in account B.', 1, 'The trusted side must allow the call.'),
        _o('Share the bucket from account B with account A through AWS Resource Access Manager and accept the share in account A.', 0, 'S3 buckets are not RAM-shareable.'),
        _o('Add a bucket policy in account B that allows s3:PutObject for the ARN of the Lambda execution role in account A.', 1, 'The trusting side must allow it too.'),
        _o('Attach an SCP to account A that allows s3:PutObject on the bucket in account B for the Lambda execution role.', 0, SCP_GRANT)],
      stub: { scope: 'cross-account', control: 'grant', who: 'workload', sup: 'none stated' }, words: ['account A must write objects to an S3 bucket in account B', 'Which TWO actions are required'],
      expl: 'Cross-account = **both** policies. (Add bucket-owner-enforced Object Ownership in B so that B owns the objects written by A — the default for new buckets.)' },
    { id: 'G14', src: 'New', line: 'iam',
      q: 'A KMS key policy must allow decryption only for principals in the accounts of the Finance OU of the company’s organization, including Finance accounts created in the future. What is the most maintainable condition to use?',
      opts: [_o('aws:PrincipalAccount with a list of the Finance account IDs, updated whenever an account is added.', 0, 'A static list that someone must edit for every new Finance account.'),
        _o('aws:PrincipalOrgID set to the organization ID, which every account in the organization matches.', 0, 'Too broad: every account in the organization, not only Finance.'),
        _o('aws:ResourceOrgPaths matching the Finance OU path of the company’s organization.', 0, 'Resource keys describe the account that owns the key, not the caller’s account.'),
        _o('aws:PrincipalOrgPaths matching the Finance OU path of the company’s organization.', 1, 'Matches principals whose account sits under that OU path, now and later.')],
      stub: { scope: 'OU', control: 'grant', who: 'workload', sup: 'least ops' }, words: ['only for principals in the accounts of the Finance OU', 'created in the future'],
      expl: '`aws:PrincipalOrgID` = the whole organization; **`aws:PrincipalOrgPaths`** = an OU (and below). Both follow accounts as they are added or moved; no account lists to maintain. `aws:ResourceOrg…` keys look at the resource’s account, not the caller’s.' },
    { id: 'G15', src: 'New', line: 'iam',
      q: 'A security team must continuously identify S3 buckets, KMS keys, IAM roles and SQS queues in all member accounts that grant access to principals outside the company’s organization, and review each finding. Which service should they use?',
      opts: [_o('IAM Access Analyzer with an external access analyzer whose zone of trust is the organization.', 1, 'It analyses resource-based and trust policies and reports every resource shared outside the zone of trust.'),
        _o('Amazon Macie with automated sensitive data discovery across every member account’s buckets.', 0, 'Macie finds sensitive data in S3; it does not analyse who policies let in, and it ignores keys, roles and queues.'),
        _o('IAM Access Analyzer with an unused access analyzer created for the whole organization’s accounts.', 0, 'Unused access reports unused roles, keys and permissions — not resources shared outside the organization.'),
        _o('AWS Control Tower detective controls enabled on every OU that contains the member accounts.', 0, 'A few controls check public buckets, but nothing reports external access across all these resource types — prestige distractor.')],
      stub: { scope: 'whole org', control: 'detect', who: 'third party', sup: 'none stated' }, words: ['grant access to principals outside the company’s organization', 'review each finding'],
      expl: '“Resources shared with an external entity” → **IAM Access Analyzer**, external access analyzer, zone of trust = account or **organization** (created from the management account or a delegated administrator). The external access analyzer is free; internal and unused access analyzers are paid.' },

    /* ---------------- Identity Center ---------------- */
    { id: 'G16', src: 'New', line: 'idc',
      q: 'A company has 1,500 employees in Okta. They need console and CLI access to 40 AWS accounts in the company’s organization, with permissions that differ by team and account. Access must end automatically when someone leaves the company. What is the solution with the least operational overhead?',
      opts: [_o('Configure Okta as a SAML 2.0 identity provider in each of the 40 accounts, with an IAM role per team in every account.', 0, 'Works — it is how it was done before — but 40 IdP configurations and role sets to keep in sync.'),
        _o('Enable IAM Identity Center with Okta as the external IdP over SAML 2.0 and SCIM, and assign permission sets to groups.', 1, 'One integration; SCIM syncs users and groups, so a leaver disabled in Okta loses access everywhere.'),
        _o('Create an Amazon Cognito user pool federated with Okta, and map its groups to IAM roles through an identity pool.', 0, 'Cognito is for application end users, not workforce access to the AWS console and CLI.'),
        _o('Enable IAM Identity Center with its built-in directory, recreate the 1,500 users, and assign permission sets to groups.', 0, 'A second copy of every user: a leaver disabled in Okta keeps access until someone deletes them here too.')],
      stub: { scope: 'whole org', control: 'grant', who: 'workforce human', sup: 'least ops' }, words: ['1,500 employees in Okta', '40 AWS accounts', 'end automatically when someone leaves'],
      expl: 'WHO = workforce, SCOPE = whole org → **IAM Identity Center** with the IdP (SAML 2.0 for sign-in, **SCIM** for automatic user and group provisioning). Permission sets become roles in each assigned account.' },
    { id: 'G17', src: 'New', line: 'idc',
      q: 'A company’s employees are in a self-managed Active Directory on premises. They must sign in to multiple AWS accounts with their existing AD credentials, without storing passwords in AWS or synchronising them to the cloud. What should a solutions architect do?',
      opts: [_o('Connect IAM Identity Center to AWS Managed Microsoft AD and synchronise users and passwords into it from on premises.', 0, 'Synchronising passwords into a directory in AWS is exactly what the requirement rules out.'),
        _o('Deploy Simple AD in AWS, recreate the users there, and connect it to IAM Identity Center as the identity source.', 0, 'A separate directory with separate passwords stored in AWS — and Simple AD is closed to new customers.'),
        _o('Connect IAM Identity Center to the on-premises AD through an AD Connector and assign permission sets to AD groups.', 1, 'AD Connector proxies authentication to the on-premises domain controllers; nothing is cached or synchronised.'),
        _o('Use the IAM Identity Center directory, import the AD users with a nightly script, and assign permission sets to groups.', 0, 'Copies the identities into AWS with their own passwords, stored in Identity Center.')],
      stub: { scope: 'whole org', control: 'grant', who: 'workforce human', sup: 'none stated' }, words: ['self-managed Active Directory on premises', 'existing AD credentials', 'without storing passwords in AWS'],
      expl: 'Identity Center identity sources: its own directory, **Active Directory** (AWS Managed Microsoft AD, or **AD Connector** to a self-managed AD), or an external SAML 2.0 IdP. “Keep using on-premises AD, nothing stored in AWS” → **AD Connector** (a proxy, Session 2).' },
    { id: 'G18', src: 'New', line: 'idc',
      q: 'Developers sign in through IAM Identity Center. Each developer may manage only the resources tagged with their own project, and the company adds new projects every week. The security team wants to avoid writing new policies for each project. What should a solutions architect do?',
      opts: [_o('Create one permission set per project with a policy scoped to that project’s tag, and assign the developers to it as each project starts.', 0, 'One more permission set and policy every week — the maintenance the team wants to avoid.'),
        _o('Create an IAM group per project in each account with a policy scoped to that project’s tag, and add the developers to it.', 0, 'A new policy per project, and Identity Center users are not IAM users, so they cannot join IAM groups.'),
        _o('Use one permission set whose policy allows actions when aws:ResourceTag/project equals aws:RequestTag/project.', 0, 'The caller chooses the request tag, so any developer can reach any project by sending its tag.'),
        _o('Pass each user’s project as a session tag and use one permission set comparing aws:ResourceTag/project to aws:PrincipalTag/project.', 1, 'Attribute-based access control: the tag comes from the identity source, so one policy scales to any number of projects.')],
      stub: { scope: 'whole org', control: 'grant', who: 'workforce human', sup: 'none stated' }, words: ['only the resources tagged with their own project', 'new projects every week', 'avoid writing new policies for each project'],
      expl: '**ABAC**: compare a principal tag with a resource tag. Identity Center’s attributes for access control pass user attributes (department, project, cost centre) as session tags, so new projects need a tag, not a policy. The principal tag must come from the identity source, not from the request.' },

    /* ---------------- RAM and sharing ---------------- */
    { id: 'G19', src: 'New', line: 'ram',
      q: 'An application team runs EC2 instances in subnets that the network account shares with it through AWS RAM (VPC sharing). The team needs a new route to an on-premises network in the route table of its shared subnet, but the change fails. What is the correct way to get the route added?',
      opts: [_o('Ask the network account that owns the VPC to add the route, since participants cannot modify its route tables.', 1, 'Only the owner manages the VPC, subnets, route tables, NACLs and gateways.'),
        _o('Create a transit gateway attachment for the shared subnet from the participant account and add the route through it.', 0, 'Participants cannot create attachments in the owner’s VPC, and a new hub is not needed for one route — prestige distractor.'),
        _o('Attach an IAM policy to the team’s role in the participant account that allows ec2:CreateRoute on the route table.', 0, 'IAM in the participant account cannot give rights over resources the owner account holds.'),
        _o('Create a new route table in the participant account with the route, and associate it with the shared subnet.', 0, 'Participants cannot create route tables in the shared VPC or change subnet associations; the owner does.')],
      stub: { scope: 'cross-account', control: 'share', who: 'workload', sup: 'none stated' }, words: ['shares with it through AWS RAM', 'route table of its shared subnet', 'the change fails'],
      expl: 'VPC sharing splits duties: **owner** = VPC, subnets, route tables, NACLs, gateways, endpoints; **participants** = their own EC2, RDS, Lambda … in the shared subnets. Participants cannot view or change each other’s resources.' },
    { id: 'G20', src: 'New', line: 'ram',
      q: 'A network account has Route 53 VPC Resolver outbound endpoints and forwarding rules that send corp.example.com queries to on-premises DNS servers. VPCs in 25 other accounts of the organization must resolve those names. What is the solution with the least operational overhead?',
      opts: [_o('Create outbound endpoints and the same forwarding rules in each of the 25 accounts, pointing at the on-premises DNS.', 0, '25 copies of the same configuration and 25 sets of endpoint charges.'),
        _o('Share the forwarding rules with the organization through AWS RAM and associate them with the VPCs in each account.', 1, 'Rules are RAM-shareable; the shared rules use the network account’s outbound endpoints.'),
        _o('Attach the VPCs of the 25 accounts to a transit gateway with the network VPC so queries reach its endpoints.', 0, 'Routing alone does not tell each VPC’s resolver to forward corp.example.com — prestige distractor.'),
        _o('Create a private hosted zone for corp.example.com in the network account and associate it with all the VPCs.', 0, 'The records live on premises; a copy in a hosted zone must be kept in sync by hand.')],
      stub: { scope: 'whole org', control: 'share', who: 'workload', sup: 'least ops' }, words: ['forwarding rules', '25 other accounts of the organization', 'least operational overhead'],
      expl: 'Resolver rules (and DNS Firewall rule groups, query logging configs, Route 53 Profiles) are shared with **RAM**. Inside an organization with sharing enabled, accounts get the share without invitations.',
      update: 'Route 53 Resolver is now called **Route 53 VPC Resolver** in AWS docs. Banks say “Resolver rules”; same thing.' },

    /* ---------------- Control Tower ---------------- */
    { id: 'G21', src: 'New', line: 'ct',
      q: 'A company uses AWS Control Tower. Teams deploy infrastructure only with AWS CloudFormation. The security team wants to stop any stack from creating an S3 bucket without versioning, before the bucket is provisioned, and show the reason in the failed stack event. Which type of control should be enabled?',
      opts: [_o('A detective control, backed by an AWS Config rule, that marks unversioned S3 buckets as noncompliant.', 0, 'Detective controls report noncompliant resources after they exist.'),
        _o('A preventive control, backed by an SCP, that denies s3:CreateBucket in the accounts of the OU.', 0, 'That blocks every bucket, versioned or not; an SCP cannot see the versioning setting in the template.'),
        _o('A proactive control, implemented as a CloudFormation Hook, that checks the bucket’s versioning.', 1, 'Proactive controls evaluate resources in the template before CloudFormation provisions them and fail the operation with a reason.'),
        _o('A stack policy on each CloudFormation stack that denies updates creating unversioned buckets.', 0, 'Stack policies only protect existing stack resources from updates; they do not validate new resource properties.')],
      stub: { scope: 'whole org', control: 'prevent', who: 'workforce human', sup: 'none stated' }, words: ['only with AWS CloudFormation', 'before the bucket is provisioned', 'failed stack event'],
      expl: 'Three behaviours: **preventive** (SCP, RCP, declarative policy — blocks API calls), **detective** (Config rule — finds after), **proactive** (CloudFormation Hook — checks resource properties **before provisioning**, only for CloudFormation).' },

    /* ---------------- Config ---------------- */
    { id: 'G22', src: 'New', line: 'config',
      q: 'The security team needs a single view, across all accounts and Regions of the organization, of every security group that allows inbound SSH from 0.0.0.0/0. It must update as soon as a security group changes. Nothing should be blocked. Which solution meets these requirements?',
      opts: [_o('An SCP on the organization root that denies ec2:AuthorizeSecurityGroupIngress in every member account.', 0, 'That blocks changes; the requirement is visibility, and SCPs report nothing.'),
        _o('Amazon GuardDuty with a delegated administrator account that aggregates findings from all accounts and Regions.', 0, 'GuardDuty detects threats in activity and logs, not how security groups are configured.'),
        _o('AWS Network Firewall in a central inspection VPC, with a rule that logs and alerts on inbound SSH.', 0, 'Filters and logs traffic that passes through it; it does not report security-group configuration — prestige distractor.'),
        _o('The restricted-ssh Config rule in all accounts via a conformance pack, viewed in an organization aggregator.', 1, 'A change-triggered managed rule in every account, and one aggregated view for all accounts and Regions.')],
      stub: { scope: 'whole org', control: 'detect', who: 'workload', sup: 'none stated' }, words: ['single view, across all accounts and Regions', 'as soon as a security group changes', 'Nothing should be blocked'],
      expl: 'CONTROL = detect. **Config rules** evaluate on configuration change; **conformance packs** deploy them org-wide; the **aggregator** gives the multi-account, multi-Region view (read-only, no extra charge).' },
    { id: 'G23', src: 'New', line: 'config',
      q: 'An outage started last Tuesday. The operations team needs to see how a production security group and its attached network interfaces were configured before the outage and every configuration change since then. What should the team use?',
      opts: [_o('The AWS Config configuration timeline for the security group and its related network interfaces.', 1, 'Configuration items record each state, with relationships to ENIs and instances, over time.'),
        _o('CloudTrail event history filtered by the security group ID for API calls made since the outage.', 0, 'Shows who called which API, not the full configuration at a point in time — useful next to Config, not instead.'),
        _o('VPC Flow Logs on the attached network interfaces, queried with CloudWatch Logs Insights for that week.', 0, 'Flow Logs record traffic, not configuration, and only from the moment they are enabled.'),
        _o('AWS Systems Manager Inventory for the instances behind those interfaces, compared day by day.', 0, 'Inventory collects software and OS metadata from managed instances, not security-group rules.')],
      stub: { scope: 'one account', control: 'detect', who: 'workload', sup: 'none stated' }, words: ['how a production security group and its attached network interfaces were configured', 'every configuration change since then'],
      expl: 'Your baseline Q49 keyword: “**configuration changes**” → **AWS Config**. CloudTrail answers “who did it”; Config answers “what did it look like, and what changed”.' },
    { id: 'G24', src: 'New', line: 'config',
      q: 'Whenever an S3 bucket in the account becomes publicly accessible, the company wants the bucket-level Block Public Access settings turned back on automatically, with no custom code to maintain. Which TWO steps should a solutions architect take? (Select TWO.)',
      opts: [_o('Enable Amazon Macie automated sensitive data discovery and send its public-bucket findings to Security Hub.', 0, 'Macie reports on buckets and data; it does not change bucket settings.'),
        _o('Enable the AWS Config managed rule s3-bucket-level-public-access-prohibited for the account’s buckets.', 1, 'A change-triggered managed rule that flags publicly accessible buckets.'),
        _o('Create an EventBridge rule on bucket policy changes that invokes a Lambda function to re-enable the settings.', 0, 'It would work, but the Lambda function is custom code the company must maintain.'),
        _o('Configure automatic remediation on the rule with the SSM Automation runbook that re-enables the settings.', 1, 'Config runs the SSM Automation document for each noncompliant bucket, with retries.')],
      stub: { scope: 'one account', control: 'remediate', who: 'workload', sup: 'none stated' }, words: ['turned back on automatically', 'no custom code to maintain', 'Which TWO steps'],
      expl: 'Detect with a **Config rule**, fix with **automatic remediation** that runs an AWS-owned **SSM Automation** runbook — no code of your own. To make the change impossible in the first place, an SCP denying `s3:PutBucketPublicAccessBlock` (or account-level Block Public Access) would be the preventive answer.' },
    { id: 'G25', src: 'New', line: 'config',
      q: 'A company must deploy the same set of 25 AWS Config rules, with their remediation actions, to all 80 member accounts and to every account created later. Member accounts must not be able to modify or delete the rules. What is the solution with the least operational overhead?',
      opts: [_o('Deploy the rules with a CloudFormation StackSet that targets the organization and deploys automatically to new accounts.', 0, 'Reaches new accounts, but the rules are ordinary resources that member administrators can modify or delete.'),
        _o('Deploy an organization conformance pack from the management account or a Config delegated administrator.', 1, 'Deployed to all member accounts, new ones included; members cannot modify or delete it.'),
        _o('Enable AWS Security Hub CSPM in all accounts with a delegated administrator and its foundational standard.', 0, 'Security Hub CSPM runs its own standards through Config; it does not deploy your 25 rules and remediations.'),
        _o('Create an AWS Config aggregator in the audit account that collects rule results from all 80 accounts.', 0, 'An aggregator only collects results; it deploys no rules.')],
      stub: { scope: 'whole org', control: 'detect', who: 'workload', sup: 'least ops' }, words: ['same set of 25 AWS Config rules', 'every account created later', 'must not be able to modify or delete'],
      expl: 'A **conformance pack** is a bundle of Config rules and remediation actions; an **organization** conformance pack deploys it to every member account and new ones, and members cannot change it. A StackSet also reaches new accounts but leaves editable resources. **Aggregator** = view; **conformance pack** = deploy.' },

    /* ---------------- neighbours ---------------- */
    { id: 'G26', src: 'New', line: 'nbr',
      q: 'Developers must be able to launch only pre-approved, company-standard architectures (for example an EC2 stack with the company’s AMI and tags) from a catalog, without having IAM permissions to create the underlying EC2, IAM and S3 resources themselves. What should a solutions architect do?',
      opts: [_o('Give developers PowerUserAccess and attach an SCP that denies ec2:RunInstances unless the AMI is approved.', 0, 'Developers would then hold the underlying permissions, which the requirement excludes.'),
        _o('Publish the approved CloudFormation templates in a shared S3 bucket and let developers launch them as stacks.', 0, 'Anyone launching a plain stack needs every underlying permission.'),
        _o('Create an AWS Service Catalog portfolio of the products with a launch constraint role that provisions them.', 1, 'Users need only Service Catalog permissions; the launch constraint role creates the resources.'),
        _o('Create an AWS Service Catalog portfolio of the products and grant developers the permissions they need.', 0, 'Without a launch constraint, Service Catalog provisions with the user’s own permissions — which they must not have.')],
      stub: { scope: 'one account', control: 'provision', who: 'workforce human', sup: 'none stated' }, words: ['only pre-approved, company-standard architectures', 'without having IAM permissions to create the underlying'],
      expl: '**AWS Service Catalog**: portfolios of approved products (CloudFormation or Terraform); a **launch constraint** is the IAM role Service Catalog assumes, so end users need no permissions on the underlying services. Portfolios can be shared across the organization.' },

    /* ---------------- consolidated billing ---------------- */
    { id: 'G27', src: 'New', line: 'billing',
      q: 'Account A in an organization bought Reserved Instances for 10 m6i.large instances but now runs only 4. Accounts B and C in the same organization run 5 m6i.large instances each, On-Demand, in the same Region. Which action is the most cost-effective?',
      opts: [_o('Buy Reserved Instances for the 10 On-Demand instances, five in each of the other two accounts, with the same term.', 0, 'The purchasing account already has 6 unused reservations that can cover most of that usage.'),
        _o('Buy a Compute Savings Plan in the management account sized to cover all 10 On-Demand m6i.large instances.', 0, 'A new commitment while 6 reservations sit unused — paying twice for the same capacity.'),
        _o('Sell the 6 unused Reserved Instances of the purchasing account on the Reserved Instance Marketplace.', 0, 'You would give away a discount the other two accounts could be using now.'),
        _o('Keep RI discount sharing on for all three accounts so the 6 unused reservations apply to their usage.', 1, 'Consolidated billing applies unused RI and Savings Plans discounts to matching usage in other accounts; both the buyer and the receiver must have sharing active.')],
      stub: { scope: 'whole org', control: 'share', who: 'any', sup: 'cheapest' }, words: ['bought Reserved Instances for 10', 'now runs only 4', 'most cost-effective'],
      expl: 'Consolidated billing **shares RI and Savings Plans discounts** across all accounts by default; the purchasing account benefits first, then the rest. The management account can turn sharing off per account (or share only within groups).',
      update: 'Sharing can now also be scoped: **prioritized** or **restricted group sharing** (account groups defined with Cost Categories). Banks only know “on or off per account”.' },
    { id: 'G28', src: 'New', line: 'billing',
      q: 'A company has five separate AWS accounts, each with its own bill and payment method. Finance wants a single monthly bill and the benefit of combined usage for volume pricing tiers, with the least effort.',
      opts: [_o('Create an organization in AWS Organizations from one account and invite the other four accounts.', 1, 'Consolidated billing: one bill paid by the management account, usage combined for volume pricing, no extra fee.'),
        _o('Set up an AWS Control Tower landing zone in one account and enroll the other four accounts into it.', 0, 'It ends with an organization too, but a whole landing zone is far more than billing needs — prestige distractor.'),
        _o('Use AWS Billing Conductor in one account to create a billing group that merges the other four bills.', 0, 'Billing Conductor creates pro forma billing views inside an organization; it does not merge separate payer accounts.'),
        _o('Deliver the five accounts’ Cost and Usage Reports to one S3 bucket and query them together in Athena.', 0, 'Reports in one place, but still five bills and no combined volume tiers.')],
      stub: { scope: 'whole org', control: 'provision', who: 'any', sup: 'least ops' }, words: ['single monthly bill', 'combined usage for volume pricing tiers', 'least effort'],
      expl: 'Every organization — even with **consolidated billing only** — gets one bill, combined volume tiers and shared RI/SP discounts at no charge. SCPs and other policies need **all features**.' },
    { id: 'G29', src: 'New', line: 'billing',
      q: 'The finance team charges costs back by department. No EC2 instance or EBS volume may be created in any member account without a CostCenter tag, and existing CostCenter tags must not be deleted. Which solution enforces this?',
      opts: [_o('A tag policy on the organization root that defines CostCenter and enforces it for EC2 instances and volumes.', 0, 'Enforcement blocks noncompliant values of a tag that is set; untagged resources are not evaluated, so they are not blocked.'),
        _o('An SCP that denies RunInstances and CreateVolume when aws:RequestTag/CostCenter is null, and denies DeleteTags.', 1, 'Denies the create call if the tag is missing and prevents removing it — in every member account.'),
        _o('An AWS Config required-tags rule in every account, with remediation that adds a default CostCenter tag.', 0, 'Detects missing tags after creation; it does not enforce at creation.'),
        _o('CostCenter activated as a cost allocation tag in the management account, with untagged usage reported to finance.', 0, 'Needed for the cost reports, but it enforces nothing.')],
      stub: { scope: 'whole org', control: 'prevent', who: 'workforce human', sup: 'none stated' }, words: ['without a CostCenter tag', 'must not be deleted', 'enforces'],
      expl: 'Require a tag = **SCP** with `aws:RequestTag` + `Null` (and `aws:TagKeys` to protect deletion). **Tag policies** keep values and capitalisation consistent; **cost allocation tags** must also be activated so the bill can be split. Use all three together in real life.' }
  ];
})();
