/* Session 6 drills (Multi-account & governance). stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit.
   G1–G5 come from his prestige-distractor pattern (mine: true, src 'Exam pattern', tag 'C'): Control Tower, Transit Gateway
   and Network Firewall tempting and wrong (G1 G2 G3), Control Tower and Transit Gateway genuinely right (G4 G5).
   Other drills where a prestige service is a wrong option: G6 G10 G15 G16 G19 G20 G22 G25 G28 G30.
   Select TWO: G13, G24. Correct letters: A 7 · B 7 · C 7 · D 7 · AC 1 · BD 1. */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _o = (t, ok, why) => ({ t, ok: !!ok, why });
  const CT_ONE = 'Control Tower builds and governs a whole landing zone. Deploying one to get a single restriction in an organization that already exists is far more work than one SCP — prestige distractor.';
  const TGW_ONE = 'Transit Gateway connects many separate VPCs through a hub, billed per attachment-hour and per GB. It does not let other accounts launch resources into one VPC — prestige distractor.';
  const SCP_GRANT = 'SCPs never grant permissions; they only set the maximum.';
  S.drills = [
    /* ---------------- the prestige pattern (his record) ---------------- */
    { id: 'G1', src: 'Exam pattern', line: 'org', mine: true, tag: 'C',
      q: 'A company already uses AWS Organizations with all features enabled and 60 member accounts in several OUs. A new regulation requires that no one in any member account, including account administrators, can create resources in any AWS Region other than eu-west-1 and eu-central-1. The solution must require the least operational overhead.',
      opts: [_o('Set up AWS Control Tower, enroll all 60 accounts, and enable its Region deny control.', 0, CT_ONE + ' It would work in the end, after enrolling every account.'),
        _o('Attach an IAM policy that denies other Regions to every IAM role and user in each account.', 0, 'Account administrators can detach or edit IAM policies, and new roles are not covered.'),
        _o('Attach an SCP to the organization root that denies all actions when aws:RequestedRegion is not eu-west-1 or eu-central-1, with exceptions for global services.', 1, 'One policy, inherited by every member account and OU, binding administrators and the member root user.'),
        _o('Deploy an AWS Config rule in every account that flags resources created in other Regions.', 0, 'Config detects after the fact; the requirement is that no one **can** create them.')],
      stub: { scope: 'whole org', control: 'prevent', who: 'workforce human', sup: 'least ops' }, words: ['already uses AWS Organizations', 'including account administrators', 'least operational overhead'],
      expl: 'SCOPE = whole org, CONTROL = prevent. The organization exists, so the guardrail is **one SCP** at the root with an `aws:RequestedRegion` condition (global services such as IAM, Organizations and CloudFront are excluded with `NotAction`). Control Tower is the prestige pick: it contains a Region deny control, but it is a landing zone, not a single policy.' },
    { id: 'G2', src: 'Exam pattern', line: 'ram', mine: true, tag: 'C',
      q: 'A central network team manages the company’s networking. Application teams in 15 accounts of the same organization must launch EC2 instances and RDS databases into subnets that the network team controls. The company wants to minimize the number of VPCs, keep routing under the network team’s control, and avoid extra networking charges.',
      opts: [_o('Create one VPC in a network account and share its subnets with the 15 accounts through AWS Resource Access Manager (VPC sharing).', 1, 'Participants launch resources into the shared subnets; only the owner manages the VPC, route tables and NACLs. No peering or hub to pay for.'),
        _o('Create a VPC in each account and attach all 15 VPCs to a transit gateway in the network account.', 0, TGW_ONE + ' It also adds 15 VPCs to manage and attachment charges.'),
        _o('Create a VPC in each account and peer every VPC with a central network VPC.', 0, 'Still 16 VPCs, and routing lives in 15 accounts.'),
        _o('Enable AWS Control Tower and use Account Factory to create a VPC in each account.', 0, 'Account Factory can create a VPC per account — the opposite of minimising VPCs.')],
      stub: { scope: 'whole org', control: 'share', who: 'workload', sup: 'cheapest' }, words: ['launch EC2 instances and RDS databases into subnets that the network team controls', 'minimize the number of VPCs', 'avoid extra networking charges'],
      expl: 'CONTROL = share. Many accounts deploying **into one VPC** is **VPC sharing through RAM**. Transit Gateway is your recorded prestige pick: it connects separate VPCs and is right only when separate VPCs must route to each other or to on-premises.' },
    { id: 'G3', src: 'Exam pattern', line: 'iam', mine: true, tag: 'C',
      q: 'A company stores audit reports in an S3 bucket. Only IAM principals from accounts in the company’s AWS Organizations organization may read them, and accounts added to the organization later must get access without changes to the bucket policy. What should a solutions architect do?',
      opts: [_o('Deploy AWS Network Firewall in front of the bucket and allow only the organization’s IP ranges.', 0, 'S3 authorization is not a packet filter: principals call S3 from anywhere with credentials. Network Firewall sits in VPC routing — prestige distractor.'),
        _o('List the account ID of every member account as a principal in the bucket policy.', 0, 'Works today, but every new account needs a bucket-policy change.'),
        _o('Share the bucket with the organization through AWS Resource Access Manager.', 0, 'S3 buckets are not a RAM-shareable resource type.'),
        _o('Add a bucket policy statement that allows s3:GetObject only when aws:PrincipalOrgID equals the organization ID.', 1, 'The condition matches any principal in any account of the organization, now or later.')],
      stub: { scope: 'whole org', control: 'grant', who: 'workforce human', sup: 'least ops' }, words: ['Only IAM principals from accounts in the company’s AWS Organizations organization', 'accounts added to the organization later', 'without changes to the bucket policy'],
      expl: '“Anyone in our organization” in a resource policy = **`aws:PrincipalOrgID`**. For one OU use `aws:PrincipalOrgPaths`. Network Firewall appears because “only our network” sounds like a firewall job; the requirement is about **who** calls, which is IAM.' },
    { id: 'G4', src: 'Exam pattern', line: 'ct', mine: true, tag: 'C',
      q: 'A startup will grow from 1 to about 30 AWS accounts over the next year. It needs a centralized log archive, a separate security audit account, single sign-on for employees, and baseline guardrails applied automatically to every new account. The company has a small cloud team and wants the solution with the least operational overhead.',
      opts: [_o('Create an organization in AWS Organizations and write CloudFormation StackSets, SCPs and Lambda functions to configure each new account.', 0, 'Works, but the team builds and maintains everything a landing zone gives for free.'),
        _o('Set up an AWS Control Tower landing zone and create new accounts with Account Factory.', 1, 'Log Archive and Audit accounts, organization trail, Identity Center, controls on OUs, and governed account vending out of the box.'),
        _o('Create IAM users for employees in each account and enable AWS Config in each account manually.', 0, 'IAM users per account and manual setup: the most overhead and no guardrails for new accounts.'),
        _o('Set up an AWS Config aggregator in a security account.', 0, 'An aggregator only views compliance; it creates no accounts, logs or guardrails.')],
      stub: { scope: 'whole org', control: 'provision', who: 'workforce human', sup: 'least ops' }, words: ['grow from 1 to about 30 AWS accounts', 'centralized log archive', 'applied automatically to every new account', 'least operational overhead'],
      expl: 'Here Control Tower is **genuinely the answer**: CONTROL = provision a whole governed environment, SUP = least ops. The prestige test is not “never pick Control Tower”; it is “pick it when the job is a landing zone, not one policy”.',
      update: 'Control Tower landing zone 4.0 (Nov 2025) makes the Security OU, Config, CloudTrail and Backup integrations optional. Banks still describe the classic landing zone (Security OU with Log Archive and Audit), which remains the default design.' },
    { id: 'G5', src: 'Exam pattern', line: 'ram', mine: true, tag: 'C',
      q: 'A company has 60 VPCs spread across 20 accounts in one AWS Region, all in the same organization. The VPCs must stay separate, but every VPC must be able to reach every other VPC and the on-premises data center over an existing AWS Direct Connect connection. The network team wants to manage routing centrally with the least operational overhead.',
      opts: [_o('Share the subnets of one VPC with all 20 accounts through AWS RAM.', 0, 'VPC sharing collapses workloads into one VPC; here the VPCs must stay separate.'),
        _o('Create a full mesh of VPC peering connections and a Direct Connect private VIF for each VPC.', 0, 'About 1,770 peerings and 60 VIFs — peering is not transitive and does not scale.'),
        _o('Create a transit gateway in a network account, share it with the organization through AWS RAM, attach every VPC, and connect it to Direct Connect through a Direct Connect gateway.', 1, 'A hub with central route tables, transitive routing between VPCs and to on-premises.'),
        _o('Set up AWS Control Tower and enable its networking controls.', 0, 'Control Tower governs accounts; it does not route traffic between VPCs.')],
      stub: { scope: 'whole org', control: 'share', who: 'workload', sup: 'least ops' }, words: ['60 VPCs spread across 20 accounts', 'The VPCs must stay separate', 'reach every other VPC and the on-premises data center'],
      expl: 'This time **Transit Gateway is right**: many **separate** VPCs, transitive routing, on-premises. RAM still appears — it is how the network account **shares the transit gateway** with the other accounts. Control Tower is the prestige distractor this time.' },

    /* ---------------- Organizations and SCPs ---------------- */
    { id: 'G6', src: 'New', line: 'org',
      q: 'A developer with the AdministratorAccess managed policy in a member account receives an AccessDenied error when launching EC2 instances in us-east-1. The same action works in eu-west-1. No permission boundary is set on the developer’s role. What is the most likely cause?',
      opts: [_o('An SCP attached to the account or one of its parent OUs denies EC2 actions outside eu-west-1.', 1, 'SCPs bind every principal in a member account, administrators included; AdministratorAccess cannot override a Deny.'),
        _o('AdministratorAccess does not include EC2 permissions in us-east-1.', 0, 'AdministratorAccess allows all actions on all resources in every Region.'),
        _o('The account’s root user has not enabled us-east-1.', 0, 'us-east-1 is enabled by default; opt-in Regions are different (and would fail in the console with another message).'),
        _o('AWS Control Tower blocks all Regions except the home Region by default.', 0, 'Control Tower’s Region deny control is optional, and it is itself implemented as an SCP — the cause would still be an SCP.')],
      stub: { scope: 'OU', control: 'prevent', who: 'workforce human', sup: 'none stated' }, words: ['AdministratorAccess', 'member account', 'works in eu-west-1', 'No permission boundary'],
      expl: 'Admin + AccessDenied in one Region + no boundary → an **SCP** with a Region condition. Effective permissions are the **intersection** of SCPs and IAM policies; an explicit Deny in an SCP beats any Allow in the account.' },
    { id: 'G7', src: 'New', line: 'org',
      q: 'A company attached an SCP to the organization root that denies disabling AWS CloudTrail. An audit finds that a user in the management account was still able to stop the organization trail logging. Several production workloads also run in the management account. What should a solutions architect recommend?',
      opts: [_o('Attach the SCP directly to the management account as well.', 0, 'SCPs never affect the management account, wherever they are attached.'),
        _o('Add a permission boundary to the organization root.', 0, 'Permission boundaries attach to IAM users and roles, not to organization entities.'),
        _o('Convert the SCP into an RCP.', 0, 'RCPs do not apply to the management account either, and they restrict resource access, not the principals in it.'),
        _o('Move the workloads into member accounts, and restrict and monitor access to the management account with few users, MFA and least-privilege roles.', 1, 'SCPs cannot protect the management account, so keep it minimal and tightly controlled; workloads belong in member accounts where SCPs apply.')],
      stub: { scope: 'one account', control: 'prevent', who: 'workforce human', sup: 'none stated' }, words: ['user in the management account', 'still able to stop', 'production workloads also run in the management account'],
      expl: 'SCPs (and RCPs) **never apply to the management account**. AWS’s guidance: use the management account only for tasks that need it (organization, billing), protect it strongly, and run nothing else in it.' },
    { id: 'G8', src: 'New', line: 'org',
      q: 'A new member account sits in an OU that has only the default FullAWSAccess SCP attached. A developer creates an IAM role for an application, attaches no policies to it, and the application gets AccessDenied when reading an S3 bucket in the same account. What should the developer do to fix this following least privilege?',
      opts: [_o('Attach an SCP to the account that allows s3:GetObject.', 0, SCP_GRANT + ' FullAWSAccess already leaves room for it.'),
        _o('Attach an IAM policy to the role that allows s3:GetObject on that bucket.', 1, 'Something must grant the action: an identity policy (or a bucket policy naming the role). Scoped to the one bucket.'),
        _o('Attach the AdministratorAccess managed policy to the role.', 0, 'It works but violates least privilege.'),
        _o('Remove the FullAWSAccess SCP from the OU.', 0, 'Removing it would leave no Allow in the SCP path and deny everything.')],
      stub: { scope: 'one account', control: 'grant', who: 'workload', sup: 'least privilege' }, words: ['only the default FullAWSAccess SCP', 'attaches no policies to it', 'least privilege'],
      expl: 'FullAWSAccess means “SCPs do not restrict anything here”, not “everything is allowed”. Without a policy that **grants** the action, the default is an **implicit deny**.' },
    { id: 'G10', src: 'New', line: 'org',
      q: 'A company gives each developer a sandbox account in a Sandbox OU with full administrator access. To control cost, no one in these accounts may launch any EC2 instance type larger than t3.large, and the developers must not be able to remove the restriction. Which solution meets these requirements?',
      opts: [_o('An SCP on the Sandbox OU that denies ec2:RunInstances when ec2:InstanceType is not one of the approved types.', 1, 'Inherited by every sandbox account; account administrators cannot detach it.'),
        _o('A permission boundary on each developer’s role that allows only the approved instance types.', 0, 'The developers are administrators in their own accounts and could remove or bypass the boundary.'),
        _o('AWS Budgets alerts at $100 per account.', 0, 'Alerts notify after spending; they do not stop a large instance.'),
        _o('An AWS Control Tower landing zone for the sandbox accounts.', 0, 'A landing zone does not by itself restrict instance types; the restriction would still be an SCP (or a control built on one).')],
      stub: { scope: 'OU', control: 'prevent', who: 'workforce human', sup: 'none stated' }, words: ['full administrator access', 'Sandbox OU', 'must not be able to remove the restriction'],
      expl: 'Restriction on **all principals of several accounts**, administrators included, that they cannot remove → **SCP** on the OU. A boundary is the right tool only when an admin above the developers sets it inside one account.' },
    { id: 'G30', src: 'New', line: 'org',
      q: 'Company A acquired company B. Company B has an AWS account that is a member of company B’s organization. The account must become a member of company A’s organization with the least operational overhead and without losing consolidated billing benefits during the move.',
      opts: [_o('Close the account and recreate its resources in a new account created in company A’s organization.', 0, 'Rebuilding everything is the most work of all.'),
        _o('Remove the account from company B’s organization, add a payment method and support plan so it can stand alone, then accept an invitation from company A’s organization.', 0, 'The classic procedure. It still works, but it is more steps and the account runs standalone in between.'),
        _o('From company A’s management account, invite the account, and accept the invitation from the account so it transfers directly between the organizations.', 1, 'Direct account transfer (Nov 2025): no standalone period, no payment method or support plan to set up.'),
        _o('Enroll the account into company A’s AWS Control Tower with Account Factory.', 0, 'Enrollment works only for accounts already in the organization.')],
      stub: { scope: 'cross-account', control: 'provision', who: 'any', sup: 'least ops' }, words: ['must become a member of company A’s organization', 'least operational overhead', 'without losing consolidated billing benefits'],
      expl: 'Since **November 2025** an account can **transfer directly** from one organization to another: the destination sends an invitation and the account accepts it. Requirements include the account being at least 4 days old if it was created in its organization, and the destination organization being at least 7 days old.',
      update: 'Practice exams still answer “remove the account from the old organization, then accept the invitation from the new one” (the account had to stand alone in between, with its own payment method). Today AWS supports a **direct transfer** without leaving first.' },

    /* ---------------- IAM mechanics ---------------- */
    { id: 'G9', src: 'New', line: 'iam',
      q: 'A platform team wants developers to create IAM roles for their own Lambda functions without waiting for the security team. The security team must ensure that no role a developer creates can ever have more permissions than a defined set, and that developers cannot escalate their own privileges. What should a solutions architect do?',
      opts: [_o('Attach an SCP to the account that denies iam:CreateRole.', 0, 'That blocks role creation entirely.'),
        _o('Give developers the IAMFullAccess managed policy and review CloudTrail weekly.', 0, 'Detective and late; developers could create admin roles in the meantime.'),
        _o('Create the roles for developers through a ticketing process.', 0, 'The requirement is that developers create them without waiting.'),
        _o('Create a permission boundary policy and allow developers to create roles only when that boundary is attached (iam:PermissionsBoundary condition), and deny them changing or removing the boundary.', 1, 'The delegation pattern: every role they create is capped by the boundary, and they cannot lift it.')],
      stub: { scope: 'one account', control: 'grant', who: 'workforce human', sup: 'least privilege' }, words: ['create IAM roles for their own Lambda functions', 'can ever have more permissions than a defined set', 'cannot escalate their own privileges'],
      expl: 'This is the textbook use of a **permission boundary**: delegated administration inside one account. Effective permissions = identity policy ∩ boundary; the boundary grants nothing on its own.' },
    { id: 'G11', src: 'New', line: 'iam',
      q: 'An application role in account A must read objects from an S3 bucket in account B. The bucket policy in account B allows s3:GetObject for the role’s ARN. The application still receives AccessDenied. The objects are encrypted with SSE-S3 and no SCP or RCP restricts S3. What is missing?',
      opts: [_o('A VPC peering connection between the accounts.', 0, 'S3 access is authorised by IAM, not by network paths between VPCs.'),
        _o('A resource share for the bucket in AWS RAM.', 0, 'S3 buckets are not shared through RAM.'),
        _o('An identity-based policy on the role in account A that allows s3:GetObject on the bucket in account B.', 1, 'Cross-account requests need an Allow on both sides: the resource policy in B and the caller’s identity policy in A.'),
        _o('A permission boundary on the role that includes s3:GetObject.', 0, 'A boundary never grants; without one, nothing is capped anyway.')],
      stub: { scope: 'cross-account', control: 'grant', who: 'workload', sup: 'none stated' }, words: ['account A must read objects from an S3 bucket in account B', 'bucket policy in account B allows', 'still receives AccessDenied'],
      expl: 'In the **same** account either an identity policy or a resource policy that names the principal is enough. **Across** accounts, AWS evaluates both accounts: the trusting side (bucket policy) **and** the trusted side (the role’s identity policy) must allow.' },
    { id: 'G12', src: 'New', line: 'iam',
      q: 'A company uses a third-party SaaS monitoring vendor that must read CloudWatch metrics and describe EC2 instances in the company’s account. The vendor serves many customers from its own AWS account. The company wants the most secure access that also protects against the confused deputy problem.',
      opts: [_o('Create an IAM user with read-only permissions and give its access keys to the vendor.', 0, 'Long-term keys held outside the company; rotation and revocation are manual.'),
        _o('Create an IAM role with read-only permissions whose trust policy allows the vendor’s account and requires an external ID unique to the company.', 1, 'Temporary credentials via AssumeRole; the external ID ensures the vendor acts for this customer only.'),
        _o('Add the vendor’s users to IAM Identity Center with a ReadOnly permission set.', 0, 'Identity Center is for the company’s workforce, and the vendor’s software runs as a workload in its own account.'),
        _o('Share the account’s root user credentials with MFA.', 0, 'Never share root credentials.')],
      stub: { scope: 'cross-account', control: 'grant', who: 'third party', sup: 'least privilege' }, words: ['third-party SaaS monitoring vendor', 'serves many customers from its own AWS account', 'confused deputy problem'],
      expl: 'Third party + many customers + “confused deputy” → **role with an external ID** condition (`sts:ExternalId`) in the trust policy. Without it, another customer of the vendor could trick the vendor into using your role.' },
    { id: 'G13', src: 'New', line: 'iam',
      q: 'A Lambda function in account A must write objects to an S3 bucket in account B. Both accounts are in the same organization, and no SCP or RCP restricts S3. Which TWO actions are required? (Select TWO.)',
      opts: [_o('Attach an identity-based policy to the Lambda execution role in account A that allows s3:PutObject on the bucket in account B.', 1, 'The trusted side must allow the call.'),
        _o('Share the bucket with account A through AWS Resource Access Manager.', 0, 'S3 buckets are not RAM-shareable.'),
        _o('Add a bucket policy in account B that allows s3:PutObject for the Lambda execution role in account A.', 1, 'The trusting side must allow it too.'),
        _o('Attach an SCP to account A that allows s3:PutObject.', 0, SCP_GRANT)],
      stub: { scope: 'cross-account', control: 'grant', who: 'workload', sup: 'none stated' }, words: ['account A must write objects to an S3 bucket in account B', 'Which TWO actions are required'],
      expl: 'Cross-account = **both** policies. (Add bucket-owner-enforced Object Ownership in B so that B owns the objects written by A — the default for new buckets.)' },
    { id: 'G14', src: 'New', line: 'iam',
      q: 'A KMS key policy must allow decryption only for principals in the accounts of the Finance OU of the company’s organization, including Finance accounts created in the future. What is the most maintainable condition to use?',
      opts: [_o('aws:SourceAccount with a list of the Finance account IDs.', 0, 'A static list, and aws:SourceAccount is for AWS service principals acting on a resource, not for your own principals.'),
        _o('aws:PrincipalOrgID with the organization ID.', 0, 'Too broad: every account in the organization, not only Finance.'),
        _o('aws:SourceIp with the Finance office IP ranges.', 0, 'IP ranges say nothing about which account a principal belongs to.'),
        _o('aws:PrincipalOrgPaths matching the Finance OU path.', 1, 'Matches principals whose account sits under that OU path, now and later.')],
      stub: { scope: 'OU', control: 'grant', who: 'workload', sup: 'least ops' }, words: ['only for principals in the accounts of the Finance OU', 'created in the future'],
      expl: '`aws:PrincipalOrgID` = the whole organization; **`aws:PrincipalOrgPaths`** = an OU (and below). Both follow accounts as they are added or moved; no account lists to maintain.' },
    { id: 'G15', src: 'New', line: 'iam',
      q: 'A security team must continuously identify S3 buckets, KMS keys, IAM roles and SQS queues in all member accounts that grant access to principals outside the company’s organization, and review each finding. Which service should they use?',
      opts: [_o('IAM Access Analyzer with an external access analyzer whose zone of trust is the organization.', 1, 'It analyses resource-based and trust policies and reports every resource shared outside the zone of trust.'),
        _o('Amazon Macie.', 0, 'Macie finds sensitive data in S3; it does not analyse who policies let in, and it ignores keys, roles and queues.'),
        _o('Amazon GuardDuty.', 0, 'GuardDuty detects threats from activity, not policy-based exposure.'),
        _o('AWS Control Tower detective controls.', 0, 'A few controls check public buckets, but nothing reports external access across all these resource types — Access Analyzer is built for it.')],
      stub: { scope: 'whole org', control: 'detect', who: 'third party', sup: 'none stated' }, words: ['grant access to principals outside the company’s organization', 'review each finding'],
      expl: '“Resources shared with an external entity” → **IAM Access Analyzer**, external access analyzer, zone of trust = account or **organization** (created from the management account or a delegated administrator). The external access analyzer is free; internal and unused access analyzers are paid.' },

    /* ---------------- Identity Center ---------------- */
    { id: 'G16', src: 'New', line: 'idc',
      q: 'A company has 1,500 employees in Okta. They need console and CLI access to 40 AWS accounts in the company’s organization, with permissions that differ by team and account. Access must end automatically when someone leaves the company. What is the solution with the least operational overhead?',
      opts: [_o('Create IAM users for each employee in each account and remove them when HR reports a leaver.', 0, '60,000 users to manage; leavers depend on a manual process.'),
        _o('Enable IAM Identity Center, connect Okta as the external identity provider with SAML 2.0 and SCIM provisioning, and assign permission sets to groups per account.', 1, 'One integration; SCIM syncs users and groups, so a leaver disabled in Okta loses access everywhere.'),
        _o('Create an Amazon Cognito user pool federated with Okta and give users IAM roles through an identity pool.', 0, 'Cognito is for application end users, not workforce access to the AWS console.'),
        _o('Configure a SAML identity provider and IAM roles separately in each of the 40 accounts.', 0, 'Works — it is how it was done before — but 40 configurations to keep in sync.')],
      stub: { scope: 'whole org', control: 'grant', who: 'workforce human', sup: 'least ops' }, words: ['1,500 employees in Okta', '40 AWS accounts', 'end automatically when someone leaves'],
      expl: 'WHO = workforce, SCOPE = whole org → **IAM Identity Center** with the IdP (SAML 2.0 for sign-in, **SCIM** for automatic user and group provisioning). Permission sets become roles in each assigned account.' },
    { id: 'G17', src: 'New', line: 'idc',
      q: 'A company’s employees are in a self-managed Active Directory on premises. They must sign in to multiple AWS accounts with their existing AD credentials, without storing passwords in AWS or synchronising them to the cloud. What should a solutions architect do?',
      opts: [_o('Create an Amazon Cognito user pool and import the users from Active Directory.', 0, 'Cognito is for app users, and importing users means copying identities.'),
        _o('Write a script that creates IAM users from AD group membership every night.', 0, 'Duplicates identities with separate passwords.'),
        _o('Connect IAM Identity Center to the on-premises directory through AWS Directory Service AD Connector and assign permission sets to AD groups.', 1, 'AD Connector proxies authentication to the on-premises domain controllers; nothing is cached or synchronised.'),
        _o('Deploy Simple AD and recreate the users in it.', 0, 'A separate directory with separate passwords — and Simple AD is closed to new customers.')],
      stub: { scope: 'whole org', control: 'grant', who: 'workforce human', sup: 'none stated' }, words: ['self-managed Active Directory on premises', 'existing AD credentials', 'without storing passwords in AWS'],
      expl: 'Identity Center identity sources: its own directory, **Active Directory** (AWS Managed Microsoft AD, or **AD Connector** to a self-managed AD), or an external SAML 2.0 IdP. “Keep using on-premises AD, nothing stored in AWS” → **AD Connector** (a proxy, Session 2).' },
    { id: 'G18', src: 'New', line: 'idc',
      q: 'Developers sign in through IAM Identity Center. Each developer may manage only the resources tagged with their own project, and the company adds new projects every week. The security team wants to avoid writing new policies for each project. What should a solutions architect do?',
      opts: [_o('Create a permission set per project and reassign developers when projects change.', 0, 'One more permission set every week — the maintenance the team wants to avoid.'),
        _o('Create an IAM user per developer with an inline policy listing the project’s resources.', 0, 'Per-user policies and IAM users both grow with every change.'),
        _o('Put each project in its own AWS account.', 0, 'Heavy and not what was asked; a new account every week.'),
        _o('Pass the project attribute from the identity source as a session tag (attributes for access control) and use one permission set whose policy allows actions when aws:ResourceTag/project equals aws:PrincipalTag/project.', 1, 'Attribute-based access control: one policy scales to any number of projects.')],
      stub: { scope: 'whole org', control: 'grant', who: 'workforce human', sup: 'least ops' }, words: ['only the resources tagged with their own project', 'new projects every week', 'avoid writing new policies for each project'],
      expl: '**ABAC**: compare a principal tag with a resource tag. Identity Center’s attributes for access control pass user attributes (department, project, cost centre) as session tags, so new projects need a tag, not a policy.' },

    /* ---------------- RAM and sharing ---------------- */
    { id: 'G19', src: 'New', line: 'ram',
      q: 'An application team runs EC2 instances in subnets that the network account shares with it through AWS RAM (VPC sharing). The team needs a new route to an on-premises network in the route table of its shared subnet, but the change fails. What is the correct way to get the route added?',
      opts: [_o('Ask the network account, which owns the VPC, to add the route; participants cannot modify route tables in a shared VPC.', 1, 'Only the owner manages the VPC, subnets, route tables, NACLs and gateways.'),
        _o('Attach a transit gateway to the shared subnet from the participant account.', 0, 'Participants cannot create attachments in the owner’s VPC, and a new hub is not needed for one route — prestige distractor.'),
        _o('Grant the team’s role ec2:CreateRoute with an IAM policy in the participant account.', 0, 'IAM in the participant account cannot give rights over resources the owner account holds.'),
        _o('Re-create the subnet in the participant account.', 0, 'The team would leave the shared VPC altogether.')],
      stub: { scope: 'cross-account', control: 'share', who: 'workload', sup: 'none stated' }, words: ['shares with it through AWS RAM', 'route table of its shared subnet', 'the change fails'],
      expl: 'VPC sharing splits duties: **owner** = VPC, subnets, route tables, NACLs, gateways, endpoints; **participants** = their own EC2, RDS, Lambda … in the shared subnets. Participants cannot view or change each other’s resources.' },
    { id: 'G20', src: 'New', line: 'ram',
      q: 'A network account has Route 53 VPC Resolver outbound endpoints and forwarding rules that send corp.example.com queries to on-premises DNS servers. VPCs in 25 other accounts of the organization must resolve those names. What is the solution with the least operational overhead?',
      opts: [_o('Create outbound endpoints and forwarding rules in every account.', 0, '25 copies of the same configuration and 25 sets of endpoint charges.'),
        _o('Share the forwarding rules with the organization through AWS RAM and associate them with the VPCs in each account.', 1, 'Rules are RAM-shareable; the shared rules use the network account’s outbound endpoints.'),
        _o('Attach all VPCs to a transit gateway so DNS queries reach the network account.', 0, 'Routing alone does not tell each VPC’s resolver to forward corp.example.com — prestige distractor.'),
        _o('Create a private hosted zone for corp.example.com in each account.', 0, 'The records live on premises; copying them by hand goes stale.')],
      stub: { scope: 'whole org', control: 'share', who: 'workload', sup: 'least ops' }, words: ['forwarding rules', '25 other accounts of the organization', 'least operational overhead'],
      expl: 'Resolver rules (and DNS Firewall rule groups, query logging configs, Route 53 Profiles) are shared with **RAM**. Inside an organization with sharing enabled, accounts get the share without invitations.',
      update: 'Route 53 Resolver is now called **Route 53 VPC Resolver** in AWS docs. Banks say “Resolver rules”; same thing.' },

    /* ---------------- Control Tower ---------------- */
    { id: 'G21', src: 'New', line: 'ct',
      q: 'A company uses AWS Control Tower. Teams deploy infrastructure only with AWS CloudFormation. The security team wants to stop any stack from creating an S3 bucket without versioning, before the bucket is provisioned, and show the reason in the failed stack event. Which type of control should be enabled?',
      opts: [_o('A detective control backed by an AWS Config rule.', 0, 'Detective controls report non-compliant resources after they exist.'),
        _o('A preventive control backed by an SCP that denies s3:CreateBucket.', 0, 'That blocks every bucket, versioned or not; SCPs cannot inspect the template’s properties before provisioning.'),
        _o('A proactive control, implemented as a CloudFormation Hook.', 1, 'Proactive controls evaluate resources in the template before CloudFormation provisions them and fail the operation with a reason.'),
        _o('A Service Catalog launch constraint.', 0, 'Launch constraints give Service Catalog a role to launch products; they do not check bucket settings.')],
      stub: { scope: 'whole org', control: 'prevent', who: 'workforce human', sup: 'none stated' }, words: ['only with AWS CloudFormation', 'before the bucket is provisioned', 'failed stack event'],
      expl: 'Three behaviours: **preventive** (SCP, RCP, declarative policy — blocks API calls), **detective** (Config rule — finds after), **proactive** (CloudFormation Hook — checks resource properties **before provisioning**, only for CloudFormation).' },

    /* ---------------- Config ---------------- */
    { id: 'G22', src: 'New', line: 'config',
      q: 'The security team needs a single view, across all accounts and Regions of the organization, of every security group that allows inbound SSH from 0.0.0.0/0. It must update as soon as a security group changes. Nothing should be blocked. Which solution meets these requirements?',
      opts: [_o('An SCP that denies ec2:AuthorizeSecurityGroupIngress for port 22.', 0, 'That blocks; the requirement is visibility, and SCPs report nothing.'),
        _o('Amazon GuardDuty with delegated administration.', 0, 'GuardDuty detects threats in activity logs, not configuration of security groups.'),
        _o('AWS Network Firewall in a central inspection VPC.', 0, 'Filters traffic; it does not report security-group configuration — prestige distractor.'),
        _o('Deploy the restricted-ssh AWS Config managed rule to all accounts (for example in an organization conformance pack) and view compliance in an organization aggregator.', 1, 'A change-triggered managed rule in every account, and one aggregated view for all accounts and Regions.')],
      stub: { scope: 'whole org', control: 'detect', who: 'workload', sup: 'none stated' }, words: ['single view, across all accounts and Regions', 'as soon as a security group changes', 'Nothing should be blocked'],
      expl: 'CONTROL = detect. **Config rules** evaluate on configuration change; **conformance packs** deploy them org-wide; the **aggregator** gives the multi-account, multi-Region view (read-only, no extra charge).' },
    { id: 'G23', src: 'New', line: 'config',
      q: 'An outage started last Tuesday. The operations team needs to see how a production security group and its attached network interfaces were configured before the outage and every configuration change since then.',
      opts: [_o('Use the AWS Config configuration timeline for the security group and its relationships.', 1, 'Configuration items record each state, with relationships to ENIs and instances, over time.'),
        _o('Search CloudTrail event history for the security group ID.', 0, 'Shows who called which API, not the full configuration at a point in time — useful next to Config, not instead.'),
        _o('Enable VPC Flow Logs on the network interfaces.', 0, 'Flow Logs record traffic from now on, not past configuration.'),
        _o('Use IAM Access Analyzer.', 0, 'Access Analyzer reviews policy access, not network configuration.')],
      stub: { scope: 'one account', control: 'detect', who: 'workload', sup: 'none stated' }, words: ['how a production security group and its attached network interfaces were configured', 'every configuration change since then'],
      expl: 'Your baseline Q49 keyword: “**configuration changes**” → **AWS Config**. CloudTrail answers “who did it”; Config answers “what did it look like, and what changed”.' },
    { id: 'G24', src: 'New', line: 'config',
      q: 'Whenever an S3 bucket in the account becomes publicly accessible, the company wants the bucket-level Block Public Access settings turned back on automatically, with no custom code to maintain. Which TWO steps should a solutions architect take? (Select TWO.)',
      opts: [_o('Enable Amazon Macie automated sensitive data discovery.', 0, 'Macie finds sensitive data; it does not change bucket settings.'),
        _o('Enable the AWS Config managed rule s3-bucket-level-public-access-prohibited.', 1, 'A change-triggered managed rule that flags publicly accessible buckets.'),
        _o('Enable Amazon GuardDuty S3 Protection.', 0, 'Detects suspicious access activity; it does not evaluate configuration or remediate.'),
        _o('Configure automatic remediation on the rule with an AWS Systems Manager Automation runbook that re-enables Block Public Access.', 1, 'Config runs the SSM Automation document for each non-compliant bucket, with retries.')],
      stub: { scope: 'one account', control: 'remediate', who: 'workload', sup: 'least ops' }, words: ['turned back on automatically', 'no custom code to maintain', 'Which TWO steps'],
      expl: 'Detect with a **Config rule**, fix with **automatic remediation** that runs an **SSM Automation** runbook. To make the change impossible in the first place, an SCP denying `s3:PutBucketPublicAccessBlock` (or account-level Block Public Access) would be the preventive answer.' },
    { id: 'G25', src: 'New', line: 'config',
      q: 'A company must deploy the same set of 25 AWS Config rules, with their remediation actions, to all 80 member accounts and to every account created later. Member accounts must not be able to modify or delete the rules. What is the solution with the least operational overhead?',
      opts: [_o('Write a CloudFormation template and deploy it into each account by hand when accounts are created.', 0, 'Manual per account, and members could delete the stack.'),
        _o('Deploy an organization conformance pack from the management account or a Config delegated administrator account.', 1, 'Deployed to all member accounts, new ones included; members cannot modify or delete it.'),
        _o('Enable AWS Security Hub CSPM in each account.', 0, 'Security Hub CSPM runs its own standards through Config; it does not deploy your 25 rules and remediations.'),
        _o('Create an AWS Config aggregator in the audit account.', 0, 'An aggregator only collects results; it deploys no rules.')],
      stub: { scope: 'whole org', control: 'detect', who: 'workload', sup: 'least ops' }, words: ['same set of 25 AWS Config rules', 'every account created later', 'must not be able to modify or delete'],
      expl: 'A **conformance pack** is a bundle of Config rules and remediation actions; an **organization** conformance pack deploys it to every member account and new ones. **Aggregator** = view; **conformance pack** = deploy.' },

    /* ---------------- neighbours ---------------- */
    { id: 'G26', src: 'New', line: 'nbr',
      q: 'Developers must be able to launch only pre-approved, company-standard architectures (for example an EC2 stack with the company’s AMI and tags) from a catalog, without having IAM permissions to create the underlying EC2, IAM and S3 resources themselves.',
      opts: [_o('Give developers PowerUserAccess and an SCP that denies unapproved AMIs.', 0, 'Developers would then hold the underlying permissions, which the requirement excludes.'),
        _o('Publish a CloudFormation template in an S3 bucket.', 0, 'Anyone launching it needs every underlying permission.'),
        _o('Create an AWS Service Catalog portfolio with the approved products and a launch constraint role that provisions the resources.', 1, 'Users need only Service Catalog permissions; the launch constraint role creates the resources.'),
        _o('Use AWS Control Tower Account Factory.', 0, 'Account Factory vends accounts, not application stacks for developers.')],
      stub: { scope: 'one account', control: 'provision', who: 'workforce human', sup: 'least privilege' }, words: ['only pre-approved, company-standard architectures', 'without having IAM permissions to create the underlying'],
      expl: '**AWS Service Catalog**: portfolios of approved products (CloudFormation or Terraform); a **launch constraint** is the IAM role Service Catalog assumes, so end users need no permissions on the underlying services. Portfolios can be shared across the organization.' },

    /* ---------------- consolidated billing ---------------- */
    { id: 'G27', src: 'New', line: 'billing',
      q: 'Account A in an organization bought Reserved Instances for 10 m6i.large instances but now runs only 4. Accounts B and C in the same organization run 5 m6i.large instances each, On-Demand, in the same Region. What is the most cost-effective action?',
      opts: [_o('Buy Reserved Instances in accounts B and C.', 0, 'A already has 6 unused reservations that can cover them.'),
        _o('Move all instances into account A.', 0, 'Unnecessary: discounts already flow between accounts in an organization.'),
        _o('Sell account A’s unused Reserved Instances on the Reserved Instance Marketplace.', 0, 'You would lose the discount that B and C could be using.'),
        _o('Nothing to buy: make sure Reserved Instance discount sharing is active for accounts A, B and C (it is on by default), so the unused reservations apply to their usage.', 1, 'Consolidated billing applies unused RI and Savings Plans discounts to matching usage in other accounts; both the buyer and the receiver must have sharing active.')],
      stub: { scope: 'whole org', control: 'share', who: 'any', sup: 'cheapest' }, words: ['bought Reserved Instances for 10', 'now runs only 4', 'most cost-effective'],
      expl: 'Consolidated billing **shares RI and Savings Plans discounts** across all accounts by default; the purchasing account benefits first, then the rest. The management account can turn sharing off per account (or share only within groups).',
      update: 'Sharing can now also be scoped: **prioritized** or **restricted group sharing** (account groups defined with Cost Categories). Banks only know “on or off per account”.' },
    { id: 'G28', src: 'New', line: 'billing',
      q: 'A company has five separate AWS accounts, each with its own bill and payment method. Finance wants a single monthly bill and the benefit of combined usage for volume pricing tiers, with the least effort.',
      opts: [_o('Create an organization in AWS Organizations from one account and invite the other four accounts.', 1, 'Consolidated billing: one bill paid by the management account, usage combined for volume pricing, no extra fee.'),
        _o('Set up AWS Control Tower in each account.', 0, 'Control Tower is a landing zone per organization, and it is not needed for billing — prestige distractor.'),
        _o('Use AWS Billing Conductor to merge the five bills.', 0, 'Billing Conductor creates pro forma billing views inside an organization; it does not merge separate payer accounts.'),
        _o('Export each account’s Cost and Usage Report into one bucket.', 0, 'Reports in one place, but five bills and no combined discounts.')],
      stub: { scope: 'whole org', control: 'provision', who: 'any', sup: 'least ops' }, words: ['single monthly bill', 'combined usage for volume pricing tiers', 'least effort'],
      expl: 'Every organization — even with **consolidated billing only** — gets one bill, combined volume tiers and shared RI/SP discounts at no charge. SCPs and other policies need **all features**.' },
    { id: 'G29', src: 'New', line: 'billing',
      q: 'The finance team charges costs back by department. No EC2 instance or EBS volume may be created in any member account without a CostCenter tag, and existing CostCenter tags must not be deleted. Which solution enforces this?',
      opts: [_o('A tag policy that defines CostCenter and its allowed values.', 0, 'Tag policies standardise keys and values of tags that are set; untagged resources are not evaluated, so they are not blocked.'),
        _o('An SCP that denies ec2:RunInstances and ec2:CreateVolume when aws:RequestTag/CostCenter is null, and denies ec2:DeleteTags for the CostCenter key.', 1, 'Denies the create call if the tag is missing and prevents removing it — in every member account.'),
        _o('An AWS Config required-tags rule with automatic remediation.', 0, 'Detects missing tags after creation; it does not enforce at creation.'),
        _o('Activate CostCenter as a cost allocation tag in the Billing console.', 0, 'Needed for the cost reports, but it enforces nothing.')],
      stub: { scope: 'whole org', control: 'prevent', who: 'workforce human', sup: 'none stated' }, words: ['without a CostCenter tag', 'must not be deleted', 'enforces'],
      expl: 'Require a tag = **SCP** with `aws:RequestTag` + `Null` (and `aws:TagKeys` to protect deletion). **Tag policies** keep values and capitalisation consistent; **cost allocation tags** must also be activated so the bill can be split. Use all three together in real life.' }
  ];
})();
