/* Session 4 drills (Global architecture & edge). stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit.
   Q4, Q53 and Q43 are his baseline-exam misses (mine: true). G-drills are new.
   Prestige drills where Global Accelerator is tempting and wrong: G1 G2 G3 G4 G5 G24.
   Drills where Global Accelerator IS right: G7 G8 G9 G26. */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _o = (t, ok, why) => ({ t, ok: !!ok, why });
  const GA_NO_S3 = 'Global Accelerator endpoints are ALBs, NLBs, EC2 instances and Elastic IPs. S3 is not one, and GA caches nothing.';
  const LE = 'Lambda@Edge quotas now show 30 s and 50 MB for every trigger; older material says 5 s / 1 MB for viewer triggers. The viewer-only / all-four-triggers split is unchanged.';
  S.drills = [
    /* ---------------- his exam misses ---------------- */
    { id: 'Q4', src: 'Exam Q4', line: 'cf', mine: true, tag: 'C',
      q: 'A software company stores installation packages of 1–3 GB in an Amazon S3 bucket in us-east-1. Customers in Europe, Asia and South America download the same packages many times a day and complain that downloads are slow. The company wants to improve download performance for all customers in the most cost-effective way, without changing how the packages are stored. What should a solutions architect recommend?',
      opts: [_o('Enable S3 Transfer Acceleration on the bucket and give customers the s3-accelerate endpoint.', 0, 'Speeds each transfer over the AWS network but caches nothing: every download still comes from us-east-1 and each one pays the acceleration fee. This was your pick.'),
        _o('Create a CloudFront distribution with the S3 bucket as the origin, protected with origin access control, and publish the CloudFront URL.', 1, 'The same objects are cached at edge locations near every customer; repeat downloads never reach the bucket.'),
        _o('Create an accelerator in AWS Global Accelerator with the S3 bucket as an endpoint.', 0, GA_NO_S3),
        _o('Replicate the bucket to a Region on each continent with S3 Cross-Region Replication and use Route 53 latency routing.', 0, 'Works, but triples storage and replication cost and changes how packages are stored. CloudFront does it with no extra buckets.')],
      stub: { what: 'static content', scope: 'global users', need: 'cache', sup: 'cheapest' }, words: ['download the same packages many times a day', 'improve download performance', 'most cost-effective'],
      expl: 'WHAT = static files, SCOPE = global users, NEED = cache (the same objects many times). CloudFront caches at the edge. Transfer Acceleration is for long-distance transfers into or out of one bucket with no cache — the tempting look-alike.' },
    { id: 'Q53', src: 'Exam Q53', line: 's3web', mine: true, tag: 'F',
      q: 'A company registered the domain example.com with Amazon Route 53 and wants to host a static marketing website on Amazon S3 at http://example.com. The site must be served directly from S3 static website hosting with the least operational overhead. Which combination of steps meets these requirements?',
      opts: [_o('Create a bucket with any unique name, enable static website hosting, and create a CNAME record for example.com that points to the website endpoint.', 0, 'A CNAME cannot exist at the zone apex, and a website endpoint only answers for a bucket named like the host.'),
        _o('Create a bucket named example.com, enable static website hosting, allow public read access with a bucket policy, and create a Route 53 alias A record for example.com that targets the S3 website endpoint.', 1, 'Bucket name = domain, public read for the website endpoint, and an alias record at the apex.'),
        _o('Create a bucket named example.com, keep Block Public Access on, and create an alias record that targets the bucket’s REST endpoint (example.com.s3.amazonaws.com).', 0, 'The REST endpoint is not website hosting, and Route 53 alias targets include the S3 website endpoint, not the REST endpoint.'),
        _o('Create a bucket named example-website, enable static website hosting, and place a Global Accelerator in front of it with an alias record for example.com.', 0, GA_NO_S3 + ' The bucket name also does not match the domain.')],
      stub: { what: 'static content', scope: 'one Region', need: 'DNS steering', sup: 'least ops' }, words: ['static website hosting', 'http://example.com', 'registered the domain example.com with Amazon Route 53'],
      expl: 'Facts to know cold: the **bucket name must equal the domain** (example.com), the website endpoint is **public and HTTP only**, and at the zone apex you use an **alias A record** to the website endpoint. HTTPS would need CloudFront in front.' },
    { id: 'Q43', src: 'Exam Q43', line: 'alb', mine: true, tag: 'K',
      q: 'A company runs several microservices as Amazon ECS services in one AWS Region. Clients call a single domain. Requests for /orders/* must reach the order service, requests for /users/* the user service, and requests to admin.example.com the admin service. The company wants path-based and host-based routing with the least operational overhead. Which solution meets these requirements?',
      opts: [_o('Put a Network Load Balancer in front with one listener per service on different ports.', 0, 'An NLB works at layer 4: it sees ports, not URL paths or host names.'),
        _o('Create Route 53 weighted records for each path and point them at each service.', 0, 'DNS resolves names; it never sees the URL path.'),
        _o('Create an accelerator in Global Accelerator with one endpoint group per service.', 0, 'GA proxies TCP/UDP to endpoints; it does not route by path. Prestige distractor.'),
        _o('Put an Application Load Balancer in front with listener rules that use path-pattern and host-header conditions to forward to each service’s target group.', 1, 'Path and host conditions are exactly what ALB listener rules do.')],
      stub: { what: 'dynamic HTTP', scope: 'one Region', need: 'path routing', sup: 'least ops' }, words: ['path-based and host-based routing', '/orders/*', 'admin.example.com'],
      expl: 'The keyword was **path-based / host-based routing** → ALB listener rules to target groups. Route 53 cannot see paths, an NLB is layer 4, and Global Accelerator is a prestige distractor here.' },

    /* ---------------- CloudFront ---------------- */
    { id: 'G1', src: 'New', line: 'cf',
      q: 'A news website runs on EC2 instances behind an Application Load Balancer in eu-west-1. Most pages are images and articles that change a few times a day; a small API returns personalised data. Readers are worldwide, and the company wants to reduce latency and the load on the web servers.',
      opts: [_o('Create an accelerator in Global Accelerator with the ALB as the endpoint.', 0, 'GA shortens the network path but caches nothing, so every request still hits the web servers. Prestige distractor.'),
        _o('Add EC2 instances in more Availability Zones behind the ALB.', 0, 'More capacity in the same Region does nothing for readers on other continents.'),
        _o('Create a CloudFront distribution with the ALB as the origin, cache the images and articles, and forward the API path with caching disabled.', 1, 'Cacheable content is served from the edge; the API still benefits from the AWS network path.'),
        _o('Create Route 53 geolocation records that send each continent to the same ALB.', 0, 'Every record points to the same ALB, so nothing changes.')],
      stub: { what: 'static content', scope: 'global users', need: 'cache', sup: 'lowest latency' }, words: ['change a few times a day', 'reduce latency and the load on the web servers', 'worldwide'],
      expl: 'Mostly cacheable content, global readers, and origin load → CloudFront. GA would speed the path to the ALB but never offload it.' },
    { id: 'G5', src: 'New', line: 'cf',
      q: 'A media company streams on-demand video from an S3 bucket to millions of viewers on several continents. Egress from the bucket and request load on S3 are growing fast. The company wants better playback start times and lower costs.',
      opts: [_o('Put Global Accelerator in front of the bucket so viewers reach it over the AWS backbone.', 0, GA_NO_S3),
        _o('Serve the video through a CloudFront distribution with the bucket as the origin and Origin Shield enabled in the bucket’s Region.', 1, 'Edge caching serves repeat views; Origin Shield collapses cache misses so S3 sees far fewer requests.'),
        _o('Enable S3 Transfer Acceleration and use the accelerated endpoint in the player.', 0, 'No caching: every view is a full transfer from S3, with an extra per-GB fee.'),
        _o('Move the video to S3 Express One Zone for faster reads.', 0, 'Single-digit-ms latency inside one AZ does not help viewers on other continents.')],
      stub: { what: 'static content', scope: 'global users', need: 'cache', sup: 'cheapest' }, words: ['millions of viewers on several continents', 'request load on S3', 'lower costs'],
      expl: 'Popular objects, many viewers → cache them. CloudFront cuts both latency and S3 egress/requests; Origin Shield reduces origin fetches further.' },
    { id: 'G6', src: 'New', line: 'cf',
      q: 'A single-page application is served through CloudFront from S3 with a 24-hour TTL. The team deploys new JavaScript bundles up to 20 times a day and users must get the new version immediately after each deploy. The team wants the most cost-effective approach that does not reduce the cache hit ratio.',
      opts: [_o('Create an invalidation for /* after every deploy.', 0, 'Works, but invalidations take time to propagate and throw away every cached object, so the next requests all go to S3.'),
        _o('Set the default TTL to 0 on the distribution.', 0, 'Every request would go back to S3: the hit ratio collapses.'),
        _o('Put the version in the file names (app.3f9c.js) and reference them from index.html, which has a short TTL.', 1, 'New names are cache misses by definition; old names keep their long TTL. Nothing to invalidate.'),
        _o('Enable S3 Versioning so CloudFront serves the newest object version.', 0, 'S3 object versions are invisible to CloudFront’s cache key.')],
      stub: { what: 'static content', scope: 'global users', need: 'cache', sup: 'cheapest' }, words: ['up to 20 times a day', 'immediately after each deploy', 'does not reduce the cache hit ratio'],
      expl: 'Frequent changes → **versioned file names**. Invalidations are for the occasional mistake: the first 1,000 paths a month are free (a wildcard counts as one), and they empty the cache.' },
    { id: 'G18', src: 'New', line: 'cf',
      q: 'A static website is delivered by CloudFront from an S3 bucket in us-east-1. The bucket is replicated to eu-west-1 with S3 Cross-Region Replication. If the primary bucket returns server errors, viewers must keep receiving content automatically without a DNS change.',
      opts: [_o('Create a Route 53 failover record that points to a second CloudFront distribution for the replica.', 0, 'Works but adds a second distribution and depends on DNS TTLs; CloudFront can do this per request.'),
        _o('Put both buckets behind Global Accelerator with two endpoint groups.', 0, GA_NO_S3),
        _o('Enable S3 Transfer Acceleration on both buckets.', 0, 'Acceleration has nothing to do with availability.'),
        _o('Create an origin group with the us-east-1 bucket as primary and the eu-west-1 replica as secondary, failing over on 500, 502, 503 and 504.', 1, 'CloudFront retries the secondary origin for GET/HEAD requests when the primary returns the chosen codes.')],
      stub: { what: 'static content', scope: 'multi-Region active-passive', need: 'failover', sup: 'least ops' }, words: ['server errors', 'without a DNS change', 'Cross-Region Replication'],
      expl: '“Without a DNS change” + reads from a replicated bucket → **CloudFront origin group**. Failover happens per request for GET, HEAD (and OPTIONS if cached); status codes you can pick include 400, 403, 404, 416, 429, 500, 502, 503, 504.' },
    { id: 'G21', src: 'New', line: 'cf',
      q: 'A company serves app.example.com through CloudFront. The origin ALB is in eu-central-1, where the team requested a public certificate for app.example.com in AWS Certificate Manager. When they edit the distribution, the certificate does not appear in the custom SSL certificate list. What should they do?',
      opts: [_o('Request (or import) the certificate for app.example.com in ACM in us-east-1 and select it on the distribution.', 1, 'CloudFront only uses ACM certificates from us-east-1 (N. Virginia).'),
        _o('Export the certificate from ACM in eu-central-1 and upload it to the ALB.', 0, 'The ALB can already use the eu-central-1 certificate; the viewer side of CloudFront still needs one in us-east-1.'),
        _o('Choose dedicated IP custom SSL instead of SNI.', 0, 'Changes how the certificate is served (and costs $600 a month), not which Region it comes from.'),
        _o('Create an alias record for app.example.com before selecting the certificate.', 0, 'DNS does not make a certificate visible to CloudFront.')],
      stub: { what: 'dynamic HTTP', scope: 'global users', need: 'restrict access', sup: 'none stated' }, words: ['eu-central-1', 'does not appear in the custom SSL certificate list'],
      expl: 'CloudFront is global and reads certificates from ACM in **us-east-1** only. The ALB keeps its own regional certificate for the origin connection.' },

    /* ---------------- edge security ---------------- */
    { id: 'G4', src: 'New', line: 'protect',
      q: 'A streaming service delivers video through CloudFront. Licensing contracts forbid delivery to viewers in three countries. The company wants to enforce this with the least operational overhead.',
      opts: [_o('Enable CloudFront geographic restriction with a blocklist of the three countries.', 1, 'Built for this: country-level blocklist at the edge, returns 403.'),
        _o('Create Route 53 geolocation records that return no answer for the three countries.', 0, 'DNS steers; anyone using a resolver elsewhere, or the CloudFront domain directly, still gets the video.'),
        _o('Put Global Accelerator in front of CloudFront and block the countries’ IP ranges.', 0, 'GA cannot front CloudFront and has no country rules. Prestige distractor.'),
        _o('Add NACL deny rules for the countries’ IP ranges on the origin subnets.', 0, 'Viewers never reach the origin subnets; CloudFront does. Also thousands of ranges.')],
      stub: { what: 'static content', scope: 'global users', need: 'restrict access', sup: 'least ops' }, words: ['forbid delivery to viewers in three countries', 'least operational overhead'],
      expl: 'Country rule on content → **CloudFront geo restriction** (allowlist or blocklist). AWS WAF geo match rules also work when you need more conditions. DNS routing is not access control.' },
    { id: 'G19', src: 'New', line: 'protect',
      q: 'A company serves a private S3 bucket through CloudFront. The bucket uses SSE-KMS with a customer managed key, and the bucket was created in a Region launched in 2024. Direct access to the bucket must be blocked so objects are reachable only through the distribution.',
      opts: [_o('Create an origin access identity (OAI) and grant it read access in the bucket policy.', 0, 'OAI is legacy: it does not support SSE-KMS or Regions launched after January 2023.'),
        _o('Create an origin access control (OAC), attach it to the origin, allow the CloudFront service principal for this distribution in the bucket policy, and allow it to use the KMS key.', 1, 'OAC signs requests with SigV4, works in all Regions and supports SSE-KMS.'),
        _o('Make the bucket public and require a Referer header with a secret value.', 0, 'The bucket stays public; headers are trivially copied.'),
        _o('Use signed URLs for every object and keep the bucket public.', 0, 'Signed URLs control viewers at CloudFront; a public bucket can still be read directly.')],
      stub: { what: 'static content', scope: 'global users', need: 'restrict access', sup: 'most secure' }, words: ['SSE-KMS', 'reachable only through the distribution', 'launched in 2024'],
      expl: 'Bucket only via CloudFront → **OAC**. OAI is the legacy mechanism and fails on SSE-KMS and newer Regions.' },
    { id: 'G20', src: 'New', line: 'protect',
      q: 'An e-learning site on CloudFront has a members’ area with hundreds of videos and PDFs. Only paying members may access them, and the existing URLs used in the site’s HTML and in bookmarks must not change.',
      opts: [_o('Generate a signed URL for each file when the member logs in.', 0, 'Works per file, but every URL changes — the requirement says they must not.'),
        _o('Enable geo restriction with an allowlist.', 0, 'Geography is not membership.'),
        _o('Put the bucket behind origin access control.', 0, 'Keeps people from bypassing CloudFront, but anyone can still fetch through CloudFront.'),
        _o('Issue CloudFront signed cookies at login, signed with a trusted key group, and require signed requests on the members’ cache behaviour.', 1, 'Many files, URLs unchanged: exactly what signed cookies are for.')],
      stub: { what: 'static content', scope: 'global users', need: 'restrict access', sup: 'none stated' }, words: ['hundreds of videos and PDFs', 'must not change'],
      expl: 'Signed URL = one file (or clients without cookies). **Signed cookies** = many files, keep URLs. Sign with a **trusted key group**, not a root-account key pair.' },
    { id: 'G25', src: 'New', line: 'protect',
      q: 'An internet-facing Application Load Balancer is the origin of a CloudFront distribution. Attackers are bypassing CloudFront and its AWS WAF rules by calling the ALB’s DNS name directly. Which actions ensure the ALB serves only requests that come through CloudFront? (Select TWO.)',
      opts: [_o('Allow inbound HTTPS in the ALB’s security group only from the AWS-managed prefix list for CloudFront origin-facing servers.', 1, 'Only CloudFront’s origin-facing IPs can connect.'),
        _o('Attach an origin access control to the ALB origin.', 0, 'OAC signs requests to S3, Lambda function URLs and MediaStore/MediaPackage origins, not ALBs.'),
        _o('Configure CloudFront to add a secret custom header, and add an ALB listener rule that forwards only requests carrying it (return 403 otherwise).', 1, 'Proves the request passed through your distribution, not just any CloudFront distribution.'),
        _o('Place Global Accelerator in front of the ALB and remove its public DNS name.', 0, 'GA adds another public entry point; it does not restrict the ALB to CloudFront.'),
        _o('Create a Route 53 private hosted zone for the ALB’s name.', 0, 'Attackers already know the public DNS name and IPs.')],
      stub: { what: 'dynamic HTTP', scope: 'one Region', need: 'restrict access', sup: 'most secure' }, words: ['bypassing CloudFront', 'only requests that come through CloudFront'],
      expl: 'The classic pair: **CloudFront prefix list** in the ALB security group + a **secret origin header** checked by an ALB rule (or WAF). Since Nov 2024 a **VPC origin** can go further: a private ALB with no internet exposure at all.',
      update: 'CloudFront **VPC origins** (GA Nov 2024) let CloudFront reach an internal ALB, NLB or EC2 instance in private subnets. Banks still expect the prefix list + custom header answer.' },

    /* ---------------- edge code ---------------- */
    { id: 'G22', src: 'New', line: 'edge',
      q: 'A retailer’s CloudFront distribution receives tens of millions of requests a day. The team must add HSTS and other security headers to every response and redirect legacy /shop/ URLs to /store/. The logic needs no external calls. The team wants the lowest cost and latency.',
      opts: [_o('A Lambda@Edge function on the origin response event.', 0, 'Works, but costs more per request and runs only on cache misses unless moved to viewer events.'),
        _o('CloudFront Functions on the viewer request (redirect) and viewer response (headers) events.', 1, 'Lightweight header and URL work at the edge, sub-millisecond, built for millions of requests.'),
        _o('Code in the origin application behind the ALB.', 0, 'Cached responses never reach the origin, so headers would be missing on hits.'),
        _o('An AWS WAF rule that rewrites the headers.', 0, 'WAF allows, blocks, counts and can insert request headers; it does not rewrite response headers or redirect.')],
      stub: { what: 'dynamic HTTP', scope: 'global users', need: 'edge logic', sup: 'cheapest' }, words: ['tens of millions of requests a day', 'needs no external calls', 'lowest cost'],
      expl: 'Header/redirect logic, viewer events, no network → **CloudFront Functions**. (A managed response headers policy could add the headers without code.)' },
    { id: 'G23', src: 'New', line: 'edge',
      q: 'Before CloudFront fetches content from the origin, a function must call a third-party entitlement API over HTTPS and, depending on the answer, send the request to one of two origins. The function must run only on cache misses.',
      opts: [_o('CloudFront Functions on the viewer request event.', 0, 'No network access, and viewer request runs on every request, not only on misses.'),
        _o('An ALB listener rule that calls the API.', 0, 'Listener rules match request attributes; they cannot call an API.'),
        _o('Lambda@Edge on the origin request event.', 1, 'Origin request runs only on cache misses, has network access and can change the origin.'),
        _o('A Route 53 weighted record between the two origins.', 0, 'DNS cannot see the entitlement answer.')],
      stub: { what: 'dynamic HTTP', scope: 'global users', need: 'edge logic', sup: 'none stated' }, words: ['call a third-party entitlement API', 'one of two origins', 'only on cache misses'],
      expl: 'Network call + origin selection + only on misses → **Lambda@Edge, origin request trigger**. CloudFront Functions have viewer triggers only and no network access.', update: LE },

    /* ---------------- S3 website / TA ---------------- */
    { id: 'G2', src: 'New', line: 's3web',
      q: 'A company hosts www.example.com with S3 static website hosting. A security audit requires HTTPS with a certificate for www.example.com, and the bucket should no longer be publicly readable.',
      opts: [_o('Enable HTTPS on the S3 website endpoint with an ACM certificate.', 0, 'Website endpoints do not support HTTPS.'),
        _o('Put Global Accelerator in front of the bucket with a TLS listener.', 0, 'GA has TCP/UDP listeners, does not terminate TLS for your domain and cannot use S3 as an endpoint. Prestige distractor.'),
        _o('Enable S3 Transfer Acceleration, which uses HTTPS.', 0, 'Different endpoint name, still no certificate for your domain, still a public bucket.'),
        _o('Create a CloudFront distribution with an ACM certificate from us-east-1, use the bucket’s REST endpoint as the origin with origin access control, and point www.example.com at the distribution with an alias record.', 1, 'HTTPS on your domain at the edge; OAC lets the bucket stay private.')],
      stub: { what: 'static content', scope: 'global users', need: 'restrict access', sup: 'most secure' }, words: ['requires HTTPS', 'no longer be publicly readable'],
      expl: 'S3 website endpoints are **HTTP only** and public. HTTPS + private bucket → **CloudFront + ACM (us-east-1) + OAC** on the REST endpoint.',
      update: 'The S3 user guide now lists **AWS Amplify Hosting** as the recommended way to serve an S3 site over HTTPS, with CloudFront as the alternative. Banks answer CloudFront.' },
    { id: 'G24', src: 'New', line: 's3web',
      q: 'Field teams in Australia, Brazil and Japan upload 5–20 GB survey files every evening to a single S3 bucket in eu-west-1. Uploads over the public internet are slow and often have to be retried. The company wants faster uploads with minimal changes to the upload scripts.',
      opts: [_o('Enable S3 Transfer Acceleration on the bucket and change the scripts to use the s3-accelerate endpoint.', 1, 'Built for long-distance uploads into one bucket: enter at the nearest edge location, then the AWS network.'),
        _o('Create a CloudFront distribution in front of the bucket and upload through it.', 0, 'Possible with PUT allowed, but CloudFront is built to cache downloads; TA is the purpose-built, minimal-change answer.'),
        _o('Put Global Accelerator in front of the bucket.', 0, GA_NO_S3),
        _o('Replicate the bucket to buckets in each country with Cross-Region Replication.', 0, 'Replication copies data out of a bucket; it does not speed uploads into one.')],
      stub: { what: 'uploads to S3', scope: 'global users', need: 'faster transfer', sup: 'least ops' }, words: ['upload 5–20 GB survey files', 'single S3 bucket', 'faster uploads'],
      expl: 'WHAT = uploads to one bucket from far away → **S3 Transfer Acceleration** (plus multipart upload). This is the mirror image of Q4: downloads to many → CloudFront.' },

    /* ---------------- Global Accelerator (where it IS right) ---------------- */
    { id: 'G7', src: 'New', line: 'ga',
      q: 'A game studio runs its multiplayer servers on EC2 behind Network Load Balancers in us-west-2 and ap-northeast-1. The game uses UDP. Players worldwide need consistent low latency, the client must connect to two fixed IP addresses, and traffic must fail over to the other Region quickly if one Region fails.',
      opts: [_o('A CloudFront distribution with both NLBs as origins in an origin group.', 0, 'CloudFront speaks HTTP/HTTPS only; UDP game traffic cannot pass.'),
        _o('Route 53 latency records with health checks for both NLBs.', 0, 'No fixed IPs for the client, and failover waits for DNS caches.'),
        _o('Elastic IP addresses on the NLBs in both Regions, hard-coded in the client.', 0, 'Four regional IPs and client-side failover logic; no backbone entry near the player.'),
        _o('An accelerator in Global Accelerator with a UDP listener and one endpoint group per Region containing the NLB.', 1, 'Two static anycast IPs, UDP, nearest edge entry, and automatic Regional failover.')],
      stub: { what: 'non-HTTP TCP/UDP', scope: 'multi-Region active-active', need: 'static IP', sup: 'lowest latency' }, words: ['uses UDP', 'two fixed IP addresses', 'fail over to the other Region quickly'],
      expl: 'UDP + fixed IPs + fast Regional failover: the three things **Global Accelerator** was built for. This is where GA is the right answer.' },
    { id: 'G8', src: 'New', line: 'ga',
      q: 'Thousands of IoT devices connect over MQTT (TCP 8883) to brokers on EC2 in two Regions. The device firmware caches DNS answers for 24 hours and cannot be changed. When a Region fails, devices must reconnect to the healthy Region within a minute.',
      opts: [_o('Route 53 failover records with a 60-second TTL.', 0, 'The firmware ignores the TTL and keeps the old answer for 24 hours.'),
        _o('Global Accelerator with a TCP listener on 8883 and an endpoint group in each Region.', 1, 'The devices keep the same anycast IPs; GA moves new connections to the healthy Region in under a minute.'),
        _o('CloudFront with an origin group of the two brokers.', 0, 'MQTT over raw TCP is not HTTP; CloudFront cannot carry it.'),
        _o('Route 53 multivalue answer records for both Regions.', 0, 'Still DNS, still cached for 24 hours.')],
      stub: { what: 'non-HTTP TCP/UDP', scope: 'multi-Region active-passive', need: 'failover', sup: 'fastest failover' }, words: ['caches DNS answers for 24 hours', 'within a minute', 'MQTT'],
      expl: 'When clients cache DNS, DNS failover cannot beat their cache. **GA** keeps the IPs fixed and fails over behind them (“less than one minute”).' },
    { id: 'G9', src: 'New', line: 'ga',
      q: 'A payments API runs behind Application Load Balancers in us-east-1 and eu-west-1. Corporate customers must add the API’s IP addresses to their outbound firewall allowlists, and those addresses must never change, even when the company adds Regions.',
      opts: [_o('Assign Elastic IP addresses to both ALBs.', 0, 'ALBs cannot take Elastic IPs.'),
        _o('Publish the ALBs’ current IP addresses.', 0, 'ALB IPs change as the load balancer scales.'),
        _o('Create an accelerator in Global Accelerator with both ALBs as endpoints and give customers its two static IP addresses.', 1, 'Two static anycast IPs that stay the same as Regions and endpoints change behind them.'),
        _o('Use a CloudFront distribution and publish its edge IP ranges.', 0, 'Hundreds of changing ranges shared with other customers — not an allowlist.')],
      stub: { what: 'dynamic HTTP', scope: 'multi-Region active-active', need: 'static IP', sup: 'none stated' }, words: ['outbound firewall allowlists', 'must never change'],
      expl: 'Static IPs in front of ALBs in several Regions → **Global Accelerator**. (One Region only: an NLB with Elastic IPs in front of the ALB also works; CloudFront now offers anycast static IPs as an add-on, but banks answer GA.)' },
    { id: 'G26', src: 'New', line: 'ga',
      q: 'A VoIP provider must send each user to a specific session on a specific EC2 instance and port, chosen by its own matchmaking service, while still entering the AWS network at the edge location nearest the user.',
      opts: [_o('A standard accelerator with the instances as weighted endpoints.', 0, 'A standard accelerator load-balances across healthy endpoints; you cannot pin a user to one instance and port.'),
        _o('A custom routing accelerator with the VPC subnets as endpoints, mapping listener ports to instance IPs and ports.', 1, 'Built for this: deterministic mapping to a specific EC2 instance and port.'),
        _o('Route 53 multivalue answer records for all instances.', 0, 'Returns up to 8 IPs at random; no port mapping and no edge entry.'),
        _o('An NLB with one listener per session port.', 0, 'Regional, no edge entry, and ports do not map to users.')],
      stub: { what: 'non-HTTP TCP/UDP', scope: 'global users', need: 'static IP', sup: 'lowest latency' }, words: ['specific EC2 instance and port', 'its own matchmaking service'],
      expl: '“Specific instance and port” is the phrase for a **custom routing accelerator**. Endpoints are VPC subnets; only EC2 instances; traffic is denied until you allow it.' },

    /* ---------------- Route 53 ---------------- */
    { id: 'G3', src: 'New', line: 'r53',
      q: 'A web application runs behind ALBs in us-east-1, eu-west-1 and ap-southeast-1. Users should reach the Region with the lowest network latency. The company already hosts its DNS zone in Route 53, has no requirement for static IP addresses, and wants the most cost-effective solution.',
      opts: [_o('Route 53 latency-based records for the three ALBs with health checks (evaluate target health).', 1, 'DNS-level latency steering for a small per-query charge; unhealthy Regions drop out.'),
        _o('An accelerator in Global Accelerator with three endpoint groups.', 0, 'Works, but adds an hourly fee plus premium data transfer for a need DNS already covers. Prestige distractor.'),
        _o('Route 53 geolocation records by continent.', 0, 'Location is not latency; a user can be closer to another Region.'),
        _o('Route 53 weighted records at 33% each.', 0, 'Spreads traffic evenly, ignoring where users are.')],
      stub: { what: 'dynamic HTTP', scope: 'multi-Region active-active', need: 'DNS steering', sup: 'cheapest' }, words: ['lowest network latency', 'no requirement for static IP addresses', 'most cost-effective'],
      expl: 'Nothing here needs GA (no static IPs, HTTP, no DNS-caching problem). **Latency routing** is the purpose-built, cheapest answer.' },
    { id: 'G10', src: 'New', line: 'r53',
      q: 'A company moved its website to an Application Load Balancer. The domain example.com is hosted in Route 53. Users must reach the site at example.com (without www), and the company wants to avoid DNS query charges where possible.',
      opts: [_o('Create a CNAME record for example.com that points to the ALB’s DNS name.', 0, 'A CNAME cannot exist at the zone apex.'),
        _o('Create an A record for example.com with the ALB’s current IP addresses.', 0, 'ALB IPs change; the site would break.'),
        _o('Create an alias A record for example.com that targets the ALB.', 1, 'Alias works at the apex, follows the ALB’s changing IPs, and queries to AWS targets are free.'),
        _o('Create an NS record for example.com that points to the ALB.', 0, 'NS records delegate zones to name servers.')],
      stub: { what: 'DNS name', scope: 'one Region', need: 'DNS steering', sup: 'cheapest' }, words: ['example.com (without www)', 'avoid DNS query charges'],
      expl: 'Zone apex + AWS resource → **alias record**. Free for AWS targets, TTL comes from the target.' },
    { id: 'G11', src: 'New', line: 'r53',
      q: 'A team runs version 1 of an API behind one ALB and version 2 behind another ALB in the same Region. They want to send 10% of users to version 2, watch error rates, and increase the share gradually, using DNS.',
      opts: [_o('Weighted records with weights 90 and 10.', 1, 'Traffic splits in proportion to weight; change the weights to shift more.'),
        _o('Failover records with version 2 as secondary.', 0, 'Secondary gets traffic only when the primary fails.'),
        _o('Latency records for both ALBs.', 0, 'Same Region: latency cannot split them.'),
        _o('Global Accelerator endpoint groups with a traffic dial.', 0, 'Traffic dials are per Region; both ALBs are in one Region. (Endpoint weights exist, but the question asks for DNS.)')],
      stub: { what: 'DNS name', scope: 'one Region', need: 'DNS steering', sup: 'none stated' }, words: ['send 10% of users', 'increase the share gradually', 'using DNS'],
      expl: 'A percentage split in DNS → **weighted routing** (weights 0–255; 0 stops traffic).' },
    { id: 'G12', src: 'New', line: 'multi',
      q: 'A company runs its application in us-east-1 and keeps a scaled-down copy in us-west-2. If us-east-1 becomes unhealthy, traffic should go to us-west-2. A recovery time of several minutes is acceptable, the clients are ordinary browsers, and the company wants the lowest-cost solution.',
      opts: [_o('Global Accelerator with endpoint groups in both Regions and the us-west-2 traffic dial at 0%.', 0, 'Faster than needed and costs an hourly fee plus premium data transfer.'),
        _o('Route 53 multivalue answer records for both Regions.', 0, 'Returns both Regions to everyone: active-active, not active-passive.'),
        _o('CloudFront with an origin group of both Regions.', 0, 'Origin groups fail over only GET/HEAD/OPTIONS; a full application also POSTs.'),
        _o('Route 53 failover records: primary for us-east-1 with a health check, secondary for us-west-2, and a TTL of 60 seconds.', 1, 'Active-passive DNS failover; time ≈ health-check interval × threshold + TTL, well within minutes.')],
      stub: { what: 'dynamic HTTP', scope: 'multi-Region active-passive', need: 'failover', sup: 'cheapest' }, words: ['several minutes is acceptable', 'lowest-cost', 'scaled-down copy'],
      expl: 'Active-passive, minutes are fine, browsers respect TTLs, cheapest → **Route 53 failover** with a health check. With 30 s × 3 + 60 s TTL, users move in about 2.5 minutes.' },
    { id: 'G13', src: 'New', line: 'r53',
      q: 'Because of data-protection law, users in the European Union must always be served by the application in eu-central-1, users in the United States by us-east-1, and everyone else by us-east-1 as well.',
      opts: [_o('Latency-based records for both Regions.', 0, 'A European user could be sent to us-east-1 whenever it is measured faster.'),
        _o('Geoproximity records with a bias of +50 on eu-central-1.', 0, 'Bias grows an area by distance; it does not follow the EU border.'),
        _o('Geolocation records: Europe → eu-central-1, United States → us-east-1, and a Default record → us-east-1.', 1, 'Answers by the user’s location; Default catches everyone else.'),
        _o('Weighted records 50/50.', 0, 'Random split, ignores location.')],
      stub: { what: 'DNS name', scope: 'multi-Region active-active', need: 'DNS steering', sup: 'none stated' }, words: ['data-protection law', 'must always be served by', 'everyone else'],
      expl: 'A rule about where the user **is** → **geolocation**, with a **Default** record for unmatched locations (without it they get no answer).' },
    { id: 'G14', src: 'New', line: 'r53',
      q: 'An application runs in us-east-1 and us-west-2, and Route 53 sends users to the nearest Region by distance. The us-west-2 deployment was just doubled in size, and the team wants to move a larger geographic area of users to it without listing countries or states.',
      opts: [_o('Increase the TTL of the us-west-2 record.', 0, 'TTL controls caching, not who gets which answer.'),
        _o('Switch to latency-based routing.', 0, 'Latency cannot be told to prefer one Region.'),
        _o('Add a geolocation record for each additional state.', 0, 'The requirement says no lists of locations.'),
        _o('Use geoproximity routing and give the us-west-2 record a positive bias.', 1, 'Positive bias makes the Region look closer: biased distance = distance × (1 − bias/100).')],
      stub: { what: 'DNS name', scope: 'multi-Region active-active', need: 'DNS steering', sup: 'none stated' }, words: ['larger geographic area', 'without listing countries or states'],
      expl: '“Shift the area served” → **geoproximity bias** (+1…+99 grows, −1…−99 shrinks).', update: 'Geoproximity records can be created directly in the Route 53 console since January 2024; older material says Traffic Flow only.' },
    { id: 'G15', src: 'New', line: 'r53',
      q: 'A small service runs on six EC2 instances with public IP addresses and no load balancer. The team wants DNS to return several healthy instance IPs to each client so clients can retry another one, and to stop returning an instance that fails its health check.',
      opts: [_o('Multivalue answer records, one per instance, each with a health check.', 1, 'Returns up to 8 healthy records per query, randomly chosen.'),
        _o('A simple record with the six IP addresses.', 0, 'Simple routing returns all values and cannot use health checks.'),
        _o('Failover records for the six instances.', 0, 'Failover has one primary and one secondary.'),
        _o('Latency records for the six instances.', 0, 'All in one Region: latency does not distinguish them, and it returns one answer.')],
      stub: { what: 'DNS name', scope: 'one Region', need: 'DNS steering', sup: 'none stated' }, words: ['several healthy instance IPs', 'fails its health check'],
      expl: '“Several healthy IPs, client-side retry” → **multivalue answer** (up to 8 healthy). It is not a load balancer.' },
    { id: 'G16', src: 'New', line: 'r53',
      q: 'A primary database proxy in a private subnet (private IP only) must be monitored so that a Route 53 failover record switches to a standby when the proxy becomes unhealthy.',
      opts: [_o('Create a Route 53 HTTP health check against the proxy’s private IP address.', 0, 'Route 53 health checkers are on the internet and cannot reach private IPs.'),
        _o('Create a Route 53 calculated health check with no child checks.', 0, 'A calculated check needs child checks to combine.'),
        _o('Enable “evaluate target health” on a simple record.', 0, 'Only alias records to AWS resources can evaluate target health.'),
        _o('Publish a CloudWatch metric for the proxy, create an alarm on it, and create a Route 53 health check based on the CloudWatch alarm state.', 1, 'Alarm-based health checks work for resources the health checkers cannot reach.')],
      stub: { what: 'DNS name', scope: 'multi-Region active-passive', need: 'failover', sup: 'none stated' }, words: ['private IP only', 'becomes unhealthy'],
      expl: 'Private resource → **CloudWatch-alarm health check**. The three types: endpoint, calculated, CloudWatch alarm.' },
    { id: 'G17', src: 'New', line: 'r53',
      q: 'EC2 instances in three VPCs must resolve internal names such as db.corp.internal to private IP addresses. The names must not be resolvable from the internet. Which actions should a solutions architect take? (Select TWO.)',
      opts: [_o('Create a Route 53 private hosted zone for corp.internal and associate it with the three VPCs.', 1, 'Answers only inside associated VPCs.'),
        _o('Create a public hosted zone and restrict it with a bucket policy.', 0, 'Public zones answer the whole internet; bucket policies are for S3.'),
        _o('Enable DNS hostnames and DNS resolution (enableDnsHostnames, enableDnsSupport) on each VPC.', 1, 'Both must be on for private hosted zones to resolve.'),
        _o('Create an alias record for each instance.', 0, 'EC2 instances are not alias targets.'),
        _o('Create an accelerator so the names get static IPs.', 0, 'Nothing to do with DNS resolution. Prestige distractor.')],
      stub: { what: 'DNS name', scope: 'one Region', need: 'DNS steering', sup: 'most secure' }, words: ['three VPCs', 'must not be resolvable from the internet'],
      expl: '**Private hosted zone** associated with the VPCs + **enableDnsHostnames and enableDnsSupport**. (To share DNS setup across many accounts, Route 53 Profiles now exist.)' },
    { id: 'G27', src: 'New', line: 'r53',
      q: 'A video platform has a partnership with two internet service providers. Viewers coming from each ISP’s published IP ranges must be sent to an edge cache deployment inside that ISP’s network; everyone else goes to the default deployment.',
      opts: [_o('Geolocation records by country.', 0, 'Both ISPs operate in the same countries; location does not identify the ISP.'),
        _o('Latency records.', 0, 'Latency does not know which ISP a viewer uses.'),
        _o('IP-based routing with a CIDR collection for each ISP’s ranges and a default location.', 1, 'Answers by the resolver or client subnet’s IP range.'),
        _o('Weighted records by ISP market share.', 0, 'Random split, not by ISP.')],
      stub: { what: 'DNS name', scope: 'global users', need: 'DNS steering', sup: 'none stated' }, words: ['published IP ranges', 'everyone else'],
      expl: 'Routing by the client’s **IP range** → **IP-based routing** (CIDR collections; add a default “*” location). Public hosted zones only.' }
  ];
})();
