/* Session 4 drills (Global architecture & edge). stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit.
   Q4, Q53 and Q43 are his baseline-exam misses (mine: true). G-drills are new.
   Prestige drills where Global Accelerator is tempting and wrong: G1 G2 G3 G4 G5 G24.
   Drills where Global Accelerator IS right: G7 G8 G9 G26.
   Options are written to the same length, each distractor wrong by one detail; the engine shuffles order. */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _o = (t, ok, why) => ({ t, ok: !!ok, why });
  const GA_NO_S3 = 'Global Accelerator endpoints are ALBs, NLBs, EC2 instances and Elastic IPs. S3 is not one, and GA caches nothing.';
  const LE = 'Lambda@Edge quotas now show 30 s and 50 MB for every trigger; older material says 5 s / 1 MB for viewer triggers. The viewer-only / all-four-triggers split is unchanged.';
  S.drills = [
    /* ---------------- his exam misses ---------------- */
    { id: 'Q4', src: 'Exam Q4', line: 'cf', mine: true, tag: 'C',
      q: 'A software company stores installation packages of 1–3 GB in an Amazon S3 bucket in us-east-1. Customers in Europe, Asia and South America download the same packages many times a day and complain that downloads are slow. The company wants to improve download performance for all customers in the most cost-effective way, without changing how the packages are stored. What should a solutions architect recommend?',
      opts: [_o('Enable S3 Transfer Acceleration on the bucket and give customers download links that use the bucket’s s3-accelerate endpoint.', 0, 'Speeds each transfer over the AWS network but caches nothing: every download still comes from us-east-1 and pays the acceleration fee. This was your pick.'),
        _o('Create a CloudFront distribution with the bucket as origin, protect it with origin access control, and publish the CloudFront links.', 1, 'The same objects are cached at edge locations near every customer; repeat downloads never reach the bucket.'),
        _o('Create an accelerator in Global Accelerator with the bucket as its endpoint and give customers the accelerator’s two static IP addresses.', 0, GA_NO_S3),
        _o('Replicate the bucket to eu-west-1, ap-south-1 and sa-east-1 with S3 Cross-Region Replication and steer customers with latency records.', 0, 'Changes how the packages are stored and pays for three more copies plus replication — not the most cost-effective.')],
      stub: { what: 'static content', scope: 'global users', need: 'cache', sup: 'cheapest' }, words: ['download the same packages many times a day', 'improve download performance', 'most cost-effective'],
      expl: 'WHAT = static files, SCOPE = global users, NEED = cache (the same objects many times). CloudFront caches at the edge. Transfer Acceleration is for long-distance transfers into or out of one bucket with no cache — the tempting look-alike.' },
    { id: 'Q53', src: 'Exam Q53', line: 's3web', mine: true, tag: 'F',
      q: 'A company registered the domain example.com with Amazon Route 53 and wants to host a static marketing website on Amazon S3 at http://example.com. The site must be served directly from S3 static website hosting with the least operational overhead. Which combination of steps meets these requirements?',
      opts: [_o('Create a bucket named example-com-site, enable static website hosting with public read, and add an alias A record for example.com to its website endpoint.', 0, 'The website endpoint answers only for a bucket whose name matches the host name, so the bucket must be named example.com.'),
        _o('Create a bucket named example.com, enable static website hosting with public read, and add a CNAME record for example.com to its website endpoint.', 0, 'example.com is the zone apex, and a CNAME cannot exist at the apex.'),
        _o('Create a bucket named example.com, keep Block Public Access on, and add an alias A record for example.com that targets the bucket’s REST endpoint.', 0, 'The REST endpoint is not website hosting and is not a Route 53 alias target; with Block Public Access on, nobody can read the site.'),
        _o('Create a bucket named example.com, enable static website hosting with public read, and add an alias A record for example.com to its website endpoint.', 1, 'Bucket name = domain, public read for the website endpoint, and an alias record at the apex.')],
      stub: { what: 'static content', scope: 'one Region', need: 'DNS steering', sup: 'least ops' }, words: ['static website hosting', 'http://example.com', 'registered the domain example.com with Amazon Route 53'],
      expl: 'Facts to know cold: the **bucket name must equal the domain** (example.com), the website endpoint is **public and HTTP only**, and at the zone apex you use an **alias A record** to the website endpoint. HTTPS would need CloudFront in front.' },
    { id: 'Q43', src: 'Exam Q43', line: 'alb', mine: true, tag: 'K',
      q: 'A company runs several microservices as Amazon ECS services in one AWS Region. Clients call a single domain. Requests for /orders/* must reach the order service, requests for /users/* the user service, and requests to admin.example.com the admin service. The company wants path-based and host-based routing with the least operational overhead. Which solution meets these requirements?',
      opts: [_o('Put one Network Load Balancer in front of the services, with a separate TCP listener and target group for each ECS service.', 0, 'An NLB works at layer 4: it sees ports, not URL paths or host names.'),
        _o('Give each service its own Application Load Balancer, and use Route 53 records to send /orders/*, /users/* and admin traffic to the right one.', 0, 'DNS resolves names; it never sees the URL path. Three load balancers also add operational overhead.'),
        _o('Put one Application Load Balancer in front, with path-pattern and host-header listener rules that forward to each service’s target group.', 1, 'Path and host conditions are exactly what ALB listener rules do.'),
        _o('Create one accelerator in Global Accelerator, with a listener and an endpoint group for each of the three ECS services behind it.', 0, 'GA proxies TCP/UDP to endpoints by port and Region; it does not route by path or host name. Prestige distractor.')],
      stub: { what: 'dynamic HTTP', scope: 'one Region', need: 'path routing', sup: 'least ops' }, words: ['path-based and host-based routing', '/orders/*', 'admin.example.com'],
      expl: 'The keyword was **path-based / host-based routing** → ALB listener rules to target groups. Route 53 cannot see paths, an NLB is layer 4, and Global Accelerator is a prestige distractor here.' },

    /* ---------------- CloudFront ---------------- */
    { id: 'G1', src: 'New', line: 'cf',
      q: 'A news website runs on EC2 instances behind an Application Load Balancer in eu-west-1. Most pages are images and articles that change a few times a day; a small API returns personalised data for each signed-in reader. Readers are worldwide, and the company wants to reduce latency and the load on the web servers. Which solution meets these requirements?',
      opts: [_o('Create an accelerator in Global Accelerator with the ALB as its endpoint, so readers enter the AWS network at the nearest edge location.', 0, 'GA shortens the network path but caches nothing, so every request still hits the web servers. Prestige distractor.'),
        _o('Add an ElastiCache (Redis OSS) cluster in eu-west-1 that the web servers use to cache rendered articles, images and API responses.', 0, 'Offloads the web servers, but readers on other continents still cross the internet to eu-west-1 for every page.'),
        _o('Create a CloudFront distribution with the ALB as origin, caching images and articles, and an API behaviour with caching disabled.', 1, 'Cacheable content is served from the edge; the API still benefits from the AWS network path.'),
        _o('Create a CloudFront distribution with the ALB as origin and one default behaviour that caches every path, the API included, for 24 hours.', 0, 'Caches personalised API responses and serves one reader’s data to others.')],
      stub: { what: 'static content', scope: 'global users', need: 'cache', sup: 'none stated' }, words: ['change a few times a day', 'reduce latency and the load on the web servers', 'worldwide'],
      expl: 'Mostly cacheable content, global readers, and origin load → CloudFront, with the personalised API on its own behaviour that does not cache. GA would speed the path to the ALB but never offload it; a cache in eu-west-1 offloads but stays far away.' },
    { id: 'G5', src: 'New', line: 'cf',
      q: 'A media company streams on-demand video from an S3 bucket to millions of viewers on several continents. Egress from the bucket and request load on S3 are growing fast. The company wants better playback start times and lower costs. Which solution meets these requirements MOST cost-effectively?',
      opts: [_o('Create an accelerator in Global Accelerator with the bucket as its endpoint, so viewers reach the video over the AWS global network.', 0, GA_NO_S3),
        _o('Serve the video through CloudFront with the bucket as origin, the default cache policy, and Origin Shield in the bucket’s Region.', 1, 'Edge caching serves repeat views; Origin Shield collapses cache misses so S3 sees far fewer requests.'),
        _o('Enable S3 Transfer Acceleration on the bucket and point the video player at the bucket’s s3-accelerate endpoint for every request.', 0, 'No caching: every view is a full transfer from S3, with an extra per-GB acceleration fee.'),
        _o('Serve the video through CloudFront with the bucket as origin and legacy cache settings that forward all viewer headers.', 0, 'Forwarding all headers turns caching off for that behaviour, so every view still goes to S3.')],
      stub: { what: 'static content', scope: 'global users', need: 'cache', sup: 'cheapest' }, words: ['millions of viewers on several continents', 'request load on S3', 'lower costs'],
      expl: 'Popular objects, many viewers → cache them. CloudFront cuts both latency and S3 egress/requests; Origin Shield reduces origin fetches further. Forwarding all headers turns the cache off.' },
    { id: 'G6', src: 'New', line: 'cf',
      q: 'A single-page application is served through CloudFront from S3 with a 24-hour TTL. The team deploys new JavaScript bundles up to 20 times a day and users must get the new version immediately after each deploy. The team wants the most cost-effective approach that does not reduce the cache hit ratio.',
      opts: [_o('After every deploy, create a CloudFront invalidation for /* so each edge location fetches the new bundles from S3.', 0, 'Invalidations take time to propagate and empty the whole cache, so the next requests all go to S3 — the hit ratio drops.'),
        _o('Set the default, minimum and maximum TTL to 0 seconds so CloudFront revalidates every object with S3 on every request.', 0, 'Every request goes back to S3: the hit ratio collapses.'),
        _o('Give every bundle a versioned file name such as app.3f9c.js with a long TTL, and give only index.html a short TTL.', 1, 'New names are cache misses by definition; old names keep their long TTL. Nothing to invalidate.'),
        _o('Enable S3 Versioning and upload each bundle under the same key, so CloudFront always serves the object’s newest version.', 0, 'S3 object versions are invisible to CloudFront’s cache key; the old copy stays cached for 24 hours.')],
      stub: { what: 'static content', scope: 'global users', need: 'cache', sup: 'cheapest' }, words: ['up to 20 times a day', 'immediately after each deploy', 'does not reduce the cache hit ratio'],
      expl: 'Frequent changes → **versioned file names**. Invalidations are for the occasional mistake: the first 1,000 paths a month are free (a wildcard counts as one), and they empty the cache.' },
    { id: 'G18', src: 'New', line: 'cf',
      q: 'A static website is delivered by CloudFront from an S3 bucket in us-east-1. The bucket is replicated to eu-west-1 with S3 Cross-Region Replication. If the primary bucket returns server errors, viewers must keep receiving content automatically without a DNS change. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('Create a second distribution for the eu-west-1 replica and a Route 53 failover record that switches to it when the first is unhealthy.', 0, 'Failover happens by changing the DNS answer, which the requirement rules out, and adds a second distribution to run.'),
        _o('Create an accelerator in Global Accelerator with an endpoint group in each Region for the two buckets, and use it as the origin.', 0, GA_NO_S3),
        _o('Add the eu-west-1 replica as a second origin with its own /* cache behaviour, listed after the behaviour for the primary bucket.', 0, 'Behaviours pick an origin by path, first match wins; a second /* behaviour is never reached and never fails over on errors.'),
        _o('Create an origin group with the us-east-1 bucket as primary and the replica as secondary, failing over on 500, 502, 503 and 504.', 1, 'CloudFront retries the secondary origin for GET/HEAD requests when the primary returns the chosen codes.')],
      stub: { what: 'static content', scope: 'multi-Region active-passive', need: 'failover', sup: 'least ops' }, words: ['server errors', 'without a DNS change', 'Cross-Region Replication'],
      expl: '“Without a DNS change” + reads from a replicated bucket → **CloudFront origin group**. Failover happens per request for GET, HEAD (and OPTIONS if cached); status codes you can pick include 400, 403, 404, 416, 429, 500, 502, 503, 504.' },
    { id: 'G21', src: 'New', line: 'cf',
      q: 'A company serves app.example.com through CloudFront. The origin ALB is in eu-central-1, where the team requested a public certificate for app.example.com in AWS Certificate Manager; its status is Issued. When they edit the distribution, the certificate does not appear in the custom SSL certificate list. What should they do?',
      opts: [_o('Request or import a certificate for app.example.com in ACM in us-east-1 and select it as the distribution’s custom certificate.', 1, 'CloudFront only uses ACM certificates from us-east-1 (N. Virginia).'),
        _o('Switch the distribution from SNI to dedicated IP custom SSL, which lets it use ACM certificates from the origin’s Region.', 0, 'Changes how the certificate is served (and costs $600 a month), not which Region it comes from.'),
        _o('Share the eu-central-1 certificate with the CloudFront service principal through AWS RAM, then reselect it on the distribution.', 0, 'AWS RAM does not share ACM certificates with CloudFront; the viewer certificate must live in us-east-1.'),
        _o('Add an alias record for app.example.com that targets the distribution, then wait for ACM to list the certificate for CloudFront.', 0, 'DNS records do not make a certificate visible to CloudFront; the Region does.')],
      stub: { what: 'dynamic HTTP', scope: 'global users', need: 'restrict access', sup: 'none stated' }, words: ['eu-central-1', 'does not appear in the custom SSL certificate list'],
      expl: 'CloudFront is global and reads certificates from ACM in **us-east-1** only. The ALB keeps its own regional certificate for the origin connection.' },

    /* ---------------- edge security ---------------- */
    { id: 'G4', src: 'New', line: 'protect',
      q: 'A streaming service delivers video through CloudFront from origins in ap-southeast-2. Licensing contracts forbid delivery to viewers in three countries. The company wants to enforce this with the least operational overhead. Which solution meets these requirements?',
      opts: [_o('Turn on CloudFront geographic restrictions for the distribution, with a blocklist that contains the three countries.', 1, 'Built for this: country-level blocklist at the edge, returns 403, no extra service to run.'),
        _o('Create Route 53 geolocation records that return no answer for the three countries and a default record for all other viewers.', 0, 'DNS steers; it is not access control. Anyone using another resolver, or the CloudFront domain directly, still gets the video.'),
        _o('Create an AWS WAF web ACL in ap-southeast-2 with a geo match rule for the three countries and associate it with the distribution.', 0, 'A web ACL for CloudFront must be created with CLOUDFRONT scope in us-east-1; a regional one cannot be associated. Geo restriction is also less to run.'),
        _o('Put Global Accelerator in front of the distribution and add listener rules that drop traffic from the three countries’ IP ranges.', 0, 'GA cannot use CloudFront as an endpoint and has no country rules. Prestige distractor.')],
      stub: { what: 'static content', scope: 'global users', need: 'restrict access', sup: 'least ops' }, words: ['forbid delivery to viewers in three countries', 'least operational overhead'],
      expl: 'Country rule on content → **CloudFront geo restriction** (allowlist or blocklist). AWS WAF geo match rules also work when you need more conditions, but a CloudFront web ACL lives in us-east-1. DNS routing is not access control.' },
    { id: 'G19', src: 'New', line: 'protect',
      q: 'A company serves a private S3 bucket through CloudFront. The bucket uses SSE-KMS with a customer managed key, and the bucket was created in a Region launched in 2024. Direct access to the bucket must be blocked so objects are reachable only through the distribution. Which solution meets these requirements?',
      opts: [_o('Create an origin access identity, grant it s3:GetObject in the bucket policy, and grant it kms:Decrypt on the customer managed key.', 0, 'OAI is legacy: it does not support SSE-KMS or Regions launched after January 2023.'),
        _o('Create an origin access control and allow the CloudFront service principal for this distribution in the bucket policy and key policy.', 1, 'OAC signs requests with SigV4, works in all Regions and supports SSE-KMS.'),
        _o('Keep the bucket public, have CloudFront send a secret Referer header, and allow only requests that carry it in the bucket policy.', 0, 'Anonymous requests cannot read SSE-KMS objects, and a Referer value is easily copied — the bucket is still reachable directly.'),
        _o('Require CloudFront signed URLs from a trusted key group for every object, and keep a bucket policy that allows public s3:GetObject.', 0, 'Signed URLs control viewers at CloudFront; a public bucket can still be read directly.')],
      stub: { what: 'static content', scope: 'global users', need: 'restrict access', sup: 'none stated' }, words: ['SSE-KMS', 'reachable only through the distribution', 'launched in 2024'],
      expl: 'Bucket only via CloudFront → **OAC**. OAI is the legacy mechanism and fails on SSE-KMS and newer Regions.' },
    { id: 'G20', src: 'New', line: 'protect',
      q: 'An e-learning site on CloudFront has a members’ area with hundreds of videos and PDFs. Only paying members may access them, and the existing URLs used in the site’s HTML and in bookmarks must not change. Which solution meets these requirements?',
      opts: [_o('Generate a CloudFront signed URL for each file at login, signed with a trusted key group, and require signed requests on that behaviour.', 0, 'Works per file, but every URL changes — the requirement says they must not.'),
        _o('Restrict the bucket with origin access control and block public access, so the files are reachable only through the members’ behaviour.', 0, 'Stops people bypassing CloudFront, but anyone can still fetch the files through CloudFront.'),
        _o('Attach an AWS WAF web ACL with a rule that lets requests into the members’ path only when they carry the site’s session cookie.', 0, 'WAF can match a cookie name or value but cannot verify it; a copied or invented cookie passes.'),
        _o('Issue CloudFront signed cookies at login, signed with a trusted key group, and require signed requests on the members’ behaviour.', 1, 'Many files, URLs unchanged: exactly what signed cookies are for.')],
      stub: { what: 'static content', scope: 'global users', need: 'restrict access', sup: 'none stated' }, words: ['hundreds of videos and PDFs', 'must not change'],
      expl: 'Signed URL = one file (or clients without cookies). **Signed cookies** = many files, keep URLs. Sign with a **trusted key group**, not a root-account key pair.' },
    { id: 'G25', src: 'New', line: 'protect',
      q: 'An internet-facing Application Load Balancer is the origin of a CloudFront distribution. Attackers are bypassing CloudFront and its AWS WAF rules by calling the ALB’s DNS name directly. Which actions ensure the ALB serves only requests that come through CloudFront? (Select TWO.)',
      opts: [_o('Allow inbound HTTPS in the ALB security group only from the AWS-managed prefix list for CloudFront origin-facing servers.', 1, 'Only CloudFront’s origin-facing IPs can connect.'),
        _o('Attach an origin access control to the ALB origin, and allow only the CloudFront service principal in the ALB’s resource policy.', 0, 'OAC signs requests to S3, Lambda function URLs and MediaStore/MediaPackage origins, not ALBs; ALBs have no resource policy.'),
        _o('Have CloudFront add a secret custom header to origin requests, and add ALB listener rules that forward only requests carrying it.', 1, 'Proves the request passed through your distribution, not just any CloudFront distribution.'),
        _o('Put Global Accelerator in front of the ALB, make the accelerator the distribution’s origin, and remove the ALB’s public listener.', 0, 'GA adds another public entry point with static IPs anyone can call; it does not restrict the ALB to CloudFront.'),
        _o('Associate the same AWS WAF web ACL with the ALB as well, adding a rate-based rule that limits requests from any single IP address.', 0, 'A CloudFront-scope web ACL cannot be attached to an ALB, and a rate limit still serves direct requests.')],
      stub: { what: 'dynamic HTTP', scope: 'one Region', need: 'restrict access', sup: 'none stated' }, words: ['bypassing CloudFront', 'only requests that come through CloudFront'],
      expl: 'The classic pair: **CloudFront prefix list** in the ALB security group + a **secret origin header** checked by an ALB rule (or WAF). Since Nov 2024 a **VPC origin** can go further: a private ALB with no internet exposure at all.',
      update: 'CloudFront **VPC origins** (GA Nov 2024) let CloudFront reach an internal ALB, NLB or EC2 instance in private subnets. Banks still expect the prefix list + custom header answer.' },

    /* ---------------- edge code ---------------- */
    { id: 'G22', src: 'New', line: 'edge',
      q: 'A retailer’s CloudFront distribution receives tens of millions of requests a day. The team must add HSTS and other security headers to every response and redirect legacy /shop/ URLs to /store/. The logic needs no external calls. The team wants the lowest cost and latency. Which solution meets these requirements?',
      opts: [_o('Lambda@Edge functions on the viewer request event for the redirects and on the viewer response event for the headers.', 0, 'Works, but Lambda@Edge costs more per request and is slower than CloudFront Functions for logic this small.'),
        _o('CloudFront Functions on the viewer request event for the redirects and on the viewer response event for the headers.', 1, 'Lightweight header and URL work at the edge, sub-millisecond, built for millions of requests.'),
        _o('CloudFront Functions on the origin request event for the redirects and on the origin response event for the headers.', 0, 'CloudFront Functions run only on viewer events; there is no origin request or origin response trigger for them.'),
        _o('An AWS WAF web ACL on the distribution that inserts the security headers and blocks /shop/ with a custom 301 response.', 0, 'WAF custom header insertion adds headers to the request sent to the origin, not to the response the viewer gets.')],
      stub: { what: 'dynamic HTTP', scope: 'global users', need: 'edge logic', sup: 'cheapest' }, words: ['tens of millions of requests a day', 'needs no external calls', 'lowest cost'],
      expl: 'Header/redirect logic, viewer events, no network → **CloudFront Functions**. (A managed response headers policy could add the headers without code.)' },
    { id: 'G23', src: 'New', line: 'edge',
      q: 'Before CloudFront fetches content from the origin, a function must call a third-party entitlement API over HTTPS and, depending on the answer, send the request to one of two origins. The function must run only on cache misses. Which solution meets these requirements?',
      opts: [_o('CloudFront Functions on the origin request event, calling the entitlement API and setting the origin from its answer.', 0, 'CloudFront Functions have viewer triggers only and no network access.'),
        _o('Lambda@Edge on the viewer request event, calling the entitlement API and setting the origin from its answer.', 0, 'Viewer request runs on every request, cache hits included, not only on misses.'),
        _o('Lambda@Edge on the origin request event, calling the entitlement API and setting the origin from its answer.', 1, 'Origin request runs only on cache misses, has network access and can change the origin.'),
        _o('Lambda@Edge on the origin response event, calling the entitlement API and setting the origin from its answer.', 0, 'Origin response runs after the origin has already answered — too late to choose the origin.')],
      stub: { what: 'dynamic HTTP', scope: 'global users', need: 'edge logic', sup: 'none stated' }, words: ['call a third-party entitlement API', 'one of two origins', 'only on cache misses'],
      expl: 'Network call + origin selection + only on misses → **Lambda@Edge, origin request trigger**. CloudFront Functions have viewer triggers only and no network access.', update: LE },

    /* ---------------- S3 website / TA ---------------- */
    { id: 'G2', src: 'New', line: 's3web',
      q: 'A company hosts www.example.com with S3 static website hosting. A security audit requires HTTPS with a certificate for www.example.com, and the bucket should no longer be publicly readable. Which solution meets these requirements?',
      opts: [_o('Request an ACM certificate for www.example.com in the bucket’s Region and attach it to the bucket’s static website endpoint.', 0, 'S3 website endpoints do not support HTTPS at all.'),
        _o('Create a CloudFront distribution with an ACM certificate from us-east-1 and the bucket’s website endpoint as a custom origin.', 0, 'HTTPS works, but the website endpoint only serves public objects and cannot use OAC, so the bucket stays public.'),
        _o('Create an accelerator in Global Accelerator with a TCP 443 listener and the bucket as its endpoint, and point www at its IPs.', 0, 'GA does not terminate TLS for your domain and cannot use S3 as an endpoint. Prestige distractor.'),
        _o('Create a CloudFront distribution with an ACM certificate from us-east-1 and the bucket’s REST endpoint as origin, using OAC.', 1, 'HTTPS on your domain at the edge; OAC lets the bucket stay private.')],
      stub: { what: 'static content', scope: 'global users', need: 'restrict access', sup: 'none stated' }, words: ['requires HTTPS', 'no longer be publicly readable'],
      expl: 'S3 website endpoints are **HTTP only** and public. HTTPS + private bucket → **CloudFront + ACM (us-east-1) + OAC** on the REST endpoint, with an alias record for www.example.com.',
      update: 'The S3 user guide now lists **AWS Amplify Hosting** as the recommended way to serve an S3 site over HTTPS, with CloudFront as the alternative. Banks answer CloudFront.' },
    { id: 'G24', src: 'New', line: 's3web',
      q: 'Field teams in Australia, Brazil and Japan upload 5–20 GB survey files every evening to a single S3 bucket in eu-west-1. Uploads over the public internet are slow and often have to be retried. The company wants faster uploads with minimal changes to the upload scripts. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('Enable S3 Transfer Acceleration on the bucket and point the upload scripts at the bucket’s s3-accelerate endpoint.', 1, 'Built for long-distance uploads into one bucket: enter at the nearest edge location, then the AWS network.'),
        _o('Create a CloudFront distribution with the bucket as origin, allow PUT, and have the scripts upload through the distribution.', 0, 'Can carry PUTs, but needs signed origin requests and a new upload path; Transfer Acceleration is the one-setting answer.'),
        _o('Create an accelerator in Global Accelerator with the bucket as its endpoint and have the scripts upload to its static IPs.', 0, GA_NO_S3),
        _o('Create a bucket in each team’s country and replicate all three into the eu-west-1 bucket with S3 Cross-Region Replication.', 0, 'Uploads get faster, but three more buckets, replication rules and per-team scripts are far more to run.')],
      stub: { what: 'uploads to S3', scope: 'global users', need: 'faster transfer', sup: 'least ops' }, words: ['upload 5–20 GB survey files', 'single S3 bucket', 'faster uploads'],
      expl: 'WHAT = uploads to one bucket from far away → **S3 Transfer Acceleration** (plus multipart upload). This is the mirror image of Q4: downloads to many → CloudFront.' },

    /* ---------------- Global Accelerator (where it IS right) ---------------- */
    { id: 'G7', src: 'New', line: 'ga',
      q: 'A game studio runs its multiplayer servers on EC2 behind Network Load Balancers in us-west-2 and ap-northeast-1. The game uses UDP. Players worldwide need consistent low latency, the client must connect to two fixed IP addresses, and traffic must fail over to the other Region quickly if one Region fails. Which solution meets these requirements?',
      opts: [_o('A CloudFront distribution with both NLBs in an origin group, and CloudFront anycast static IPs configured for the client.', 0, 'CloudFront carries HTTP(S), WebSocket and gRPC — not UDP game traffic.'),
        _o('Route 53 latency records with health checks for both NLBs, and an Elastic IP address on each NLB for the client.', 0, 'The client gets one IP per NLB subnet in each Region, not two fixed ones, and failover waits for DNS caches.'),
        _o('A custom routing accelerator with a UDP listener and the game servers’ VPC subnets in each Region as its endpoints.', 0, 'Custom routing maps ports to specific instances chosen by your own logic; it does not use the NLBs or fail over between Regions for you.'),
        _o('A standard accelerator in Global Accelerator with a UDP listener and an endpoint group per Region that holds its NLB.', 1, 'Two static anycast IPs, UDP, nearest edge entry, and automatic Regional failover.')],
      stub: { what: 'non-HTTP TCP/UDP', scope: 'multi-Region active-active', need: 'static IP', sup: 'none stated' }, words: ['uses UDP', 'two fixed IP addresses', 'fail over to the other Region quickly'],
      expl: 'UDP + fixed IPs + fast Regional failover: the three things **Global Accelerator** was built for. A standard accelerator in front of the NLBs; custom routing is only for pinning users to an instance and port.' },
    { id: 'G8', src: 'New', line: 'ga',
      q: 'Thousands of IoT devices connect over MQTT (TCP 8883) to brokers on EC2 in two Regions. The device firmware caches DNS answers for 24 hours and cannot be changed. When a Region fails, devices must reconnect to the healthy Region within a minute. Which solution meets these requirements?',
      opts: [_o('Route 53 failover records for the two Regions’ brokers, with 10-second health checks and a 60-second TTL.', 0, 'The firmware ignores the TTL and keeps the old answer for 24 hours.'),
        _o('Global Accelerator with a TCP listener on port 8883 and an endpoint group in each Region for its brokers.', 1, 'The devices keep the same anycast IPs; GA moves new connections to the healthy Region in under a minute.'),
        _o('CloudFront with an origin group of both Regions’ brokers, failing over on 502, 503 and 504 responses.', 0, 'MQTT over raw TCP is not HTTP; CloudFront cannot carry it.'),
        _o('Route 53 multivalue answer records for both Regions’ brokers, each with its own 10-second health check.', 0, 'Still DNS, still cached in the firmware for 24 hours.')],
      stub: { what: 'non-HTTP TCP/UDP', scope: 'multi-Region active-passive', need: 'failover', sup: 'none stated' }, words: ['caches DNS answers for 24 hours', 'within a minute', 'MQTT'],
      expl: 'When clients cache DNS, DNS failover cannot beat their cache. **GA** keeps the IPs fixed and fails over behind them (“less than one minute”).' },
    { id: 'G9', src: 'New', line: 'ga',
      q: 'A payments API runs behind Application Load Balancers in us-east-1 and eu-west-1. Corporate customers must add the API’s IP addresses to their outbound firewall allowlists, and those addresses must never change, even when the company adds Regions. Which solution meets these requirements?',
      opts: [_o('Put an NLB with an Elastic IP per subnet in front of each Region’s ALB, and publish those addresses to customers.', 0, 'Static per Region, but every new Region adds new addresses that customers must allowlist.'),
        _o('Allocate Elastic IP addresses for the subnets of both ALBs, and publish those addresses to the customers.', 0, 'ALBs cannot take Elastic IPs; their addresses change as they scale.'),
        _o('Create an accelerator in Global Accelerator with both ALBs as endpoints, and publish its two static IPs.', 1, 'Two static anycast IPs that stay the same as Regions and endpoints change behind them.'),
        _o('Put a CloudFront distribution in front of both ALBs, and publish CloudFront’s IP ranges to the customers.', 0, 'Hundreds of ranges, shared with other customers and updated by AWS — not a fixed allowlist.')],
      stub: { what: 'dynamic HTTP', scope: 'multi-Region active-active', need: 'static IP', sup: 'none stated' }, words: ['outbound firewall allowlists', 'must never change'],
      expl: 'Static IPs in front of ALBs in several Regions → **Global Accelerator**. (One Region only: an NLB with Elastic IPs in front of the ALB also works; CloudFront now offers anycast static IPs as an add-on, but banks answer GA.)' },
    { id: 'G26', src: 'New', line: 'ga',
      q: 'A VoIP provider must send each user to a specific session on a specific EC2 instance and port, chosen by its own matchmaking service, while still entering the AWS network at the edge location nearest the user. Which solution meets these requirements?',
      opts: [_o('A standard accelerator with a UDP listener and the instances as endpoints, using weights to pin users to instances.', 0, 'Weights set proportions across healthy endpoints; you cannot pin a user to one instance and port.'),
        _o('A custom routing accelerator with VPC subnets as endpoints, mapping listener ports to instance IPs and ports.', 1, 'Built for this: deterministic mapping to a specific EC2 instance and port.'),
        _o('A standard accelerator with client affinity set to source IP, so each user keeps reaching the same instance.', 0, 'Affinity keeps a user on whatever endpoint GA picked; the matchmaking service cannot choose it.'),
        _o('Route 53 multivalue answer records for every instance, with the matchmaking service sending the port.', 0, 'DNS returns random healthy IPs with no edge entry; it cannot direct a user to one instance.')],
      stub: { what: 'non-HTTP TCP/UDP', scope: 'global users', need: 'static IP', sup: 'none stated' }, words: ['specific EC2 instance and port', 'its own matchmaking service'],
      expl: '“Specific instance and port” is the phrase for a **custom routing accelerator**. Endpoints are VPC subnets; only EC2 instances; traffic is denied until you allow it.' },

    /* ---------------- Route 53 ---------------- */
    { id: 'G3', src: 'New', line: 'r53',
      q: 'A web application runs behind ALBs in us-east-1, eu-west-1 and ap-southeast-1. Users should reach the Region with the lowest network latency. The company already hosts its DNS zone in Route 53, has no requirement for static IP addresses, and wants the most cost-effective solution.',
      opts: [_o('Route 53 latency-based alias records for the three ALBs, with evaluate target health turned on.', 1, 'DNS-level latency steering for no extra service; alias queries to ALBs are free and unhealthy Regions drop out.'),
        _o('An accelerator in Global Accelerator with an endpoint group in each Region holding its ALB.', 0, 'Works, but adds an hourly fee plus premium data transfer for a need DNS already covers. Prestige distractor.'),
        _o('Route 53 geolocation alias records that map each continent to an ALB, plus a Default record.', 0, 'Location is not latency; a user can be faster to a Region on another continent.'),
        _o('Route 53 geoproximity alias records for the three ALBs, with a bias of 0 on every Region.', 0, 'Geoproximity uses map distance, not measured network latency.')],
      stub: { what: 'dynamic HTTP', scope: 'multi-Region active-active', need: 'DNS steering', sup: 'cheapest' }, words: ['lowest network latency', 'no requirement for static IP addresses', 'most cost-effective'],
      expl: 'Nothing here needs GA (no static IPs, HTTP, no DNS-caching problem). **Latency routing** is the purpose-built, cheapest answer.' },
    { id: 'G10', src: 'New', line: 'r53',
      q: 'A company moved its website to an Application Load Balancer. The domain example.com is hosted in Route 53. Users must reach the site at example.com (without www), and the company wants to avoid DNS query charges where possible. Which record should be created?',
      opts: [_o('A CNAME record for example.com that points to the ALB’s DNS name, with a TTL of 300 seconds.', 0, 'A CNAME cannot exist at the zone apex.'),
        _o('An A record for example.com that lists the ALB’s current IP addresses, with a TTL of 60 seconds.', 0, 'ALB IPs change as it scales; the site would break.'),
        _o('An A record for example.com with the two static IPs of a Global Accelerator in front of the ALB.', 0, 'Works at the apex, but standard A record queries are charged and the accelerator adds an hourly fee.'),
        _o('An alias A record for example.com that targets the ALB, with evaluate target health turned on.', 1, 'Alias works at the apex, follows the ALB’s changing IPs, and queries to AWS targets are free.')],
      stub: { what: 'DNS name', scope: 'one Region', need: 'DNS steering', sup: 'cheapest' }, words: ['example.com (without www)', 'avoid DNS query charges'],
      expl: 'Zone apex + AWS resource → **alias record**. Free for AWS targets, TTL comes from the target.' },
    { id: 'G11', src: 'New', line: 'r53',
      q: 'A team runs version 1 of an API behind one ALB and version 2 behind another ALB in the same Region. They want to send 10% of users to version 2, watch error rates, and increase the share gradually, using DNS. Which solution meets these requirements?',
      opts: [_o('Weighted alias records for the two ALBs with weights of 90 and 10, raised as errors stay low.', 1, 'Traffic splits in proportion to weight; change the weights to shift more.'),
        _o('Failover alias records with the version 1 ALB as primary and the version 2 ALB as secondary.', 0, 'The secondary gets traffic only when the primary fails, never a share.'),
        _o('Latency-based alias records for the two ALBs, with a health check on the version 2 ALB.', 0, 'Both ALBs are in the same Region, so latency cannot split users between them.'),
        _o('A Global Accelerator endpoint group with both ALBs and the version 2 traffic dial at 10%.', 0, 'A traffic dial applies to a whole Region’s endpoint group, not to one ALB — and this is not DNS.')],
      stub: { what: 'DNS name', scope: 'one Region', need: 'DNS steering', sup: 'none stated' }, words: ['send 10% of users', 'increase the share gradually', 'using DNS'],
      expl: 'A percentage split in DNS → **weighted routing** (weights 0–255; 0 stops traffic).' },
    { id: 'G12', src: 'New', line: 'multi',
      q: 'A company runs its application in us-east-1 and keeps a scaled-down copy in us-west-2. If us-east-1 becomes unhealthy, traffic should go to us-west-2. A recovery time of several minutes is acceptable, the clients are ordinary browsers, and the company wants the lowest-cost solution.',
      opts: [_o('A Global Accelerator accelerator with an endpoint group in each Region, each holding that Region’s ALB.', 0, 'Fails over faster than needed, for an hourly fee plus premium data transfer — not lowest cost.'),
        _o('Route 53 multivalue answer records for both Regions’ ALBs, each with a 30-second health check.', 0, 'Returns both Regions to everyone: active-active onto the scaled-down copy, not active-passive.'),
        _o('A CloudFront distribution with an origin group of both Regions’ ALBs, failing over on 5xx codes.', 0, 'Origin groups fail over only GET, HEAD and OPTIONS; the application’s POSTs and PUTs would fail.'),
        _o('Route 53 failover alias records: primary to us-east-1 with a health check, secondary to us-west-2.', 1, 'Active-passive DNS failover; time ≈ health-check interval × threshold + TTL, well within minutes.')],
      stub: { what: 'dynamic HTTP', scope: 'multi-Region active-passive', need: 'failover', sup: 'cheapest' }, words: ['several minutes is acceptable', 'lowest-cost', 'scaled-down copy'],
      expl: 'Active-passive, minutes are fine, browsers respect TTLs, cheapest → **Route 53 failover** with a health check. With 30 s × 3 + 60 s TTL, users move in about 2.5 minutes.' },
    { id: 'G13', src: 'New', line: 'r53',
      q: 'Because of data-protection law, users in the European Union must always be served by the application in eu-central-1, users in the United States by us-east-1, and everyone else by us-east-1 as well. Each Region has its own ALB. Which Route 53 configuration meets these requirements?',
      opts: [_o('Latency-based alias records for both Regions’ ALBs, each with evaluate target health turned on.', 0, 'A European user is sent to us-east-1 whenever it measures faster.'),
        _o('Geoproximity records for both Regions, with a bias of +50 on the eu-central-1 record to cover Europe.', 0, 'Bias grows an area by distance; it does not follow the EU border.'),
        _o('Geolocation records: Europe to eu-central-1 and United States to us-east-1, with no Default record.', 0, 'Users outside Europe and the US match no record and get no answer.'),
        _o('Geolocation records: Europe to eu-central-1, United States to us-east-1, and Default to us-east-1.', 1, 'Answers by the user’s location; Default catches everyone else.')],
      stub: { what: 'DNS name', scope: 'multi-Region active-active', need: 'DNS steering', sup: 'none stated' }, words: ['data-protection law', 'must always be served by', 'everyone else'],
      expl: 'A rule about where the user **is** → **geolocation**, with a **Default** record for unmatched locations (without it they get no answer).' },
    { id: 'G14', src: 'New', line: 'r53',
      q: 'An application runs in us-east-1 and us-west-2, and Route 53 geoproximity records send users to the nearest Region by distance. The us-west-2 deployment was just doubled in size, and the team wants to move a larger geographic area of users to it without listing countries or states. What should the team do?',
      opts: [_o('Give the us-west-2 geoproximity record a positive bias, such as +25, and leave us-east-1 at 0.', 1, 'Positive bias makes the Region look closer: biased distance = distance × (1 − bias/100).'),
        _o('Give the us-west-2 geoproximity record a negative bias, such as −25, and leave us-east-1 at 0.', 0, 'Negative bias shrinks the area a Region serves — the opposite of what is needed.'),
        _o('Replace both records with latency-based records, so the larger us-west-2 fleet attracts users.', 0, 'Latency measures the network path, not fleet size; it cannot be told to prefer one Region.'),
        _o('Add geolocation records for the central states that point to us-west-2, and keep the rest.', 0, 'The requirement says no lists of countries or states.')],
      stub: { what: 'DNS name', scope: 'multi-Region active-active', need: 'DNS steering', sup: 'none stated' }, words: ['larger geographic area', 'without listing countries or states'],
      expl: '“Shift the area served” → **geoproximity bias** (+1…+99 grows, −1…−99 shrinks).', update: 'Geoproximity records can be created directly in the Route 53 console since January 2024; older material says Traffic Flow only.' },
    { id: 'G15', src: 'New', line: 'r53',
      q: 'A small service runs on six EC2 instances with public IP addresses and no load balancer. The team wants DNS to return several healthy instance IPs to each client so clients can retry another one, and to stop returning an instance that fails its health check. Which routing policy meets these requirements?',
      opts: [_o('Multivalue answer records, one per instance IP, each with its own health check.', 1, 'Returns up to 8 healthy records per query, randomly chosen.'),
        _o('A simple record that lists all six instance IPs, with a health check on the record.', 0, 'Simple routing returns every value but cannot use health checks.'),
        _o('Weighted records with equal weights, one per instance IP, each with a health check.', 0, 'Weighted routing returns one answer per query, so the client has nothing to retry.'),
        _o('Latency-based records, one per instance IP, each with its own health check attached.', 0, 'All in one Region: latency does not distinguish them, and it returns one answer.')],
      stub: { what: 'DNS name', scope: 'one Region', need: 'DNS steering', sup: 'none stated' }, words: ['several healthy instance IPs', 'fails its health check'],
      expl: '“Several healthy IPs, client-side retry” → **multivalue answer** (up to 8 healthy). It is not a load balancer.' },
    { id: 'G16', src: 'New', line: 'r53',
      q: 'A primary database proxy in a private subnet (private IP only) must be monitored so that a Route 53 failover record switches to a standby when the proxy becomes unhealthy. Which health check setup works?',
      opts: [_o('A Route 53 HTTP health check against the proxy’s private IP address, with a 10-second interval.', 0, 'Route 53 health checkers are on the internet and cannot reach private IPs.'),
        _o('A Route 53 calculated health check that is healthy while at least one endpoint check on the proxy passes.', 0, 'The child endpoint checks still cannot reach a private IP, so the calculated check has nothing true to combine.'),
        _o('Evaluate target health turned on for a failover record whose value is the proxy’s private IP address.', 0, 'Only alias records to AWS resources can evaluate target health.'),
        _o('A CloudWatch alarm on a metric the proxy publishes, and a Route 53 health check on that alarm’s state.', 1, 'Alarm-based health checks work for resources the health checkers cannot reach.')],
      stub: { what: 'DNS name', scope: 'multi-Region active-passive', need: 'failover', sup: 'none stated' }, words: ['private IP only', 'becomes unhealthy'],
      expl: 'Private resource → **CloudWatch-alarm health check**. The three types: endpoint, calculated, CloudWatch alarm.' },
    { id: 'G17', src: 'New', line: 'r53',
      q: 'EC2 instances in three VPCs must resolve internal names such as db.corp.internal to private IP addresses. The names must not be resolvable from the internet. Which actions should a solutions architect take? (Select TWO.)',
      opts: [_o('Create a Route 53 private hosted zone for corp.internal and associate it with all three VPCs.', 1, 'Answers only inside associated VPCs.'),
        _o('Create a Route 53 public hosted zone for corp.internal and allow queries only from the VPC CIDRs.', 0, 'Public zones answer the whole internet; they have no source-IP restriction.'),
        _o('Turn on the enableDnsHostnames and enableDnsSupport attributes on each of the three VPCs.', 1, 'Both must be on for private hosted zones to resolve.'),
        _o('Create a VPC Resolver outbound endpoint in each VPC with a forwarding rule for corp.internal.', 0, 'Outbound endpoints forward queries to DNS servers outside AWS; here nothing outside holds the names.'),
        _o('Create an accelerator in Global Accelerator so each internal name maps to a static IP address.', 0, 'Nothing to do with DNS resolution. Prestige distractor.')],
      stub: { what: 'DNS name', scope: 'one Region', need: 'DNS steering', sup: 'none stated' }, words: ['three VPCs', 'must not be resolvable from the internet'],
      expl: '**Private hosted zone** associated with the VPCs + **enableDnsHostnames and enableDnsSupport**. (To share DNS setup across many accounts, Route 53 Profiles now exist.)' },
    { id: 'G27', src: 'New', line: 'r53',
      q: 'A video platform has a partnership with two internet service providers. Viewers coming from each ISP’s published IP ranges must be sent to an edge cache deployment inside that ISP’s network; everyone else goes to the default deployment. Which Route 53 routing policy meets these requirements?',
      opts: [_o('Geolocation records by country for the two ISPs’ markets, with a Default record for everyone else.', 0, 'Both ISPs operate in the same countries; location does not identify the ISP.'),
        _o('IP-based routing with a CIDR collection for each ISP’s ranges and a default location for everyone else.', 1, 'Answers by the resolver or client subnet’s IP range.'),
        _o('Latency-based records for the two ISP deployments and the default deployment, with health checks.', 0, 'Latency does not know which ISP a viewer uses; an ISP’s viewer can be sent elsewhere.'),
        _o('Geoproximity records for each ISP deployment, with a positive bias so that ISP’s viewers stay inside it.', 0, 'Bias grows an area on the map; it does not follow an ISP’s IP ranges.')],
      stub: { what: 'DNS name', scope: 'global users', need: 'DNS steering', sup: 'none stated' }, words: ['published IP ranges', 'everyone else'],
      expl: 'Routing by the client’s **IP range** → **IP-based routing** (CIDR collections; add a default “*” location). Public hosted zones only.' }
  ];
})();
