/* Session 5 trigger cards (Security services & identity). f = what the exam says, b = the answer. line = transit line id or topic.
   Cards marked mine come from his prestige-distractor pattern (ACM, Network Firewall) — src 'Exam pattern'. */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _c = (id, line, f, b, why, tempt, extra) => Object.assign({ id, line, f, b, why, tempt }, extra || {});
  const MINE = { mine: true, src: 'Exam pattern' };
  S.cards = [
    /* KMS · CloudHSM */
    _c('c01', 'kms', 'Encrypt data at rest with a key you control, audit every use, disable it any time', 'Customer managed KMS key', 'Your key policy, CloudTrail logs every call, disable or schedule deletion yourself.', 'ACM — certificates protect data in transit only.', MINE),
    _c('c02', 'kms', 'Three kinds of KMS key', 'AWS owned · AWS managed (aws/service) · customer managed', 'Owned: invisible, free. Managed: visible, legacy, yearly rotation, no policy edits, no cross-account. Customer managed: full control, $1/month.', '“All KMS keys are the same, only names differ.”', { update: 'AWS managed keys are a legacy type, no longer created for new services since 2021; new services default to AWS owned keys.' }),
    _c('c03', 'kms', 'Encrypt a 2 GB file with a KMS key', 'Envelope encryption: GenerateDataKey, encrypt locally, store the encrypted data key', 'KMS Encrypt takes at most 4 KB of plaintext; the data key does the bulk work.', 'Call Encrypt on the file, or in 4 KB chunks.'),
    _c('c04', 'kms', 'IAM policy allows kms:Decrypt but the call is denied', 'The key policy does not allow it', 'Every KMS key has exactly one key policy; IAM policies work only if the key policy lets them (the default key policy does).', 'Add more IAM permissions.'),
    _c('c05', 'kms', 'Rotate a customer managed key every 90 days automatically', 'Enable automatic rotation with a 90-day period', 'Period 90–2,560 days (default 365); same key ID, old material kept for decryption. On-demand rotation also exists.', 'New key + alias switch every 90 days via Lambda.', { update: 'Configurable period and on-demand rotation since April 2024 (older material: yearly only).' }),
    _c('c06', 'kms', 'How long before a scheduled KMS key deletion happens', '7–30 days waiting period (default 30); cancel any time before', 'Pending Deletion keys fail every call. After the window the key material is gone and so is the data.', '“Deleted immediately.”'),
    _c('c07', 'kms', 'Decrypt in another Region without calling the original Region', 'KMS multi-Region keys', 'Same key ID and key material in each Region; each replica is an independent regional key.', '“KMS keys are global.”'),
    _c('c08', 'kms', 'Dedicated HSMs, only your admins manage keys, AWS has no access', 'AWS CloudHSM', 'Single-tenant, FIPS 140-3 Level 3 (hsm2m.medium); cluster 2+ HSMs across AZs for HA.', 'KMS — FIPS 140-3 L3 too, but multi-tenant and AWS-operated.'),
    _c('c09', 'kms', 'KMS integration with S3/EBS/RDS but keys in your own CloudHSM', 'KMS custom key store backed by CloudHSM', 'Services still call KMS; key material lives in your cluster. Symmetric keys only.', 'Rewrite the services to call CloudHSM.'),
    _c('c10', 'kms', 'KMS ThrottlingException under heavy load', 'Request quota shared per account per Region: cut calls (Bucket Keys, data key caching) or raise the quota', 'Symmetric operations: 10,000/s default, 20,000 or 100,000/s in larger Regions.', 'Create more keys to spread the load.', { update: 'Quotas were 5,500 / 10,000 / 30,000–50,000 per second in older material.' }),
    /* encryption at rest */
    _c('c11', 'rest', 'S3 encryption applied when you do nothing', 'SSE-S3 (since January 2023, every new object)', 'S3-managed keys, no cost, no key audit.', '“S3 objects are unencrypted by default.”', { update: 'Default encryption for all new objects since 5 Jan 2023.' }),
    _c('c12', 'rest', 'S3 encryption with key-use audit and separate key permissions', 'SSE-KMS (+ S3 Bucket Keys to cut KMS calls up to 99%)', 'KMS key policy is a second gate; CloudTrail logs decrypts.', 'SSE-S3.'),
    _c('c13', 'rest', 'Company keeps its own keys; AWS must never store them; upload to S3', 'SSE-C (HTTPS only) — or client-side encryption', 'S3 uses the key for the request and stores only a salted HMAC of it.', 'SSE-KMS with imported key material — KMS stores it.', { update: 'SSE-C is blocked on new buckets since April 2026 until you allow it with PutBucketEncryption.' }),
    _c('c14', 'rest', 'Require TLS for every request to a bucket', 'Bucket policy: Deny when aws:SecureTransport is false', 'Encryption in transit is a policy condition; default encryption covers rest only.', 'Enable SSE-KMS.'),
    _c('c15', 'rest', 'Encrypt an existing unencrypted RDS instance', 'Snapshot → copy with encryption (KMS key) → restore → switch the app', 'RDS encryption is chosen at creation only; replicas match the source.', 'Modify the instance and tick “encryption”.'),
    _c('c16', 'rest', 'Share an encrypted EBS or RDS snapshot with another account', 'Re-encrypt with a customer managed key, allow the account in the key policy, share the snapshot', 'AWS managed keys (aws/ebs, aws/rds) cannot be shared.', 'Add the account ID to a snapshot encrypted with aws/ebs.'),
    /* secrets */
    _c('c17', 'secrets', 'Database password must rotate automatically, least ops', 'AWS Secrets Manager (managed rotation)', 'No Lambda needed for RDS, Aurora, DocumentDB, Redshift; custom Lambda for others; every 4 h at the shortest.', 'Parameter Store SecureString — no rotation.'),
    _c('c18', 'secrets', 'Hundreds of configuration values, cheapest', 'SSM Parameter Store standard parameters (free)', 'Up to 10,000 per Region, 4 KB each; SecureString uses KMS.', 'Secrets Manager — $0.40 per secret per month.'),
    _c('c19', 'secrets', 'Parameter bigger than 4 KB, or needs an expiry date', 'Parameter Store advanced tier', '8 KB, up to 100,000 parameters, parameter policies; $0.05 per parameter per month; cannot go back to standard.', 'Secrets Manager.'),
    _c('c20', 'secrets', 'Same secret, current value, in the DR Region', 'Secrets Manager replica secret', 'Rotation on the primary updates replicas; a replica can be promoted.', 'KMS multi-Region key — that is the key, not the secret.'),
    _c('c21', 'secrets', 'Let RDS create and rotate the master user password', 'RDS integration with Secrets Manager (ManageMasterUserPassword)', 'RDS generates, stores and rotates the password in Secrets Manager.', 'Store it in the CloudFormation template.'),
    /* ACM */
    _c('c22', 'acm', 'HTTPS on an ALB with no manual renewals', 'ACM public certificate, DNS validation', 'Free; ACM renews DNS-validated certificates in use automatically.', 'Import a third-party certificate — never renewed by ACM.', Object.assign({ update: 'Public certificates are valid 198 days and renew 45 days before expiry (was 13 months / 60 days).' }, MINE)),
    _c('c23', 'acm', 'Imported certificate about to expire — get warned', 'EventBridge ACM “Certificate Approaching Expiration” event (or Config rule acm-certificate-expiration-check)', 'Events daily from 45 days before expiry (configurable); you must re-import.', 'ACM managed renewal.'),
    _c('c24', 'acm', 'TLS certificates for internal names (*.corp.internal)', 'AWS Private CA (+ ACM private certificates)', '$400 per CA per month general-purpose; $50 in short-lived mode (certs ≤ 7 days).', 'Public ACM certificates — public CAs cannot sign private names.'),
    _c('c25', 'acm', 'Certificate for a CloudFront custom domain', 'ACM certificate in us-east-1', 'CloudFront reads certificates from N. Virginia only; other services use their own Region.', 'Certificate in the ALB’s Region.'),
    /* WAF · Shield · Firewall Manager */
    _c('c26', 'edge', 'SQL injection and XSS against an ALB or CloudFront', 'AWS WAF with managed rule groups (SQL database, core rule set)', 'Layer-7 rules on HTTP requests at the entry point.', 'Network Firewall — VPC traffic inspection, your recorded prestige pick.', MINE),
    _c('c27', 'edge', 'One IP sends too many requests to /login', 'WAF rate-based rule (scope-down to the path)', 'Limit from 10 requests per 1, 2, 5 or 10 minutes; action Block, CAPTCHA, Challenge or Count.', 'Shield Advanced.', { update: 'Older material: minimum 100 per fixed 5 minutes.' }),
    _c('c28', 'edge', 'Resources AWS WAF can protect', 'CloudFront, ALB, API Gateway REST, AppSync, Cognito user pool, App Runner, Verified Access, Amplify', 'Not NLB, not EC2 directly, not API Gateway HTTP APIs.', 'A Network Load Balancer.'),
    _c('c29', 'edge', 'DDoS experts on call + refund of scaling costs from an attack', 'AWS Shield Advanced', '$3,000/month per org, 1-year commitment; SRT needs Business or Enterprise Support.', 'Shield Standard — free, but no team, no cost protection.'),
    _c('c30', 'edge', 'Free DDoS protection you do not enable', 'AWS Shield Standard', 'Common L3/L4 attacks, for every AWS customer.', 'Shield Advanced.'),
    _c('c31', 'edge', 'Same WAF / security group rules in every account of an Organization, new accounts included', 'AWS Firewall Manager', 'Needs Organizations + AWS Config; also Shield Advanced, NACL, Network Firewall and DNS Firewall policies.', 'Security Hub — reports, does not enforce.'),
    /* Network Firewall */
    _c('c32', 'nfw', 'VPC egress only to approved domains, with IPS', 'AWS Network Firewall (stateful domain list + Suricata rules)', 'Firewall subnets per AZ, or native Transit Gateway attachment (2025).', 'Security groups — IPs only, no domains.', Object.assign({ update: 'Native TGW attachment since mid-2025: no inspection VPC to build.' }, MINE)),
    _c('c33', 'nfw', 'Block one malicious CIDR from a subnet, cheapest', 'NACL deny rule (Session 3)', 'Free, stateless, numbered rules. Network Firewall is for stateful inspection at scale.', 'Network Firewall.', MINE),
    /* detection */
    _c('c34', 'detect', 'Detect crypto mining, credential misuse, calls from malicious IPs', 'Amazon GuardDuty', 'Reads CloudTrail, VPC Flow Logs and DNS logs on its own; findings → EventBridge. Detects, never blocks.', 'Inspector.', { update: 'Extended Threat Detection (Dec 2024): attack sequence findings, on by default.' }),
    _c('c35', 'detect', 'Root cause and blast radius of a GuardDuty finding', 'Amazon Detective', 'Behaviour graph over up to a year of CloudTrail, flow logs and findings.', 'Security Hub — aggregates, does not investigate.'),
    _c('c36', 'scan', 'CVEs in EC2, ECR images and Lambda, continuously', 'Amazon Inspector', 'Agent (SSM) or agentless hybrid scanning for EC2; rescans when new CVEs appear.', 'GuardDuty.', { update: 'Inspector Classic ended 20 May 2026.' }),
    _c('c37', 'scan', 'Find PII in S3 buckets', 'Amazon Macie', 'S3 only; managed and custom data identifiers; automated discovery samples every bucket.', 'GuardDuty S3 Protection — watches access, not contents.'),
    _c('c38', 'hub', 'One view of findings from all accounts and Regions + CIS / PCI checks', 'AWS Security Hub (CSPM) with a delegated admin and an aggregation Region', 'Controls run on AWS Config rules — Config must be on.', 'Detective.', { update: 'Renamed Security Hub CSPM; the new AWS Security Hub (GA Dec 2025) adds correlated exposure findings in OCSF.' }),
    /* Cognito */
    _c('c39', 'cognito', 'Sign-up and sign-in for app users, social login, MFA, JWT', 'Cognito user pool', 'Managed login pages; ALB and API Gateway can check its tokens.', 'Identity pool — no user directory.'),
    _c('c40', 'cognito', 'App users (or guests) call S3 or DynamoDB directly', 'Cognito identity pool → temporary AWS credentials', 'Exchanges a user pool / social token (or nothing, for guests) for an IAM role’s STS credentials.', 'IAM users with access keys in the app.')
  ];
})();
