/* Session 5 drills (Security services & identity). stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit.
   Options are written to the same size, each distractor a plausible design that breaks on one detail; the engine shuffles them.
   S1–S5 come from his prestige-distractor pattern (mine: true, src 'Exam pattern', tag 'C'): ACM, Network Firewall and
   Shield Advanced tempting and wrong (S1 S2 S3), ACM and Network Firewall genuinely right (S4 S5).
   Other drills where a prestige service is a wrong option: S7 S18 S20 S21 S23 S24 S26 S29.
   Where it is right: S20 S21 (ACM / Private CA), S22 (Shield Advanced), S24 (Firewall Manager), S25 (GuardDuty), S29 (Security Hub). */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _o = (t, ok, why) => ({ t, ok: !!ok, why });
  const ACM_REST = 'ACM issues TLS certificates for data in transit. It never encrypts data at rest — prestige distractor.';
  const NFW_L7 = 'Network Firewall inspects traffic crossing VPC boundaries; it does not sit in front of an ALB’s HTTP requests with managed SQLi rules the way WAF does — prestige distractor.';
  const ROT = 'Older material: KMS rotation was fixed at one year, so a shorter period meant a new key and an alias switch. Since April 2024 the period is configurable (90–2,560 days) and on-demand rotation exists.';
  S.drills = [
    /* ---------------- the prestige pattern (his record) ---------------- */
    { id: 'S1', src: 'Exam pattern', line: 'kms', mine: true, tag: 'C',
      q: 'A company stores customer contracts in an Amazon S3 bucket. A new policy requires that the objects are encrypted at rest with a key the security team controls, that every use of the key is recorded for audit, and that the key can be disabled at any time. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('Set SSE-KMS with the AWS managed key aws/s3 as the bucket’s default encryption, and review key use in CloudTrail.', 0, 'CloudTrail does log aws/s3 use, but an AWS managed key’s policy cannot be edited and the key cannot be disabled.'),
        _o('Create a customer managed KMS key and set it as the bucket’s default SSE-KMS key, with S3 Bucket Keys enabled.', 1, 'The team owns the key policy and can disable the key; CloudTrail logs every use. Bucket Keys keep the KMS request cost down.'),
        _o('Request a private certificate in AWS Certificate Manager and set it as the key for the bucket’s default encryption.', 0, ACM_REST + ' A certificate cannot be the key for bucket encryption.'),
        _o('Create a KMS key in a CloudHSM custom key store and set it as the bucket’s default SSE-KMS key with Bucket Keys.', 0, 'Meets control, audit and disable, but the team now runs a CloudHSM cluster — more work than a standard KMS key.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'least ops' }, words: ['encrypted at rest', 'every use of the key is recorded', 'can be disabled at any time', 'LEAST operational overhead'],
      expl: 'ASSET = data at rest, MODE = prevent, SUP = least ops. “Key the team controls + audit + disable” = **customer managed KMS key** with SSE-KMS. aws/s3 fails on “disable” (an AWS managed key is visible, not controllable); a CloudHSM custom key store works but adds a cluster to run. ACM appears because “encryption” sounds like certificates; it only protects data **in transit**. Cross it out on the ASSET slot.' },
    { id: 'S2', src: 'Exam pattern', line: 'edge', mine: true, tag: 'C',
      q: 'An e-commerce application runs on EC2 instances behind an Application Load Balancer. The security team sees SQL injection and cross-site scripting attempts in the application logs. The company wants to block these requests before they reach the instances. Which solution meets this requirement with the LEAST operational overhead?',
      opts: [_o('Deploy AWS Network Firewall in the ALB’s VPC with stateful Suricata rules written to match SQL injection and XSS strings.', 0, NFW_L7 + ' You would also write and maintain the signatures yourself.'),
        _o('Subscribe to AWS Shield Advanced, protect the ALB, and turn on automatic application layer DDoS mitigation for it.', 0, 'Shield Advanced mitigates DDoS floods; injection attempts are not a volume attack. $3,000 a month for the wrong job.'),
        _o('Create an AWS WAF web ACL with the AWS managed core rule set and SQL database rule groups, and associate it with each EC2 instance.', 0, 'Right rules, wrong place: a web ACL cannot be associated with EC2 instances, only with entry points such as the ALB.'),
        _o('Create an AWS WAF web ACL with the AWS managed core rule set and SQL database rule groups, and associate it with the ALB.', 1, 'AWS names these two for SQLi (SQL database) and XSS (core rule set); maintained by AWS, evaluated on every HTTP request at the ALB.')],
      stub: { asset: 'web requests', layer: 'entry point', mode: 'prevent', sup: 'least ops' }, words: ['SQL injection and cross-site scripting', 'Application Load Balancer', 'before they reach the instances'],
      expl: 'SQLi and XSS live inside **HTTP requests** → **WAF** at the entry point (ALB). A web ACL attaches to the ALB, never to instances. Network Firewall is your recorded prestige pick: it filters traffic between networks with IPS signatures and domain lists, and it is not the managed answer for web exploits at an ALB.' },
    { id: 'S3', src: 'Exam pattern', line: 'edge', mine: true, tag: 'C',
      q: 'A company’s login API behind Amazon API Gateway (REST) receives thousands of password guesses per minute from a small number of IP addresses. Legitimate users log in a few times a day. The company wants to stop the abuse in the MOST cost-effective way.',
      opts: [_o('Associate an AWS WAF web ACL with the API stage, with a rate-based rule per source IP scoped down to the login path.', 1, 'Each IP above the limit in the evaluation window is blocked; normal users never reach it. A few dollars a month.'),
        _o('Subscribe to AWS Shield Advanced and ask the Shield Response Team to write custom rules that block the attacking IPs.', 0, 'Shield Advanced costs $3,000 a month with a one-year commitment and is built for DDoS; a few IPs guessing passwords is not a DDoS.'),
        _o('Enable Amazon GuardDuty and route brute-force findings through EventBridge to a Lambda function that updates a network ACL.', 0, 'API Gateway’s endpoint is not in your subnets, so a NACL never sees these requests; GuardDuty itself only detects.'),
        _o('Set API Gateway stage throttling for the login method to a rate of 10 requests per second and a burst of 20.', 0, 'Stage throttling limits the method for all clients together: legitimate users get 429 errors while the attackers keep their share.')],
      stub: { asset: 'web requests', layer: 'entry point', mode: 'prevent', sup: 'cheapest' }, words: ['thousands of password guesses per minute', 'small number of IP addresses', 'most cost-effective'],
      expl: 'One noisy client per IP → **WAF rate-based rule** (minimum limit 10, window 1–10 minutes), scoped down to the login path. API Gateway throttling is per method, not per client. Shield Advanced is the prestige pick that sounds strongest and costs most.',
      update: 'Rate-based rules now allow limits from **10** requests and windows of **60, 120, 300 or 600 s** (older material: minimum 100 per 5 minutes).' },
    { id: 'S4', src: 'Exam pattern', line: 'acm', mine: true, tag: 'C',
      q: 'A company exposes a web application at shop.example.com through an internet-facing Application Load Balancer in eu-west-1. The domain’s DNS is in Amazon Route 53. Customers must connect over HTTPS, and the operations team does not want to track or renew certificates manually. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('Request a public ACM certificate for shop.example.com in us-east-1 with DNS validation, and attach it to the ALB’s HTTPS listener.', 0, 'ACM certificates are regional: an ALB in eu-west-1 can only use a certificate from eu-west-1. us-east-1 is the CloudFront rule.'),
        _o('Request a public ACM certificate for shop.example.com in eu-west-1 with email validation, and attach it to the ALB’s HTTPS listener.', 0, 'Email-validated certificates need someone to act on the renewal emails; DNS-validated ones renew with nobody involved.'),
        _o('Request a public ACM certificate for shop.example.com in eu-west-1 with DNS validation, and attach it to the ALB’s HTTPS listener.', 1, 'Free, in the ALB’s own Region, and ACM renews DNS-validated certificates automatically while they are in use.'),
        _o('Buy a certificate for shop.example.com from a third-party CA, import it into ACM in eu-west-1, and attach it to the listener.', 0, 'Works, but ACM never renews imported certificates: someone must re-import before every expiry.')],
      stub: { asset: 'TLS certificates', layer: 'entry point', mode: 'prevent', sup: 'least ops' }, words: ['over HTTPS', 'does not want to track or renew certificates manually'],
      expl: 'Here ACM is **genuinely the answer**: ASSET = TLS certificates, and ACM-issued, **DNS-validated** public certificates renew automatically. The certificate must be in the **same Region as the ALB** (us-east-1 only for CloudFront). The prestige test is not “never pick ACM”, it is “pick ACM only when there is a certificate to issue”.',
      update: 'ACM public certificates are now valid for **198 days** (older material: 13 months) and renew **45 days** before expiry (was 60). Automatic renewal still needs the DNS validation CNAME in place.' },
    { id: 'S5', src: 'Exam pattern', line: 'nfw', mine: true, tag: 'C',
      q: 'A company runs workloads in private subnets of 15 VPCs connected by a transit gateway. Outbound internet traffic must be allowed only to a list of approved software-update domains, all other outbound connections must be blocked and logged, and known malware signatures must be detected with intrusion prevention. Which solution meets these requirements?',
      opts: [_o('Security groups on each workload that allow outbound HTTPS only to the update domains’ resolved IP addresses, with VPC Flow Logs.', 0, 'Security groups know IPs, not domain names, cannot run IPS signatures, and the update servers’ IPs change.'),
        _o('AWS Network Firewall attached to the transit gateway, with a stateful domain allow list, Suricata IPS rules and alert logs.', 1, 'Domain filtering on Host/SNI, stateful IPS and flow/alert logs for every VPC in one place.'),
        _o('Route 53 Resolver DNS Firewall in every VPC, with an allow list of the update domains, a block-all rule and query logging.', 0, 'Filters DNS lookups only: no IPS signatures, and a connection made straight to an IP address never asks DNS.'),
        _o('An AWS WAF web ACL with a string match allow list of the update domains, associated with each VPC’s NAT gateway.', 0, 'WAF attaches to web entry points (CloudFront, ALB, API Gateway …), not to NAT gateways or outbound traffic.')],
      stub: { asset: 'network traffic', layer: 'VPC', mode: 'prevent', sup: 'none stated' }, words: ['only to a list of approved software-update domains', 'intrusion prevention', '15 VPCs connected by a transit gateway'],
      expl: 'This time **Network Firewall is right**: traffic crossing a VPC boundary, domain allow list, IPS. That is its built-for job. Security groups cannot do domains, DNS Firewall filters lookups but runs no IPS, and WAF cannot see outbound VPC traffic.',
      update: 'Since June–July 2025 Network Firewall can attach **natively to a Transit Gateway**, with no inspection VPC or firewall subnets to manage. Banks still describe an inspection VPC with firewall subnets — also correct.' },

    /* ---------------- KMS ---------------- */
    { id: 'S6', src: 'New', line: 'kms',
      q: 'An application must encrypt 5 GB video files with a key protected by AWS KMS before storing them in an on-premises archive. Developers call the KMS Encrypt API with the file contents and receive errors. What should they do?',
      opts: [_o('Request a quota increase for KMS cryptographic operations in the Region, then retry the failed Encrypt calls with backoff.', 0, 'The error is the 4 KB plaintext limit of Encrypt, not a request-rate quota.'),
        _o('Split each file into 4 KB chunks, call Encrypt on every chunk, and store the encrypted chunks in order in the archive.', 0, 'Over a million KMS calls per 5 GB file: slow, expensive and throttled.'),
        _o('Call GenerateDataKeyWithoutPlaintext, encrypt each file locally with the returned key, and store that key with the file.', 0, 'That call returns only the encrypted data key; there is no plaintext key to encrypt with until you call Decrypt.'),
        _o('Call GenerateDataKey, encrypt each file locally with the plaintext key, and store the encrypted data key with the file.', 1, 'Envelope encryption: KMS only protects the small data key; the bulk data never leaves the application.')],
      stub: { asset: 'data at rest', layer: 'workload', mode: 'prevent', sup: 'none stated' }, words: ['5 GB video files', 'KMS Encrypt API with the file contents'],
      expl: 'KMS Encrypt accepts at most **4 KB (4,096 bytes)** of plaintext. For anything larger, use **envelope encryption**: GenerateDataKey returns a plaintext and an encrypted data key; the plaintext key encrypts the data locally and is discarded, and only the encrypted data key is stored next to it. To decrypt, send the encrypted data key to KMS Decrypt.' },
    { id: 'S7', src: 'New', line: 'kms',
      q: 'A financial regulator requires a company to keep its encryption keys in hardware security modules that are dedicated to the company alone. Only the company’s own security officers may create and manage keys, AWS personnel must have no access to them, and the HSMs must be validated at FIPS 140-3 Level 3. Which solution meets these requirements?',
      opts: [_o('AWS CloudHSM, with a cluster of HSMs in two Availability Zones and keys created by the company’s security officers.', 1, 'Single-tenant HSMs; the customer creates the crypto users and keys and AWS cannot access them.'),
        _o('AWS KMS customer managed keys, with a key policy that allows only the security officers’ IAM roles to create and manage them.', 0, 'KMS HSMs are FIPS 140-3 Level 3, but they are multi-tenant and operated by AWS; they are not dedicated to one customer.'),
        _o('AWS KMS keys with key material that the security officers generate on premises and import into the KMS keys.', 0, 'The imported key material then lives in the same shared, AWS-operated KMS HSMs.'),
        _o('AWS Private CA with ACM, with the CA’s private keys held in AWS-managed HSMs that only the security officers use.', 0, 'A private certificate authority issues certificates; it is not a dedicated key store, and its HSMs are AWS-managed. Prestige distractor.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'compliance' }, words: ['dedicated to the company alone', 'AWS personnel must have no access', 'FIPS 140-3 Level 3'],
      expl: '**Dedicated / single-tenant / exclusive control** → **CloudHSM**. FIPS 140-3 Level 3 alone does not decide it: KMS is validated at that level too, and importing your own key material still leaves it in KMS’s shared HSMs. For HA, run at least two HSMs in different AZs.',
      update: 'KMS is now validated at **FIPS 140-3 Level 3** (older material: FIPS 140-2), and CloudHSM’s current hsm2m.medium type at FIPS 140-3 Level 3. The deciding words are single-tenant and exclusive control, not the FIPS level.' },
    { id: 'S9', src: 'New', line: 'kms',
      q: 'A company is building an application that will encrypt sensitive fields client-side with AWS KMS in us-east-1 and replicate the ciphertext to a DynamoDB global table in eu-west-1. During a Regional outage, the application in eu-west-1 must decrypt the data locally without calling KMS in us-east-1 and without re-encrypting anything. What should the company do?',
      opts: [_o('Create a single-Region key in us-east-1, and allow the eu-west-1 application’s IAM role kms:Decrypt in its key policy.', 0, 'A KMS key is regional; eu-west-1 would still have to call KMS in us-east-1.'),
        _o('Create a key in each Region, and use a DynamoDB Streams Lambda function to re-encrypt each item under the eu-west-1 key.', 0, 'Works, but it re-encrypts everything and adds code and cost.'),
        _o('Create a multi-Region primary key in us-east-1, replicate it to eu-west-1 now, and encrypt the fields with that key.', 1, 'Same key ID and key material in both Regions: ciphertext from one decrypts in the other with a local call.'),
        _o('Create a multi-Region primary key in us-east-1, and replicate it to eu-west-1 as soon as an outage in us-east-1 begins.', 0, 'Replicating a multi-Region key is a call made in the primary key’s Region — the Region that is down.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'none stated' }, words: ['decrypt the data locally', 'without re-encrypting anything', 'eu-west-1'],
      expl: 'KMS keys never leave their Region. **Multi-Region keys** are related keys with the **same key ID and key material** in several Regions; each is still an independent regional resource with its own policy. Create the replica before you need it. Built for client-side encryption of globally replicated data and DR.' },
    { id: 'S12', src: 'New', line: 'kms',
      q: 'A compliance rule requires that the customer managed KMS key protecting an application’s data is rotated automatically every 90 days, that data encrypted under older key material stays readable, and that no application changes are needed. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('Create a new KMS key every 90 days with a scheduled Lambda function, and move the application’s alias to the new key.', 0, 'The old workaround from before April 2024. Still works, but it is code to maintain and is no longer needed.'),
        _o('Enable automatic rotation on the existing customer managed key, and set its rotation period to 90 days.', 1, 'Rotation periods of 90–2,560 days are supported; KMS keeps old key material to decrypt older ciphertext.'),
        _o('Switch the application to the AWS managed key for the service, which KMS rotates automatically for every customer.', 0, 'AWS managed keys rotate every year, and you cannot change the period.'),
        _o('Import new key material into the existing key every 90 days, and keep the previous material for older data.', 0, 'The key was created with KMS-generated material; a key’s origin is fixed, so it cannot take imported material — and importing is manual.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'least ops' }, words: ['rotated automatically every 90 days', 'no application changes'],
      expl: 'Automatic rotation keeps the **same key ID and ARN**, so nothing changes in the application, and old key material stays available for decryption. The period is now configurable from **90 to 2,560 days** (default 365).',
      update: ROT },
    { id: 'S13', src: 'New', line: 'kms',
      q: 'An administrator accidentally scheduled a customer managed KMS key for deletion with the default settings two days ago. The key encrypts production EBS volumes. What should the company do to avoid losing access to the data?',
      opts: [_o('Wait for the waiting period to end, then restore the key from the backup copy that KMS keeps for another 30 days.', 0, 'There is no such backup: after the waiting period the key material is gone, and data encrypted under it is unrecoverable.'),
        _o('Create a new customer managed key, move the old key’s alias to it, and reattach the EBS volumes to the instances.', 0, 'A new key has different key material and cannot decrypt the existing data.'),
        _o('Call EnableKey on the key now; enabling a key that is pending deletion cancels the scheduled deletion automatically.', 0, 'A key in Pending Deletion cannot be enabled; the deletion has to be cancelled first.'),
        _o('Cancel the key deletion during the waiting period, which leaves the key disabled, and then enable the key again.', 1, 'The key stays in Pending Deletion for the waiting period (default 30 days) and can be restored until it ends.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'none stated' }, words: ['scheduled a customer managed KMS key for deletion', 'default settings'],
      expl: 'Deletion always has a **waiting period of 7–30 days (default 30)**. During it the key is disabled (Pending Deletion) and every cryptographic call fails — which is also how you find out who still uses it. **Cancel deletion**, then re-enable. Disabling is the safe alternative to deleting.' },

    /* ---------------- encryption at rest ---------------- */
    { id: 'S8', src: 'New', line: 'rest',
      q: 'A company must share an encrypted Amazon EBS snapshot with a partner’s AWS account. The snapshot is encrypted with the default AWS managed key (aws/ebs). What is the correct approach?',
      opts: [_o('Copy the snapshot with a customer managed KMS key, allow the partner account in that key’s policy, and share the copy.', 1, 'Only customer managed keys can be shared; the partner needs permission on the key and on the snapshot.'),
        _o('Add the partner’s account ID to the snapshot’s permissions, and grant the partner kms:Decrypt in the aws/ebs key policy.', 0, 'You cannot edit the policy of an AWS managed key, and snapshots encrypted with it cannot be shared.'),
        _o('Copy the snapshot without encryption to remove the aws/ebs dependency, and share the unencrypted copy with the partner.', 0, 'A copy of an encrypted snapshot is always encrypted; copying cannot remove encryption.'),
        _o('Copy the snapshot with a customer managed KMS key, share the copy with the partner account, and keep the key policy as it is.', 0, 'The partner can see the shared snapshot but cannot use the key, so it cannot create a volume from it.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'none stated' }, words: ['share an encrypted Amazon EBS snapshot', 'default AWS managed key (aws/ebs)'],
      expl: 'AWS managed keys (aws/ebs, aws/rds) can only be used by principals in their own account. To share: **copy with a customer managed key → add the other account to the key policy → share the snapshot**. Skip the key policy step and the partner sees a snapshot it cannot use. The same rule applies to RDS snapshots.' },
    { id: 'S10', src: 'New', line: 'rest',
      q: 'An S3 bucket with SSE-KMS default encryption receives millions of small object uploads per hour. The application now receives KMS ThrottlingException errors and the KMS bill has grown sharply. The company wants to reduce the number of KMS requests without changing the encryption type. What should a solutions architect do?',
      opts: [_o('Request a quota increase for KMS cryptographic operations in the bucket’s Region to stop the throttling errors.', 0, 'Raises the ceiling but sends just as many requests — the bill stays the same.'),
        _o('Change the bucket’s default encryption to DSSE-KMS with the same KMS key to make fewer KMS requests per object.', 0, 'Changes the encryption type, and DSSE-KMS does not support S3 Bucket Keys.'),
        _o('Enable S3 Bucket Keys in the bucket’s default SSE-KMS encryption settings, keeping the same KMS key.', 1, 'S3 uses a short-lived bucket-level key derived from the KMS key, cutting KMS requests by up to 99%.'),
        _o('Create a second customer managed KMS key, and split the uploads between the two keys by object prefix.', 0, 'The request quota is per account and Region, shared by all symmetric keys, and every request is still billed.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'none stated' }, words: ['ThrottlingException', 'without changing the encryption type'],
      expl: 'SSE-KMS calls KMS for every object. **S3 Bucket Keys** reduce those calls (and their cost) by up to 99%. The KMS request quota is shared per account per Region across keys, so a second key does not help, and a quota increase leaves the request count — and the bill — unchanged.',
      update: 'KMS request quotas are now 10,000 / 20,000 / 100,000 per second depending on the Region (older material: 5,500 / 10,000 / 30,000–50,000).' },
    { id: 'S11', src: 'New', line: 'rest',
      q: 'An Amazon RDS for MySQL DB instance was created without encryption. An audit requires the database to be encrypted at rest with a KMS key, with the LEAST effort. Which steps should a solutions architect take? (Select TWO.)',
      opts: [_o('Modify the DB instance to turn on storage encryption with a KMS key, and apply the change immediately.', 0, 'RDS encryption can only be chosen when the instance is created.'),
        _o('Take a snapshot of the DB instance and copy the snapshot with encryption enabled, choosing a KMS key.', 1, 'Copying is where an unencrypted RDS snapshot can be encrypted.'),
        _o('Create a read replica of the instance with encryption enabled, then promote the replica to a standalone instance.', 0, 'A read replica must have the same encryption state as its source.'),
        _o('Enable EBS encryption by default in the Region, then reboot the DB instance so its storage is re-encrypted.', 0, 'Affects new EBS volumes only; a reboot does not re-encrypt existing RDS storage.'),
        _o('Restore a new DB instance from the encrypted snapshot copy, and point the application at the new endpoint.', 1, 'The restored instance is encrypted; switch the endpoint (and plan a short write freeze).')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'least ops' }, words: ['created without encryption', 'encrypted at rest with a KMS key'],
      expl: 'RDS: **encryption only at creation**. Snapshot → **copy with encryption** → **restore** → switch the application. (Aurora differs: restore the snapshot with encryption turned on.) Encryption cannot be turned off later either.' },
    { id: 'S14', src: 'New', line: 'rest',
      q: 'A company’s policy says that encryption keys for archived data must be generated and stored only in its on-premises key management system. AWS may use a key only while processing a request and must never store it. The company creates a new S3 bucket for the archive in 2026. What should it do?',
      opts: [_o('Use SSE-KMS with a customer managed key whose key material is generated on premises and imported into KMS.', 0, 'Imported key material is stored in KMS — AWS keeps it.'),
        _o('Upload each object with SSE-C over HTTPS, passing the on-premises key in the request headers; no bucket change is needed.', 0, 'Since April 2026 new buckets block SSE-C by default, so these uploads fail with 403 until SSE-C is allowed.'),
        _o('Use DSSE-KMS with a customer managed KMS key, so that every object carries two independent layers of encryption.', 0, 'Two layers, but both come from KMS keys that AWS stores.'),
        _o('Allow SSE-C on the bucket with PutBucketEncryption, then upload each object over HTTPS with its key in the headers.', 1, 'S3 uses the key for that request and discards it. Since April 2026 new buckets block SSE-C until you allow it.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'compliance' }, words: ['stored only in its on-premises key management system', 'must never store it', 'new S3 bucket'],
      expl: '“AWS must never store the key” → **SSE-C** (or client-side encryption). S3 uses the key you send (HTTPS only), keeps only a salted HMAC to validate later requests, and forgets the key. On a bucket created in 2026, SSE-C must be allowed first.',
      update: 'Since **April 2026** S3 **blocks SSE-C by default on new general purpose buckets** (and on existing buckets in accounts that never used it). Allow it with `PutBucketEncryption` (BlockedEncryptionTypes = NONE). Banks still answer “SSE-C” with no extra step.' },
    { id: 'S15', src: 'New', line: 'rest',
      q: 'A security audit found that some clients upload objects to an S3 bucket over plain HTTP. The company must ensure that every request to the bucket uses encryption in transit. What should a solutions architect do?',
      opts: [_o('Add a bucket policy statement that denies all S3 actions on the bucket when aws:SecureTransport is false.', 1, 'Requests over HTTP carry SecureTransport = false and are refused, whatever path they take to the bucket.'),
        _o('Add a bucket policy statement that denies s3:PutObject when the request lacks the aws:kms encryption header.', 0, 'Forces SSE-KMS on uploads — encryption at rest; says nothing about the connection.'),
        _o('Put a CloudFront distribution with an HTTPS-only viewer protocol policy in front of the bucket for all clients.', 0, 'Clients can still call the bucket’s own endpoint over HTTP; nothing on the bucket refuses them.'),
        _o('Set default encryption to SSE-KMS with a customer managed key and S3 Bucket Keys enabled on the bucket.', 0, 'Encrypts objects at rest; says nothing about the connection.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'none stated' }, words: ['over plain HTTP', 'encryption in transit'],
      expl: 'Transport is enforced in the **bucket policy**: `Deny` with the condition `"Bool": {"aws:SecureTransport": "false"}`. To force SSE-KMS on uploads, deny PutObject without the KMS encryption header — a separate statement about data at rest.' },
    { id: 'S16', src: 'New', line: 'rest',
      q: 'A company wants every new Amazon EBS volume and snapshot created in its account in eu-central-1 to be encrypted, even when engineers forget to select encryption. Which solution meets this requirement with the LEAST operational overhead?',
      opts: [_o('Turn on EBS encryption by default once in us-east-1, since the setting then applies to every Region in the account.', 0, 'EBS encryption by default is set per Region; turning it on in us-east-1 does nothing in eu-central-1.'),
        _o('Turn on EBS encryption by default for the account in eu-central-1, and select the KMS key it should use.', 1, 'Every new volume and snapshot copy in that Region is encrypted automatically.'),
        _o('Attach an SCP that denies ec2:CreateVolume in eu-central-1 when the ec2:Encrypted condition key is false.', 0, 'Refuses the forgotten volumes instead of encrypting them; engineers have to retry.'),
        _o('Deploy the AWS Config rule encrypted-volumes in eu-central-1 with automatic remediation through Systems Manager.', 0, 'Detects after creation, and a volume cannot be encrypted in place: remediation means snapshot, copy and replace.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'least ops' }, words: ['even when engineers forget', 'eu-central-1'],
      expl: '**EBS encryption by default** is an account setting **per Region**. It affects new volumes only; existing unencrypted volumes need snapshot → encrypted copy → new volume.' },

    /* ---------------- secrets ---------------- */
    { id: 'S17', src: 'New', line: 'secrets',
      q: 'An application on EC2 connects to an Amazon Aurora PostgreSQL database with a user name and password stored in a configuration file. The company must remove the password from the file and rotate it automatically every 30 days. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('Store the password as a SecureString parameter in Parameter Store, and attach a 30-day rotation policy to it.', 0, 'Parameter Store has no rotation; advanced parameter policies only expire a value or notify.'),
        _o('Encrypt the configuration file with a customer managed KMS key that has automatic rotation set to 30 days.', 0, 'Rotates the key, not the password — and the password stays in the file.'),
        _o('Store the credentials in Secrets Manager with built-in rotation every 30 days, and read the secret at run time.', 1, 'Secrets Manager rotates Aurora credentials with an AWS-provided rotation function — no code to write; the app reads the current value through its instance role.'),
        _o('Store the credentials in Secrets Manager with a rotation Lambda function you write, scheduled every 30 days.', 0, 'Works, but Secrets Manager already provides the Aurora rotation function — your own Lambda function is code to maintain.')],
      stub: { asset: 'secrets & config', layer: 'workload', mode: 'prevent', sup: 'least ops' }, words: ['rotate it automatically every 30 days', 'LEAST operational overhead'],
      expl: '“Rotate automatically” → **Secrets Manager**. For RDS, Aurora, DocumentDB and Redshift it ships the rotation functions (nothing to write), and RDS/Aurora can even manage the master password in Secrets Manager for you (**managed rotation**). Parameter Store has no rotation at all.',
      update: 'Managed rotation (no Lambda) now covers RDS, Aurora, DocumentDB and Redshift, and the shortest rotation schedule is every 4 hours. Older material shows a Lambda rotation function for every case.' },
    { id: 'S18', src: 'New', line: 'secrets',
      q: 'A team needs a central place for about 300 configuration values per environment — service endpoints, feature flags, timeouts — plus a few third-party API keys that are changed manually once a year. Values are under 1 KB. The team wants the cheapest managed option with encryption for the API keys.',
      opts: [_o('Parameter Store standard parameters for the configuration, and SecureString standard parameters for the API keys.', 1, 'Standard parameters are free (10,000 per Region, 4 KB each); SecureString encrypts the keys with KMS.'),
        _o('Parameter Store advanced parameters for the configuration values, and SecureString advanced parameters for the API keys.', 0, '$0.05 per parameter per month for features (8 KB values, policies) these values do not need; standard is free.'),
        _o('AWS Secrets Manager for the API keys and the configuration values alike, stored as one secret per value.', 0, 'About $0.40 per secret per month: over $120 a month per environment for mostly plain config.'),
        _o('AWS Certificate Manager for the API keys as imported certificates, and Parameter Store standard parameters for the rest.', 0, 'ACM stores TLS certificates, not API keys. Prestige distractor.')],
      stub: { asset: 'secrets & config', layer: 'workload', mode: 'prevent', sup: 'cheapest' }, words: ['about 300 configuration values', 'changed manually once a year', 'cheapest managed option'],
      expl: 'Config + no rotation + cheapest → **Parameter Store standard** (free, 4 KB values, up to 10,000 per Region). Advanced tier (8 KB, 100,000 parameters, expiry policies) costs $0.05 per parameter per month.' },
    { id: 'S19', src: 'New', line: 'secrets',
      q: 'An application uses a database secret in AWS Secrets Manager in us-east-1 that rotates every 30 days. For disaster recovery, the standby application in us-west-2 must read the same, current secret locally if us-east-1 is unavailable. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('Encrypt the secret with a KMS multi-Region key, and replicate that key to us-west-2 for the standby to decrypt with.', 0, 'The key would be available in both Regions, but the secret itself would still live only in us-east-1.'),
        _o('Copy the secret into a new secret in us-west-2 with a Lambda function that runs after each rotation event.', 0, 'Custom code that can fall behind rotation, and it is yours to maintain.'),
        _o('Store the secret as a SecureString parameter in us-east-1, and have the standby read it by its full ARN.', 0, 'Still a call to us-east-1 — the Region that is down — and Parameter Store does not rotate.'),
        _o('Replicate the secret to us-west-2 with Secrets Manager multi-Region secrets, and read the replica locally.', 1, 'The replica keeps the same name and is updated when the primary rotates; it can be promoted if needed.')],
      stub: { asset: 'secrets & config', layer: 'workload', mode: 'prevent', sup: 'least ops' }, words: ['read the same, current secret locally', 'us-west-2'],
      expl: 'Secrets Manager **replicates secrets to other Regions**: same ARN except the Region, rotation propagates to replicas, a replica can be promoted to a standalone secret. Each replica is billed as a secret.' },

    /* ---------------- certificates ---------------- */
    { id: 'S20', src: 'New', line: 'acm',
      q: 'A company imported a certificate from a third-party certificate authority into AWS Certificate Manager and attached it to an ALB. Last year the certificate expired unnoticed and caused an outage. The company wants to be notified well before the imported certificate expires, with the LEAST operational overhead.',
      opts: [_o('Turn on ACM managed renewal for the imported certificate, and subscribe an SNS topic to its renewal events.', 0, 'ACM does not renew imported certificates; there is nothing to turn on.'),
        _o('Create an EventBridge rule for the ACM Certificate Approaching Expiration event that publishes to an SNS topic.', 1, 'ACM emits daily expiry events starting 45 days before expiry for imported certificates (the Config rule acm-certificate-expiration-check also works).'),
        _o('Create a CloudWatch alarm on the ALB’s HTTPCode_ELB_5XX_Count metric that publishes to an SNS topic.', 0, 'Fires only after clients already fail — the outage has started.'),
        _o('Enable Shield Advanced proactive engagement so that the Shield Response Team calls before the certificate expires.', 0, 'The Shield Response Team contacts you during DDoS events, not about certificates. Prestige distractor.')],
      stub: { asset: 'TLS certificates', layer: 'entry point', mode: 'detect', sup: 'least ops' }, words: ['imported a certificate from a third-party certificate authority', 'notified well before'],
      expl: 'ACM renews only certificates **it issued**. For **imported** ones: react to the **EventBridge expiry events** (from 45 days before, configurable) or the **Config rule** `acm-certificate-expiration-check`, then re-import. ACM is right here — the prestige distractor is Shield.' },
    { id: 'S21', src: 'New', line: 'acm',
      q: 'A company runs 200 internal microservices on Amazon ECS that talk to each other over TLS using internal host names such as orders.corp.internal. The security team wants to stop managing a self-hosted certificate authority and have certificates issued and renewed centrally by a managed service.',
      opts: [_o('Request public ACM certificates with DNS validation for each internal name, such as orders.corp.internal.', 0, 'Public CAs cannot issue certificates for private names such as .internal.'),
        _o('Run a CA on EC2 in an Auto Scaling group, keep its root key in AWS CloudHSM, and issue certificates from it.', 0, 'Still a self-hosted CA — exactly what the team wants to stop running.'),
        _o('Create an AWS Private CA and issue private certificates for the internal names through ACM, which renews them.', 1, 'A managed private CA for internal names; ACM renews private certificates issued through it.'),
        _o('Enable TLS inspection in AWS Network Firewall between the services so that it re-signs their traffic with one CA.', 0, 'Inspects traffic; it does not issue or renew the services’ own certificates. Prestige distractor.')],
      stub: { asset: 'TLS certificates', layer: 'workload', mode: 'prevent', sup: 'none stated' }, words: ['internal host names', 'stop managing a self-hosted certificate authority'],
      expl: 'Internal names and your own trust chain → **AWS Private CA** ($400 per CA per month in general-purpose mode; $50 in short-lived certificate mode). Public ACM certificates only cover public DNS names.' },

    /* ---------------- WAF, Shield, Firewall Manager ---------------- */
    { id: 'S22', src: 'New', line: 'edge',
      q: 'A media company’s CloudFront distributions and ALBs were hit by several large DDoS attacks last quarter, and scaling during the attacks added significant charges. The company wants 24/7 access to AWS DDoS experts during attacks and protection against the extra scaling costs.',
      opts: [_o('Rely on AWS Shield Standard, which is already active, and open an urgent AWS Support case during each attack.', 0, 'Shield Standard absorbs common L3/L4 attacks but has no response team and no cost protection.'),
        _o('Subscribe to AWS Shield Advanced and protect the distributions and ALBs, keeping the account on Developer Support.', 0, 'Cost protection yes, but the Shield Response Team needs Business or Enterprise Support.'),
        _o('Add AWS WAF rate-based rules to every web ACL, and manage them centrally with AWS Firewall Manager policies.', 0, 'Helps with L7 floods but gives neither expert support nor cost protection.'),
        _o('Subscribe to AWS Shield Advanced, protect the distributions and ALBs, and use Business or Enterprise Support.', 1, 'SRT access (with Business or Enterprise Support), DDoS cost protection, automatic L7 mitigation with WAF.')],
      stub: { asset: 'web requests', layer: 'entry point', mode: 'prevent', sup: 'none stated' }, words: ['24/7 access to AWS DDoS experts', 'extra scaling costs'],
      expl: 'Here **Shield Advanced is right**: “DDoS experts” = the **Shield Response Team** (needs Business or Enterprise Support) and “scaling costs during an attack” = **DDoS cost protection**. $3,000 a month per organization with a one-year commitment.' },
    { id: 'S23', src: 'New', line: 'edge',
      q: 'A company publishes a REST API with Amazon API Gateway (no CloudFront in front). For licensing reasons, requests from three specific countries must be blocked. Which solution meets this requirement with the LEAST operational overhead?',
      opts: [_o('Associate an AWS WAF web ACL with the API stage, with a geo match rule that blocks the three countries.', 1, 'Geo match is a built-in WAF statement; REST API stages are supported WAF resources.'),
        _o('Put a CloudFront distribution in front of the API, and turn on its geographic restriction for the three countries.', 0, 'Clients can still call the API’s own endpoint directly, and you add a distribution to run.'),
        _o('Add network ACL rules to the API backend’s subnets that deny the published IP ranges of the three countries.', 0, 'The backend sees API Gateway’s addresses, not the clients’, and country ranges run into thousands of CIDRs.'),
        _o('Deploy AWS Network Firewall with a geographic IP filtering rule in the VPC that hosts the API’s backend.', 0, 'Traffic inside the VPC comes from API Gateway, not the clients; the public endpoint never passes the firewall. Prestige distractor.')],
      stub: { asset: 'web requests', layer: 'entry point', mode: 'prevent', sup: 'least ops' }, words: ['REST API with Amazon API Gateway', 'three specific countries'],
      expl: 'Country rules at an API entry point → **WAF geo match**. Remember the supported resources: CloudFront, ALB, API Gateway **REST** APIs, AppSync, Cognito user pools, App Runner, Verified Access, Amplify — **not NLB**, not HTTP APIs.' },
    { id: 'S24', src: 'New', line: 'edge',
      q: 'A company with 40 AWS accounts in AWS Organizations must apply the same AWS WAF rules to every internet-facing ALB, including ALBs in accounts created in the future, and see which resources are not compliant. Which solution meets these requirements with the LEAST operational overhead?',
      opts: [_o('Deploy the web ACL to all accounts with CloudFormation StackSets auto-deployment, and associate each existing ALB.', 0, 'New accounts get the web ACL, but ALBs created later are not associated and nothing reports compliance.'),
        _o('Enable Security Hub CSPM with the FSBP standard so that every ALB without a web ACL is flagged in each account.', 0, 'Reports missing WAF but applies no rules. Prestige distractor.'),
        _o('Use AWS Firewall Manager with an AWS WAF policy for ALBs across the organization, with AWS Config enabled.', 1, 'Firewall Manager applies the web ACL to existing and new in-scope resources and reports compliance.'),
        _o('Deploy an organization conformance pack with the alb-waf-enabled rule and an SSM remediation that attaches a web ACL.', 0, 'Can be made to work, but you build the web ACLs in every account and maintain the remediation yourself.')],
      stub: { asset: 'web requests', layer: 'account / org', mode: 'prevent', sup: 'least ops' }, words: ['40 AWS accounts in AWS Organizations', 'accounts created in the future'],
      expl: 'Same firewall rules everywhere in an Organization, automatically for new resources → **Firewall Manager** (needs Organizations, a Firewall Manager administrator and AWS Config). It manages WAF, Shield Advanced, security group, NACL, Network Firewall, DNS Firewall and third-party firewall policies.' },

    /* ---------------- detection ---------------- */
    { id: 'S25', src: 'New', line: 'detect',
      q: 'A company wants to be alerted when any EC2 instance in its account communicates with known cryptocurrency-mining pools or command-and-control servers, or when IAM credentials are used from unusual locations. It does not want to deploy agents or manage log pipelines.',
      opts: [_o('Enable Amazon Inspector for EC2 in the account, and route its findings through Amazon EventBridge to Amazon SNS.', 0, 'Inspector finds software vulnerabilities and exposure, not live malicious traffic or credential misuse.'),
        _o('Enable Amazon GuardDuty in the account, and route its findings through Amazon EventBridge to Amazon SNS.', 1, 'GuardDuty analyses CloudTrail, VPC Flow Logs and DNS logs itself and raises exactly these findings.'),
        _o('Enable GuardDuty Runtime Monitoring with its security agent on every instance, and alert through EventBridge.', 0, 'Adds an agent to every instance — and the foundational GuardDuty sources already catch these threats.'),
        _o('Send VPC Flow Logs to CloudWatch Logs with metric filters for known mining-pool IPs, and alarm to SNS.', 0, 'A log pipeline and IP lists you maintain yourself — what GuardDuty replaces — and it ignores credential misuse.')],
      stub: { asset: 'API & account activity', layer: 'account / org', mode: 'detect', sup: 'least ops' }, words: ['cryptocurrency-mining pools', 'IAM credentials are used from unusual locations', 'does not want to deploy agents'],
      expl: 'Threat detection from account and network activity → **GuardDuty**. It reads its **own** copy of CloudTrail management events, VPC Flow Logs and DNS logs, so nothing needs enabling first and no agent is needed for these findings. It **detects**; response goes through EventBridge.',
      update: 'GuardDuty **Extended Threat Detection** (Dec 2024) is on by default at no extra cost and correlates several signals into attack sequence findings.' },
    { id: 'S26', src: 'New', line: 'detect',
      q: 'GuardDuty reported that IAM access keys were used to call APIs from an unusual IP address. The security team must determine which resources those credentials accessed over the past several weeks, which other IP addresses were involved, and how the activity started, with the LEAST effort.',
      opts: [_o('Send the finding to Security Hub CSPM, and review the account’s related findings and security score there.', 0, 'Security Hub lists and prioritises findings; it does not reconstruct weeks of activity. Prestige distractor.'),
        _o('Query the CloudTrail logs in S3 with Amazon Athena, and join them with the VPC Flow Logs for those IP addresses.', 0, 'Possible, but it is the investigation Detective does for you.'),
        _o('Search CloudTrail event history in the console for the access key ID, Region by Region, over the past weeks.', 0, 'Management events only, one Region at a time, and no network view — slow, manual work.'),
        _o('Pivot from the finding into Amazon Detective, and examine the behavior graph for the key and IP addresses.', 1, 'Detective links CloudTrail, flow logs and GuardDuty findings in a graph over up to a year.')],
      stub: { asset: 'API & account activity', layer: 'account / org', mode: 'investigate', sup: 'least ops' }, words: ['determine which resources those credentials accessed', 'how the activity started'],
      expl: 'MODE = investigate → **Detective**. GuardDuty detected; Security Hub would aggregate; Detective explains root cause and scope from its behaviour graph. Athena or event history can get there too, with far more work.' },
    { id: 'S27', src: 'New', line: 'scan',
      q: 'A company builds container images that are pushed to Amazon ECR and deploys Lambda functions. The security team must continuously find known software vulnerabilities (CVEs) in the images and function packages and be alerted when a new CVE affects something already deployed.',
      opts: [_o('Activate Amazon Inspector with enhanced scanning for Amazon ECR and Lambda standard scanning for the functions.', 1, 'Scans on push and continuously re-evaluates when new CVEs are published.'),
        _o('Turn on Amazon ECR basic scanning on push for every repository, and Lambda code signing for every function.', 0, 'Basic scanning runs on push or on demand only, not when a new CVE appears later; code signing checks integrity, not CVEs.'),
        _o('Enable GuardDuty Runtime Monitoring for the containers, and GuardDuty Lambda Protection for the functions.', 0, 'Watches runtime behaviour and network activity for threats; it does not inventory package CVEs.'),
        _o('Enable Amazon Macie from a delegated administrator, with managed data identifiers for the image layers and function packages.', 0, 'Macie analyses S3 objects for sensitive data; it neither reads ECR images nor knows CVEs.')],
      stub: { asset: 'workloads & images', layer: 'workload', mode: 'detect', sup: 'none stated' }, words: ['known software vulnerabilities (CVEs)', 'Amazon ECR', 'Lambda functions'],
      expl: 'CVEs in EC2, ECR images and Lambda → **Inspector**. It rescans continuously as new vulnerabilities are published; findings go to EventBridge and Security Hub. ECR basic scanning does not rescan on its own.',
      update: 'Inspector Classic ended support on 20 May 2026. Current Inspector also scans EC2 agentless (hybrid mode) and source repositories (code security, GA June 2025).' },
    { id: 'S28', src: 'New', line: 'scan',
      q: 'A company has 3,000 S3 buckets across its AWS accounts. Before a GDPR audit it must find which buckets contain personal data such as names, passport numbers and bank account numbers, and keep checking new objects, with the LEAST effort.',
      opts: [_o('Enable GuardDuty S3 Protection from a delegated administrator account, and alert on its findings for all buckets.', 0, 'Watches S3 API activity for threats; it never reads object contents.'),
        _o('Create a one-time Macie sensitive data discovery job in each account that covers all of its existing buckets.', 0, 'Finds the personal data once but never checks new objects, and it is a job per account.'),
        _o('Enable Amazon Macie from a delegated administrator account with automated sensitive data discovery.', 1, 'Samples objects across all buckets continuously with managed data identifiers and reports where personal data lives.'),
        _o('Activate Amazon Inspector from a delegated administrator account, and scan all buckets for personal data.', 0, 'Inspector scans workloads (EC2, ECR, Lambda) for CVEs; it does not read S3 objects for personal data.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'detect', sup: 'least ops' }, words: ['personal data such as names, passport numbers', '3,000 S3 buckets'],
      expl: 'Sensitive data in S3 → **Macie**, and only Macie. Automated sensitive data discovery samples every bucket continuously; discovery jobs target specific buckets once or on a schedule. Findings go to EventBridge and Security Hub.' },

    /* ---------------- posture ---------------- */
    { id: 'S29', src: 'New', line: 'hub',
      q: 'A company with 30 accounts in AWS Organizations operates in four Regions. The security team wants one place to see findings from GuardDuty, Inspector and Macie for all accounts and Regions, and an automated, continuous check of every account against the CIS AWS Foundations Benchmark. Which steps are required? (Select TWO.)',
      opts: [_o('Enable AWS Config recording in every account and in each of the four Regions that will be checked.', 1, 'Security Hub CSPM evaluates most controls with AWS Config rules.'),
        _o('Enable Amazon Detective from a delegated administrator in each Region, and add all 30 accounts as members.', 0, 'Investigates findings; it does not aggregate them or run benchmark checks.'),
        _o('Deploy an organization conformance pack from the CIS sample template, and view it in a Config aggregator.', 0, 'Checks CIS-style rules, but a Config aggregator does not show GuardDuty, Inspector or Macie findings.'),
        _o('Enable Security Hub CSPM from a delegated administrator, with an aggregation Region and the CIS standard.', 1, 'Central configuration, cross-Region aggregation, and the CIS checks as controls.'),
        _o('Deploy AWS Network Firewall in each VPC, and send its alert logs to an S3 bucket in the security account.', 0, 'Network traffic logs are not findings from GuardDuty, Inspector and Macie. Prestige distractor.')],
      stub: { asset: 'API & account activity', layer: 'account / org', mode: 'report / audit', sup: 'none stated' }, words: ['one place to see findings', 'CIS AWS Foundations Benchmark', 'four Regions'],
      expl: '“Single pane of glass” + “benchmark” → **Security Hub** (the posture part is now called **Security Hub CSPM**) with a delegated administrator, a cross-Region **aggregation Region**, the CIS standard — and **AWS Config** enabled, because the controls are Config rules.',
      update: 'The original Security Hub is now **AWS Security Hub CSPM**; the new **AWS Security Hub** (GA December 2025) correlates GuardDuty, Inspector, Macie and CSPM findings into exposure findings in OCSF. Banks say “Security Hub”.' },

    /* ---------------- Cognito ---------------- */
    { id: 'S30', src: 'New', line: 'cognito',
      q: 'A mobile photo app lets users sign up with email or sign in with their Google accounts. Signed-in users must upload photos directly to their own prefix in an S3 bucket without a backend server, and the company does not want to create IAM users.',
      opts: [_o('A Cognito identity pool alone, with Google as a provider and email sign-up handled by the identity pool’s user directory.', 0, 'Identity pools have no user directory; sign-up and sign-in are user pool features.'),
        _o('A Cognito user pool with Google federation, and an identity pool that exchanges its tokens for a prefix-scoped IAM role.', 1, 'User pool = who the user is; identity pool = temporary AWS credentials to call S3 directly.'),
        _o('A Cognito user pool with Google federation, and the app sends the user pool ID token straight to S3 to authorize uploads.', 0, 'S3 does not accept Cognito JWTs; it needs AWS credentials, which the identity pool provides.'),
        _o('IAM Identity Center with Google as the external identity provider, and a permission set scoped to each user’s prefix.', 0, 'Identity Center is workforce access to AWS accounts, not sign-up for a public app’s users.')],
      stub: { asset: 'app users', layer: 'app sign-in', mode: 'prevent', sup: 'none stated' }, words: ['sign in with their Google accounts', 'upload photos directly', 'does not want to create IAM users'],
      expl: 'Two pools, two jobs: the **user pool** signs users in (email or Google) and issues JWTs; the **identity pool** swaps them for **temporary AWS credentials** of an IAM role, whose policy can use the identity ID to restrict each user to their prefix.' }
  ];
})();
