/* Session 5 drills (Security services & identity). stub values must match SESSION.stub chip labels exactly ('any' accepts anything).
   words must appear verbatim (case-insensitive) in q so they can be highlighted after submit.
   S1–S5 come from his prestige-distractor pattern (mine: true, src 'Exam pattern', tag 'C'): ACM, Network Firewall and
   Shield Advanced tempting and wrong (S1 S2 S3), ACM and Network Firewall genuinely right (S4 S5).
   Other drills where a prestige service is a wrong option: S6 S7 S10 S14 S15 S16 S18 S20 S21 S22 S23 S24 S25 S26 S27 S28 S29 S30.
   Where it is right: S20 S21 (ACM / Private CA), S22 (Shield Advanced), S24 (Firewall Manager), S25 (GuardDuty), S29 (Security Hub). */
(function () {
  'use strict';
  const S = window.SESSION = window.SESSION || {};
  const _o = (t, ok, why) => ({ t, ok: !!ok, why });
  const ACM_REST = 'ACM issues TLS certificates for data in transit. It never encrypts data at rest — prestige distractor.';
  const NFW_L7 = 'Network Firewall inspects traffic crossing VPC boundaries; it does not sit in front of an ALB’s HTTP requests with managed SQLi rules the way WAF does — prestige distractor.';
  const ROT = 'Older material: KMS rotation was fixed at one year, so a shorter period meant a new key and an alias switch. Since April 2024 the period is configurable (90–2,560 days) and on-demand rotation exists.';
  S.drills = [
    /* ---------------- the prestige pattern (his record) ---------------- */
    { id: 'S1', src: 'Exam pattern', line: 'kms', mine: true, tag: 'C',
      q: 'A company stores customer contracts in an Amazon S3 bucket. A new policy requires that the objects are encrypted at rest with a key the security team controls, that every use of the key is recorded for audit, and that the key can be disabled at any time. The team wants the least operational overhead. What should a solutions architect do?',
      opts: [_o('Request a public certificate in AWS Certificate Manager (ACM) and associate it with the bucket to encrypt the objects.', 0, ACM_REST + ' Certificates cannot be associated with a bucket at all.'),
        _o('Keep the default SSE-S3 encryption and enable S3 server access logging.', 0, 'SSE-S3 keys are managed by S3: nobody can see, audit or disable them.'),
        _o('Create a customer managed KMS key and set it as the bucket’s default encryption (SSE-KMS) with S3 Bucket Keys enabled.', 1, 'The team owns the key policy, can disable the key, and CloudTrail logs every use. Bucket Keys keep the KMS request cost down.'),
        _o('Deploy an AWS CloudHSM cluster and encrypt each object in the application before upload.', 0, 'Meets “control”, but the team now runs HSMs and client-side code — the opposite of least overhead.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'least ops' }, words: ['encrypted at rest', 'every use of the key is recorded', 'can be disabled at any time', 'least operational overhead'],
      expl: 'ASSET = data at rest, MODE = prevent, SUP = least ops. “Key the team controls + audit + disable” = **customer managed KMS key** with SSE-KMS. ACM appears because “encryption” sounds like certificates; it only protects data **in transit**. Cross it out on the ASSET slot.' },
    { id: 'S2', src: 'Exam pattern', line: 'edge', mine: true, tag: 'C',
      q: 'An e-commerce application runs on EC2 instances behind an Application Load Balancer. The security team sees SQL injection and cross-site scripting attempts in the application logs. The company wants to block these requests before they reach the instances, with the least operational overhead.',
      opts: [_o('Create an AWS WAF web ACL with the AWS managed core rule set and SQL database rule group, and associate it with the ALB.', 1, 'AWS names these two for SQLi (SQL database) and XSS (core rule set); maintained by AWS, evaluated on every HTTP request at the ALB.'),
        _o('Deploy AWS Network Firewall in the VPC with Suricata rules that match SQL keywords.', 0, NFW_L7 + ' You would also write and maintain the signatures yourself.'),
        _o('Add inbound deny rules to the network ACL of the ALB subnets for the attackers’ IP addresses.', 0, 'NACLs see IP and port, not HTTP content, and attackers change IPs.'),
        _o('Subscribe to AWS Shield Advanced and enable automatic application layer mitigation.', 0, 'Shield Advanced mitigates DDoS floods; SQL injection is not a volume attack. $3,000 a month for the wrong job.')],
      stub: { asset: 'web requests', layer: 'entry point', mode: 'prevent', sup: 'least ops' }, words: ['SQL injection and cross-site scripting', 'Application Load Balancer', 'before they reach the instances'],
      expl: 'SQLi and XSS live inside **HTTP requests** → **WAF** at the entry point (ALB). Network Firewall is your recorded prestige pick: it filters traffic between networks with IPS signatures and domain lists, and it is not the managed answer for web exploits at an ALB.' },
    { id: 'S3', src: 'Exam pattern', line: 'edge', mine: true, tag: 'C',
      q: 'A company’s login API behind Amazon API Gateway (REST) receives thousands of password guesses per minute from a small number of IP addresses. Legitimate users log in a few times a day. The company wants to stop the abuse in the most cost-effective way.',
      opts: [_o('Subscribe to AWS Shield Advanced and ask the Shield Response Team to block the addresses.', 0, 'Shield Advanced costs $3,000 a month with a one-year commitment and is built for DDoS; a few IPs guessing passwords is not a DDoS.'),
        _o('Enable Amazon GuardDuty and wait for a brute-force finding.', 0, 'GuardDuty detects; it blocks nothing.'),
        _o('Deploy AWS Network Firewall in front of API Gateway.', 0, 'API Gateway is a managed regional endpoint, not a subnet in your VPC routing. Prestige distractor.'),
        _o('Associate an AWS WAF web ACL with the API stage containing a rate-based rule that limits requests per source IP to the login path.', 1, 'Each IP above the limit in the evaluation window is blocked; normal users never reach it. A few dollars a month.')],
      stub: { asset: 'web requests', layer: 'entry point', mode: 'prevent', sup: 'cheapest' }, words: ['thousands of password guesses per minute', 'small number of IP addresses', 'most cost-effective'],
      expl: 'One noisy client per IP → **WAF rate-based rule** (minimum limit 10, window 1–10 minutes), scoped down to the login path. Shield Advanced is the prestige pick that sounds strongest and costs most.',
      update: 'Rate-based rules now allow limits from **10** requests and windows of **60, 120, 300 or 600 s** (older material: minimum 100 per 5 minutes).' },
    { id: 'S4', src: 'Exam pattern', line: 'acm', mine: true, tag: 'C',
      q: 'A company exposes a web application through an internet-facing Application Load Balancer at shop.example.com, whose DNS is in Amazon Route 53. Customers must connect over HTTPS, and the operations team does not want to track or renew certificates manually. What is the solution with the least operational overhead?',
      opts: [_o('Buy a certificate from a third-party CA, import it into ACM, and attach it to an HTTPS listener.', 0, 'Works, but ACM never renews imported certificates: someone must re-import before every expiry.'),
        _o('Request a public certificate for shop.example.com in AWS Certificate Manager with DNS validation, and attach it to an HTTPS listener on the ALB.', 1, 'Free, and ACM renews DNS-validated certificates automatically while they are in use.'),
        _o('Generate a self-signed certificate on each EC2 instance and use a TCP listener.', 0, 'Browsers reject self-signed certificates, and every instance needs its own.'),
        _o('Enable SSE-KMS on the ALB with a customer managed key.', 0, 'KMS encrypts data at rest; the ALB needs a TLS certificate for data in transit.')],
      stub: { asset: 'TLS certificates', layer: 'entry point', mode: 'prevent', sup: 'least ops' }, words: ['over HTTPS', 'does not want to track or renew certificates manually'],
      expl: 'Here ACM is **genuinely the answer**: ASSET = TLS certificates, and ACM-issued, **DNS-validated** public certificates renew automatically. The prestige test is not “never pick ACM”, it is “pick ACM only when there is a certificate to issue”.',
      update: 'ACM public certificates are now valid for **198 days** (older material: 13 months) and renew **45 days** before expiry (was 60). Automatic renewal still needs the DNS validation CNAME in place.' },
    { id: 'S5', src: 'Exam pattern', line: 'nfw', mine: true, tag: 'C',
      q: 'A company runs workloads in private subnets of 15 VPCs connected by a transit gateway. Outbound internet traffic must be allowed only to a list of approved software-update domains, all other outbound connections must be blocked and logged, and known malware signatures must be detected with intrusion prevention. Which solution meets these requirements?',
      opts: [_o('Security groups that allow outbound HTTPS only to the update servers’ current IP addresses.', 0, 'Security groups know IPs, not domain names, and cannot run IPS signatures.'),
        _o('An AWS WAF web ACL with a string match rule for the approved domains, associated with each VPC.', 0, 'WAF attaches to web entry points (CloudFront, ALB, API Gateway …), not to VPCs or outbound traffic.'),
        _o('Centralised AWS Network Firewall inspection (attached to the transit gateway) with a stateful domain allow list and Suricata IPS rules, with logging enabled.', 1, 'Domain filtering on Host/SNI, stateful IPS and flow/alert logs for every VPC in one place.'),
        _o('Amazon GuardDuty with a threat list of malicious domains.', 0, 'GuardDuty would detect some bad destinations but blocks nothing and cannot allow-list domains.')],
      stub: { asset: 'network traffic', layer: 'VPC', mode: 'prevent', sup: 'none stated' }, words: ['only to a list of approved software-update domains', 'intrusion prevention', '15 VPCs connected by a transit gateway'],
      expl: 'This time **Network Firewall is right**: traffic crossing a VPC boundary, domain allow list, IPS. That is its built-for job. Security groups cannot do domains, WAF cannot see outbound VPC traffic, GuardDuty only detects.',
      update: 'Since June–July 2025 Network Firewall can attach **natively to a Transit Gateway**, with no inspection VPC or firewall subnets to manage. Banks still describe an inspection VPC with firewall subnets — also correct.' },

    /* ---------------- KMS ---------------- */
    { id: 'S6', src: 'New', line: 'kms',
      q: 'An application must encrypt 5 GB video files with a key protected by AWS KMS before storing them in an on-premises archive. Developers call the KMS Encrypt API with the file contents and receive errors. What should they do?',
      opts: [_o('Request a KMS quota increase for the Encrypt API.', 0, 'The error is the plaintext size limit, not a request-rate quota.'),
        _o('Split each file into 4 KB chunks and call Encrypt for each chunk.', 0, 'Over a million KMS calls per file: slow, expensive and throttled.'),
        _o('Store the files in S3 with an ACM certificate attached to the bucket.', 0, ACM_REST),
        _o('Call GenerateDataKey, encrypt the file locally with the plaintext data key, discard it, and store the encrypted data key with the file.', 1, 'Envelope encryption: KMS only protects the small data key; the bulk data never leaves the application.')],
      stub: { asset: 'data at rest', layer: 'workload', mode: 'prevent', sup: 'none stated' }, words: ['5 GB video files', 'KMS Encrypt API with the file contents'],
      expl: 'KMS Encrypt accepts at most **4 KB (4,096 bytes)** of plaintext. For anything larger, use **envelope encryption**: a data key from GenerateDataKey encrypts the data locally, and only the encrypted data key is stored next to it. To decrypt, send the encrypted data key to KMS Decrypt.' },
    { id: 'S7', src: 'New', line: 'kms',
      q: 'A financial company must keep its encryption keys in hardware security modules that are dedicated to the company alone. Only the company’s own security officers may create and manage keys, AWS personnel must have no access to them, and the HSMs must be validated at FIPS 140-3 Level 3. Which service meets these requirements?',
      opts: [_o('AWS KMS with customer managed keys.', 0, 'KMS HSMs are FIPS 140-3 Level 3, but they are multi-tenant and operated by AWS; they are not dedicated to one customer.'),
        _o('AWS CloudHSM, with a cluster of HSMs in two Availability Zones.', 1, 'Single-tenant HSMs; the customer creates the crypto users and keys and AWS cannot access them.'),
        _o('AWS Private CA with keys stored in ACM.', 0, 'A private certificate authority issues certificates; it is not a general key store. Prestige distractor.'),
        _o('AWS Secrets Manager with a customer managed KMS key.', 0, 'Stores secrets, encrypted by KMS; the keys are still in shared KMS HSMs.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'most control' }, words: ['dedicated to the company alone', 'AWS personnel must have no access', 'FIPS 140-3 Level 3'],
      expl: '**Dedicated / single-tenant / exclusive control** → **CloudHSM**. FIPS 140-3 Level 3 alone does not decide it: KMS is validated at that level too. For HA, run at least two HSMs in different AZs.',
      update: 'KMS is now validated at **FIPS 140-3 Level 3** (older material: FIPS 140-2), and CloudHSM’s current hsm2m.medium type at FIPS 140-3 Level 3. The deciding words are single-tenant and exclusive control, not the FIPS level.' },
    { id: 'S9', src: 'New', line: 'kms',
      q: 'A company encrypts sensitive fields client-side with AWS KMS in us-east-1 and replicates the ciphertext to a DynamoDB global table in eu-west-1. During a Regional outage, the application in eu-west-1 must decrypt the data locally without calling KMS in us-east-1 and without re-encrypting anything. What should the company use?',
      opts: [_o('A KMS key in each Region and a Lambda function that re-encrypts every item during replication.', 0, 'Works, but it re-encrypts everything and adds code and cost.'),
        _o('Share the us-east-1 key with the eu-west-1 account through a key policy.', 0, 'A KMS key is regional; eu-west-1 would still have to call us-east-1.'),
        _o('A KMS multi-Region primary key in us-east-1 with a replica key in eu-west-1.', 1, 'Same key ID and key material in both Regions: ciphertext from one decrypts in the other with a local call.'),
        _o('Store the key material in AWS Secrets Manager with cross-Region replication.', 0, 'You would be exporting key material into a secret — defeats KMS entirely.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'least ops' }, words: ['decrypt the data locally', 'without re-encrypting anything', 'eu-west-1'],
      expl: 'KMS keys never leave their Region. **Multi-Region keys** are related keys with the **same key ID and key material** in several Regions; each is still an independent regional resource with its own policy. Built for client-side encryption of globally replicated data and DR.' },
    { id: 'S12', src: 'New', line: 'kms',
      q: 'A compliance rule requires that the customer managed KMS key protecting an application’s data is rotated automatically every 90 days, that data encrypted under older key material stays readable, and that no application changes are needed. What should a solutions architect do?',
      opts: [_o('Create a new KMS key every 90 days with a scheduled Lambda function and move the alias to it.', 0, 'The old workaround from before April 2024. Still works, but it is code to maintain and is no longer needed.'),
        _o('Switch to the AWS managed key for the service, which rotates automatically.', 0, 'AWS managed keys rotate every year, and you cannot change the period.'),
        _o('Import new key material into the key every 90 days.', 0, 'Keys with imported material do not support automatic rotation.'),
        _o('Enable automatic rotation on the key with a rotation period of 90 days.', 1, 'Rotation periods of 90–2,560 days are supported; KMS keeps old key material to decrypt older ciphertext.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'least ops' }, words: ['rotated automatically every 90 days', 'no application changes'],
      expl: 'Automatic rotation keeps the **same key ID and ARN**, so nothing changes in the application, and old key material stays available for decryption. The period is now configurable from **90 to 2,560 days** (default 365).',
      update: ROT },
    { id: 'S13', src: 'New', line: 'kms',
      q: 'An administrator accidentally scheduled a customer managed KMS key for deletion with the default settings two days ago. The key encrypts production EBS volumes. What should the company do to avoid losing access to the data?',
      opts: [_o('Cancel the key deletion now, then enable the key again.', 1, 'The key is in Pending Deletion for the waiting period (default 30 days) and can be restored until it ends.'),
        _o('Nothing: AWS keeps a backup of deleted keys for 30 days after deletion.', 0, 'After the waiting period, the key material is gone for good; data encrypted under it is unrecoverable.'),
        _o('Create a new KMS key with the same alias.', 0, 'A new key has different key material and cannot decrypt the existing data.'),
        _o('Export the key material and import it into a new key.', 0, 'You cannot export KMS-generated key material.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'fastest' }, words: ['scheduled a customer managed KMS key for deletion', 'default settings'],
      expl: 'Deletion always has a **waiting period of 7–30 days (default 30)**. During it the key is disabled (Pending Deletion) and every cryptographic call fails — which is also how you find out who still uses it. **Cancel deletion** and re-enable. Disabling is the safe alternative to deleting.' },

    /* ---------------- encryption at rest ---------------- */
    { id: 'S8', src: 'New', line: 'rest',
      q: 'A company must share an encrypted Amazon EBS snapshot with a partner’s AWS account. The snapshot is encrypted with the default AWS managed key (aws/ebs). What is the correct approach?',
      opts: [_o('Copy the snapshot and re-encrypt it with a customer managed KMS key, allow the partner account in that key’s policy, and share the copy with the partner account.', 1, 'Only customer managed keys can be shared; the partner needs permission on the key and on the snapshot.'),
        _o('Modify the snapshot permissions to add the partner’s account ID.', 0, 'Snapshots encrypted with the AWS managed key cannot be shared.'),
        _o('Edit the key policy of aws/ebs to allow the partner account.', 0, 'You cannot edit the policy of an AWS managed key.'),
        _o('Make the snapshot public for one hour.', 0, 'Encrypted snapshots can never be made public — and it would be a data leak.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'none stated' }, words: ['share an encrypted Amazon EBS snapshot', 'default AWS managed key (aws/ebs)'],
      expl: 'AWS managed keys (aws/ebs, aws/rds) can only be used by principals in their own account. To share: **copy with a customer managed key → add the other account to the key policy → share the snapshot**. The same rule applies to RDS snapshots.' },
    { id: 'S10', src: 'New', line: 'rest',
      q: 'An S3 bucket with SSE-KMS default encryption receives millions of small object uploads per hour. The application now receives KMS ThrottlingException errors and the KMS bill has grown sharply. The company wants to reduce KMS requests without changing the encryption type.',
      opts: [_o('Switch the bucket to SSE-C so S3 no longer calls KMS.', 0, 'Changes the encryption type and moves key management to the application (and SSE-C is blocked on new buckets by default).'),
        _o('Enable S3 Bucket Keys for SSE-KMS on the bucket.', 1, 'S3 uses a short-lived bucket-level key derived from the KMS key, cutting KMS requests by up to 99%.'),
        _o('Create a second KMS key and alternate between the keys.', 0, 'The request quota is per account and Region, shared by all symmetric keys.'),
        _o('Attach an ACM certificate to the bucket to offload encryption.', 0, ACM_REST)],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'cheapest' }, words: ['ThrottlingException', 'without changing the encryption type'],
      expl: 'SSE-KMS calls KMS for every object. **S3 Bucket Keys** reduce those calls (and their cost) by up to 99%. The KMS request quota is shared per account per Region across keys, so a second key does not help.',
      update: 'KMS request quotas are now 10,000 / 20,000 / 100,000 per second depending on the Region (older material: 5,500 / 10,000 / 30,000–50,000).' },
    { id: 'S11', src: 'New', line: 'rest',
      q: 'An Amazon RDS for MySQL DB instance was created without encryption. An audit requires the database to be encrypted at rest with a KMS key, with the least effort. Which steps should a solutions architect take? (Select TWO.)',
      opts: [_o('Take a snapshot of the DB instance and copy the snapshot with encryption enabled, choosing a KMS key.', 1, 'Copying is where an unencrypted RDS snapshot can be encrypted.'),
        _o('Modify the DB instance and turn on encryption; apply immediately.', 0, 'RDS encryption can only be chosen when the instance is created.'),
        _o('Create an encrypted read replica of the unencrypted instance and promote it.', 0, 'A read replica must have the same encryption state as its source.'),
        _o('Restore a new DB instance from the encrypted snapshot copy and point the application to it.', 1, 'The restored instance is encrypted; switch the endpoint (and plan a short write freeze).'),
        _o('Enable EBS encryption by default in the Region.', 0, 'Affects new EBS volumes only, not RDS storage that already exists.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'least ops' }, words: ['created without encryption', 'encrypted at rest with a KMS key'],
      expl: 'RDS: **encryption only at creation**. Snapshot → **copy with encryption** → **restore** → switch the application. (Aurora differs: restore the snapshot with encryption turned on.) Encryption cannot be turned off later either.' },
    { id: 'S14', src: 'New', line: 'rest',
      q: 'A company’s policy says that encryption keys for archived data must be generated and stored only in its on-premises key management system. AWS may use a key only while processing a request and must never store it. The company creates a new S3 bucket for the archive in 2026. What should it do?',
      opts: [_o('Use SSE-KMS with keys imported into KMS from the on-premises system.', 0, 'Imported key material is stored in KMS — AWS keeps it.'),
        _o('Use the default SSE-S3 encryption.', 0, 'S3 generates and stores those keys.'),
        _o('Allow SSE-C on the bucket with PutBucketEncryption, then upload each object over HTTPS with the customer-provided key in the request headers.', 1, 'S3 uses the key for that request and discards it. Since April 2026 new buckets block SSE-C until you allow it.'),
        _o('Attach a private certificate from AWS Private CA to the bucket.', 0, 'Certificates are for TLS; they do not encrypt objects at rest.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'most control' }, words: ['stored only in its on-premises key management system', 'must never store it', 'new S3 bucket'],
      expl: '“AWS must never store the key” → **SSE-C** (or client-side encryption). S3 uses the key you send (HTTPS only), keeps only a salted HMAC to validate later requests, and forgets the key.',
      update: 'Since **April 2026** S3 **blocks SSE-C by default on new general purpose buckets** (and on existing buckets in accounts that never used it). Allow it with `PutBucketEncryption` (BlockedEncryptionTypes = NONE). Banks still answer “SSE-C” with no extra step.' },
    { id: 'S15', src: 'New', line: 'rest',
      q: 'A security audit found that some clients upload objects to an S3 bucket over plain HTTP. The company must ensure that every request to the bucket uses encryption in transit. What should a solutions architect do?',
      opts: [_o('Enable default encryption with SSE-KMS on the bucket.', 0, 'Encrypts objects at rest; says nothing about the connection.'),
        _o('Add a bucket policy statement that denies all S3 actions when aws:SecureTransport is false.', 1, 'Requests over HTTP carry SecureTransport = false and are refused.'),
        _o('Request an ACM certificate for the bucket’s endpoint.', 0, 'S3 endpoints already present AWS certificates; ACM cannot be attached to a bucket.'),
        _o('Enable S3 Object Lock in compliance mode.', 0, 'WORM retention, unrelated to transport.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'none stated' }, words: ['over plain HTTP', 'encryption in transit'],
      expl: 'Transport is enforced in the **bucket policy**: `Deny` with the condition `"Bool": {"aws:SecureTransport": "false"}`. To force SSE-KMS on uploads, deny PutObject without the KMS encryption header — a separate statement.' },
    { id: 'S16', src: 'New', line: 'rest',
      q: 'A company wants every new Amazon EBS volume and snapshot created in its account in eu-central-1 to be encrypted, even when engineers forget to select encryption, with the least effort.',
      opts: [_o('Write an AWS Config rule that deletes unencrypted volumes.', 0, 'Detects after the fact and destroys data; not a preventive setting.'),
        _o('Use Amazon Macie to find unencrypted volumes.', 0, 'Macie only analyses S3.'),
        _o('Create an SCP that denies ec2:CreateVolume for everyone.', 0, 'Blocks all volumes, encrypted or not.'),
        _o('Turn on EBS encryption by default in eu-central-1 and choose the KMS key to use.', 1, 'Every new volume and snapshot copy in that Region is encrypted automatically.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'prevent', sup: 'least ops' }, words: ['even when engineers forget', 'eu-central-1'],
      expl: '**EBS encryption by default** is an account setting **per Region**. It affects new volumes only; existing unencrypted volumes need snapshot → encrypted copy → new volume.' },

    /* ---------------- secrets ---------------- */
    { id: 'S17', src: 'New', line: 'secrets',
      q: 'An application on EC2 connects to an Amazon Aurora PostgreSQL database with a user name and password stored in a configuration file. The company must remove the password from the file and rotate it automatically every 30 days, with the least operational overhead.',
      opts: [_o('Store the credentials in AWS Secrets Manager with managed rotation every 30 days, and have the application read the secret at run time through its instance role.', 1, 'Managed rotation for Aurora needs no Lambda code; the app always reads the current value.'),
        _o('Store the password as a SecureString in Parameter Store and enable automatic rotation.', 0, 'Parameter Store has no built-in rotation.'),
        _o('Encrypt the configuration file with a KMS key and re-encrypt it every 30 days.', 0, 'The password still never changes, and you now manage file encryption.'),
        _o('Put the password in the EC2 user data and replace instances monthly.', 0, 'User data is readable from the instance metadata; no rotation of the database password happens.')],
      stub: { asset: 'secrets & config', layer: 'workload', mode: 'prevent', sup: 'least ops' }, words: ['rotate it automatically every 30 days', 'least operational overhead'],
      expl: '“Rotate automatically” → **Secrets Manager**. For RDS, Aurora, DocumentDB and Redshift it has **managed rotation** (no Lambda to maintain); RDS/Aurora can even manage the master password in Secrets Manager for you.',
      update: 'Managed rotation (no Lambda) now covers RDS, Aurora, DocumentDB and Redshift, and the shortest rotation schedule is every 4 hours. Older material shows a Lambda rotation function for every case.' },
    { id: 'S18', src: 'New', line: 'secrets',
      q: 'A team needs a central place for about 300 configuration values per environment — service endpoints, feature flags, timeouts — plus a few third-party API keys that are changed manually once a year. Values are under 1 KB. The team wants the cheapest managed option with encryption for the API keys.',
      opts: [_o('AWS Secrets Manager, one secret per value.', 0, 'About $0.40 per secret per month: over $120 a month per environment for mostly plain config.'),
        _o('An S3 bucket with a JSON file per environment.', 0, 'Works, but you build versioning, access per value and encryption handling yourself.'),
        _o('SSM Parameter Store standard parameters, with SecureString (KMS) for the API keys.', 1, 'Standard parameters are free (10,000 per Region, 4 KB each); SecureString encrypts the keys with KMS.'),
        _o('AWS Certificate Manager for the API keys and DynamoDB for the rest.', 0, 'ACM stores TLS certificates, not API keys. Prestige distractor.')],
      stub: { asset: 'secrets & config', layer: 'workload', mode: 'prevent', sup: 'cheapest' }, words: ['about 300 configuration values', 'changed manually once a year', 'cheapest managed option'],
      expl: 'Config + no rotation + cheapest → **Parameter Store standard** (free, 4 KB values, up to 10,000 per Region). Advanced tier (8 KB, 100,000 parameters, expiry policies) costs $0.05 per parameter per month.' },
    { id: 'S19', src: 'New', line: 'secrets',
      q: 'An application uses a database secret in AWS Secrets Manager in us-east-1 that rotates every 30 days. For disaster recovery, the standby application in us-west-2 must read the same, current secret locally if us-east-1 is unavailable.',
      opts: [_o('Copy the secret to Parameter Store in us-west-2 with a scheduled Lambda function.', 0, 'Custom code that can fall behind rotation.'),
        _o('Replicate the secret to us-west-2 with Secrets Manager multi-Region secrets.', 1, 'The replica keeps the same name and is updated when the primary rotates; it can be promoted if needed.'),
        _o('Use a KMS multi-Region key to encrypt the secret.', 0, 'The key would be available in both Regions, but the secret itself would still live only in us-east-1.'),
        _o('Store the secret in an S3 bucket with Cross-Region Replication.', 0, 'Moves a credential into a bucket; no rotation, weaker controls.')],
      stub: { asset: 'secrets & config', layer: 'workload', mode: 'prevent', sup: 'least ops' }, words: ['read the same, current secret locally', 'us-west-2'],
      expl: 'Secrets Manager **replicates secrets to other Regions**: same ARN except the Region, rotation propagates to replicas, a replica can be promoted to a standalone secret. Each replica is billed as a secret.' },

    /* ---------------- certificates ---------------- */
    { id: 'S20', src: 'New', line: 'acm',
      q: 'A company imported a certificate from a third-party certificate authority into AWS Certificate Manager and attached it to an ALB. Last year the certificate expired unnoticed and caused an outage. The company wants to be notified well before the imported certificate expires, with the least effort.',
      opts: [_o('Enable ACM managed renewal on the imported certificate.', 0, 'ACM does not renew imported certificates.'),
        _o('Enable AWS Shield Advanced proactive engagement.', 0, 'The Shield Response Team contacts you during DDoS events, not about certificates. Prestige distractor.'),
        _o('Create a CloudWatch alarm on the ALB’s HTTPCode_ELB_5XX_Count metric.', 0, 'Fires after the outage has started.'),
        _o('Create an Amazon EventBridge rule for the ACM “Certificate Approaching Expiration” event and send it to Amazon SNS (or use the AWS Config rule acm-certificate-expiration-check).', 1, 'ACM emits daily expiry events starting 45 days before expiry for imported certificates; the Config rule flags certificates near expiry.')],
      stub: { asset: 'TLS certificates', layer: 'entry point', mode: 'detect', sup: 'least ops' }, words: ['imported a certificate from a third-party certificate authority', 'notified well before'],
      expl: 'ACM renews only certificates **it issued**. For **imported** ones: react to the **EventBridge expiry events** (from 45 days before, configurable) or the **Config rule** `acm-certificate-expiration-check`, then re-import. ACM is right here — the prestige distractor is Shield.' },
    { id: 'S21', src: 'New', line: 'acm',
      q: 'A company runs 200 internal microservices on Amazon ECS that talk to each other over TLS using internal host names such as orders.corp.internal. The security team wants to stop managing a self-hosted certificate authority and have certificates issued and renewed centrally.',
      opts: [_o('Create an AWS Private CA and issue private certificates to the services through ACM.', 1, 'A managed private CA for internal names; ACM renews private certificates issued through it.'),
        _o('Request public ACM certificates for orders.corp.internal.', 0, 'Public CAs cannot issue certificates for private names such as .internal.'),
        _o('Store self-signed certificates in Secrets Manager and rotate them.', 0, 'Still self-managed and self-signed: every client must trust each one.'),
        _o('Enable AWS Network Firewall TLS inspection between the services.', 0, 'Inspects traffic; it does not issue the services’ certificates.')],
      stub: { asset: 'TLS certificates', layer: 'workload', mode: 'prevent', sup: 'least ops' }, words: ['internal host names', 'stop managing a self-hosted certificate authority'],
      expl: 'Internal names and your own trust chain → **AWS Private CA** ($400 per CA per month in general-purpose mode; $50 in short-lived certificate mode). Public ACM certificates only cover public DNS names.' },

    /* ---------------- WAF, Shield, Firewall Manager ---------------- */
    { id: 'S22', src: 'New', line: 'edge',
      q: 'A media company’s CloudFront distributions and ALBs were hit by several large DDoS attacks last quarter, and scaling during the attacks added significant charges. The company wants 24/7 access to AWS DDoS experts during attacks and protection against the extra scaling costs.',
      opts: [_o('Rely on AWS Shield Standard, which is already active.', 0, 'Shield Standard absorbs common L3/L4 attacks but has no response team and no cost protection.'),
        _o('Add AWS WAF rate-based rules to every web ACL.', 0, 'Helps with L7 floods but gives neither expert support nor cost protection.'),
        _o('Subscribe to AWS Shield Advanced, add the distributions and ALBs as protected resources, and have Business or Enterprise Support for the Shield Response Team.', 1, 'SRT access, DDoS cost protection, automatic L7 mitigation with WAF.'),
        _o('Enable Amazon GuardDuty in all Regions.', 0, 'GuardDuty detects account threats; it does not mitigate DDoS.')],
      stub: { asset: 'web requests', layer: 'entry point', mode: 'prevent', sup: 'none stated' }, words: ['24/7 access to AWS DDoS experts', 'extra scaling costs'],
      expl: 'Here **Shield Advanced is right**: “DDoS experts” = the **Shield Response Team** (needs Business or Enterprise Support) and “scaling costs during an attack” = **DDoS cost protection**. $3,000 a month per organization with a one-year commitment.' },
    { id: 'S23', src: 'New', line: 'edge',
      q: 'A company publishes a REST API with Amazon API Gateway (no CloudFront in front). For licensing reasons, requests from three specific countries must be blocked, with the least operational overhead.',
      opts: [_o('Create network ACL rules that deny the IP ranges of the three countries.', 0, 'API Gateway is not in your subnets, and country IP ranges run into thousands of CIDRs.'),
        _o('Associate an AWS WAF web ACL with the API stage and add a geo match rule that blocks the three countries.', 1, 'Geo match is a built-in WAF statement; REST API stages are supported WAF resources.'),
        _o('Deploy AWS Network Firewall with a geographic IP filter in front of API Gateway.', 0, 'Network Firewall lives in VPC routing; API Gateway’s public endpoint does not pass through it. Prestige distractor.'),
        _o('Enable CloudFront geographic restrictions on the API.', 0, 'There is no CloudFront distribution in this design.')],
      stub: { asset: 'web requests', layer: 'entry point', mode: 'prevent', sup: 'least ops' }, words: ['REST API with Amazon API Gateway', 'three specific countries'],
      expl: 'Country rules at an API entry point → **WAF geo match**. Remember the supported resources: CloudFront, ALB, API Gateway **REST** APIs, AppSync, Cognito user pools, App Runner, Verified Access, Amplify — **not NLB**, not HTTP APIs.' },
    { id: 'S24', src: 'New', line: 'edge',
      q: 'A company with 40 AWS accounts in AWS Organizations must apply the same AWS WAF rules to every internet-facing ALB, including ALBs in accounts created in the future, and see which resources are not compliant.',
      opts: [_o('Enable AWS Security Hub and the AWS Foundational Security Best Practices standard.', 0, 'Reports missing WAF on some resources but does not apply rules. Prestige distractor.'),
        _o('Deploy the web ACL to every account with CloudFormation StackSets and re-run for new accounts.', 0, 'Creates the web ACLs, but associating new ALBs and tracking compliance is left to you.'),
        _o('Ask each account team to create the web ACL by hand and review them every month.', 0, 'Manual, drifts between reviews, misses new ALBs, and gives no compliance view.'),
        _o('Use AWS Firewall Manager with an AWS WAF policy scoped to ALBs across the organization, with AWS Config enabled.', 1, 'Firewall Manager applies the web ACL to existing and new in-scope resources and reports compliance.')],
      stub: { asset: 'web requests', layer: 'account / org', mode: 'prevent', sup: 'least ops' }, words: ['40 AWS accounts in AWS Organizations', 'accounts created in the future'],
      expl: 'Same firewall rules everywhere in an Organization, automatically for new resources → **Firewall Manager** (needs Organizations, a Firewall Manager administrator and AWS Config). It manages WAF, Shield Advanced, security group, NACL, Network Firewall, DNS Firewall and third-party firewall policies.' },

    /* ---------------- detection ---------------- */
    { id: 'S25', src: 'New', line: 'detect',
      q: 'A company wants to be alerted when any EC2 instance in its account communicates with known cryptocurrency-mining pools or command-and-control servers, or when IAM credentials are used from unusual locations. It does not want to deploy agents or manage log pipelines.',
      opts: [_o('Enable Amazon GuardDuty and send its findings through Amazon EventBridge to Amazon SNS.', 1, 'GuardDuty analyses CloudTrail, VPC Flow Logs and DNS logs itself and raises exactly these findings.'),
        _o('Enable Amazon Inspector for EC2.', 0, 'Inspector finds software vulnerabilities and exposure, not live malicious traffic.'),
        _o('Enable VPC Flow Logs to CloudWatch Logs and write metric filters for each mining pool IP.', 0, 'A log pipeline and IP lists you maintain yourself — what GuardDuty replaces.'),
        _o('Deploy AWS Network Firewall with IPS rules in every VPC.', 0, 'Could block some traffic but ignores IAM credential misuse and is heavy to run. Prestige distractor.')],
      stub: { asset: 'API & account activity', layer: 'account / org', mode: 'detect', sup: 'least ops' }, words: ['cryptocurrency-mining pools', 'IAM credentials are used from unusual locations', 'does not want to deploy agents'],
      expl: 'Threat detection from account and network activity → **GuardDuty**. It reads its **own** copy of CloudTrail management events, VPC Flow Logs and DNS logs, so nothing needs enabling first. It **detects**; response goes through EventBridge.',
      update: 'GuardDuty **Extended Threat Detection** (Dec 2024) is on by default at no extra cost and correlates several signals into attack sequence findings.' },
    { id: 'S26', src: 'New', line: 'detect',
      q: 'GuardDuty reported that IAM access keys were used to call APIs from an unusual IP address. The security team must determine which resources those credentials accessed over the past several weeks, which other IP addresses were involved, and how the activity started, with the least effort.',
      opts: [_o('Aggregate the finding in AWS Security Hub and review the security score.', 0, 'Security Hub lists and prioritises findings; it does not reconstruct weeks of activity. Prestige distractor.'),
        _o('Query CloudTrail logs in S3 with Athena and join them with VPC Flow Logs manually.', 0, 'Possible, but it is the investigation Detective does for you.'),
        _o('Pivot from the finding into Amazon Detective and examine the behaviour graph for the access key and IP addresses.', 1, 'Detective links CloudTrail, flow logs and GuardDuty findings in a graph over up to a year.'),
        _o('Enable Amazon Macie on all buckets.', 0, 'Finds sensitive data in S3; it does not trace credential use.')],
      stub: { asset: 'API & account activity', layer: 'account / org', mode: 'investigate', sup: 'least ops' }, words: ['determine which resources those credentials accessed', 'how the activity started'],
      expl: 'MODE = investigate → **Detective**. GuardDuty detected; Security Hub would aggregate; Detective explains root cause and scope from its behaviour graph.' },
    { id: 'S27', src: 'New', line: 'scan',
      q: 'A company builds container images that are pushed to Amazon ECR and deploys Lambda functions. The security team must continuously find known software vulnerabilities (CVEs) in the images and function packages and be alerted when a new CVE affects something already deployed.',
      opts: [_o('Amazon GuardDuty Runtime Monitoring.', 0, 'Watches runtime behaviour for threats; it does not inventory package CVEs.'),
        _o('Amazon Macie with custom data identifiers.', 0, 'Macie analyses S3 objects for sensitive data.'),
        _o('AWS Security Hub alone.', 0, 'Aggregates findings; something must produce the CVE findings first.'),
        _o('Amazon Inspector with enhanced ECR scanning and Lambda scanning enabled.', 1, 'Scans on push and continuously re-evaluates when new CVEs are published.')],
      stub: { asset: 'workloads & images', layer: 'workload', mode: 'detect', sup: 'least ops' }, words: ['known software vulnerabilities (CVEs)', 'Amazon ECR', 'Lambda functions'],
      expl: 'CVEs in EC2, ECR images and Lambda → **Inspector**. It rescans continuously as new vulnerabilities are published; findings go to EventBridge and Security Hub.',
      update: 'Inspector Classic ended support on 20 May 2026. Current Inspector also scans EC2 agentless (hybrid mode) and source repositories (code security, GA June 2025).' },
    { id: 'S28', src: 'New', line: 'scan',
      q: 'A company has 3,000 S3 buckets across its AWS accounts. Before a GDPR audit it must find which buckets contain personal data such as names, passport numbers and bank account numbers, and keep checking new objects with the least effort.',
      opts: [_o('Enable GuardDuty S3 Protection in every account.', 0, 'Watches S3 API activity for threats; it never reads object contents.'),
        _o('Enable Amazon Macie with automated sensitive data discovery from a delegated administrator account.', 1, 'Samples objects across all buckets with managed data identifiers and reports where personal data lives.'),
        _o('Run Amazon Inspector scans on the buckets.', 0, 'Inspector scans workloads for CVEs, not S3 objects.'),
        _o('Use S3 Inventory reports and grep them for passport numbers.', 0, 'Inventory lists object metadata, not contents.')],
      stub: { asset: 'data at rest', layer: 'data store', mode: 'detect', sup: 'least ops' }, words: ['personal data such as names, passport numbers', '3,000 S3 buckets'],
      expl: 'Sensitive data in S3 → **Macie**, and only Macie. Automated sensitive data discovery samples every bucket continuously; discovery jobs target specific buckets. Findings go to EventBridge and Security Hub.' },

    /* ---------------- posture ---------------- */
    { id: 'S29', src: 'New', line: 'hub',
      q: 'A company with 30 accounts in AWS Organizations operates in four Regions. The security team wants one place to see findings from GuardDuty, Inspector and Macie for all accounts and Regions, and an automated, continuous check of every account against the CIS AWS Foundations Benchmark. Which steps are required? (Select TWO.)',
      opts: [_o('Enable Amazon Detective in every account and Region.', 0, 'Investigates findings; it does not aggregate them or run benchmark checks.'),
        _o('Enable AWS Config recording in every account and Region that will be checked.', 1, 'Security Hub CSPM evaluates most controls with AWS Config rules.'),
        _o('Enable Security Hub CSPM through a delegated administrator in Organizations, set an aggregation Region for the four Regions, and enable the CIS standard.', 1, 'Central configuration, cross-Region aggregation, and the CIS checks as controls.'),
        _o('Deploy AWS Network Firewall in each VPC and send its logs to the security account.', 0, 'Network traffic logs are not findings from GuardDuty, Inspector and Macie. Prestige distractor.'),
        _o('Create a Macie discovery job for every bucket.', 0, 'One source of findings, not the place that aggregates them.')],
      stub: { asset: 'API & account activity', layer: 'account / org', mode: 'report / audit', sup: 'least ops' }, words: ['one place to see findings', 'CIS AWS Foundations Benchmark', 'four Regions'],
      expl: '“Single pane of glass” + “benchmark” → **Security Hub** (the posture part is now called **Security Hub CSPM**) with a delegated administrator, a cross-Region **aggregation Region**, the CIS standard — and **AWS Config** enabled, because the controls are Config rules.',
      update: 'The original Security Hub is now **AWS Security Hub CSPM**; the new **AWS Security Hub** (GA December 2025) correlates GuardDuty, Inspector, Macie and CSPM findings into exposure findings in OCSF. Banks say “Security Hub”.' },

    /* ---------------- Cognito ---------------- */
    { id: 'S30', src: 'New', line: 'cognito',
      q: 'A mobile photo app lets users sign up with email or sign in with their Google accounts. Signed-in users must upload photos directly to their own prefix in an S3 bucket without a backend server, and the company does not want to create IAM users.',
      opts: [_o('A Cognito user pool with Google as an identity provider for sign-in, plus a Cognito identity pool that exchanges the user pool tokens for temporary credentials of an IAM role limited to the user’s own prefix.', 1, 'User pool = who the user is; identity pool = temporary AWS credentials to call S3 directly.'),
        _o('A Cognito identity pool only, with users signing up with an email and password in the identity pool.', 0, 'Identity pools have no user directory; sign-up and sign-in are user pool features.'),
        _o('An IAM user per app user, with access keys embedded in the app.', 0, 'Long-term keys in a mobile app; unmanageable at scale.'),
        _o('An ACM certificate on the S3 bucket and pre-shared keys for each user.', 0, 'Certificates do not authenticate app users to AWS. Prestige distractor.')],
      stub: { asset: 'app users', layer: 'app sign-in', mode: 'prevent', sup: 'none stated' }, words: ['sign in with their Google accounts', 'upload photos directly', 'does not want to create IAM users'],
      expl: 'Two pools, two jobs: the **user pool** signs users in (email or Google) and issues JWTs; the **identity pool** swaps them for **temporary AWS credentials** of an IAM role, whose policy can use the identity ID to restrict each user to their prefix.' }
  ];
})();
